### PR TITLE
fix: Select onChange is fired when the same item is selected in single mode

### LINKED ISSUE #27668: Select component fires onChange when selected value has not changed
### Bug description

When rendering the Select component in singleMode (only one selection can be selected), selecting the currently selected value from the dropdown options triggers the onChange function to fire, even though the selection has not changed.

### How to reproduce the bug

Go to alerts and reports
Add an alert or report
Under notification settings, select Email
Add some text to the recipients section
Select Email again
See that the recipients field has been cleared

### Screenshots/recordings

https://www.loom.com/share/9f9829e8877a444db074e6f8ce0f669f?sid=1e4fe88d-4075-4b6a-9dc0-50749316baa2

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

ALERT_REPORTS=True

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Prevents Select's `onChange` from being fired when the same item is selected in single mode. 

Fixes https://github.com/apache/superset/issues/27668.

### TESTING INSTRUCTIONS
CI.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/components/Select/utils.tsx [hunk 1]
```diff
@@ -49,22 +49,25 @@ export function getValue(
...
   return optionsArray.find(
     x =>
-      // eslint-disable-next-line eqeqeq
-      x == value ||
-      (isObject(x) &&
-        // eslint-disable-next-line eqeqeq
-        (('value' in x && x.value == value) ||
-          (checkLabel && 'label' in x && x.label === value))),
+      equalValues(x, value) ||
+      (checkLabel && isObject(x) && 'label' in x && x.label === value),
```
Comment (kgabryje) [inline superset-frontend/src/components/Select/utils.tsx:70]: Do you think it makes sense to extend `equalValues` to accept "key" argument, so you could call `equalValues(x, checkLabel, "label")` here?

**Review by kgabryje — APPROVED** [review]
LGTM, added 1 non blocking comment

File: superset-frontend/src/components/Select/utils.tsx (hunk 1 above)
Comment (michael-s-molina) [reply superset-frontend/src/components/Select/utils.tsx]: Good call. Done.
