### PR TITLE
fix: In chart gallery thumbnail is rendered in case of no example in #16707

### LINKED ISSUE #16707: [Gallery] Some chart type in gallery do not have example
Some chart type are missing example image in gallery:

Screen Shot 2021-09-14 at 1 56 56 PM

This is the list of chart  type that missing example in gallery

Bubble chart
Calendar heatmap
Country map
deck.gl.Arc
deck.gl.Geojson
deck.gl.Grid
deck.gl 3D Hexagon
deck.gl Multiple Layers
deck.gl Path
deck.gl Polygon
deck.gl Scatterplot
deck.gl Screen Grid
Event Flow
Funnel Chart
Gauge Chart
Graph Chart
Mixed Time-Series
Pivot Table v2
Radar Chart
Nightingale Rose Chart
Time-series Table

### PR DESCRIPTION
**Pull request by sivasathyaseeelan**
### SUMMARY
This PR solves the issue mentioned in #16707 . I have made VizTypeGallery component to render the thumbnail image for selected chart for which example images are not available.

### BEFORE
[![Before Changes]](https://github.com/apache/superset/assets/95441117/8e39d778-c7bc-49aa-a279-8b6ab99a51ba)

### AFTER
[![After Changes]](https://github.com/apache/superset/assets/95441117/9d5325fd-26e3-42cd-aacd-578b2b379254)

### TESTING INSTRUCTIONS
Kindly go to http://localhost:9000/chart/add and please select any chart so that you can be able to see example images of selected chart

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #16707 
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [x] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/explore/components/controls/VizTypeControl/VizTypeGallery.tsx [hunk 1]
```diff
@@ -849,17 +849,26 @@ export default function VizTypeGallery(props: VizTypeGalleryProps) {
                 grid-area: examples-header;
               `}
             >
-              {!!selectedVizMetadata?.exampleGallery?.length && t('Examples')}
+              {t('Examples')}
             </SectionTitle>
             <Examples>
-              {(selectedVizMetadata?.exampleGallery || []).map(example => (
+              {selectedVizMetadata?.exampleGallery.length ? (
```
Comment (michael-s-molina) [inline superset-frontend/src/explore/components/controls/VizTypeControl/VizTypeGallery.tsx:855]: Maybe this looks more readable?

```
<Examples>
  {(
    selectedVizMetadata?.exampleGallery || [
      {
        url: selectedVizMetadata?.thumbnail,
        caption: selectedVizMetadata?.thumbnail,
      },
    ]
  ).map(example => (
    <img
      key={example.url}
      src={example.url}
      alt={example.caption}
      title={example.caption}
    />
  ))}
</Examples>
```

Comment (sivasathyaseeelan) [reply superset-frontend/src/explore/components/controls/VizTypeControl/VizTypeGallery.tsx:855]: Hi @michael-s-molina, The above piece of code which you have mentioned doesn't render the thumbnail image in case of no exampleGallery.

But,
```jsx
           <Examples>
              {(selectedVizMetadata?.exampleGallery?.length
                ? selectedVizMetadata.exampleGallery
                : [
                    {
                      url: selectedVizMetadata?.thumbnail,
                      caption: selectedVizMetadata?.name,
                    },
                  ]
              ).map(example => (
                <img
                  key={example.url}
                  src={example.url}
                  alt={example.caption}
                  title={example.caption}
                />
              ))}
            </Examples>
```
this code works.

Can I go and use this piece of code and modify this PR?

Comment (michael-s-molina) [reply superset-frontend/src/explore/components/controls/VizTypeControl/VizTypeGallery.tsx:855]: 👍🏼

**Review by michael-s-molina — APPROVED** [review]
LGTM. Thanks for the improvement @sivasathyaseeelan!
