### PR TITLE
fix(Select): Prevent closing the select when clicking on a tag

### LINKED ISSUE #35132: [6.0.0][Filter] Can not display filter dropdown when click selection in filter
### Bug description

When click an empty filter, the selection dropdown should keep display on the screen.
Bug if select some filter selection, then click, dropdown displays and then disappears automatically. Only clicking on a blank part of the filter will keep it displayed.
It's hard to add multiple filters. And the width of the dropdown is also incorrect.

My superset version is 6.0.0 (branch 6.0)

### Screenshots/recordings

Here is my record:

https://github.com/user-attachments/assets/f086f388-6693-4648-bdf4-a1d54353e6f7

### Superset version

master / latest-dev

### Python version

3.11

### Node version

18 or greater

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by msyavuz**
### SUMMARY

Fixes an issue where clicking on tags in the Select component's `oneLine` mode would cause the dropdown to not open because the click target would disappear during the click event.

The problem occurred when `oneLine` mode changed `maxTagCount` from 1 to 0 immediately when the dropdown was opened, causing the tag element to disappear while the user was clicking on it, preventing the click from registering.

**Solution:**
- Introduced a stable `maxTagCount` state that doesn't change immediately during click events
- Used `requestAnimationFrame` to delay the tag count change until after the DOM has settled
- Added proper state management with `useRef` to track when the dropdown is opening to prevent race conditions

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

**Before:** Clicking on tags in oneLine mode would sometimes fail to open the dropdown because the tag would disappear mid-click.

**After:** Tags remain stable during click events, ensuring the dropdown opens reliably when clicking on any tag.

### TESTING INSTRUCTIONS

1. Create a Select component with `mode="multiple"` and `oneLine={true}`
2. Set a value with multiple options so tags are displayed with overflow (e.g., 3+ options)
3. Click directly on the first visible tag
4. Verify that the dropdown opens consistently every time
5. Verify that when the dropdown opens, only the overflow tag is shown
6. Close the dropdown and verify the first tag reappears immediately

**Test case:**
```tsx
<Select
  mode="multiple"
  oneLine
  value={[option1, option2, option3]}
  options={options}
/>
```

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #35132
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/packages/superset-ui-core/src/components/Select/Select.tsx [hunk 1]
```diff
@@ -143,6 +144,32 @@ const Select = forwardRef(
         : 1
       : (propsMaxTagCount ?? MAX_TAG_COUNT);
 
+    // Prevent maxTagCount change during click events to avoid click target disappearing
+    const [stableMaxTagCount, setStableMaxTagCount] = useState(maxTagCount);
+    const isOpeningRef = useRef(false);
+
+    useEffect(() => {
```
Comment (michael-s-molina) [inline superset-frontend/packages/superset-ui-core/src/components/Select/Select.tsx:151]: Maybe `useLayoutEffect` could help?

Comment (msyavuz) [reply superset-frontend/packages/superset-ui-core/src/components/Select/Select.tsx:151]: Good suggestion, unfortunately it does not work with useLayoutEffect

**Review by michael-s-molina — APPROVED** [review]
