### PR TITLE
fix(filters): fix filter / customization name not updating in sidebar in real time

### LINKED ISSUE #37356: Filter / customization name not updating in sidebar in real time.
### Bug description

When editing a filter or chart customization name, the left-side list item remains [untitled] while typing and only updates after clicking the (untitled) name.
Expected behavior is for the list label to update live as the name field changes.

### Screenshots/recordings

Image

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by LevisNgigi**
### SUMMARY
fixes an issue where the filter and customization name in the sidebar did not update in real time as user typed the name of the filter/customization.Previously, when a user updated the name of a filter or customization control, the sidebar display would not reflect the new name immediately and one would have to click on the untitled section.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
AFTER:

https://github.com/user-attachments/assets/9290d44a-c67b-4978-961e-41150b16888a

### TESTING INSTRUCTIONS
1)  Navigate to a dashboard
2) Open the filters and customiation controls.
3) Add a filter and edit the name of a filter or customization control.
4) Verify that the sidebar immediately displays the new name after editing, without requiring a refresh/clicking on the untitled section.
5) Confirm that other filters or UI elements continue to function normally after the update.

### ADDITIONAL INFORMATION

- [x ] Has associated issue: Fixes #37356
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/components/nativeFilters/FiltersConfigModal/ConfigModalSidebar/ConfigModalSidebar.tsx [hunk 1]
```diff
@@ -140,6 +142,7 @@ const ConfigModalSidebar: FC<ConfigModalSidebarProps> = ({
         />
       </StyledHeaderFlex>
       <StyledCollapse
+        key={formValuesVersion}
```
Comment (EnxDev) [inline superset-frontend/src/dashboard/components/nativeFilters/FiltersConfigModal/ConfigModalSidebar/ConfigModalSidebar.tsx]: Using key={formValuesVersion} on StyledCollapse causes React to fully unmount and remount the entire collapse tree on every form change (including each keystroke). This might be a bit heavy-handed

**Comment by EnxDev** [comment]
Code looks good, what do you think to add some RTL tests?

**Review by EnxDev — APPROVED** [review]
LGTM!
