### PR TITLE
fix: Popover closes on change of dropdowns values

### LINKED ISSUE #12310: [Dashboard]refresh Interval modal scroll and dropdown
Before:
Screen Shot 2021-01-06 at 10 41 08 AM

Now
Screen Shot 2021-01-06 at 3 35 13 PM

thanks for spotting this issue @michael-s-molina !

### LINKED ISSUE #12388: [Explore]LONGITUDE & LATITUDE popover close after select
> There might be another issue though. It seems the Popover is closed on every change without giving the user the ability to apply the changes @junlincc

right, that's also happening in the LONGITUDE & LATITUDE popover in deck.gl chart 

_Originally posted by @junlincc in https://github.com/apache/superset/issues/12328#issuecomment-756911674_

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
The option `menuPortalTarget` of the react-select component was introduced in order for the dropdowns to show fully when overlaying certain container elements. However, setting the `menuPortalTarget` to `document.body` (as originally the multi-choice dropdown did and later the single-choice) comes with several issues, such as the click events being targeted outside of the container elements, that ultimately caused this issue #12388.

This PR removes the `menuPortalTarget` for both single-choice and multi-choice dropdowns. In addition to that, this introduces the optional ability to force the overflow visibility of the dropdowns for cases where setting the `overflow` `visible` isn't viable on the container element (see for instance issue #12004 )

It also adjusts some excessive z-index by setting it high enough to give it precedence over the Antd Popover and other components.

Closes #12388 

### BEFORE

https://user-images.githubusercontent.com/60598000/104368923-06b6fc00-551d-11eb-935b-b6b7ba657dc3.mp4

### AFTER

https://user-images.githubusercontent.com/60598000/104368799-dc653e80-551c-11eb-9778-3fed7cede574.mp4

### TEST PLAN
1. Open the single and multi-choice dropdowns throughout the project
2. Make sure the dropdowns are displaying correctly

### ADDITIONAL INFORMATION

- [x] Has associated issue: #12388 
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@junlincc @rusackas

**Comment by junlincc** [comment]
@villebro @rusackas @ktmud need to make sure merging this PR will not create any conflict to changes in #12406

**Comment by adam-stasiak** [comment]
I found issue related to scrolling with dropdown active:
Left side - PR, before change
https://user-images.githubusercontent.com/25153919/104233738-ab203c00-5452-11eb-9f21-908329b3de88.mov

**Comment by geido** [comment]
For reference, this is the react-select issue related to scroll https://github.com/JedWatson/react-select/issues/4088

**Comment by ktmud** [comment]
Can we add an option to `SupersetSelect` to disable the portal wrap by default and only enable it for places where it's likely to overflow the parent container?

File: superset-frontend/src/components/Select/SupersetStyledSelect.tsx [hunk 1]
```diff
@@ -259,36 +257,43 @@ function styled<
...
-        theme={reactSelectTheme =>
-          merge(reactSelectTheme, defaultTheme(theme), themeConfig)
-        }
-        formatOptionLabel={formatOptionLabel}
-        getOptionLabel={getOptionLabel}
-        getOptionValue={getOptionValue}
-        components={components}
-        {...restProps}
-      />
+      <div ref={menuPortalTargetRef}>
```
Comment (kkucharc) [inline superset-frontend/src/components/Select/SupersetStyledSelect.tsx:263]: I've tried to test it and I can't find places where exact benefit of referring `menuPortalTarget` to the div. Maybe you could provide some gif or screens where it helps? Otherwise maybe `menuPortalTarget={document.body}` would be enough?

**Review by kkucharc — COMMENTED** [review]
Thank you for the contribution! Seems that moving `menuPortalTarget` higher structure may help.

I also saw scroll problem that @adam-stasiak mentioned. Unfortunately it happens in many places such as explore:
Large GIF (798x774)

File: superset-frontend/src/components/Select/SupersetStyledSelect.tsx (hunk 1 above)
Comment (geido) [reply superset-frontend/src/components/Select/SupersetStyledSelect.tsx:263]: Hi. @kkucharc thanks for your feedback. The `menuPortalTarget` to `document.body` will create the issue #12388 as the click event will be targeted outside of the Popover container. This is actually one of the main reasons why I am implementing this change. However, I think we can make this optional and just use it as a fallback, while managing all the other cases individually with ad hoc solutions where possible. I am looking into that.

**Comment by geido** [comment]
I have cleaned up the things a bit. The `menuPortalTarget` wasn't really needed and I removed it. What is needed is only the `menuPosition` to be `fixed` for instances where setting the overflow to visible on the container element isn't possible. I made that optional as well by introducing a `forceOverflow` option so that individual cases can be handle appropriately. Finally, when the option`forceOverflow` is used, I am closing the dropdown on scroll when the target of the scroll isn't the dropdown itself so that issue mentioned by @adam-stasiak and @kkucharc is mitigated.

**Comment by adam-stasiak** [comment]
Removing data from dropdown causes modal dismiss.

Uploading Nagranie z ekranu 2021-01-12 o 22.51.08.mov…

**Comment by geido** [comment]
@adam-stasiak seems related to a different issue to me

File: superset-frontend/src/components/Select/SupersetStyledSelect.tsx [hunk 2]
```diff
@@ -243,6 +244,18 @@ function styled<
       });
     }
 
+    // handle forcing dropdown overflow
+    // use only when setting overflow:visible isn't possible on the container element
+    if (forceOverflow) {
```
Comment (kkucharc) [inline superset-frontend/src/components/Select/SupersetStyledSelect.tsx:249]: Are there any places that have this option already as `true`?

**Review by kkucharc — COMMENTED** [review]
Thanks a lot for improvement!
According to the video in your comment: I understand that keeping dropdown open and sticked to the input until we click somewhere else is just impossible to achieve?

**Comment by geido** [comment]
> Thanks a lot for improvement!
> According to the video in your comment: I understand that keeping dropdown open and sticked to the input until we click somewhere else is just impossible to achieve?

@kkucharc impossible is not I would define it. The problem is this is a known issue of the react-select library and it does not have a solution right now. Fixing this problem on our side might mean coming up with hacks that are not desirable. Closing the dropdown on scroll is already some sort of hack, but I would not go beyond that really.

File: superset-frontend/src/components/Select/SupersetStyledSelect.tsx (hunk 2 above)
Comment (geido) [reply superset-frontend/src/components/Select/SupersetStyledSelect.tsx:249]: Yes you can see two instances in this PR already. One is on the dashboard filters and the other one is used for the refresh-interval modal. The one for the dashboard filters is required. The one for refresh-interval is more to show how it looks like on a modal but it is not necessary and can be removed.

Comment (kkucharc) [reply superset-frontend/src/components/Select/SupersetStyledSelect.tsx:249]: I see, thanks for explanation 👍

**Comment by geido** [comment]
@kkucharc that's an issue affecting all the modals. I think I have a solution for that and I am going to submit a separate PR. In fact, we don't need to necessarily use the `forceOverflow` option to fix that problem. In general, I'd use the `forceOverflow` option introduced by this PR only for those cases where the overflow issue can't be solved otherwise.

**Comment by adam-stasiak** [comment]
Tested manually across other places in app - looks fine.

**Review by ktmud — APPROVED** [review]
LGTM, tested and works great after rebase.

**Comment by ktmud** [comment]
@junlincc @villebro can we make sure this PR goes into `v1.0`, too? Currently in `1.0.0 RC2`, the dropdown menu of react-select is sticky on page scroll, which is not very nice:

sticky menu

**Comment by junlincc** [comment]
we are canceling rc2 kicking of rc3 to include this and a couple of others @ktmud

**Comment by villebro** [comment]
@ktmud I already cancelled rc2, so I can pick this into rc3. @junlincc remember to flag all PRs you want included in 1.0 with the appropriate label so I have a checklist.
