### PR TITLE
fix: adding and removing tags does not work in control panel properties modal

### LINKED ISSUE #33758: Tag is not removed
### Bug description

A user can add a tag but the remove is KO if it'is done in the element : 
- Remove a tag is OK if it'is done directly with "Edit" button from elements list (see at 30'' or 1'05'' in the video)
- Remove a tag is KO if it'is done in the edition mode of an element with "Edit properties" button (see at 47'' in the video)

### Screenshots/recordings

https://github.com/user-attachments/assets/7afd3aa2-ae33-4f4d-9be3-5d696dd37195

### Superset version

5.0.0-RC2

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by SBIN2010**
This PR fix #33758

When saving a dashboard after editing a property in a modal window, missing tag transfer has been added.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by rusackas** [comment]
Running CI 🤞

File: superset-frontend/src/dashboard/actions/dashboardState.js [hunk 1]
```diff
@@ -315,6 +316,9 @@ export function saveDashboardRequest(data, id, saveType) {
         ? undefined
         : ensureIsArray(roles).map(r => (hasId(r) ? r.id : r)),
       slug: slug || null,
+      tags: !isFeatureEnabled(FeatureFlag.TaggingSystem)
+        ? undefined
+        : ensureIsArray(tags).map(r => (hasId(r) ? r.id : r)),
```
Comment (rusackas) [inline superset-frontend/src/dashboard/actions/dashboardState.js]: Is there any chance `tags` could be undefined here? If so, you could add `ensureIsArray(tags || [])`

File: superset-frontend/src/dashboard/actions/dashboardState.js [hunk 2]
```diff
@@ -445,6 +449,7 @@ export function saveDashboardRequest(data, id, saveType) {
               slug: cleanedData.slug,
               owners: cleanedData.owners,
               roles: cleanedData.roles,
+              tags: cleanedData.tags,
```
Comment (rusackas) [inline superset-frontend/src/dashboard/actions/dashboardState.js]: Similarly, not sure if there's a need for `cleanedData.tags || []` safety here.

**Review by msyavuz — APPROVED** [review]
LGTM!
