### PR TITLE
fix: Detecting top scroll on Dashboard header

### LINKED ISSUE #11907: Dashboard not scroll up when user moving chart
Dashboard not scroll up when user moving chart, or adding a new chart at the bottom of long dashboard.

### Expected results
Be able to scroll so that chart can go to the place user wants.

### Actual results
Doesn't scroll. 

#### How to reproduce the bug

1. open a large dashboard and start Edit mode
2. move chart from the bottom of page to dashboard top area
3. See dashbaord doesn't scroll

### Environment

(please complete the following information):

- superset version: `master`

### Screenshots
scroll-issue-1

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This is regression - it was previously possible to scroll.

### PR DESCRIPTION
**Pull request by kkucharc**
### SUMMARY
This is updated [PR](https://github.com/apache/superset/pull/12104) which was closed due to react-dnd upgrade. 
Currently in edit mode in dashboard it's impossible to scroll to top while dragging an element. It is now possible when dragged element is hovering dashboard's header.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/2536609/102547288-47a42800-40b9-11eb-8915-05a7db66226c.gif

### TEST PLAN
1. Go to one of dashboards
2. Go to edit mode
3. Add so many elements that right scroll appears
4. Scroll down
5. Drag element and move it over header

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes: #11907
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by kkucharc** [comment]
Hi @ktmud (This is [the old one]( https://github.com/apache/superset/pull/12104))! I reopened the PR with all suggestions from the old one. I also adjusted scroll speed. Hope this will better this way.

File: superset-frontend/src/dashboard/components/dnd/handleScroll.ts [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+ * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+ * KIND, either express or implied.  See the License for the
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+let scrollTopDashboardInterval: any;
+const SCROLL_STEP = 120;
+const INTERVAL_DELAY = 50;
+
+export default function handleScroll(dropPosition: string) {
```
Comment (ktmud) [inline superset-frontend/src/dashboard/components/dnd/handleScroll.ts:23]:
```suggestion
type DragPosition = 'DROP_TOP' | 'DROP_RIGHT' | ...;

export default function handleScroll(dropPosition: DragPosition) {
```

`dropPosition` could be of string literal type. But that could be in another refactoring PR when we migrate `superset-frontend/src/dashboard/util/getDropPosition.js` to TypeScript, too.

**Review by ktmud — APPROVED** [review]

**Review by junlincc — COMMENTED** [review]
Thanks for the PR, Kashia! LGTM✅

Spotted a separate issue below, I will open a new ticket but will not assign to you 😁 thanks for all your great work! 

https://user-images.githubusercontent.com/67837651/106956402-630bd680-66eb-11eb-8536-441e713de46b.mov
