### PR TITLE
fix(explore): pass partitionColumn when creating new adhoc filter

### LINKED ISSUE #12752: [explore][adhoc filter] "use latest_partition" operator disappeared
in #9637 we added an optional operator for adhoc filter: use latest_partition. It will show up when datasource has single partition. This feature was lost since recent filter redesign work. Note: this feature is not enabled by feature flag. The operator should show up based on the attribute of dataset.

### Before
80538611-e4fbf180-895a-11ea-9e72-fbd1ebebb7e1

### Current
 
Screen Shot 2021-01-25 at 1 32 32 PM

#### How to reproduce the bug

1. Create a new chart from dataset which has single partition
2. Check adhoc filter operators
3. if you can choose use latest_partition, make sure it generate correct custom sql with `latest_partition` template.

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

cc @junlincc @zuzana-vej

### PR DESCRIPTION
**Pull request by villebro**
### SUMMARY
The prop `partitionColumn` was not being passed  to `AdhocFilterPopoverTrigger` in `addNewFilterPopoverTrigger` of `AdhocFilterControl`, causing the latest partition operator to be missing for datasources that support it. The override of `valueRender` seemed to be a leftover from some old time, so it was removed and `partitionColumn` added to the original `valueRenderer` that's created in the constructor. In addition, the operator dropdown showed irrelevant operators, causing the operator count to be inflated. Also fixed a typo ("operators(s)" to "operator(s)") along with relevant translations.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before: Partition operator is missing from dropdown. Also notice how the dropdown shows 13 operators, despite only 11 being visible:
before

After
Partition operator pops up if column supports it. The placeholder is also updated to reflect the new operator count after the column has been selected:
after

### ADDITIONAL INFORMATION

- [x] Has associated issue: closes #12752
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/explore/components/controls/FilterControl/AdhocFilterControl.jsx [hunk 1]
```diff
@@ -128,14 +128,14 @@ class AdhocFilterControl extends React.Component {
                 partitions.cols &&
                 Object.keys(partitions.cols).length === 1
               ) {
-                const partitionColumn = partitions.cols[0];
+                this.setState({ partitionColumn: partitions.cols[0] });
```
Comment (kgabryje) [inline superset-frontend/src/explore/components/controls/FilterControl/AdhocFilterControl.jsx:131]: I think we should include `partitionColumn` in state declaration in constructor

**Comment by kgabryje** [comment]
1 nit, other than that LGTM 👍

**Review by ktmud — APPROVED** [review]
lgtm

**Comment by kgabryje** [comment]
LGTM

**Review by kgabryje — APPROVED** [review]
