### PR TITLE
fix(theming): Theming visual fixes p5

### LINKED ISSUE #34604: Inconsistent Primary/Secondary Button Order in Pages within "Security" Section (Roles, Users, Groups)
## Screenshot
Example of inconsistent button order (primary on the left):
Image
Image
Image

Example of consistent button order (primary on the right):
Image

## Description

There is an inconsistency in the placement of primary and secondary buttons on multiple pages within the Security section of the Settings.

On the Roles, Users, and Groups pages, the primary button appears on the left and the secondary on the right.

On the Row Level Security page (and in other pages like Themes and CSS Templates), the secondary button is on the left and the primary on the right, which seems to be the standard across the application.

If this inconsistency is not deliberate, I have a fix prepared and can open a PR to address it.

### PR DESCRIPTION
**Pull request by msyavuz**
### SUMMARY

Fix secondary button disabled colors:
Before:
image

After:
image

About section in right menu font size:
Before:
image

After:
image

Fixes the button positions on security views

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #34566 Fixes #34604
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/packages/superset-ui-core/src/components/DropdownContainer/DropdownContainer.tsx [hunk 1]
```diff
@@ -0,0 +1,395 @@
...
+                  />
+                </Button>
+              </Tooltip>
+            </Popover>
+          </>
+        )}
+      </div>
+    );
+  },
+);
```
Comment (msyavuz) [inline superset-frontend/packages/superset-ui-core/src/components/DropdownContainer/DropdownContainer.tsx:395]: This change is for webpack build errors importing and exporting dropdown container types

**Comment by alexandrusoare** [comment]
LGTM

**Review by alexandrusoare — APPROVED** [review]

**Comment by mistercrunch** [comment]
@msyavuz this need a rebase ...

**Comment by msyavuz** [comment]
@mistercrunch Just rebased, this should be good to go now.

**Review by geido — APPROVED** [review]
