### PR TITLE
fix: string aggregation is incorrect in PivotTableV2

### LINKED ISSUE #18572: PivotTable vs PivotTableV2. String aggregation is incorrect in PivotTableV2
When the Aggregation Column is a String/Text, PivotTableV2 fails to show the values, where as PivotTable correctly shows it.
For example, in SQL syntax, one can do MAX(filed_that_is_a_string), and it would show you just the value, but in case of PivotTableV2 it shows `Null`, `NaN`, `NaNUndefined`, depending on the aggregation option, and none of them work.

Here is how to reproduce the bug:

I used the public.FCC 2018 Survey Dataset and the following columns:
- `MAX(marital_status)` as the aggregation, or metric
- In case of PivotTableV2, Row is `is_self_employed` and Column is `bootcamp_attend`
- In case of PivotTable, `is_self_employed` is in GROUP BY, `bootcamp_attend` is in Column and `MAX(marital_status)` is in metric.
-  Follow the Screenshots attached to create a version of your own Chart and you will see PivotTable doesn't show the metric results, where it should.

#### Screenshots

PivotTableV2ScreenShot

PivotTableScreenshot

### Environment

(please complete the following information):

- browser type: Chrome
- superset version: HEAD of master branch: ac2545e357bff22697fb91aa6ce73eded1f12750
- python version: 3

Let me know what else you would like to see, I would try to provide.

### PR DESCRIPTION
**Pull request by diegomedina248**
### SUMMARY
The aggregation functions for PivotTableV2 only take into account numeric values.
This PR adds support for strings, only for the aggregation functions that were supported on PivotTable originally.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/17252075/157701090-70ad6668-b319-485a-82cb-7edabcc042c6.mov

### TESTING INSTRUCTIONS
Follow the example described in the issue

### ADDITIONAL INFORMATION
Fixes #18572 
- [ ] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/utilities.js [hunk 1]
```diff
@@ -353,7 +370,7 @@ const baseAggregatorTemplates = {
                 throw new Error('unknown mode for runningStat');
             }
           },
-          format: formatter,
+          format: x => (typeof x === 'string' ? x : formatter(x)),
```
Comment (kgabryje) [inline superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/utilities.js:373]: Nit: since we do the same operation in line 241, could you extract that logic to a function?

**Review by kgabryje — APPROVED** [review]
Added 1 minor comment. Looks great!

**Review by kgabryje — CHANGES_REQUESTED** [review]
Just noticed 1 issue - selecting `Median` results in returning nulls
image

Also, selecting `List unique values` or `Sum as fraction of total` returns NaNs

**Comment by diegomedina248** [comment]
> Just noticed 1 issue - selecting `Median` results in returning nulls image
> 
> Also, selecting `List unique values` or `Sum as fraction of total` returns NaNs

@kgabryje I only made the changes for the ones present in v1. Can make it for all options if you're ok with it.

**Comment by yousoph** [comment]
@kgabryje can you re-review this when you get a chance? thanks!

**Review by kgabryje — APPROVED** [review]
Lgtm, thanks for the fix... and sorry for a very late review
