### PR TITLE
fix(localization): pybabel doesn't extract plural forms from frontend 

### LINKED ISSUE #21701: Plural forms are not compiled from .tsx files to messages.pot for translation
#### How to reproduce the bug

1. There is a file(example): 
```
/superset-frontend/src/components/ErrorMessage/DatabaseErrorMessage.tsx
```
image
2. Run the following command
```
pybabel extract -F superset/translations/babel.cfg -o superset/translations/messages.pot -k _ -k __ -k t -k tn -k tct .
```
### Expected results
message.pot file contains the following lines
photo_2022-10-05_14-04-32

### Actual results
message.pot file is missing the following lines
photo_2022-10-05_14-04-35

### Environment

- browser type and version: Google Chrome 98.0.4758.102
- superset version: v2.0.0rc2
- python version: Python 3.10.0
- node.js version: v16.15.1

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Plure forms from .py files are exported correctly

### PR DESCRIPTION
**Pull request by artemonsh**
### SUMMARY

Currently there is an issue with the plural forms on the frontend. At first, let's take a look at this code: https://github.com/apache/superset/blob/7d8fff87b55a2276b7e287772a654c3c63f5b2ce/superset-frontend/src/explore/components/controls/DndColumnSelectControl/DndColumnSelect.tsx#L206-L210 
It is expected that while extracting these strings into `.po` file using `babel-update.sh` they should look like this:
```
msgid "Drop a column here or click"
msgid_plural "Drop columns here or click"
msgstr[0] ""
msgstr[1] ""
```
or this:
```
msgid "Drop a column here or click"
msgid_plural "Drop columns here or click"
msgstr[0] ""
msgstr[1] ""
msgstr[2] ""
```
depending on the number of plural forms in the language. For instance, English and French have 2 plural forms and Russian has 3.

But in reality none of the `.po` files contain plural forms. For instance, `.po` file for French translations, which has 2 plural forms https://github.com/apache/superset/blob/7d8fff87b55a2276b7e287772a654c3c63f5b2ce/superset/translations/fr/LC_MESSAGES/messages.po#L25 does not contain the desired syntax for translating both of forms: https://github.com/apache/superset/blob/7d8fff87b55a2276b7e287772a654c3c63f5b2ce/superset/translations/fr/LC_MESSAGES/messages.po#L4873-L4874

The solution to this issue is simple and is offered in this PR. [This is the only official source I have found to prove my changes](https://github.com/python-babel/babel/blob/a45e25e3125f6ee0a9f32387545df318b0b3b2d0/babel/messages/extract.py#L33), but I found same solutions on some russian websites.

### TESTING INSTRUCTIONS

Go to the root directory of superset and run `./scripts/babel-update.sh`.

### ADDITIONAL INFORMATION

- [x] Has associated issue: closes #21701
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: scripts/babel_update.sh [hunk 1]
```diff
@@ -45,7 +45,7 @@ pybabel extract \
   --sort-output \
   --copyright-holder=Superset \
   --project=Superset \
-  -k _ -k __ -k t -k tn -k tct .
+  -k _ -k __ -k t -k tn:1,2 -k tct .
```
Comment (villebro) [inline scripts/babel_update.sh:48]: Bycatch - we probably don't need `-k tct` here as I don't believe we even have such a translator function, but I suppose it doesn't matter that much.

**Review by villebro — APPROVED** [review]
LGTM and confirmed to work as expected.
