### PR TITLE
fix(native-filters): show error if default value query failed

### LINKED ISSUE #14937: [native filter]configuration on broken dataset default value timeout
https://user-images.githubusercontent.com/67837651/120393265-7c620f80-c2e6-11eb-9df8-f00c60ed2811.mov

1. Current behavior:
When user create a new filter using a dataset that is either broken or with columns names that have been changed, user can not set default value(filter). In this case, `OrderDate` as time column in the dataset was renamed to `order_date`
Expected behavior:
When user create a new filter and check the Filter has default value checkbox, Superset is able to detect/scan all the available values in the selected filter column, even if the dataset has been altered.

Alternative: show the Cannot load error earlier in the modal, set spinning timeout to 60s.

### PR DESCRIPTION
**Pull request by villebro**
### SUMMARY
Currently the default value picker will show an eternal spinner if the query errors out.
Closes https://github.com/apache/superset/issues/14937 

### BEFORE
Previously the spinner would spin forever if the query returned an error:
image

### AFTER
Now a proper error is shown:
image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by junlincc — COMMENTED** [review]
LGTM 🟢 
Screen Shot 2021-06-09 at 1 40 09 PM

File: superset-frontend/src/dashboard/components/nativeFilters/FiltersConfigModal/FiltersConfigForm/FiltersConfigForm.tsx [hunk 1]
```diff
@@ -345,36 +347,45 @@ const FiltersConfigForm = (
       defaultValueQueriesData: null,
       isDataDirty: false,
     });
+    setError('');
```
Comment (suddjian) [inline superset-frontend/src/dashboard/components/nativeFilters/FiltersConfigModal/FiltersConfigForm/FiltersConfigForm.tsx:350]: Might be cleaner to make a wrapper function `setFilterQueryResult` that calls both `setNativeFilterFieldValues` and `setError` since they are always called together.

As well as setting the value to null when there is an error maybe?

**Review by suddjian — APPROVED** [review]
