### PR TITLE
fix(sqllab): Invalid start date

### LINKED ISSUE #24790: SQL lab shows invalid date for Started column in Query History
#### How to reproduce the bug

1. Go to 'SQL Lab' and run a query
2. Click on the 'Query History' tab
3. Look at the values of to 'Started' column
4. See the "Invalid date" written

### Expected results

proper time should be shown as per [the current code](https://github.com/apache/superset/blob/master/superset-frontend/src/SqlLab/components/QueryTable/index.tsx#L216) 

### Actual results

"invalid date" is shown

#### Screenshots

image

### Environment

(please complete the following information):

- browser type and version: Chrome and Mozilla
- superset version: 3.0.0.rc1
- python version: 3.9.x
- node.js version: NA
- any feature flags active: NA

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for Python stack traces and included them here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of the superset.
- [x] I have checked the issue tracker for the same issue and haven't found one similar.

### Additional context

The current output only shows time which is not useful if we want to see queries more than a day old. 
While fixing this, request to add the date as well in the output.

### PR DESCRIPTION
**Pull request by justinpark**
### SUMMARY
Fixes #24790

Since /updated_since api migrate to v1 in #22611 , the startDttm format has been changed from a number to a string.

|api/v1|legacy api|
|--|--|
|Superset|superset-dev_-_Airbnb_-_Slack|

Similar to #19605, it fails the conversion to a moment object. Since the Flask’s JSON serialization of decimals casts it to a string is actually correct as it preserves precision, so the frontend should expect strings.
This commit adds the extra parse logic in sqllab query sync to handle the floating value in the string format.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

After:

https://user-images.githubusercontent.com/1392866/264449407-c2015fe7-d1ef-48b4-9c98-60de6aa27c9c.png

Before:

https://user-images.githubusercontent.com/57723564/255794908-2b4a9005-00fc-4adc-95b0-d7a8a0fdee09.png

### TESTING INSTRUCTIONS
Go to SQLLab and run a query
Go to Query history and check the start date column

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/packages/superset-ui-core/src/connection/callApi/parseResponse.ts [hunk 1]
```diff
@@ -56,7 +56,10 @@ export default async function parseResponse<T extends ParseMethod = 'json'>(
       // `json-bigint` could not handle floats well, see sidorares/json-bigint#62
       // TODO: clean up after json-bigint>1.0.1 is released
       json: cloneDeepWith(json, (value: any) =>
-        value?.isInteger?.() === false ? Number(value) : undefined,
+        value?.isInteger?.() === false ||
```
Comment (john-bodley) [inline superset-frontend/packages/superset-ui-core/src/connection/callApi/parseResponse.ts:59]: @justinpark how is there any merit to casting this to a [Decimal](https://mikemcl.github.io/decimal.js/) as opposed to a `Number` or are these types typically not used by the Superset frontend?

Comment (justinpark) [reply superset-frontend/packages/superset-ui-core/src/connection/callApi/parseResponse.ts]: Good point. I also concerned about the data inaccuracy issue since this will convert all float numbers in Number(even Decimal) `234020423042304302.402` vs `234020423042304300 (=Number(234020423042304302.402))`

I reverted this json-bigint modification and made the extra date value conversion logic in SqlLab instead.

**Comment by john-bodley** [comment]
@justinpark I think your current implementation is safer, i.e., casting specific instances of stringified decimals to a `Number` as opposed to all.

**Comment by mdeshmu** [comment]
@justinpark can you please also add a date component to it as it is really difficult to identify what date query ran on with just time displayed.

**Comment by justinpark** [comment]
@mdeshmu I added the date value in the format.
Screenshot 2023-08-31 at 10 07 55 AM

**Comment by mdeshmu** [comment]
`2023-08-31 19:37:53+05:30`

@justinpark thanks for adding the date. We are using the above format in the Query History Tab. 
Do we wanna keep it the same here for the sake of consistency?
I am fine with either though :)

**Review by michael-s-molina — APPROVED** [review]
LGTM. Thanks for the fix @justinpark!

I like @mdeshmu suggestion to make the time format consistent with SQL -> Query History 👍🏼

**Comment by mdeshmu** [comment]
@michael-s-molina Please include this PR in 3.0. Thanks.

**Comment by justinpark** [comment]
> justinpark thanks for adding the date. We are using the above format in the Query History Tab. Do we wanna keep it the same here for the sake of consistency? I am fine with either though :)

Sounds good. I changed to same format as Query History as well as from `MM/DD/YYYY` to `L` (which is like 09/04/1986 in local format, so date value comes first in eu countries)

Screenshot 2023-09-01 at 10 04 27 AM
