### PR TITLE
[vis] bug num improvements

### LINKED ISSUE #1766: [vis] big number w/trendline doesn't show last date on axis
- show last date on axis
- show date in tooltip when hovering over trend line

screenshot 2016-12-05 13 41 48

### PR DESCRIPTION
**Pull request by ascott**
- use roboto font for ticks
- add tooltip on trend line hover
- show min/max ticks on xaxis
- show fewer ticks when slice width is smaller
- make big num and subhead text scale depending on width of container
- adjust margins based on yAxisLabel widths

before:

screenshot 2017-03-29 23 19 45
screenshot 2017-03-29 23 18 17
screenshot 2017-03-29 23 15 18

after:
screenshot 2017-04-04 18 14 34
screenshot 2017-04-04 18 14 09
screenshot 2017-04-04 18 13 56
screenshot 2017-04-04 18 16 30

fixes https://github.com/airbnb/superset/issues/1766

### CODE REVIEW

File: superset/assets/visualizations/big_number.js [hunk 1]
```diff
@@ -39,7 +48,7 @@ function bigNumberVis(slice, payload) {
   const dateExt = d3.extent(data, (d) => d[0]);
   const valueExt = d3.extent(data, (d) => d[1]);
 
-  const margin = 20;
+  const margin = 30;
```
Comment (mistercrunch) [inline superset/assets/visualizations/big_number.js]: Should the margin be relative? 30 becomes relatively big when using the smallest 1by1 cell in the dashboard

File: superset/assets/visualizations/big_number.js [hunk 2]
```diff
@@ -3,6 +3,15 @@ import { formatDate } from '../javascripts/modules/dates';
 
 require('./big_number.css');
 
+function getNumTicks(data) {
```
Comment (mistercrunch) [inline superset/assets/visualizations/big_number.js]: The number of ticks should probably be a function of the width and/or height. The slice object has a `.width()` method you can use

File: superset/assets/visualizations/big_number.js [hunk 3]
```diff
@@ -59,36 +68,41 @@ function bigNumberVis(slice, payload) {
...
-  .attr('class', 'big')
-  .attr('alignment-baseline', 'middle')
-  .attr('id', 'bigNumber')
-  .style('font-weight', 'bold')
-  .style('cursor', 'pointer')
-  .text(f(v))
-  .style('font-size', d3.min([height, width]) / 3.5)
-  .style('text-anchor', 'middle')
-  .attr('fill', 'black');
+   .attr('opacity', 1)
```
Comment (mistercrunch) [inline superset/assets/visualizations/big_number.js]: no a biggy, but I'm surprised to see an odd indent. I'd go aligned or 2 spaces in for method chaining.

**Comment by mistercrunch** [comment]
It could be good to have some sort of generic `fitText(s, width, fontinfo)` function in `utils`. I'm not exactly sure what it should receive and return, but I have the intuition that we need that in many places.

File: superset/assets/visualizations/big_number.js (hunk 2 above)
Comment (ascott) [inline superset/assets/visualizations/big_number.js]: good call

File: superset/assets/visualizations/big_number.js (hunk 1 above)
Comment (ascott) [inline superset/assets/visualizations/big_number.js]: 👍

Comment (ascott) [inline superset/assets/visualizations/big_number.js]: this should really be dependent on the width of the y axis label. working on a fix for that.

**Comment by ascott** [comment]
thanks for the review @mistercrunch. can you plz take another look...

**Comment by mistercrunch** [comment]
LGTM!

**Comment by lilila** [comment]
I have an issue with the new version: 
When I choose "i" as format to print a simple integer the sub-header appears on the number. Do you have an advice to solve this?

It is the same issue with big number and big number with trend line

screen shot 2017-04-05 at 09 12 01

screen shot 2017-04-05 at 09 11 41

**Comment by lilila** [comment]
One more point: Do you think it would be possible to fix the font size for the dashboard. 

Now, the size depends on the number itself so small numbers appear bigger .
Before the modifications all numbers appeared with the same font size , it looks nicer .

**Comment by mistercrunch** [comment]
@ascott should we revert?

**Comment by ascott** [comment]
thanks @lilila for your feedback. i fixed the too large single digit issue. i am not seeing the issue with the overlapping subheader text, but i will take another look.
