### PR TITLE
[SQL Lab] Show warning when user used up localStorage

### LINKED ISSUE #6909: large data not on SQLLAB
<

large data result from giving error sqllab 

  ret = select.select(self.wait_fds, [], [], timeout)
OverflowError: timestamp too large to convert to C _PyTime_t
[2019-02-18 12:04:49 +0000] [8828] [INFO] Worker exiting (PID: 8828)
[ERROR] Exception in worker process
!--

- [* ] I have checked the superset logs for python stack traces and included it here as text if there are any.
- [* ] I have reproduced the issue with at least the latest released version of superset.
- [* ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version

0.28.1
### Expected results

result not showing on sqllab 
### Actual results
no output 

### Steps to reproduce

screen shot 2019-02-18 at 6 24 13 pm

### PR DESCRIPTION
**Pull request by graceguo-supercat**
### CATEGORY

Choose one

- [x] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
See https://github.com/apache/incubator-superset/issues/6909#issuecomment-490682323
53304389-a6703000-389a-11e9-8d9e-ebbd6f2fbe87

SQL Lab stores queries and results in browser's localStorage. But when localStorage space is used up, browser may show error, or run very slow then crash.

This PR tries to address this issue by following:
- if existed query's `startDttm` > 24 hours, remove its query's `results` attribute from localStorage.
- when they used up 90% of suggested limit, adding warning message to user.
The upper limit for localStorage varies by browser type (and version). From this discussion: https://stackoverflow.com/questions/2989284/what-is-the-max-size-of-localstorage-values
I choose **5120KB** as limit. In my local test, Chrome can hold up to 10MB localStorage data. But when data size > 5MB, it runs really slow.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Screen Shot 2019-05-29 at 1 43 45 PM

### TEST PLAN
CI and manual test in SQL Lab.

### ADDITIONAL INFORMATION
Fixes https://github.com/apache/incubator-superset/issues/6909

### REVIEWERS
@michellethomas @williaster

### CODE REVIEW

**Comment by sylvia-tomiyama** [comment]
Made some quick grammar fixes:

> SQL Lab uses your browser's local storage to store queries and results. Currently, you are using ___ out of ___ storage space. To keep SQL Lab from crashing, please delete some query tabs. You can re-access these queries by using the Save feature _before_ you delete the tab. Note that you will need to close other SQL Lab windows before you do this.

**Comment by michellethomas** [comment]
Fixes: #7591

File: superset/assets/src/SqlLab/constants.js [hunk 1]
```diff
@@ -43,3 +43,6 @@ export const TIME_OPTIONS = [
   '90 days ago',
   '1 year ago',
 ];
+
+// 24 hours
+export const LOCALSTORAGE_MAX_QUERY_AGE = 24 * 60 * 60 * 1000;
```
Comment (etr2460) [inline superset/assets/src/SqlLab/constants.js]: `LOCALSTORAGE_MAX_QUERY_AGE_MS`?

File: superset/assets/src/SqlLab/components/App.jsx [hunk 2]
```diff
@@ -21,27 +21,39 @@ import PropTypes from 'prop-types';
...
+
 class App extends React.PureComponent {
   constructor(props) {
     super(props);
     this.state = {
       hash: window.location.hash,
       contentHeight: '0px',
     };
+
+    this.showLocalStorageUsageWarning = debounce(this.showLocalStorageUsageWarning, 2000);
```
Comment (etr2460) [inline superset/assets/src/SqlLab/components/App.jsx]: Should `2000` be defined as a constant too? I'm not really sure

**Review by etr2460 — COMMENTED** [review]
A few naming nits, but otherwise everything seems to make sense!

**Comment by graceguo-supercat** [comment]
all comments are fixed.

File: superset/assets/src/SqlLab/constants.js [hunk 3]
```diff
@@ -48,3 +48,13 @@ export const TIME_OPTIONS = [
...
+
+// kilobyte storage
+export const KB_STORAGE = 1024;
+export const BYTES_PER_CHAR = 2;
+
+// browser's localStorage max usage constants
+export const LOCALSTORAGE_MAX_QUERY_AGE_MS = 24 * 60 * 60 * 1000; // 24 hours
+export const LOCALSTORAGE_MAX_USAGE_KB = 5 * 1024; // 5M
+export const LOCALSTORAGE_WARNING_THRESHOLD = 0.9;
+export const LOCALSTORAGE_WARNING_MESSAGE_THROTTLE_MS = 8000; // warning type toast duration
```
Comment (graceguo-supercat) [inline superset/assets/src/SqlLab/constants.js]: for danger type toast, it has 8000 MS duration. if we set lower throttle threshold, user will see multiple message box, which is also annoying.
https://github.com/apache/incubator-superset/blob/1dd4d7a587a55525ff14e1e051d268adccbc15a1/superset/assets/src/messageToasts/actions/index.js#L77

File: superset/assets/src/SqlLab/constants.js [hunk 4]
```diff
@@ -48,3 +48,13 @@ export const TIME_OPTIONS = [
...
 export const SQL_EDITOR_GUTTER_MARGIN = 3;
 export const SQL_TOOLBAR_HEIGHT = 51;
+
+// kilobyte storage
+export const KB_STORAGE = 1024;
+export const BYTES_PER_CHAR = 2;
+
+// browser's localStorage max usage constants
+export const LOCALSTORAGE_MAX_QUERY_AGE_MS = 24 * 60 * 60 * 1000; // 24 hours
+export const LOCALSTORAGE_MAX_USAGE_KB = 5 * 1024; // 5M
```
Comment (etr2460) [inline superset/assets/src/SqlLab/constants.js]: I assume this is the same for all browsers?

**Review by etr2460 — APPROVED** [review]
LGTM!

File: superset/assets/src/SqlLab/constants.js (hunk 4 above)
Comment (graceguo-supercat) [reply superset/assets/src/SqlLab/constants.js]: yes. Superset doesn't have much browser-specific code. Most features we only target Chrome.

Comment (mistercrunch) [reply superset/assets/src/SqlLab/constants.js]: As a project I think we should target "modern browsers", whatever that means today and tomorrow.
