### PR TITLE
[explore] fix height in embed mode

### LINKED ISSUE #1624: Iframe embedding misaligned
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.13.2 from https://hub.docker.com/r/amancevice/superset/

### Expected results

Charts show up nicely in iframes.

### Actual results

Charts are displayed too low or too big, and as a result half of them falls below the bottom of the `iframe`.

superset-embedding

### Steps to reproduce

Load example data. Explore the charts on the World Bank dashboard. Copy the embedding links. Resulting HTML:

```
<html>
  <body style="background: salmon">

    <iframe src="http://localhost:8088/superset/explore/table/2/?metric=sum__SP_POP_TOTL&add_to_dash=false&flt_col_0=&until=2011-01-01&datasource_id=2&datasource_name=wb_health_population&force=false&since=2011-01-01&groupby=region&groupby=country_name&having=&granularity_sqla=year&slice_name=Rural+Breakdown&time_grain_sqla=Time+Column&new_slice_name=&datasource_type=table&rdo_save=overwrite&flt_eq_0=&secondary_metric=sum__SP_RUR_TOTL&save_to_dashboard_id=&standalone=true&previous_viz_type=sunburst&flt_op_0=in&goto_dash=false&viz_type=sunburst&collapsed_fieldsets=&new_dashboard_name=&userid=1&row_limit=5000&where="
            width="600"
            height="400"
            seamless frameBorder="0" scrolling="no">
    </iframe>

    <iframe src="http://localhost:8088/superset/explore/table/2/?metric=sum__SP_RUR_TOTL_ZS&show_bubbles=y&show_bubbles=false&add_to_dash=false&flt_col_0=&until=2014-01-02&country_fieldtype=cca3&datasource_id=2&datasource_name=wb_health_population&force=false&since=2014-01-01&having=&granularity_sqla=year&goto_dash=false&time_grain_sqla=Time+Column&new_slice_name=&datasource_type=table&rdo_save=overwrite&flt_eq_0=&secondary_metric=sum__SP_POP_TOTL&save_to_dashboard_id=&standalone=true&previous_viz_type=world_map&flt_op_0=in&entity=country_code&viz_type=world_map&slice_name=%25+Rural&collapsed_fieldsets=&new_dashboard_name=&userid=1&max_bubble_size=25&where="
            width="600"
            height="400"
            seamless frameBorder="0" scrolling="no">
    </iframe>

  </body>
</html>
```

### PR DESCRIPTION
**Pull request by mistercrunch**
Currently the `height` param in the embed modal only affect the height of the iframe itself, not the height of the chart contained in the iframe. This PR addresses this issue by adding a height parameter to the querystring in the url.

fixes https://github.com/airbnb/superset/issues/1624

### CODE REVIEW

File: superset/assets/javascripts/explore/components/EmbedCodeButton.jsx [hunk 1]
```diff
@@ -25,15 +25,21 @@ export default class EmbedCodeButton extends React.Component {
...
-        height="${this.state.height}"
-        seamless frameBorder="0" scrolling="no">
-      </iframe>`;
+    const srcLink = (
+      window.location.origin +
+      this.props.slice.data.standalone_endpoint +
+      `&height=${this.state.height}`
+    );
+    return (
+      '<iframe\n' +
```
Comment (ascott) [inline superset/assets/javascripts/explore/components/EmbedCodeButton.jsx]: thanks for fixing this formatting too.

**Comment by ascott** [comment]
LGTM 🚢
