### PR TITLE
[fix] Enforcing main dttm column

### LINKED ISSUE #3629: [Explore] Regression: Main Datetime Column not chosen automatically
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.3

### Expected results
When creating a new slice, the _Time Column_ is automatically set to the one that is defined as _Main Datetime Column_ for the respective Datasource table.

This was the behavior in superset 0.15.4

### Actual results
A time column different from the Main Datetime Column is chosen. I don't exactly know by which criterion, though.

### Steps to reproduce
Explore a table which features several time columns and which has a _Main Datetime Column_ set. You may have to alter the setting of _Main Datetime Column_, maybe, as it may happen, that the right column is picked in Explore view just by chance...

### PR DESCRIPTION
**Pull request by john-bodley**
This PR ensures that if defined the "Main Datetime Column" is used as the default value. Previously this value was being ignored and thus for datasource with multiple temporal columns a sub-optimal choice may occur, i.e., using a non-partitioned column.

to: @GabeLoins @graceguo-supercat @michellethomas @mistercrunch  @williaster 

closes #3629

### CODE REVIEW

**Review by michellethomas — APPROVED** [review]

**Comment by rumbin** [comment]
This PR would remedy #3629, I suppose.

Thanks a lot!

File: superset/assets/src/explore/controls.jsx [hunk 1]
```diff
@@ -846,6 +841,12 @@ export const controls = {
       const newState = {};
       if (state.datasource) {
         newState.options = state.datasource.columns.filter(c => c.is_dttm);
+        newState.default = null;
```
Comment (mistercrunch) [inline superset/assets/src/explore/controls.jsx]: Not related to your PR: `props` would be a better variable name than `newState` in this method.

**Comment by mistercrunch** [comment]
LGTM

File: superset/assets/src/explore/controls.jsx (hunk 1 above)
Comment (john-bodley) [reply superset/assets/src/explore/controls.jsx]: @mistercrunch I've renamed `newState` to `props`.
