### PR TITLE
fix: More tweaks needed after adding Doctype tag

### LINKED ISSUE #10589: Filter box chart does not show any rows
The filter box chart does not show any rows on explore, yet it works on dashboard views

### Expected results

Filter box actually shows a dropdown list with the populated values from the dataset query

### Actual results

Nothing is shown

#### Screenshots

This is the default examples Region filter:

Screenshot 2020-08-12 at 14 20 36

#### How to reproduce the bug

1. Go to charts
2. Click on explore chart
3. No dropbox is rendered

### Environment

(please complete the following information):

- superset version: 83af9d12f83ad52036d5e3eb074b6c6d9744d530 (almost current master)
- python version: 3.7

### Checklist

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by rusackas**
### SUMMARY

Mainly, fixes a bug with the FilterBox in the Explore view. Also consolidates a few bits of styling, and adds 'px' to some font size styles that should have had them in the first place.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

After screenshots, now working:
image

image
image

### ADDITIONAL INFORMATION

- [x] Has associated issue: bug found by @ktmud, as commented in #10302 , fixes #10589
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by nytai — APPROVED** [review]

File: superset-frontend/src/chart/Chart.jsx [hunk 1]
```diff
@@ -193,12 +198,12 @@ class Chart extends React.PureComponent {
         onError={this.handleRenderContainerFailure}
         showMessage={false}
       >
-        <div
-          className={`chart-container ${isLoading ? 'is-loading' : ''}`}
-          style={containerStyles}
-        >
+        <Styles className={`chart-container`}>
```
Comment (ktmud) [inline superset-frontend/src/chart/Chart.jsx:201]: Can use `className="chart-container"`. I'm surprised ESLint didn't catch this.

File: superset-frontend/src/chart/Chart.jsx [hunk 2]
```diff
@@ -193,12 +198,12 @@ class Chart extends React.PureComponent {
...
           <div className={`slice_container ${isFaded ? ' faded' : ''}`}>
-            <ChartRenderer {...this.props} />
+            <ChartRenderer
+              {...this.props}
+              data-test={JSON.stringify(this.props)}
```
Comment (ktmud) [inline superset-frontend/src/chart/Chart.jsx:205]: Do we need the full `props` for test?

**Review by ktmud — APPROVED** [review]

**Comment by rusackas** [comment]
Fixes https://github.com/apache/incubator-superset/issues/10589
