### PR TITLE
[bugfix] cannot add options to FilterBox

### LINKED ISSUE #6227: Creating a new option in Filter chart doesn't work
Make sure these boxes are checked before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version

Version from master

### Expected results

When I select a value that is not in result, new option is created and all dependent charts are filtered with this new option.

### Actual results
When I select a value that is not in result, no value is not added. This value is ignored and doesn't show in UI and dependent charts are not filtered.

### Steps to reproduce
- Build master version
- Create filter with more values than is your limit
- Try to add new option

### PR DESCRIPTION
**Pull request by mistercrunch**
closes https://github.com/apache/incubator-superset/issues/6227

### CODE REVIEW

**Review by xtinec — APPROVED** [review]
LGTM.

File: superset/assets/src/visualizations/FilterBox/FilterBox.jsx [hunk 1]
```diff
@@ -178,8 +178,7 @@ class FilterBox extends React.Component {
     // Add created options to filtersChoices, even though it doesn't exist,
     // or these options will exist in query sql but invisible to end user.
     Object.keys(selectedValues)
-      .filter(key => !selectedValues.hasOwnProperty(key)
-        || !(key in filtersChoices))
+      .filter(key => selectedValues.hasOwnProperty(key))
```
Comment (kristw) [inline superset/assets/src/visualizations/FilterBox/FilterBox.jsx]: Add `&& (key in filtersChoices)`

Thanks for fixing this. This was due to my refactor (#5789) that reversed the logic so the correct logic should be negation of 
```js
!selectedValues.hasOwnProperty(key) || !(key in filtersChoices)
```

which is

```js
selectedValues.hasOwnProperty(key) && (key in filtersChoices)
```

**Review by kristw — APPROVED** [review]
