### PR TITLE
fix(explore): reordering columns with dnd sometimes glitching

### LINKED ISSUE #16317: [dnd][dnd hybrid] reordering by dnd is not accurate and popover is not matching when the reordering fail
This issue is observed in dnd mode and dnd hybrid mode
When doing reordering for multiple times with dnd, it become inaccurate and moving one metric sometimes was moving other metric, and when the reordering behavior is incorrect, the popover is not matching the column and metrics.

### Expected results
reordering is accurate and popover will match the metric after reordering

### Actual results

reordering is not accurate and popover did not match the metric after reordering is wrong

#### Screenshots

[dnd hybrid FF] reordering issue

https://user-images.githubusercontent.com/81597121/129855245-8f134d6c-df58-4db7-a00f-dd024da52c92.mov

[dnd FF only] reordering issue and popover did not match up with metric once the reordering is wrong

https://user-images.githubusercontent.com/81597121/129855372-f474184e-9f41-403b-8619-404ec28942c3.mov

#### How to reproduce the bug

1. add multiple metric or columns to fields
2. reordering multiple times by dnd
3. observe reordering error
4. when ordering error is observed, check popover for metrics

### Environment

(please complete the following information):

- superset version: latest master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
When user added 3 or more columns to a control that accepts only columns (such as Group by) and started reordering using drag and drop, the feature was starting to glitch after the first sorting.
The first dragging and dropping a column to reorder worked correctly. Due to memoization, when user wanted to reorder the second time, the drop index from the first reordering was being used as a start index of the next reordering. That caused a glitch, which resulted in columns "jumping" and changing their positions incorrectly.

Another issue related to reordering with dnd happened in filters and metrics controls. After reordering, when user clicked a metric label, the popover's content was stale - it showed the column name and aggregate of a metric that was at current index before reordering. The source of the problem seems to be antd popover's internal memoization, which we can switch off by setting a prop `destroyTooltipOnHide`. Before, that prop was set only for popover used to create a new metric or filter, so that user doesn't see old selections after creating a metric/filter and clicking again. Now we set that prop also for popovers used for editing metrics and filters.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before: see linked issue
After:
https://user-images.githubusercontent.com/15073128/129889010-9e5c5a1e-28f7-41e2-a3b0-46bf6d446b86.mov

### TESTING INSTRUCTIONS
0. Enable dnd feature flag
1. Open a chart and add 3 or more columns
2. Reorder the columns by drag and dropping and verify that it works correctly

### ADDITIONAL INFORMATION

- [x] Has associated issue: fixes #16317 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC @junlincc @jinghua-qa

### CODE REVIEW

**Comment by kgabryje** [comment]
/testenv up FEATURE_ENABLE_EXPLORE_DRAG_AND_DROP=true FEATURE_ENABLE_DND_WITH_CLICK_UX=true

File: superset-frontend/src/explore/components/controls/DndColumnSelectControl/OptionWrapper.tsx [hunk 1]
```diff
@@ -63,15 +63,11 @@ export default function OptionWrapper(
...
-      type,
-    }),
-    [index, type],
-  );
   const [{ isDragging }, drag] = useDrag({
-    item,
+    item: {
+      type,
+      dragIndex: index,
+    },
```
Comment (villebro) [inline superset-frontend/src/explore/components/controls/DndColumnSelectControl/OptionWrapper.tsx:70]: It appears we're a few versions behind `react-dnd` (now on 14; we're on 11). Apparently the deps can now be given as a param after spec:

image

https://react-dnd.github.io/react-dnd/docs/api/use-drag

Might be a good TODO for when we bump this the next time.

**Review by villebro — APPROVED** [review]
LGTM!

File: superset-frontend/src/explore/components/controls/DndColumnSelectControl/OptionWrapper.tsx (hunk 1 above)
Comment (kgabryje) [reply superset-frontend/src/explore/components/controls/DndColumnSelectControl/OptionWrapper.tsx:70]: Good to know!

**Review by jinghua-qa — APPROVED** [review]
LGTM

https://user-images.githubusercontent.com/81597121/129937159-ba757dd3-e025-4923-a004-54fd8667f895.mov

https://user-images.githubusercontent.com/81597121/129937325-82f400d7-afed-4cee-b205-10e265f84b4b.mov

**Comment by henryyeh** [comment]
🏷️ 2021.31
