### PR TITLE
fix(dashboard): prevent crash on invalid CSS selectors in CSS templates

### LINKED ISSUE #33970: Bug Report 🐛: CSS Template Editor Crashes with Invalid Selector
### **Bug:** 
Using the CSS Template editor in Apache Superset throws a runtime error and fails to apply the template when a CSS block is added that includes invalid syntax — particularly CSS-like content inside template blocks or strings that mimic selectors.

### **Environment:**
- OS: Windows 11 with WSL2 (Ubuntu 22.04), MacOS Sequoia.
- Superset Version: 0.0.0-dev (built from latest master).
- Install Method: Forked the repository, cloned it and running via Docker.
- Browser: Chrome.

### **Steps to Reproduce:**
- Go to a new Dashboard -> Edit CSS -> Load a CSS Template
- Uncaught Runtime error as the above image. The app crashes with a runtime error due to invalid CSS being interpreted as a DOM selector via querySelector.

### **Additional Context:**
The bug arises because the key used in the Ant Design <Menu> component was incorrectly set to template.css, which is the full CSS string. When passed as a key, this raw CSS gets misused — especially when the string contains selector-like syntax. This causes the querySelector in the frontend to interpret it as a DOM selector, leading to a runtime crash.

### Screenshots/recordings

Image

### Superset version

master / latest-dev

### Python version

3.10

### Node version

18 or greater

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by HarshithGamini**
### Summary
This PR fixes a crash in the CSS Template editor where invalid CSS (like malformed selectors) caused a runtime error during querySelector evaluation.

Keys should be simple, stable and unique strings or numbers used for identification.

### Related Issue
Fixes #33970

### Screenshot
[Attach any screenshot or recording if needed]

### Test Plan
- Navigate to a Dashboard → Edit CSS
- Load a CSS Template (even with potentially broken or malformed CSS)
- Expected: App no longer crashes; editor handles input gracefully

### Before/After
Before: Runtime crash  
image

After: App gracefully handles invalid CSS; no runtime crash
image

### CODE REVIEW

**Comment by HarshithGamini** [comment]
@rusackas, here’s the PR for the CSS template crash fix. Appreciate a review when you get a chance.

File: superset-frontend/src/dashboard/components/CssEditor/index.tsx [hunk 1]
```diff
@@ -103,8 +103,13 @@ class CssEditor extends PureComponent<CssEditorProps, CssEditorState> {
   }
 
   changeCssTemplate(info: { key: Key }) {
-    const keyAsString = String(info.key);
-    this.changeCss(keyAsString);
+    const templateName = String(info.key);
+    const selectedTemplate = this.state.templates?.find(
+      template => template.label === templateName,
+    );
```
Comment (msyavuz) [inline superset-frontend/src/dashboard/components/CssEditor/index.tsx]:
```suggestion
    const selectedTemplate = this.state.templates?.find(
      template => template.label === info.key,
    );
```

**Review by msyavuz — COMMENTED** [review]
Thanks for this!

**Comment by HarshithGamini** [comment]
@msyavuz, The failing test (`UploadDataModal.test.tsx`) seems unrelated to this PR. I haven't touched anything related to UploadDataModal or upload logic. This appears to be a flaky test.

All other test suites are passing.

**Review by msyavuz — APPROVED** [review]
Yeah thats a flaky test. Thanks for this!
