### PR TITLE
fix(chart list): Facepile shows correct users when saving chart properties

### LINKED ISSUE #31592: In chart management, editing any chart properties may result in incorrect updates to the owner badge list
### Bug description

In chart management, editing any chart properties may result in incorrect updates to the owner badge list，It seems that the latest version 4.0 also has issues。

### Screenshots/recordings

de430b9ff19d4ddecc1fa6d4f6611cc
2e9eab87c2887e2f221e1ee2869efec

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

superset version： 3.1.3

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by ethan-l-geotab**
### SUMMARY

Looking to fix: https://github.com/apache/superset/issues/31592.
It's reproducible on all the test-env up environments. Add "Superset Admin" as user on a chart and then save shows the undefined undefined.

I just update the redux with the owner list back in it's original "shape".

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

first half is the broken, second half is working
fix-chart-list

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/31592
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by ethan-l-geotab** [comment]
/korbit-review.

File: superset-frontend/src/explore/components/PropertiesModal/index.tsx [hunk 1]
```diff
@@ -185,12 +185,24 @@ function PropertiesModal({
...
+      const newOwners = selectedOwnersArray.map((owner: any) => {
+        const nameParts = owner.label.split(' ');
+        const first_name = nameParts[0] || '';
+        const last_name = nameParts.length > 1 ? nameParts.slice(1).join(' ') : '';
+        return {
+          id: owner.value,
+          first_name,
+          last_name,
+        };
+      });
```
[the remark this answers is not in the document]
Comment (ethan-l-geotab) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx:199]: I think it's a pretty specific case where this one component handles owners in a specific way which when trying to update redux, the "shape" of the object is different, so i have to translate it back to the same shape which originally existed.

File: superset-frontend/src/explore/components/PropertiesModal/index.tsx [hunk 2]
```diff
@@ -185,12 +185,24 @@ function PropertiesModal({
         body: JSON.stringify(payload),
       });
       // update the redux state
+      // convert the tags to the format used in the selectOwners back to original redux format
+      const selectedOwnersArray = ensureIsArray(selectedOwners);
+      const newOwners = selectedOwnersArray.map((owner: any) => {
+        const nameParts = owner.label.split(' ');
+        const first_name = nameParts[0] || '';
+        const last_name = nameParts.length > 1 ? nameParts.slice(1).join(' ') : '';
```
[the remark this answers is not in the document]
Comment (rusackas) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: This is probably OK, but I'm _slightly_ nervous about things like middle names. This would mean if we have Michael J. Fox sign up, it'd be "Michael" "J. Fox" instead of "Michael J." "Fox."

Is there other first/last name logic currently in place, or is this a new concept?

[the remark this answers is not in the document]
Comment (ethan-l-geotab) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: I thought about that too actually. "Updating" only happens around user ID's. As for display, I'm on the same line as you where it's "probably okay". 

There is no real existing "full_name" split. I tried checking out how dashboards/dataset list handles it, but they're both different :(. 

I dont think there is a true way of doing it unless we retrieve it from the backend.

I have tried doing something like this in the backend to "pass ownership data" along with the put request 
and then just removing the modification to the owner field and using just the returned owner from the put request, but I'm not sure that's the best design either...
image
image
 
I've also tried seeing if I could sort of "cache" the load options and see if it was split there when im getting the eligible users to add as owners, but that won't work either because it's only `item.text` and makes no differentiation of first and last names.

[the remark this answers is not in the document]
Comment (rusackas) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: > There is no real existing "full_name" split. I tried checking out how dashboards/dataset list handles it, but they're both different :(.

This is what I was worried about. If there's any logic to be DRY'd up (moved to a util or something) that would be preferable than implementing another bit of inline logic.

**Comment by ethan-l-geotab** [comment]
@rusackas Hello, I went with a much more simple approach I saw use by datasets where i just make 1 get request to the resource and then update from the resource from the put request.

File: superset-frontend/src/explore/components/PropertiesModal/index.tsx [hunk 3]
```diff
@@ -179,20 +179,15 @@ function PropertiesModal({
...
-        ...res.json.result,
-        tags,
-        id: slice.slice_id,
-        owners: selectedOwners,
-      };
-      onSave(updatedChart);
+      res = await SupersetClient.get({
+        endpoint: `/api/v1/chart/${slice.slice_id}`,
+      });
+      onSave(res.json.result);
```
Comment (ethan-l-geotab) [inline superset-frontend/src/explore/components/PropertiesModal/index.tsx]: @rusackas so i was thinking about this again, and noticed that for datasets, there are actually multiple get requests. I was wondering if it was just better to return the data inside the put request as a response, or do it in a second get request.

**Comment by ethan-l-geotab** [comment]
Hey, can i get any updates on this?

**Comment by JZ6** [comment]
@rusackas we are running into this issue too, can this pr be merged, thanks

File: superset-frontend/src/explore/components/PropertiesModal/index.tsx (hunk 3 above)
Comment (rusackas) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: I don't have anything against an extra call, as long as it's not something that's going to happen a million times, like in a CRUD view (for obvious performance reasons). 

@michael-s-molina @justinpark @mistercrunch can provide a better second opinion here, perhaps.

**Comment by rusackas** [comment]
Hey! Sorry I went AWOL on the thread here :) I think we can likely merge this, pending a second opinion on the extra API call (probably not an issue). The main blocker at the moment is that there's a rebase needed, which I hope isn't too painful with the changes that have taken place in the tests.

File: superset-frontend/src/explore/components/PropertiesModal/index.tsx (hunk 3 above)
Comment (mistercrunch) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: shouldn't the PUT return the new object?

Comment (mistercrunch) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: @korbit-ai what do you think? REST api best practices on a PUT, return the new committed object?

Comment (mistercrunch) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: or @Copilot WDYT?

Comment (mistercrunch) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: how do you summon these things!? Which we had our buddy @claude in this repo ...

**Comment by JZ6** [comment]
> Hey! Sorry I went AWOL on the thread here :) I think we can likely merge this, pending a second opinion on the extra API call (probably not an issue). The main blocker at the moment is that there's a rebase needed, which I hope isn't too painful with the changes that have taken place in the tests.

should be rebased now

File: superset-frontend/src/explore/components/PropertiesModal/index.tsx (hunk 3 above)
Comment (rusackas) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: Hmmm... I thought @korbit-ai should do it. Maybe @copilot or @korbit or @dosu. C'mon bots!

Comment (rusackas) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: @ethan-l-geotab I see that CI is looking good again after your rebase, thanks! I think this part of the thread is the crux of whether we merge it now or not. Is getting/using the response from the PUT call doable? If so, that does seem like the more elegant approach, but if not, I have no personal objection to fixing the bug with the current approach.

**Comment by rusackas** [comment]
Looks technically mergeable. [This](https://github.com/apache/superset/pull/33392#discussion_r2288913534) (or the [bot version](https://github.com/apache/superset/pull/33392#discussion_r2263820617) thereof) seems to be the last standing question.

File: superset-frontend/src/explore/components/PropertiesModal/index.tsx (hunk 3 above)
Comment (ethan-l-geotab) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: @rusackas It's doable. I'm just worried theres other part of the code that "require" the specific return from the put request.

File: superset-frontend/src/explore/components/PropertiesModal/index.tsx [hunk 4]
```diff
@@ -192,20 +192,15 @@ function PropertiesModal({
...
-      const updatedChart = {
-        ...payload,
-        ...res.json.result,
-        tags,
-        id: slice.slice_id,
-        owners: selectedOwners,
-      };
-      onSave(updatedChart);
+      res = await SupersetClient.get({
+        endpoint: `/api/v1/chart/${slice.slice_id}`,
```
Comment (mistercrunch) [inline superset-frontend/src/explore/components/PropertiesModal/index.tsx]: DRY up that endpoint top-of try block

File: superset-frontend/src/explore/components/PropertiesModal/index.tsx (hunk 3 above)
Comment (mistercrunch) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: are you sure the PUT doesn't actually returns the payload already? looking at https://superset.apache.org/docs/api it seems like it might

Comment (ethan-l-geotab) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: Kinda.
put returns:
image
get returns:
image

I think cuz schema is int instead of relationship. I just am not sure if theres other parts of the code that expects the owner list to be returned as a list of ints.

Comment (mistercrunch) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: related: https://chatgpt.com/share/68a90a13-5390-8010-b149-6a87d0014de3

Personally would say: got for it, make it such that all 3 PUT/POST/GET all return the same schema as per best practices. If something break, a test should fail or we'll know soon enough.

Might be good to grep/search or add Claude Code or AI to do a deep search in the repo to confirm.

Comment (mistercrunch) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: Higher level solution I've been meaning to push forward: the superset client should be dynamically generated from the openapi spec, and be fully typed. It would mean that typescript would then be able to catch this kind of stuff at compile time. Meaning as you change the openapi spec to return this consistent schema across PUT/POST/GET, it would regenerate a fully typed client, and `tsc` would tell you exactly which calls break. Fun project if someone wants to take this on!

File: superset-frontend/src/explore/components/PropertiesModal/index.tsx (hunk 4 above)
Comment (ethan-l-geotab) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: Hey, sorry I'm not sure I'm catching the meaning of this.

Comment (rusackas) [reply superset-frontend/src/explore/components/PropertiesModal/index.tsx]: DRY = "don't repeat yourself" - i.e. set a variable for the endpoint and use it twice rather than repeating the string :D

**Comment by mistercrunch** [comment]
Need help figuring out how to get the PUT to return the same object as the GET?

**Comment by EnxDev** [comment]
Hi @ethan-l-geotab, let me know if you need any help with completing this PR

**Comment by ethan-l-geotab** [comment]
Sorry, got distracted with a lot of other stuff. Yes please, any help would be nice, could someone let me know what i have to do to modify whatever schemas  or anything else i'd have to do?

**Comment by legal-s** [comment]
Hi, 

Have you got news for merge this pull request ? 

We need this correction.

Thank you

**Review by rusackas — APPROVED** [review]
Seems like there are more reasons to merge this than not to, at this point. In it goes!
