### PR TITLE
fix(chart-table): Scrollbar causing header + footer overflow

### LINKED ISSUE #21063: Total on Table Chart gets cut off on the Dashboard if the Chart is re-sized
The total count from an aggregated Table Chart gets cut off on the Dashboard, after re-sizing it.

#### How to reproduce the bug

1. Access Superset.
2. Create a **Table Chart** using the **Vehicle Sales** Dataset.
3. Set `product_line` on the **Dimensions**.
4. Set `SUM(price_each)` on the **Metrics**.
5. Enable **SHOW TOTALS**.
6. Click on **Create Chart**.
7. Access the **CUSTOMIZE** tab.
8. Change the `SUM(price_each)` D3 format to **Original value**.
9. Save the Chart and add it to a **new** Dashboard.
10. Edit the Dashboard, and decrease the Chart height so that a horizontal scroll bar appears.
11. Increase the height so that all rows are visible.
12. Save your changes

### Expected results

The **Total** number should display as expected.

### Actual results

The **Total** number is cut off
(will paste screenshot/video here - Github is being problematic here at the moment)

### Known Workarounds

Manually re-sizing the Chart so that the number is properly displayed _might_ fix the issue. Reports are mixed.

### Environment

(please complete the following information):

- browser type and version: Chrome (on PC)
- superset version: latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by reesercollins**
### SUMMARY
This fixes a bug caused by bad (and unneeded) scrollbar compensating code. See the linked issue for more info.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:

https://user-images.githubusercontent.com/10563996/184667951-ad768f33-54f2-43d3-a995-9329a3d05071.mp4

After:

https://user-images.githubusercontent.com/10563996/184667971-87d3a993-d76f-4a09-9d72-6e1542f64efe.mp4

### TESTING INSTRUCTIONS
Try reproducing the bug in the linked issue. It should no longer appear.

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #21063
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
Hello @reesercollins it would be great if you could add a video or GIF before and after the changes. Thank you!

File: superset-frontend/plugins/plugin-chart-table/src/DataTable/hooks/useSticky.tsx [hunk 1]
```diff
@@ -246,23 +246,6 @@ function StickyWrap({
...
-    // header columns do not have vertical scroll bars,
-    // so we add scroll bar size to the last column
-    const headerColgroup =
-      sticky.hasVerticalScroll && scrollBarSize ? (
-        <colgroup>
-          {colWidths.map((x, i) => (
-            // eslint-disable-next-line react/no-array-index-key
-            <col
-              key={i}
-              width={x + (i === colWidths.length - 1 ? scrollBarSize : 0)}
```
Comment (geido) [inline superset-frontend/plugins/plugin-chart-table/src/DataTable/hooks/useSticky.tsx:258]: @reesercollins just to be triple sure, do you have evidence that this isn't required any longer?

Comment (reesercollins) [reply superset-frontend/plugins/plugin-chart-table/src/DataTable/hooks/useSticky.tsx:258]: I haven't been able to find any instances where this removal causes any breaking changes, however, I am not the most knowledgeable when it comes to the usage of this plugin within superset since our organization uses a custom table viz.

**Review by rusackas — APPROVED** [review]
Approving this, as it _seems_ fairly innocuous. I'd like to test it further on an ephemeral env, but that doesn't seem to be working, and I can't seem to find anyone with a PC to test this anyway. 

Heads up to @jinghua-qa that we might want to keep an eye on table scrolling issues in future testing, and if we have the means, make sure that the related Issue in the PR description (using PC Chrome) is resolved once and for all. 

To @geido's point, if this DOES cause any unforeseen issues, it should be easy to roll back! 🤞
