### PR TITLE
fix: fix crossfilter persisting after removal

### LINKED ISSUE #35623: Cross-filter persists after removal, leaving dashboard in inconsistent filtered state (6.0.0rc2)
### Bug description

1. Open any Superset dashboard where at least one chart supports cross-filtering and the filter sidebar is enabled.
2. Wait for the dashboard’s initial queries to complete (all visible charts finished loading).
3. In a chart that supports cross-filtering, click a single data point (e.g., a bar/point/segment) to apply a cross-filter for that value.
4. Before all charts finish updating in response to the cross-filter, open the filter sidebar and remove the newly applied cross-filter (e.g., clear the selection/deselect the value/remove the chip).
5. Scroll the dashboard so additional charts come into view (or otherwise trigger lazy loading / re-queries).

Observe that:
Several charts still render as if the removed cross-filter is applied.
The filter appears cleared in the sidebar, and there’s no visible way to remove the lingering effect.

### Screenshots/recordings

_No response_

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

We’re running in ASYNC query mode. It looks like when a cross-filter is applied, the queries it triggers aren’t canceled if the filter is removed. As those in-flight requests resolve, their filtered results are still delivered to the client and the UI re-renders the charts with that now-stale filter applied.

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by LevisNgigi**
### SUMMARY
When a cross-filter is applied, charts automatically reload to get this filter selection. If the cross-filter option is removed while charts are still loading, some of them would still load with the filtered option. Now when you apply cross-filter → Query A starts (with filter)
Remove cross-filter → Query A is aborted → Query B starts (without filter)
Only Query B completes
Charts consistently show correct unfiltered data.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
BEFORE: 

https://github.com/user-attachments/assets/c1fd747c-4406-480f-996d-89007d026823

AFTER:

https://github.com/user-attachments/assets/b953a7b0-8a63-42af-969f-9061316b456f

### TESTING INSTRUCTIONS
1) Create a dashboard with several charts powered by the same dataset (so that cross filtering is possible).
2) Apply a cross-filter value.
3) Remove it from the native filter bar before all charts load.

### ADDITIONAL INFORMATION

- [ x] Has associated issue: Fixes #35623
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/components/Chart/chartReducer.ts [hunk 1]
```diff
@@ -67,6 +67,9 @@ export default function chartReducer(
       };
     },
     [actions.CHART_UPDATE_STARTED](state) {
+      if (state.queryController) {
+        state.queryController.abort();
```
[the remark this answers is not in the document]
Comment (msyavuz) [reply superset-frontend/src/components/Chart/chartReducer.ts]: Agree with copilot on this one. Failing test might also be related

[the remark this answers is not in the document]
Comment (LevisNgigi) [reply superset-frontend/src/components/Chart/chartReducer.ts]: I updated it

File: superset-frontend/src/components/Chart/chartReducer.ts [hunk 2]
```diff
@@ -67,6 +67,10 @@ export default function chartReducer(
       };
     },
     [actions.CHART_UPDATE_STARTED](state) {
+      const controller = state.queryController;
```
Comment (amaannawab923) [inline superset-frontend/src/components/Chart/chartReducer.ts]: /**
     * Race condition fix for cross-filters:
     * When a filter is removed while charts are loading, abort the
     * in-flight request to prevent stale filtered data from rendering.
     * 
     * Related issue: issue link
     */
Please add a comment like this here so that anyone coming here in future shouldnt remove the setTimeout

Comment (LevisNgigi) [reply superset-frontend/src/components/Chart/chartReducer.ts]: added the comments

File: superset-frontend/src/components/Chart/chartReducer.ts [hunk 3]
```diff
@@ -67,6 +67,15 @@ export default function chartReducer(
...
+      /**
+       * Race condition fix for cross-filters:
+       * When a filter is removed while charts are loading, abort the
+       * in-flight request to prevent stale filtered data from rendering.
+       */
+      if (controller) {
+        setTimeout(() => controller.abort(), 0);
```
Comment (msyavuz) [inline superset-frontend/src/components/Chart/chartReducer.ts]: Is setTimeout required here?

Comment (LevisNgigi) [reply superset-frontend/src/components/Chart/chartReducer.ts]: Yes, we require setTimeout in this context to defer state update to the next event loop. This prevents the warning about updating state on an unmounted component as the cleanup runs during the components removal.

Comment (msyavuz) [reply superset-frontend/src/components/Chart/chartReducer.ts]: Should this abort live in action creator? Or can we use redux toolkit for extra reducers? Having a side effect in reducers are really not recommended:
https://redux.js.org/usage/side-effects-approaches

Comment (amaannawab923) [reply superset-frontend/src/components/Chart/chartReducer.ts]: Yes this is actually a hack for running an action within reducer

**Comment by amaannawab923** [comment]
We should just call the abort before dispatch ChartUpdate Started
chartAction.js  
Line 423 
  const prevController = getState().charts[key]?.queryController;
      if (prevController) {
        prevController.abort();
      }

 dispatch(chartUpdateStarted(controller, formData, key));
      
 Add this and remove the set timeout from chart updated started
 
 @msyavuz  @LevisNgigi

**Comment by richardfogaca** [comment]
Hi @LevisNgigi, I just opened a PR for this issue and only then I saw you also had a solution. I'm also attaching my PR just in case: https://github.com/apache/superset/pull/36092

**Comment by LevisNgigi** [comment]
> Hi @LevisNgigi, I just opened a PR for this issue and only then I saw you also had a solution. I'm also attaching my PR just in case: #36092

@richardfogaca thanks for the information.

File: superset-frontend/src/components/Chart/chartAction.js [hunk 4]
```diff
@@ -422,6 +424,14 @@ export function exploreJSON(
...
     };
     dispatch(chartUpdateStarted(controller, formData, key));
+    /**
+     * Abort in-flight requests after the new controller has been stored in
+     * state. Delaying ensures we do not mutate the Redux state between
+     * dispatches while still cancelling the previous request promptly.
+     */
+    if (prevController) {
+      setTimeout(() => prevController.abort(), 0);
+    }
```
Comment (msyavuz) [inline superset-frontend/src/components/Chart/chartAction.js:434]: Now we should not need setTimeout no?

Comment (LevisNgigi) [reply superset-frontend/src/components/Chart/chartAction.js:434]: I had not included the set timeout but tests fail. Tests fail without the setTimeout because abort() mutates the controller’s signal immediately, and Redux flags that as a mutation during dispatch. The timeout defers that mutation so Redux can complete the action.

**Comment by LevisNgigi** [comment]
fwiw got feedback that this solves the issue linked

File: superset-frontend/src/components/Chart/chartAction.js (hunk 4 above)
Comment (msyavuz) [reply superset-frontend/src/components/Chart/chartAction.js:434]: I guess the only other way is to write a custom middleware to do what you do here but i think this is fine and should cause no race conditions. Tagging @kgabryje for on opinion

Comment (LevisNgigi) [reply superset-frontend/src/components/Chart/chartAction.js:434]: Yes, this doesn’t introduce any race conditions ,it just defers the abort to the next tick, which is safe and expected IMO.

Comment (kgabryje) [reply superset-frontend/src/components/Chart/chartAction.js:434]: I think that works fine for now, but as a long term solution, Claude suggests not storing abort controllers in Redux at all, since they're inherently mutable. Let's keep this solution for now to push this fix forward

**Review by kgabryje — APPROVED** [review]
