### PR TITLE
fix: control panel fields styling (#12236)

### LINKED ISSUE #12236: [Explore]inconsistent control panel fields styling
all fields (drop down, select, input) boxes should have the same color, height & width, and corner radius

Screen Shot 2021-01-01 at 10 48 13 PM

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Adjusted METRICS and FILTER to use 4px border radius
Adjusted GROUP BY to keep same margin as METRICS and FILTERS
Adjusted RATIO height, border and box shadow
Adjusted METRICS, FILTERS and GROUP BY border colors
Adjusted search height and box shadow
Adjusted pills border color
Adjusted Add annotation layer button size
Changed `Select` component to present `placeholder` bellow the box when `multi = true`

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Screen Shot 2021-01-07 at 8 31 49 AM
Screen Shot 2021-01-09 at 2 45 27 PM

Closes #12236 

@junlincc 

### TEST PLAN
1 - Select a chart 
2 - View changes in control panel
3 - Repeat this process for charts with different control panel fields

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by adam-stasiak** [comment]
My scenario:
Built everything with command:
```CYPRESS_CONFIG=true docker-compose up```
Then opened chart:
image

Then expanded advanced analytics

I observed Rolling Function glitch:
image
I compared this to version from different branch:
image

**Comment by adam-stasiak** [comment]
Could you verify as well situation when we try to click on 
image
And then try to expand dropdowns:


https://user-images.githubusercontent.com/25153919/103895931-7712e700-50f1-11eb-8f80-11f70a90c4ce.mov

**Comment by michael-s-molina** [comment]
> Could you verify as well situation when we try to click on
> image
> And then try to expand dropdowns:
> 
>  dropdown.mov

@adam-stasiak I just confirmed that this is happening in master. Can you open a new issue and remove this comment so we can keep only related issues?

**Comment by adam-stasiak** [comment]
> > Could you verify as well situation when we try to click on
> > image
> > And then try to expand dropdowns:
> > dropdown.mov
> 
> @adam-stasiak I just confirmed that this is happening in master. Can you open a new issue and remove this comment so we can keep only related issues?

Yes sure :)

**Comment by zhaoyongjie** [comment]
same style problem at the latest master branch.  so we need new PR fix thit issue.

image

**Comment by michael-s-molina** [comment]
> same style problem at the latest master branch. so we need new PR fix thit issue.
> 
> image

@zhaoyongjie No problem. I'll fix this issue in this PR.

**Comment by junlincc** [comment]
agreed, thank you @adam-stasiak for spotting the issue! 
if the code looks good and we can confirm the styling issue preexists. let's merge this PR.

**Review by zhaoyongjie — APPROVED** [review]

**Comment by michael-s-molina** [comment]
> thank you @adam-stasiak for spotting the issue!
> if the code looks good and we can confirm the styling issue preexists. let's merge this PR.

We can't merge it just yet. Although this is problem exists in master, some inputs became bigger and when we hover them we have some layout problems. I'm fixing this right now and I'll also fix the preexisting problem.

**Comment by zhaoyongjie** [comment]
LGTM, thank you for your fix.

@michael-s-molina @junlincc

File: superset-frontend/src/explore/components/OptionControls.tsx [hunk 1]
```diff
@@ -84,7 +84,7 @@ export const HeaderContainer = styled.div`
 export const LabelsContainer = styled.div`
   padding: ${({ theme }) => theme.gridUnit}px;
   border: solid 1px ${({ theme }) => theme.colors.grayscale.light2};
-  border-radius: 3px;
+  border-radius: 4px;
```
Comment (nikolagigic) [inline superset-frontend/src/explore/components/OptionControls.tsx:87]: Could we maybe use `gridUnit` here as well? As it will have the same result but keep it consistent with the rest of the styling?
```suggestion
  border-radius: ${({ theme }) => theme.gridUnit}px;
```

File: superset-frontend/src/explore/components/OptionControls.tsx [hunk 2]
```diff
@@ -96,7 +96,7 @@ export const AddControlLabel = styled.div`
   font-size: ${({ theme }) => theme.typography.sizes.s}px;
   color: ${({ theme }) => theme.colors.grayscale.light1};
   border: dashed 1px ${({ theme }) => theme.colors.grayscale.light2};
-  border-radius: 3px;
+  border-radius: 4px;
```
Comment (nikolagigic) [inline superset-frontend/src/explore/components/OptionControls.tsx:99]: Same here ^

**Comment by michael-s-molina** [comment]
@nikolagigic Accepted all your suggestions. Thanks.

I increased the width (320px to 380px) of both panels to support bigger inputs. We still have the situation of layout flicks when we hover elements because there is no space available for the tooltip icon and this creates a line break. In talks with @junlincc she told me that this is being fixed in another PR where we're going to stack all controls and this line break problem won't happen anymore. So I will limit the scope of this PR to just fixing input styles.

For documentation purposes these images bellow show some examples where a line break happens:

Screen Shot 2021-01-07 at 2 22 30 PM
Screen Shot 2021-01-07 at 2 27 00 PM

**Comment by junlincc** [comment]
scope of the issue/pr should be limited to styling changes. which are done! 
@pkdotson and @mihir174 will open a separate PR to address the layout issue. 🙏 thanks all! 

image

Screen Shot 2021-01-07 at 9 30 34 AM

**Review by nikolagigic — APPROVED** [review]

File: superset-frontend/stylesheets/less/variables.less [hunk 3]
```diff
@@ -47,7 +47,7 @@
 
 @almost-black: #263238;
 @gray-dark: #484848;
-@gray-light: #cfd8dc;
+@gray-light: #e0e0e0;
```
Comment (rusackas) [inline superset-frontend/stylesheets/less/variables.less:50]: This is going to affect (apparently) at least 68 other things in the codebase. Is this a situation where we could use Emotion's `styled` to apply this color in a more specific place (using `theme.colors.grayscale.light2`)?

File: superset-frontend/stylesheets/less/cosmo/variables.less [hunk 4]
```diff
@@ -91,7 +91,7 @@
 //
 // ## Define common padding and border radius sizes and more. Values based on 14px text and 1.428 line-height (~20px to start).
 
-@padding-base-vertical: 10px;
+@padding-base-vertical: 6.5px;
```
Comment (rusackas) [inline superset-frontend/stylesheets/less/cosmo/variables.less:94]: Since this is part of the broader bootstrap theme, I'm a little worried this might cause some other regression somewhere else in the application. Have you done some kind of visual audit, or could we make this change in the relevant component(s) with Emotion styling?

File: superset-frontend/stylesheets/less/variables.less (hunk 3 above)
Comment (michael-s-molina) [reply superset-frontend/stylesheets/less/variables.less:50]: Actually that was the intention because `#e0e0e0` is the official gray-light theme color.

File: superset-frontend/stylesheets/less/cosmo/variables.less (hunk 4 above)
Comment (michael-s-molina) [reply superset-frontend/stylesheets/less/cosmo/variables.less:94]: I did a visual audit of most screens and I didn't found any problem. It shouldn't cause any problem because this is a configurable variable of Bootstrap. To limit the scope of this change we need to track all components that use classes that depend on this variable and apply Emotion styles individually.

**Review by junlincc — COMMENTED** [review]
1. move placeholder below the box so it does not take up to whole row and enlarge the box
Screen Shot 2021-01-07 at 4 05 25 PM
Screen Shot 2021-01-07 at 4 20 19 PM
Screen Shot 2021-01-07 at 4 20 09 PM

2. adjust the color of the pill border as well
Screen Shot 2021-01-07 at 4 05 13 PM

3. pls adjust the annotation box size  as well
Screen Shot 2021-01-07 at 4 04 54 PM

**Comment by michael-s-molina** [comment]
@junlincc I made all the requested changes.

Screen Shot 2021-01-08 at 4 22 08 PM

**Comment by junlincc** [comment]
> @junlincc I made all the requested changes.

I'm not able to see the latest changes(tried different browsers) when I tested.  @michael-s-molina

**Review by junlincc — APPROVED** [review]
this PR makes my day! thanks for all the px and color perfect styling and moving the "placeholder" options out of the box! 

Screen Shot 2021-01-11 at 8 38 59 AM

The only issue left is the rolling window styling that should have fixed in Superset-UI. let's make sure @rusackas 

Screen Shot 2021-01-11 at 8 44 41 AM

**Review by rusackas — APPROVED** [review]
There are a couple of lines in the global (bootstrap) styles that make me a little nervous, but I haven't seen any fallout yet :)

**Comment by rusackas** [comment]
Hoping E2E tests go through on this new run, will merge if so!

**Comment by junlincc** [comment]
@mihir174 want to bring this to your awareness

**Comment by junlincc** [comment]
@pkdotson need to confirm the layout issues in advanced analytics are being taken care of 🙏

**Comment by pkdotson** [comment]
rolling window will be fixed in this upcoming pr: https://github.com/apache-superset/superset-ui/pull/895

**Comment by junlincc** [comment]
Screen Shot 2021-01-11 at 4 28 20 PM
Screen Shot 2021-01-11 at 4 36 36 PM

while we tested again, we found blank page of deck.glMultiple Layers. and confirm that this has been an issue, not related to this PR. 

This PR is good to go if codes look ok!
