### PR TITLE
fix(Scope): Correct issue where filters appear out of scope when sort is unchecked.

### LINKED ISSUE #32014: Updating a native filter will mark filters as out of scope even though they aren't
## Repro steps
* Go to the video games dashboard
* Edit the Genre filter by saying sort value filters by count
* Save the filter
* Edit the filter again and uncheck filter values and save

## Actual results
When we weren't sorted all filters were in scope, after we sorted filters are still in scope, however, when you uncheck sort filters are now out of scope

##  Workaround
Moving away from the Dashboard and coming back will fix the problem

### Screenshots/recordings

https://github.com/user-attachments/assets/568cb95f-c2e7-4d22-9f46-00695e1e1491

### Superset version

master / latest-dev

### Python version

3.9

### Node version

18 or greater

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### LINKED ISSUE #32123: Filter out of scope after editing
### Bug description

Replacing a filter by another one of the same dataset is rendering the new filter as out of scope.

### Screenshots/recordings

https://github.com/user-attachments/assets/02635f08-1563-4575-aecf-88383c500b4e

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by LevisNgigi**
### SUMMARY
This fixes a bug where updating a native filter will mark filters as out of scope even though they aren't.

Fixes #32014 and #32123

Fix(Scope): Correct issue where filters appear out of scope when sort is unchecked

### TESTING INSTRUCTIONS
1.Go to the video games dashboard
2.Edit the Genre filter by saying sort value filters by count
3.Save the filter
4.Edit the filter again and uncheck filter values and save
5.When we weren't sorted all filters were in scope, after we sorted filters are still in scope, now when you uncheck, sort filters should still be in scope.

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #32014 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/components/nativeFilters/state.ts [hunk 1]
```diff
@@ -135,13 +136,16 @@ export function useSelectFiltersInScope(filters: (Filter | Divider)[]) {
       filters.forEach(filter => {
         const filterInScope = isFilterInScope(filter);
 
-        if (filterInScope) {
+        if (
```
Comment (kgabryje) [inline superset-frontend/src/dashboard/components/nativeFilters/state.ts:139]: Can we put that additional check in useIsFilterInScope hook and add some unit tests?

Comment (LevisNgigi) [reply superset-frontend/src/dashboard/components/nativeFilters/state.ts:139]: Sure will definitely do that.Thanks.

**Review by Antonio-RiveroMartnez — DISMISSED** [review]
lgtm

**Comment by michael-s-molina** [comment]
@geido Can we merge this?

**Comment by kgabryje** [comment]
https://github.com/user-attachments/assets/4e757445-3054-49d1-aba2-cf8e463aa259

It seems to me that the issue still persists when I edit the filter

**Review by kgabryje — CHANGES_REQUESTED** [review]
https://github.com/user-attachments/assets/78947032-746c-47cd-b1df-f2aaa9183544

The scoping doesn't seem to work with tabs - the range filter always appears in scope, even though it should only be active when tab2 is active

**Comment by LevisNgigi** [comment]
> Screen.Recording.2025-02-10.at.17.02.20.mov 
> The scoping doesn't seem to work with tabs - the range filter always appears in scope, even though it should only be active when tab2 is active

Thanks for this,fixed it.

File: superset-frontend/src/dashboard/components/nativeFilters/FilterBar/FilterControls/FilterControls.tsx [hunk 2]
```diff
@@ -130,16 +130,32 @@ const FilterControls: FC<FilterControlsProps> = ({
...
+      );
+
       return (
         // Empty text node is to ensure there's always an element preceding
         // the OutPortal, otherwise react-reverse-portal crashes
         <Fragment key={key}>
-          {'' /* eslint-disable-line react/jsx-curly-brace-presence */}
-          <OutPortal node={portalNodes[filterIndex]} inView />
+          {'' /* Empty text node to avoid react-reverse-portal crash */}
+          <fieldset
```
Comment (kgabryje) [inline superset-frontend/src/dashboard/components/nativeFilters/FilterBar/FilterControls/FilterControls.tsx:144]: I don't think wrapping the control in fieldset is necessary. It disables all interactions with a filter out of scope, and those interactions might be useful - for example, hovering over a filter out of scope highlights the tabs to which the filter applies. It seems to be working fine without `fieldset` so maybe let's just remove it and then this PR should be good to go?

Comment (LevisNgigi) [reply superset-frontend/src/dashboard/components/nativeFilters/FilterBar/FilterControls/FilterControls.tsx]: Okay, I thought the user should not interact with the out of scope filter.I have updated it accordingly.Thank you.

**Review by kgabryje — APPROVED** [review]
Looks good, thank you!
