### PR TITLE
fix: AceEditor Autocomplete Highlight

### LINKED ISSUE #35313: Autocomplete matched text in SQL Lab is unreadable in dark theme (black on black)
**Version 6.0.0rc2**

## Screenshot

Here I've typed "test" in my SQL Lab in dark theme. The letters of the matched objects are invisible b/c they're black text on black background:

Image

Here's the same thing on light theme:

Image

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
Fixes #35313

### AFTER SCREENSHOTS OR ANIMATED GIF

Screenshot 2025-09-27 at 14 07 45

### TESTING INSTRUCTIONS
1. Visit SQL Lab
2. Change the SQL in the editor so that the autocomplete appears
3. Highlight text should be visible in both dark and light mode

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/SqlLab/components/AceEditorWrapper/index.tsx [hunk 1]
```diff
@@ -193,6 +193,11 @@ const AceEditorWrapper = ({
             width: ${theme.sizeUnit * 130}px !important;
           }
 
+          .ace_completion-highlight {
+            color: ${theme.colorPrimaryText} !important;
```
Comment (mistercrunch) [inline superset-frontend/src/SqlLab/components/AceEditorWrapper/index.tsx:197]: `colorPrimaryTextActive` might be a tiny bit better, but LGTM

**Review by mistercrunch — APPROVED** [review]
minor comment but LGTM

File: superset-frontend/src/SqlLab/components/AceEditorWrapper/index.tsx (hunk 1 above)
Comment (geido) [reply superset-frontend/src/SqlLab/components/AceEditorWrapper/index.tsx:197]: Might be my eyes, but I feel `colorPrimaryTextActive` is less readable. @kasiazjc let me know if you have any feedback here. 

With `colorPrimaryTextActive`:
Screenshot 2025-09-29 at 13 34 04

With `colorPrimaryText`:
Screenshot 2025-09-29 at 13 36 34
