### PR TITLE
[superset-client] use getClientErrorObject for client error handling

### LINKED ISSUE #6152: "No data" error message not getting displayed
No error message shows up for "No data" error (likely for other errors as well but this is the one I tested). Instead the chart is blank.

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

image

### Superset version
master

### Expected results
Error message shows up

### Actual results
No error message

### Steps to reproduce
Go to birth names slice
Filter by a name that doesn't exist in the datasource
Run query returns a blank chart with no error message

### PR DESCRIPTION
**Pull request by williaster**
This PR fixes #6152 and is a more generic fix than #6158 for handling fetch-based errors. 

It adds a method `getClientErrorObject` which takes a fetch `Response` as input, reads it as either `json` or `text`, and returns a `Promise` that resolves to an object with all keys from the `Response` and an `error` key which can be used for display in the UI.

Note this is more complex than previous `ajax` errors because we must read the response explicitly, and because of the mixture of response types we have no idea if it's text or json.

Added unit tests and tested locally for bug reported in #6152 

image

@mistercrunch @graceguo-supercat @kristw @michellethomas

### CODE REVIEW

File: superset/assets/spec/javascripts/modules/utils_spec.jsx [hunk 1]
```diff
@@ -88,4 +98,39 @@ describe('utils', () => {
...
+    });
+
+    it('Returns a Promise that resolves to an object with an error key', () => {
+      const error = 'error';
+      getClientErrorObject(error).then((errorObj) => {
+        expect(errorObj).toMatchObject({ error });
+      });
+    });
+
+    it('Handles Repsonse that can be parsed as json', () => {
```
Comment (kristw) [inline superset/assets/spec/javascripts/modules/utils_spec.jsx]: typo `Response`

File: superset/assets/spec/javascripts/modules/utils_spec.jsx [hunk 2]
```diff
@@ -88,4 +98,39 @@ describe('utils', () => {
...
+      const jsonError = JSON.stringify({ a: 123, b: 'abc', c: ['error'] });
+      getClientErrorObject(new Response(jsonError)).then((errorObj) => {
+        expect(errorObj).toMatchObject({ error: jsonError });
+      });
+    });
+
+    it('Handles Repsonse that can be parsed as text', () => {
```
Comment (kristw) [inline superset/assets/spec/javascripts/modules/utils_spec.jsx]: another typo

**Review by kristw — APPROVED** [review]
a few nits. overall LGTM

**Comment by williaster** [comment]
🤮 build is stuck ... will give it a bit more time to sort itself out.

**Comment by williaster** [comment]
Need to merge #6133 before this one

**Comment by mistercrunch** [comment]
@williaster I wanted to add this into `0.28.2` as this is a pretty major issue with `0.28.1` but it was conflicting pretty hard. Any idea which series of cherries I should line up to avoid merge conflict? I tried lining up #6133 first but it conflicted as hard.

If it's not easy maybe I just need to cut `0.29.0` from master.

**Comment by williaster** [comment]
Hmm, it would probably need all of SupersetClient PRs because it may have been introduced in one of the earlier ones. they were

#5875 chart ajax (introduced bug?)
#5869 explorer ajax 
#5854 dashboard ajax
#5896 sqllab ajax
#6134 datasource editor ajax
#6133 logger ajax
#6135 misc ajax
#6148 csrf optimization

unsure, `0.29.0` might be easier?

**Comment by mistercrunch** [comment]
I think `0.29.0` is a safer bet
