### PR TITLE
fix: Pasting text issues in MetricsControl and AdhocFilterControl inputs

### LINKED ISSUE #11379: Chart Explore: Pasting text into Metrics fails and deletes other metrics
Pasting text into Metrics fails and deletes other metrics. This feature is commonly used if metrics are long - user finds them in documentation / from a colleague (via slack) / from previous chart - instead of typing the metric name user wants to paste it. This functionality worked at some point in the past.

### Expected results

Existing metric remain, and newly pasted metric (if exists) also is in the Metrics field.

### Actual results

Existing metrics disappear. 

#### Screenshots
Step 1: There is some metric in the METRICS field.
Screen Shot 2020-10-21 at 6 08 15 PM

Step 2: try to paste new metric, like "test_metric"

Step 3: All metrics disappear. Regardless of if metric that is being pasted exists or not.
Screen Shot 2020-10-21 at 6 08 42 PM

#### How to reproduce the bug

1. Go to 'Chart Explore'
2. Click in 'Metrics field'
3. Paste name of a metric, for example try to paste 'test_metric'
4. See issue - all existing metrics disappear

### Environment

(please complete the following information):

- superset version: `master`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Fixes https://github.com/apache/incubator-superset/issues/11379. When a user pastes text into the input field, the behaviour is the same as when the user types normally - a dropdown with suggestions appears.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before: see the screenshots in https://github.com/apache/incubator-superset/issues/11379.
After: I pasted "gen" and as expected, "gender" was suggested. The metric "gender" was correctly added after clicking. THen I pasted "test_metric" and as expected, there was no match.
ezgif com-gif-maker (3)

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/incubator-superset/issues/11379
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by kgabryje** [comment]
@zuzana-vej Is that how we expect it to work? This feature might have been broken for at least 5 months, as the last meaningful change to the offending component was done in May 2020 (and I'm not sure if that change was responsible for the bug).
@rusackas Can you please take a look?
CC: @junlincc

**Comment by zuzana-vej** [comment]
Hi @kgabryje Thanks for the details and video. I believe this is the expected behavior. I don't think this feature is used too frequently and not everyone always reports bugs, so it's certainly possible it's been around for a while. 
cc @graceguo-supercat

File: superset-frontend/src/components/Select/OnPasteSelect.jsx [hunk 1]
```diff
@@ -75,8 +75,8 @@ export default class OnPasteSelect extends React.Component {
   }
 
   render() {
-    const { selectWrap: SelectComponent, ...restProps } = this.props;
-    return <SelectComponent {...restProps} onPaste={this.onPaste} />;
+    const { selectWrap: SelectComponent, onPaste, ...restProps } = this.props;
+    return <SelectComponent {...restProps} onPaste={onPaste || this.onPaste} />;
```
Comment (etr2460) [inline superset-frontend/src/components/Select/OnPasteSelect.jsx:79]: why are we keeping around the old `this.onPaste` code? Is that actually used anywhere? Since we're adding an empty function in `AdhocFilterControl`, that will actually override the original behavior, right?

File: superset-frontend/src/explore/components/controls/AdhocFilterControl.jsx [hunk 2]
```diff
@@ -275,6 +275,7 @@ export default class AdhocFilterControl extends React.Component {
           clearable
           closeOnSelect
           onChange={this.onChange}
+          onPaste={() => {}}
```
Comment (etr2460) [inline superset-frontend/src/explore/components/controls/AdhocFilterControl.jsx:278]: Instead of defining this inline, can you define it as a constant NO_OP function above? Better yet, see if we have a NO_OP function exported from a utils file somewhere to use here.

Finally, I think `() => undefined` is prefered to `() => {}` as it doesn't construct an empty object

Comment (ktmud) [reply superset-frontend/src/explore/components/controls/AdhocFilterControl.jsx:278]: `() => {}` doesn't really return an empty object. It's equivalent to `() => { return }`.

Comment (ktmud) [reply superset-frontend/src/explore/components/controls/AdhocFilterControl.jsx:278]: I also wouldn't worry about `NO_OP` that much as I'm yet to see it causing any real performance issue.

**Comment by ktmud** [comment]
I think the original intent of `OnPasteSelect` is to automatically add new options when users pasted valid metrics or column names.

We can either stop supporting `onPaste` for AdhocMetric and AdhocFilter like this PR does, or if we want to continue the support, I think the expected behaviors can be implemented as such:

1. Split the pasted text by by `OnPasteSelect.props.separator`, get candidate metric/column name list `pastingItems`
2. For each item in `pastingItems`, do the following:
    1. If it's a valid metric/column name, create a selected option that appends to current selection
    2. If it's not valid, keep the text in `invalidInputText`
3. If `invalidInputText` is not empty, set it as `inputText` for the select control.
3. If there are updates to the updated input, call `onChange` event with the updated input.

File: superset-frontend/src/explore/components/controls/AdhocFilterControl.jsx (hunk 2 above)
Comment (etr2460) [reply superset-frontend/src/explore/components/controls/AdhocFilterControl.jsx:278]: ah yeah, you're totally right. I was mistaken from this eslint rule: https://eslint.org/docs/rules/no-empty-function where they preferred `() => undefined` as it's more obvious that the function is meant to be empty.

That said, it looks like we've defined noOp in a utils file already, so we should probably use that: https://github.com/apache/incubator-superset/blob/ccfd293227105ae1a5a24999a3b75e3db724273b/superset-frontend/src/utils/common.js#L139

File: superset-frontend/src/components/Select/OnPasteSelect.jsx (hunk 1 above)
Comment (kgabryje) [reply superset-frontend/src/components/Select/OnPasteSelect.jsx:79]: `OnPasteSelect` is also used in `visualizations/FilterBox` and in `explore/components/SelectControl`. I did not analyse these use cases and assumed that `this.onPaste` works as expected there.

**Comment by kgabryje** [comment]
@ktmud I'm having some troubles with implementing what you proposed. If the pasted value contains both incorrect and correct metric names, let's say `gender, test1, ds, test2`, gender and ds metric options are created correctly, but then the input loses focus due to re-render and it's cleared. So the actual result is that we created options `gender` and `ds` and discarded other values. Do you have any idea for a workaround?
Also, I'm not sure how to handle auto-openning popups when more than 1 option is created.
Another case is when there's more than 1 incorrect text - I think that when user pastes `test1, test2, test3` (comma is a separator), we should actually paste either the first or the last item so that we can display dropdown with suggestions. WDYT?

File: superset-frontend/src/explore/components/controls/AdhocFilterControl.jsx (hunk 2 above)
Comment (kgabryje) [reply superset-frontend/src/explore/components/controls/AdhocFilterControl.jsx:278]: Done

**Comment by ktmud** [comment]
So It seems there are a lot of edge case to consider and would need careful implementation and extensive tests.

I think it's OK to disable the `onPaste` behavior for now, but instead of passing a no-op `onPaste` handler, maybe we should replace `OnPasteSelect` with a regular `SupersetStyledSelect` for `MetricsControl` and `AdhocFilterControl`.

**Comment by kgabryje** [comment]
@ktmud Good point, done.

**Comment by kgabryje** [comment]
@ktmud Do you think we can merge it?

File: superset-frontend/src/components/Select/OnPasteSelect.jsx (hunk 1 above)
Comment (ktmud) [inline superset-frontend/src/components/Select/OnPasteSelect.jsx:79]: Can we revert the change here since it's not needed anymore?

**Review by ktmud — APPROVED** [review]
LGTM with a small nit

File: superset-frontend/src/components/Select/OnPasteSelect.jsx (hunk 1 above)
Comment (kgabryje) [reply superset-frontend/src/components/Select/OnPasteSelect.jsx]: Done
