### PR TITLE
fix(heatmap): y-axis sorts in order

### LINKED ISSUE #33245: Heatmap lost ability to sort both y-axis and x-axis starting in 4.1
### Bug description

Originally filed as https://github.com/apache/superset/issues/33105 but as a two-part issue which made it hard to track. We dealt with one part of the issue and closed that one. See that thread for some discussion about this sorting problem.

In Superset 4.0.2 you could sort both the x-axis and y-axis of the heatmap chart, allowing charts like this where day and hour are plotted against each other, both in logical order:

Image

Starting in Superset 4.1 this doesn't work if some combinations lack data. For instance (images taken from #33105):

Image

### Screenshots/recordings

_No response_

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by sfirke**
### SUMMARY
Fixes #33245. Replaces the attempt in #34547.

Note: I leaned heavily on AI coding assistance for this PR since I'm still new to TypeScript. The logic makes sense to me and I verified the desired behaviors in my test environment, but someone familiar with TypeScript should review with care.

I left the addition to .gitignore in, it seems like a developer pattern that might help others.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
**BEFORE - 6.0.0rc3**

The y-axis is out of order:

image

**AFTER**

Y-axis order is correct:

image

### TESTING INSTRUCTIONS
Tests included. I deployed to my test environment and checked ascending and descending for y- and x-axes of numeric and categorical variables.

### ADDITIONAL INFORMATION
- [x] Has associated issue: fixes #33245

### CODE REVIEW

File: superset-frontend/plugins/plugin-chart-echarts/src/Heatmap/transformProps.ts [hunk 1]
```diff
@@ -38,13 +39,104 @@ import { HeatmapChartProps, HeatmapTransformedProps } from './types';
...
+        axisValue !== null &&
+        axisValue !== undefined &&
+        typeof metricValue === 'number'
+      ) {
+        const current = valueMap.get(axisValue) || 0;
+        valueMap.set(axisValue, current + metricValue);
+      }
+    });
+
+    return values.sort((a, b) => {
```
Comment (rusackas) [inline superset-frontend/plugins/plugin-chart-echarts/src/Heatmap/transformProps.ts]:
```suggestion
    return [...values].sort((a, b) => {
```

File: superset-frontend/plugins/plugin-chart-echarts/src/Heatmap/transformProps.ts [hunk 2]
```diff
@@ -38,13 +39,104 @@ import { HeatmapChartProps, HeatmapTransformedProps } from './types';
...
+      const aValue = valueMap.get(a) || 0;
+      const bValue = valueMap.get(b) || 0;
+      return isAscending ? aValue - bValue : bValue - aValue;
+    });
+  }
+
+  // Alphabetical/lexicographic sort
+  return values.sort((a, b) => {
```
Comment (rusackas) [inline superset-frontend/plugins/plugin-chart-echarts/src/Heatmap/transformProps.ts]:
```suggestion
  return [...values].sort((a, b) => {
```

File: superset-frontend/plugins/plugin-chart-echarts/src/Heatmap/transformProps.ts [hunk 3]
```diff
@@ -144,22 +238,52 @@ export default function transformProps(
...
+      data: data.map(row => {
+        const xValue = row[xAxisColumnName];
+        const yValue = row[yAxisColumnName];
+        const metricValue = row[metricLabel];
+
+        // Convert to axis indices for ECharts when explicit axis data is provided
+        const xIndex = xAxisIndexMap.get(xValue) ?? 0;
+        const yIndex = yAxisIndexMap.get(yValue) ?? 0;
+
+        return [xIndex, yIndex, metricValue] as [number, number, any];
```
[the remark this answers is not in the document]
Comment (rusackas) [reply superset-frontend/plugins/plugin-chart-echarts/src/Heatmap/transformProps.ts]: @sfirke This seems like a good fix, but rather than using console.warn, we'll want to import `logging` and use `logging.warn` to avoid an eslint issue. Holler if you want me to jump in... I accepted some of the other copilot nits on your behalf :D

[the remark this answers is not in the document]
Comment (sfirke) [reply superset-frontend/plugins/plugin-chart-echarts/src/Heatmap/transformProps.ts]: @rusackas that would be amazing if you could hop in 🙏 I'm out of my depth here!

File: superset-frontend/plugins/plugin-chart-echarts/src/Heatmap/transformProps.ts [hunk 4]
```diff
@@ -144,22 +239,61 @@ export default function transformProps(
...
+        const yValue = row[yAxisColumnName];
+        const metricValue = row[metricLabel];
+
+        // Convert to axis indices for ECharts when explicit axis data is provided
+        const xIndex = xAxisIndexMap.get(xValue);
+        const yIndex = yAxisIndexMap.get(yValue);
+
+        if (xIndex === undefined || yIndex === undefined) {
+          // Log a warning for debugging
+          // eslint-disable-next-line no-console
```
Comment (rusackas) [inline superset-frontend/plugins/plugin-chart-echarts/src/Heatmap/transformProps.ts]:
```suggestion
```

**Review by rusackas — APPROVED** [review]
