### PR TITLE
fix(dashboard): Prevent rerendering View Query modal on window resize

### LINKED ISSUE #14696: [x-filtering]resizing window should not trigger query on dashboard
Both View query and and X-filerting are not fully available yet, but we should address below before rolling out the feature

As we can see in the "View query" modal, all charts in dashboard reload on window resize which causes performance issues: 
Resizing 

https://user-images.githubusercontent.com/67837651/118710599-5eb78500-b7d3-11eb-9806-172798520377.mov

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Due to using a complex javascript object in `useEffect`'s dependency array in `ViewQueryModal`, we were rerunning API request on every rerender of the modal (including resizing window). I fixed it by using `JSON.stringify` method in the dependency array.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before: see #14696 
After:
https://user-images.githubusercontent.com/15073128/122034659-070c3980-cdd2-11eb-8617-6650cf4b3c43.mov

### TESTING INSTRUCTIONS
1. Open a dashboard and View Query modal
2. Resize window
3. Verify that API request wasn't rerun after resizing window.

### ADDITIONAL INFORMATION

- [x] Has associated issue: closes #14696 
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC: @junlincc

### CODE REVIEW

File: superset-frontend/src/explore/components/controls/ViewQueryModal.tsx [hunk 1]
```diff
@@ -16,7 +16,7 @@
  * specific language governing permissions and limitations
  * under the License.
  */
-import React, { useEffect, useState } from 'react';
+import React, { useEffect, useState, useCallback } from 'react';
```
Comment (villebro) [inline superset-frontend/src/explore/components/controls/ViewQueryModal.tsx:19]: This doesn't appear to be needed here?

**Review by villebro — APPROVED** [review]
I just ran into this today, thanks for fixing! LGTM once passes lint (I assume `useCallback` isn't needed here).

File: superset-frontend/src/explore/components/controls/ViewQueryModal.tsx (hunk 1 above)
Comment (kgabryje) [reply superset-frontend/src/explore/components/controls/ViewQueryModal.tsx]: Ugh, forgot to remove it. Thanks!
