### PR TITLE
fix(sqllab): Update style for code viewer container

### LINKED ISSUE #39076: SQL Lab view query looks bad
### Bug description

1. The modal should be contained to the view port instead of overflowing outside the screen.
2. SQL is not formatted as SQL block
3. 2 horizontal scrolls instead of 1

### Screenshots/recordings

Image

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by justinpark**
### SUMMARY

Fixes #39076

This commit updates the style for code viewer matching with the previous version.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:

●_Superset_6_1_-_SQL_Lab_view_query_looks_bad_-_Asana

After:

Screenshot 2026-04-02 at 5 25 16 PM

### TESTING INSTRUCTIONS

Screenshot

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/features/queries/QueryPreviewModal.tsx [hunk 1]
```diff
@@ -93,6 +93,15 @@ function QueryPreviewModal({
       currentQueryId: query.id,
       fetchData,
     });
+  const theme = useTheme();
+  const codeBlockStyle = {
+    border: 1,
+    borderColor: theme.colorBorder,
+    borderStyle: 'solid',
+    marginTop: theme.sizeUnit * 4,
+    fontSize: '0.75em',
```
Comment (alexandrusoare) [inline superset-frontend/src/features/queries/QueryPreviewModal.tsx]: Could we use this instead? `theme.fontSize`

File: superset-frontend/src/features/queries/QueryPreviewModal.tsx [hunk 2]
```diff
@@ -93,6 +93,15 @@ function QueryPreviewModal({
       currentQueryId: query.id,
       fetchData,
     });
+  const theme = useTheme();
+  const codeBlockStyle = {
+    border: 1,
+    borderColor: theme.colorBorder,
+    borderStyle: 'solid',
```
Comment (alexandrusoare) [inline superset-frontend/src/features/queries/QueryPreviewModal.tsx:101]: Do we need to mention this?

File: superset-frontend/src/features/queries/QueryPreviewModal.tsx [hunk 3]
```diff
@@ -93,6 +93,15 @@ function QueryPreviewModal({
...
+    marginTop: theme.sizeUnit * 4,
+    fontSize: '0.75em',
+    height: 375,
+  };
```
Comment (alexandrusoare) [inline superset-frontend/src/features/queries/QueryPreviewModal.tsx:105]: Can we use a more standardized height?

File: superset-frontend/src/features/queries/QueryPreviewModal.tsx (hunk 1 above)
Comment (justinpark) [reply superset-frontend/src/features/queries/QueryPreviewModal.tsx]: sounds good. done!

File: superset-frontend/src/features/queries/QueryPreviewModal.tsx (hunk 2 above)
Comment (justinpark) [reply superset-frontend/src/features/queries/QueryPreviewModal.tsx:101]: Yes. Without borderStyle, no border made

File: superset-frontend/src/features/queries/QueryPreviewModal.tsx (hunk 3 above)
Comment (justinpark) [reply superset-frontend/src/features/queries/QueryPreviewModal.tsx:105]: sure. updated

**Comment by michael-s-molina** [comment]
@justinpark Can you remove the extra padding between the modal title and the content? I think you just need to remove the content top padding given that the header already has padding.

**Comment by justinpark** [comment]
> justinpark Can you remove the extra padding between the modal title and the content? I think you just need to remove the content top padding given that the header already has padding.

updated.

Screenshot 2026-04-07 at 3 18 48 PM
Screenshot 2026-04-07 at 3 22 54 PM

**Review by michael-s-molina — APPROVED** [review]
