### PR TITLE
fix(embedded-sdk): add accessible title to iframe

### LINKED ISSUE #27016: Embedded dashboard iframe missing title (accessibility)
## Screenshot

image

## Description

Screen reader users may rely on the (missing) title attribute to know that the iframe is where the dashboard content is.

## Design input

Propose that the title be "Embedded Dashboard".

### PR DESCRIPTION
**Pull request by bhaugeea**
### SUMMARY

Screen reader users may rely on the (missing) title attribute to know that the iframe is where the dashboard content is. This PR adds a title to the iframe with the generic value "Embedded Dashboard".

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
image

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #27016 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-embedded-sdk/src/index.ts [hunk 1]
```diff
@@ -154,6 +154,7 @@ export async function embedDashboard({
       });
 
       iframe.src = `${supersetDomain}/embedded/${id}${dashboardConfig}${filterConfigUrlParams}`;
+      iframe.title = 'Embedded Dashboard';
```
Comment (rusackas) [inline superset-embedded-sdk/src/index.ts:157]: This works in a pinch, but does the dashboard config (or something else) happen to provide the actual title of the dashboard? That would be the ideal thing to put here.

Comment (mistercrunch) [reply superset-embedded-sdk/src/index.ts:157]: It seems the sdk would expose the option to set this `iframeTitle`, and fall back on some default like this one "Embedded Dashboard".  Note that for extra points you could i18n that string as well.

Comment (bhaugeea) [reply superset-embedded-sdk/src/index.ts]: Moved it to the config. Didn't provide a fallback for now because I'd probably butcher the i18n. Would a fallback be required for this, or okay without?

Comment (mistercrunch) [reply superset-embedded-sdk/src/index.ts]: Ok without AFAIC, the i18n is easy though:

```js
import { t } from '@superset-ui/core';

translatableString = t("Embedded Dashboard");
```

What happens then is the i18n framework scans through the code base and inventorize all those strings on the backend and frontend, where other people can then translate then in various languages.

**Comment by rusackas** [comment]
Thanks for following up... running CI 🤞

**Comment by bhaugeea** [comment]
I believe the whole ui/core package would need to be added as a dependency here. I haven't tried to open the can of worms of actually running this repo so not confident in being able to get that working.

File: superset-embedded-sdk/src/index.ts [hunk 2]
```diff
@@ -77,6 +80,7 @@ export async function embedDashboard({
   id,
   supersetDomain,
   mountPoint,
+  iframeTitle = t("Embedded Dashboard"),
```
Comment (mistercrunch) [inline superset-embedded-sdk/src/index.ts:83]: Hey this look like a public interface, so this new [optional] param should be the last one in the function call for backwards compatibility, otherwise we'l have off-by-one param matching on the function call!

File: superset-embedded-sdk/src/index.ts [hunk 3]
```diff
@@ -154,6 +158,9 @@ export async function embedDashboard({
       });
 
       iframe.src = `${supersetDomain}/embedded/${id}${dashboardConfig}${filterConfigUrlParams}`;
+      if(iframeTitle) {
```
Comment (mistercrunch) [inline superset-embedded-sdk/src/index.ts:161]: I think given the default value set in the function header, this will always have a value, so no `if` required. Actually I think if someone actually wanted an empty string and pass `iframeTitle = ''` or `iframeTitle = null` in the function call, it would prevent them from overriding the `Embedded Dashboard` default :/

**Review by mistercrunch — CHANGES_REQUESTED** [review]

**Comment by mistercrunch** [comment]
> I believe the whole ui/core package would need to be added as a dependency here. I haven't tried to open the can of worms of actually running this repo so not confident in being able to get that working.
Oh you're right about that! Let's actually not do this then. Not worth adding the dependency for the sake of a i18n that one string!

**Comment by rusackas** [comment]
@mistercrunch @bhaugeea Curious if you see a way forward with this, so we can close out the PR and Issue. If there's no intent to rebase this in the near future and get it across the finish line, I'll convert this to a Draft, and the issue may closed as stale in time.

**Review by mistercrunch — APPROVED** [review]

**Comment by mistercrunch** [comment]
@rusackas I just made the changes I suggested and removed `superset-ui/core` dependency that was reference, but wasn't added as a dependancy of the sdk since it could have implications.

**Comment by nikola-arcadis** [comment]
I don't see this change is published on npmjs registry with version 0.1.0-alpha.11. How can we get the new package with this change?

**Comment by rusackas** [comment]
Sorry... we need to update a bunch of npm packages. We'll try to get that effort underway soon.

**Comment by mistercrunch** [comment]
@rusackas is the process to do that documented someplace? Oh nevermind found an example PR -> https://github.com/apache/superset/pull/13593/files

**Comment by rusackas** [comment]
That brings in the newly published ones, but here are the instructions (the most current I'm aware of) to actually publish the modules to NPM:

https://github.com/apache/superset/pull/23730/files

This should be made part of the release process, but for now, I have it on my task list to go back and try it on some of the voted-in release branches.
