### PR TITLE
fix(map-box): make opacity, lon, lat, and zoom controls functional

### LINKED ISSUE #38315: [6.0.0] Several fields intended to set the Deck.gl MapBox chart have no effect on the display
## Description

In the Deck.gl MapBox chart, the following fields have no effect on the display :
1) In the "Data" tab, the "Opacity" field
2) In the "Customize" tab, the fields "Default longitude", "Default latitude" and "Zoom"

### PR DESCRIPTION
**Pull request by joaopedroab**
### SUMMARY                                                                                                                                                                                    
  The Deck.gl MapBox chart's Opacity, Default longitude, Default latitude, and Zoom control panel fields had no effect on the display.

  **Root causes:**
  - **Opacity**: The `global_opacity` control was missing `renderTrigger: true`, so changing it didn't trigger a re-render — users had to re-run the query to see changes.
  - **Viewport fields**: `transformProps.ts` never extracted `viewportLongitude`, `viewportLatitude`, or `viewportZoom` from `formData`, so they were never passed to the MapBox component.
  Additionally, `MapBox.tsx` had no mechanism to respond to prop changes for these values.

  **Changes:**
  - Add `renderTrigger: true` to `global_opacity` control in `controlPanel.ts`
  - Extract and pass viewport values through `transformProps.ts`
  - Add `componentDidUpdate` to `MapBox.tsx` to update viewport state when props change
  - Add tests for `transformProps` and `MapBox` component

  ### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
  N/A — behavior change: controls that previously had no effect are now functional.

  ### TESTING INSTRUCTIONS
  1. Create a Deck.gl MapBox chart with data containing longitude/latitude columns
  2. **Test Opacity**: In the Data tab → Visual Tweaks, change Opacity (e.g. from 1 to 0.3) → chart should update immediately without re-running the query
  3. **Test Viewport**: In the Customize tab → Viewport, change Default longitude, Default latitude, or Zoom → map should pan/zoom to the new values

  ### ADDITIONAL INFORMATION
  - [x] Has associated issue: Fixes #38315
  - [ ] Required feature flags:
  - [x] Changes UI
  - [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
    - [ ] Migration is atomic, supports rollback & is backwards-compatible
    - [ ] Confirm DB migration upgrade and downgrade tested
    - [ ] Runtime estimates and downtime expectations provided
  - [ ] Introduces new feature or API
  - [ ] Removes existing feature or API

___

## **CodeAnt-AI Description**
Make MapBox opacity and viewport controls actually affect the rendered map

### What Changed
- Opacity control now triggers an immediate re-render so changing Opacity updates the map without re-running the query
- Viewport controls (Default longitude, Default latitude, Zoom) are read from the control panel, normalized from text inputs to numbers, and applied to the map; the map now updates when these control values change
- Clearing viewport controls restores fit-to-data behavior; chart size and bounds changes recompute the fit when explicit viewport fields are not set
- Added unit tests for transformProps, control panel defaults/flags, and MapBox behavior to prevent regressions

### Impact
`✅ Immediate opacity updates in MapBox charts`
`✅ Viewport controls pan/zoom the map as expected`
`✅ Clearer restore-to-fit-data workflow when viewport fields are cleared`
<details>
<summary><strong>💡 Usage Guide</strong></summary>

### Checking Your Pull Request
Every time you make a pull request, our system automatically looks through it. We check for security issues, mistakes in how you're setting up your infrastructure, and common code problems. We do this to make sure your changes are solid and won't cause any trouble later.

### Talking to CodeAnt AI
Got a question or need a hand with something in your pull request? You can easily get in touch with CodeAnt AI right here. Just type the following in a comment on your pull request, and replace "Your question here" with whatever you want to ask:
<pre>
<code>@codeant-ai ask: Your question here</code>
</pre>
This lets you have a chat with CodeAnt AI about your pull request, making it easier to understand and improve your code.

#### Example
<pre>
<code>@codeant-ai ask: Can you suggest a safer alternative to storing this secret?</code>
</pre>

### Preserve Org Learnings with CodeAnt
You can record team preferences so CodeAnt AI applies them in future reviews. Reply directly to the specific CodeAnt AI suggestion (in the same thread) and replace "Your feedback here" with your input:
<pre>
<code>@codeant-ai: Your feedback here</code>
</pre>
This helps CodeAnt AI learn and adapt to your team's coding style and standards.

#### Example
<pre>
<code>@codeant-ai: Do not flag unused imports.</code>
</pre>

### Retrigger review
Ask CodeAnt AI to review the PR again, by typing:
<pre>
<code>@codeant-ai: review</code>
</pre>

### Check Your Repository Health
To analyze the health of your code repository, visit our dashboard at [https://app.codeant.ai](https://app.codeant.ai). This tool helps you identify potential issues and areas for improvement in your codebase, ensuring your repository maintains high standards of code health.

</details>

### CODE REVIEW

**Comment by richardfogaca** [comment]
Welcome to Apache Superset @joaopedroab, congratulations on your first PR! 💯

**Comment by joaopedroab** [comment]
Thanks @richardfogaca! I'm happy to make my first contribution to Apache Superset and look forward to contributing more :D

File: superset-frontend/plugins/legacy-plugin-chart-map-box/src/MapBox.tsx [hunk 1]
```diff
@@ -100,6 +103,12 @@ class MapBox extends Component<MapBoxProps, MapBoxState> {
       ({ latitude, longitude, zoom } = mercator);
     }
 
+    // Override with explicit viewport props when provided (e.g., saved chart controls)
```
Comment (richardfogaca) [inline superset-frontend/plugins/legacy-plugin-chart-map-box/src/MapBox.tsx]: This looks like it may change the default behavior for MapBox charts, not just make saved viewport controls functional.

These viewport controls already have defaults in controlPanel, and Explore populates missing form_data keys from control defaults before transformProps runs. With that in place, this override will win over fitBounds even when the user never explicitly saved a viewport, so charts may open on the hard-coded default viewport instead of fitting to their data.

Was the intent to change the default UX for all MapBox charts? If not, we probably need to distinguish between "user explicitly set a viewport" and "formData only contains control defaults".

File: superset-frontend/plugins/legacy-plugin-chart-map-box/src/transformProps.ts [hunk 2]
```diff
@@ -116,5 +119,8 @@ export default function transformProps(chartProps: ChartProps) {
     pointRadiusUnit,
     renderWhileDragging,
     rgb,
+    viewportLongitude,
```
Comment (richardfogaca) [inline superset-frontend/plugins/legacy-plugin-chart-map-box/src/transformProps.ts]: I think we should normalize these before passing them through.

These controls are TextControls with `isFloat`, and they do not always emit numbers: `''` stays `''`, and some valid float inputs such as `10.0` / `-122.40` can remain strings. Forwarding the raw values here means MapBox can receive string or empty viewport props and then write them directly into map state.

Can we coerce these to finite numbers (or leave them undefined) before returning them?

File: superset-frontend/plugins/legacy-plugin-chart-map-box/src/MapBox.tsx (hunk 1 above)
Comment (joaopedroab) [reply superset-frontend/plugins/legacy-plugin-chart-map-box/src/MapBox.tsx]: Good catch! I agree the hardcoded defaults would have overridden `fitBounds` for charts where the user never explicitly set a viewport. I've changed the control defaults in `controlPanel.ts` from the San Francisco coordinates (`-122.405293`, `37.772123`, `11`) to empty strings (`''`). In `transformProps`, the new `toFiniteNumber` helper converts empty strings to `undefined`, so when the user hasn't touched the viewport controls the props come through as `undefined` and `fitBounds` still wins. Only when a user explicitly saves a longitude/latitude/zoom will those values be finite numbers that take effect.

File: superset-frontend/plugins/legacy-plugin-chart-map-box/src/transformProps.ts (hunk 2 above)
Comment (joaopedroab) [reply superset-frontend/plugins/legacy-plugin-chart-map-box/src/transformProps.ts]: Done. I added a `toFiniteNumber` helper that coerces the raw `TextControl` output to a proper `number` or `undefined`:

- Empty strings (`''`), `null`, and `undefined` → `undefined`
- Valid numeric strings like `'10.0'` or `'-122.40'` → the corresponding `number`
- Non-finite results (e.g. `NaN`, `Infinity`) → `undefined`

All four viewport-related props (`viewportLongitude`, `viewportLatitude`, `viewportZoom`, `globalOpacity`) go through this coercion before being returned. `globalOpacity` additionally clamps to `[0, 1]` with a fallback of `1`. Added tests covering string inputs, empty inputs, clamping, and numeric pass-through.

**Comment by richardfogaca** [comment]
I think there’s still one logic gap in the viewport handling.

This fixes the “set a default viewport” path, but it does not fully fix the control behavior when those fields are cleared again. In transformProps, empty viewport values are normalized to undefined, but in MapBox.componentDidUpdate the update logic only applies when the new prop is defined. That means if a user sets lon/lat/zoom and later clears those controls back to blank, the map keeps the last viewport state instead of falling back to fitBounds.

Concretely:

  - transformProps converts '' to undefined
  - componentDidUpdate ignores undefined viewport props
  - result: clearing the controls has no effect

I’d expect blank viewport controls to restore the default fitBounds behavior, not preserve the previous explicit viewport.

The current tests cover initial props, prop updates, and partial updates, but I don’t see coverage for “set viewport, then clear it back to empty”. I’d recommend adding that case and deciding whether clearing should recompute from bounds or otherwise reset the internal viewport state.

**Comment by joaopedroab** [comment]
@richardfogaca 
Thanks for the review. I addressed the residual `fitBounds` issue in `e122e1e13d`.

  The `MapBox` component now recomputes `fitBounds` when `bounds` or chart size changes and no explicit viewport props are set, instead of keeping stale viewport state. I also added focused tests covering:

  - bounds changes with no explicit viewport
  - chart size changes with no explicit viewport
  - explicit viewport continuing to take precedence over `fitBounds`

  The backward-compatibility concern about legacy persisted viewport defaults remains acknowledged and documented in `UPDATING.md`.

  We could handle that with a migration or a compatibility guard, but that adds more complexity and starts to push this PR beyond its scope. In practice, once a user updates the chart once and clears or adjusts the viewport
  fields as needed, the issue is resolved going forward.

  I did not add a compatibility guard for the historical San Francisco triple because that would also override charts intentionally saved at those exact coordinates.

**Review by richardfogaca — APPROVED** [review]
LGTM, great job @joaopedroab 💯
