### PR TITLE
fix: delete Chart under "All" in home page doesn't refresh after dele…

### LINKED ISSUE #39428: Delete Chart under "All" in home page doesn't reload interface
### Bug description

On the home page, there is an option to delete a Chart.

### Screenshots/recordings

Image

### Superset version

6.0.0

### Python version

3.11

### Node version

18 or greater

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by AoLiGei1221**
### SUMMARY
According to https://github.com/apache/superset/issues/39428, this PR fixes a UI refresh issue when deleting charts from the homepage.

Unexpected Behavior:
When deleting a chart under tabs such as "All", the homepage does not update, and the deleted chart remains visible until a manual refresh.

Expected Behavior:
After deleting a chart, the homepage should immediately reflect the updated chart list across all tabs.

Root Cause:
On the homepage, chart data may be initialized using `initialData`, which bypasses the fetch lifecycle in `useListViewResource`. As a result, `lastFetchDataConfig` is not initialized. When `refreshData()` is called without arguments, it becomes a no-op and does not trigger a data refresh.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
After deletion, the home page immediately reflect the changes.
BEFORE:
BEFORE

AFTER:
AFTER

https://github.com/user-attachments/assets/59678db5-ca2e-4b84-9029-efbcdfe4fc59

### TESTING INSTRUCTIONS
1. Go to the Superset homepage
2. Navigate to the "All" tab (or any non-"Mine" tab)
3. Delete a chart
4. Verify that the chart list refreshes immediately and the deleted chart is removed from the UI
5. Repeat the same steps under the "Mine" tab to confirm existing behavior remains unchanged

### ADDITIONAL INFORMATION
- [x] Has associated issue: Fixes #39428
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by AoLiGei1221** [comment]
It looks like not my fault. Could someone help me re-run the CI/CD to check? Thank you!

**Comment by rusackas** [comment]
It seems that things work for dashboards but not for charts in terms of what you're expecting here.Let's see if we can add a failing test for the deletion of charts that gets fixed by this patch.We should also make sure that we're following the same React code patterns that we're using for dashboards in this chart implementation.We might also want to look at saved queries while we're at it if that's going to have a similar problem.If there's any code that can be reused across any and all deletions in the homepage, that would be ideal.

**Comment by AoLiGei1221** [comment]
Hey @rusackas , Thanks for the feedback! I’ve aligned the chart deletion flow with the dashboard pattern. I also added a regression test covering deletion on ALL tabs to ensure the list refreshes correctly. Please check again. Thank you so much! 

https://github.com/user-attachments/assets/59678db5-ca2e-4b84-9029-efbcdfe4fc59

File: superset-frontend/src/features/charts/ChartCard.tsx [hunk 1]
```diff
@@ -120,7 +125,23 @@ export default function ChartCard({
   if (canDelete) {
     menuItems.push({
       key: 'delete',
-      label: (
+      label: onDelete ? (
```
Comment (rusackas) [inline superset-frontend/src/features/charts/ChartCard.tsx]: Is this a whole new button? If so, can we see it in a screenshot?

File: superset-frontend/src/features/home/ChartTable.test.tsx [hunk 2]
```diff
@@ -178,3 +187,58 @@ test('handles chart export with correct ID and shows spinner', async () => {
     { timeout: 3000 },
   );
 });
+
+test('refreshes other tab data after deleting a chart', async () => {
```
Comment (rusackas) [inline superset-frontend/src/features/home/ChartTable.test.tsx:191]: Thank you for adding tests.

File: superset-frontend/src/features/home/ChartTable.tsx [hunk 3]
```diff
@@ -219,6 +224,31 @@ function ChartTable({
           },
         ]}
       />
+      {chartToDelete && (
```
Comment (rusackas) [inline superset-frontend/src/features/home/ChartTable.tsx]: Just checking here, do the other delete buttons have the same kind of modal?If so, is there any code we can reuse here to keep things simple?

File: superset-frontend/src/features/charts/ChartCard.tsx (hunk 1 above)
Comment (AoLiGei1221) [reply superset-frontend/src/features/charts/ChartCard.tsx]: No, this does not introduce a new button. It reuses the existing "Delete" menu item and only changes how the deletion is handled (parent-owned on the homepage vs component-owned elsewhere). The UI remains the same.

**Comment by EnxDev** [comment]
Please could you provide the before/after video inside the description block "BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF", also one suggestion: 
rather than threading a new `refreshDataConfig` param and lifting the delete modal into `ChartTable` with a parallel `onDelete` path, could we mirror what `handleDashboardDelete` already does and just pass `getData` into `handleChartDelete`?

```
// utils.tsx
export function handleChartDelete(
  ...,
  chartFilter?: string,
  userId?: string | number,
  getData?: (tab: TableTab) => void,
) {
  ...
  if (chartFilter === 'Mine') refreshData(filters);
  else if (chartFilter && getData) getData(chartFilter as TableTab);
  else refreshData();
}
```
Then `ChartTable` just forwards its existing `getData` through `ChartCard`, and the inline `ConfirmStatusChange` in the card stays untouched. 
That keeps the fix to ~3 small edits, avoids the dual delete-UX branch in `ChartCard`, and stays consistent with the dashboard pattern.

**Review by rusackas — APPROVED** [review]
LGTM, thanks for the extra effort here, and thanks for the fix in general! 

I added the video from your comment to the PR description as @EnxDev suggested. 

Feel free to provide additional feedback, or merge this if you like it too @EnxDev - and thanks for the review(s).

**Review by EnxDev — APPROVED** [review]
LGTM, thanks!
