### PR TITLE
fix(echarts): adaptive formatting labels

### LINKED ISSUE #38072: 6.0.1.rc1 - last year on bar chart x-axis has incorrect formatting
### Bug description

I'm testing 6.0.1rc1 and found that the last value on a bar chart's x-axis is displaying not as a year, the format of all other x-axis labels, but as a timestamp plus some other string (?). See screenshots below. This is a regression from 6.0.0.

Looking through the changelog for 6.0.1rc1, could have been caused by this: https://github.com/apache/superset/pull/37181 ?

### Screenshots/recordings

Here's the desired behavior in 6.0.0:

Image

Here's the bad behavior in 6.0.1rc1:

Image

Here's the chart's design view, FYI:

Image

### Superset version

master / latest-dev

### Python version

Not applicable

### Node version

Not applicable

### Browser

Firefox

### Additional context

_No response_

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by msyavuz**
### SUMMARY

This PR fixes a critical bug in ECharts Bar Chart X-axis labels where "Adaptive Formatting" was displaying raw timestamps with milliseconds (e.g., "21:13:32 389") instead of properly
  formatted dates like "Jan 2025" or "2004".

  Root Cause: The getXAxisFormatter function was returning undefined for adaptive formatting, causing ECharts to fall back to its default formatter which didn't handle dates properly.

  Solution: Enhanced the smart date formatter to be time grain-aware, ensuring consistent date formatting based on the chart's time granularity (year, quarter, month, week, day, hour).

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:
6 0-before
After:
6 0-after

### TESTING INSTRUCTIONS

1. Create a Bar Chart (Stacked or Unstacked).
2. Use a dataset with a date range spanning several years (e.g., 2003–2005 or 2025–2027).
3. Set the Time Grain to "Month".
4. Set the Time Format on the X-axis to "Adaptive Formatting".
5. Observe the X-axis labels at the boundaries of the date range (start or end).

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #38072
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset/static/service-worker.js
Comment (gabotorresruiz) [inline superset/static/service-worker.js:1]: Do we need this file to be pushed?

File: superset-frontend/plugins/plugin-chart-echarts/src/utils/formatters.ts [hunk 1]
```diff
@@ -29,13 +29,82 @@ import {
...
+    label: baseFormatter.label,
+    formatFunc: (date: Date) => {
+      // Create a normalized date based on time grain to ensure consistent smart formatting
+      const normalizedDate = new Date(date);
+
+      // Always remove milliseconds to prevent .XXXms format
+      normalizedDate.setMilliseconds(0);
+
+      // For all time grains, normalize using UTC methods to avoid timezone issues
+      if (timeGrain === TimeGranularity.YEAR || timeGrain === 'P1Y') {
```
Comment (EnxDev) [inline superset-frontend/plugins/plugin-chart-echarts/src/utils/formatters.ts]: Just to better understand, is there a specific reason for the double comparison here, considering that TimeGranularity.YEAR equals 'P1Y'?

Is the same for the others

File: superset-frontend/plugins/plugin-chart-echarts/test/utils/formatters.test.ts [hunk 2]
```diff
@@ -35,3 +38,135 @@ describe('getPercentFormatter', () => {
     ).toEqual('60.00%');
   });
 });
+
+describe('getXAxisFormatter', () => {
```
Comment (EnxDev) [inline superset-frontend/plugins/plugin-chart-echarts/test/utils/formatters.test.ts]: Do you think it might be better to avoid that?

File: superset-frontend/plugins/plugin-chart-echarts/test/utils/formatters.test.ts [hunk 3]
```diff
@@ -35,3 +38,135 @@ describe('getPercentFormatter', () => {
...
+      // Day formatter should not show milliseconds or seconds
+      const dayResult = (dayFormatter as TimeFormatter).format(date);
+      expect(dayResult).not.toMatch(/\.\d+ms/);
+      expect(dayResult).not.toMatch(/:\d{2}:\d{2}/); // No seconds
+    });
+  });
+
+  test('time grain parameter should be passed correctly', () => {
+    // Test that formatter with time grain is different from formatter without
+    const formatterWithGrain = getXAxisFormatter(SMART_DATE_ID, 'P1M');
```
Comment (EnxDev) [inline superset-frontend/plugins/plugin-chart-echarts/test/utils/formatters.test.ts]: Would it be better to use the existing constant here rather than 'P1M'?

**Comment by EnxDev** [comment]
It might be helpful to include testing instructions in the PR description inside the Testing istructions section

**Comment by EnxDev** [comment]
I performed manual testing, and everything looks good to me

File: superset-frontend/plugins/plugin-chart-echarts/src/utils/formatters.ts (hunk 1 above)
Comment (msyavuz) [reply superset-frontend/plugins/plugin-chart-echarts/src/utils/formatters.ts]: Nice catch! This was a leftover from debugging. Fixing now

File: superset-frontend/plugins/plugin-chart-echarts/src/utils/formatters.ts [hunk 4]
```diff
@@ -29,13 +29,82 @@ import {
...
+    label: baseFormatter.label,
+    formatFunc: (date: Date) => {
+      // Create a normalized date based on time grain to ensure consistent smart formatting
+      const normalizedDate = new Date(date);
+
+      // Always remove milliseconds to prevent .XXXms format
+      normalizedDate.setMilliseconds(0);
+
+      // For all time grains, normalize using UTC methods to avoid timezone issues
+      if (timeGrain === TimeGranularity.YEAR) {
```
Comment (gabotorresruiz) [inline superset-frontend/plugins/plugin-chart-echarts/src/utils/formatters.ts:59]: So quick question here. I see that the `TimeGranularity` has more pre-defined values like `WEEK_STARTING_SUNDAY`, `WEEK_STARTING_MONDAY`, `WEEK_ENDING_SATURDAY`, `WEEK_ENDING_SUNDAY`.

So I'm not sure if we should handle all these variations here to avoid displaying raw timestamps with milliseconds

File: superset/static/service-worker.js
Comment (msyavuz) [reply superset/static/service-worker.js:1]: I am not sure what you mean? I don't see changes to that file in this pr

Comment (gabotorresruiz) [reply superset/static/service-worker.js:1]: This is an old comment. Sorry

File: superset-frontend/plugins/plugin-chart-echarts/src/utils/formatters.ts (hunk 4 above)
Comment (msyavuz) [reply superset-frontend/plugins/plugin-chart-echarts/src/utils/formatters.ts:59]: That's a nice catch. Yeah we should

**Review by EnxDev — APPROVED** [review]
LGTM, thanks memo!

File: superset-frontend/plugins/plugin-chart-echarts/src/utils/formatters.ts (hunk 4 above)
Comment (msyavuz) [reply superset-frontend/plugins/plugin-chart-echarts/src/utils/formatters.ts:59]: Should be handled now

**Comment by michaelmorera-preset** [comment]
The testing for this ticket was completed. The application is working as expected.

# Scenario
Verify the user should not see a timestamp displayed at the end of the chart X Axis when the user creates/edits a bar chart using the time grain month.

| Variant | Status |
| -------- | -------- |
| Bar Chart - Time Grain "Month" | :white_check_mark:  |
| Bar Chart - Time Grain "Quarter" | :white_check_mark:  |
| Bar Chart - Time Grain "Year" | :white_check_mark:  |
| Bar Chart Other Time Grain variants | :white_check_mark:  |
| Bar Chart Some Time Grain variants creating a chart | :white_check_mark:  |
| Bar Chart Some Time Grain variants editing a chart | :white_check_mark:  |
| Line Chart - Time Grain "Month" | :white_check_mark:  |
| Line Chart - Time Grain "Quarter" | :white_check_mark:  |
| Line Chart - Time Grain "Year" | :white_check_mark:  |
| Line Chart Other Time Grain variants | :white_check_mark:  |
| Line Chart Some Time Grain variants creating a chart | :white_check_mark:  |
| Line Chart Some Time Grain variants editing a chart | :white_check_mark:  |


## Steps
1. Create/edit a Bar chart or Line Chart.
2. Use a dataset with a date range spanning several years (e.g., 2003–2005 or 2025–2027).
3. Set the **Time Grain** to "Month".
4. Set the Time Format on the X-axis to "Adaptive Formatting".
5. Observe the X-axis labels at the boundaries of the date range (start or end).

## Expected result
After the step 5, the user should not see a timestamp displayed at the end of the chart X Axis.

## Current result
After the step 5, the user is not seeing a timestamp displayed at the end of the chart X Axis.

## Evidence
### Before - Master current behavior - old behavior
Bar chart time stamp at the end

### After - Fixed Bar chart without time stamp at the end - quarter
Bar chart time stamp not at the end

### After - Fixed Bar chart without time stamp at the end - month
Bar chart time stamp not at the end - month

### After - Fixed Line chart without time stamp at the end - month
Line chart time stamp not at the end - month
