### PR TITLE
fix(charts list): do not trigger ListViewError exception for anonymous user

### LINKED ISSUE #18210: Unexpected error: ListViewError: Invalid filter config, id is not present in columns
Prevent 'undefined' error when viewing the dashboard (or charts) listview in an anonymous mode.

#### How to reproduce the bug

Reproduce the error as follows:

Allow anonymous access by setting `PUBLIC_ROLE_LIKE = "Gamma"`
Without logging in, click on dashboards or charts. This error displays:
_Unexpected error:ListViewError: Invalid filter config, id is not present in columns_

### Expected results
Dashboards/charts must be visible without any issues/errors.

### Actual result
This issue observed when we make upgrade from v1.3 to v1.4

#### Screenshots

image

### Environment

(please complete the following information):

- browser type and version: `Chrome Version 97.0.4692.71`
- superset version: `1.4`
- python version: `Python 3.7.5`
- node.js version: `v8.10.0`

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Browser console log:

_**ListViewError: Invalid filter config, id is not present in columns
    at 87c5db28d6d4ce263182.chunk.js:932:15
    at Array.forEach (<anonymous>)
    at ListView (87c5db28d6d4ce263182.chunk.js:930:13)
    at oh (vendors.866d9853ec9ca701f3b8.entry.js:54972:146)
    at Rj (vendors.866d9853ec9ca701f3b8.entry.js:55080:496)
    at Qj (vendors.866d9853ec9ca701f3b8.entry.js:55065:199)
    at Kj (vendors.866d9853ec9ca701f3b8.entry.js:55065:128)
    at yj (vendors.866d9853ec9ca701f3b8.entry.js:55058:172)
    at vendors.866d9853ec9ca701f3b8.entry.js:54942:115
    at exports.unstable_runWithPriority (vendors.866d9853ec9ca701f3b8.entry.js:55173:467)**_
    
    
image

### PR DESCRIPTION
**Pull request by trepmag**
### SUMMARY
This PR is a follow up for issue #18210 which fixes charts list, while the first PR #19409 fixes the dashboards list.

Note well: this PR is a copy/past of @dudasaron PR #19409 for dashboards list, for which, I must admit, I don't master each changes...

#### Before
Selection_429

#### After
Selection_428

### TESTING INSTRUCTIONS
Was tested on current master (b746e6f): visit the charts list as anonymous user...

### ADDITIONAL INFORMATION
- [x] Has associated issue: fixes #18210 charts list
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/views/CRUD/chart/ChartList.tsx [hunk 1]
```diff
@@ -611,13 +617,27 @@ function ChartList(props: ChartListProps) {
...
+      addDangerToast,
+      addSuccessToast,
+      bulkSelectEnabled,
+      favoriteStatus,
+      hasPerm,
+      loading,
+      userId,
+      refreshData,
+      saveFavoriteStatus,
+      // userKey,
```
Comment (stephenLYZ) [inline superset-frontend/src/views/CRUD/chart/ChartList.tsx:637]: Can we remove this unused code?

**Review by stephenLYZ — APPROVED** [review]
LGTM and leave one nit.

File: superset-frontend/src/views/CRUD/chart/ChartList.tsx (hunk 1 above)
Comment (trepmag) [reply superset-frontend/src/views/CRUD/chart/ChartList.tsx]: Yes, I tested the chart list successfully (connected and anonymously); initial commit was amended minus the above chunk: [0bb05c4](https://github.com/apache/superset/pull/20171/commits/0bb05c4a45fe3684ca2dedf68009bff89f50a499)
