### PR TITLE
fix: toggle fullscreen on the dashboard

### LINKED ISSUE #14961: [dashboard] 'toggle to full screen' option in 3 dot menu do not turn dashboard to full screen
'toggle to full screen' option in 3 dot menu  do not turn dashboard to full screen

### Expected results

click on 'toggle to full screen' will turn dashboard to full screen

### Actual results

dashboard stay the same

#### Screenshots

https://user-images.githubusercontent.com/81597121/120584309-997d0800-c3e4-11eb-8ce9-fced16e92287.mov

#### How to reproduce the bug

1. open a dashboard
2. Click on 'toggle to full screen' option in 3 dot menu
3. See error

### Environment

(please complete the following information):

- superset version: `master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by zhaoyongjie**
### SUMMARY

closes: https://github.com/apache/superset/issues/14961
This is a regression bug. currently, the user can't make the dashboard to fullscreen mode, this PR fixed it.

#### before

https://user-images.githubusercontent.com/2016594/120742302-35b02780-c529-11eb-9b7a-bda29562ad73.mp4

#### after

https://user-images.githubusercontent.com/2016594/120742194-0e595a80-c529-11eb-985a-66dbcbd83c47.mp4

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/14961
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/index.jsx [hunk 1]
```diff
@@ -164,11 +164,12 @@ class HeaderActionsDropdown extends React.PureComponent {
         break;
       }
       case MENU_KEYS.TOGGLE_FULLSCREEN: {
+        const hasStandalone = !!getUrlParam(URL_PARAMS.standalone);
         const url = getDashboardUrl(
           window.location.pathname,
           getActiveFilters(),
           window.location.hash,
-          getUrlParam(URL_PARAMS.standalone),
+          !hasStandalone,
```
Comment (villebro) [inline superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/index.jsx:172]: This comes down to taste, but I think the double bang could be done directly here (seems clear enough).

File: superset-frontend/src/dashboard/util/getDashboardUrl.ts [hunk 2]
```diff
@@ -18,12 +18,13 @@
...
 import { URL_PARAMS } from 'src/constants';
 import serializeActiveFilterValues from './serializeActiveFilterValues';
+import { DashboardStandaloneMode } from './constants';
 
 export default function getDashboardUrl(
   pathname: string,
   filters = {},
   hash = '',
-  standalone?: number | null,
+  standalone?: boolean,
```
Comment (villebro) [inline superset-frontend/src/dashboard/util/getDashboardUrl.ts:27]: `standalone` can actually be called with the value `2`, in which case it removes the title:
image
So perhaps `number | boolean` could be a good solution here, as it appears to work as expected with values `undefined`, `true`, `false`, `0`, `1` and `2`?

Comment (zhaoyongjie) [reply superset-frontend/src/dashboard/util/getDashboardUrl.ts:27]: > `standalone` can actually be called with the value `2`, in which case it removes the title:
> image
> So perhaps `number | boolean` could be a good solution here, as it appears to work as expected with values `undefined`, `true`, `false`, `0`, `1` and `2`?

I know this, but I don't think it's a good design. When we remove the header there is no chance to return it.

File: superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/index.jsx (hunk 1 above)
Comment (zhaoyongjie) [reply superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/index.jsx:172]: the "negation" is needed here, the `hasStandalone` has been boolean type.

Comment (villebro) [reply superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/index.jsx:172]: Right, gotcha 👍

File: superset-frontend/src/dashboard/util/getDashboardUrl.ts (hunk 2 above)
Comment (villebro) [reply superset-frontend/src/dashboard/util/getDashboardUrl.ts:27]: I'm fine with that approach - I think this was discussed to some degree on the PR that introduced it: #12918

Comment (zhaoyongjie) [reply superset-frontend/src/dashboard/util/getDashboardUrl.ts:27]: Thanks for your point out.

File: superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/index.jsx (hunk 1 above)
Comment (villebro) [inline superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/index.jsx:172]: I suppose it would also be correct to do
```js
!getUrlParam(URL_PARAMS.standalone)
```
here?

**Review by villebro — APPROVED** [review]
LGTM with minor stylistic alternative to consider

File: superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/index.jsx (hunk 1 above)
Comment (zhaoyongjie) [reply superset-frontend/src/dashboard/components/Header/HeaderActionsDropdown/index.jsx:172]: right, but I am surprised to do "negation" after returning a number type or null type.
