### PR TITLE
fix: Grab datasets initially onMount

### LINKED ISSUE #12822: [sql lab] Overwrite dataset dropdown does not show available datasets
### Expected results

I would expect to see options from the beginning when I click on dropdown. As for this component 
image.

### Actual results

I can see that when I visit this modal for the first time I do not have suggested datasets to overwrite.
After I visit this place for the second time I can see suggested options.

#### Screenshots

https://user-images.githubusercontent.com/25153919/106203133-37ed2880-61bb-11eb-90d6-8bcfd2ec4255.mov

#### How to reproduce the bug

1. Go to sql lab
2. Execute query ```SELECT grantee from information_schema.applicable_roles  ```
3. tap on explore
4. Click on radio switch Overwrite existing
5. Start typing to see some proposals
6. Clear the edit field
7. Switch the first radio and leave the modal
8. Open Explore again 
9. Click on second radio button and click on edit field -> suggestions are there

### Environment

docker build on a0e05a5eff51a117ff8427967d14fe8758a81332

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x ] I have reproduced the issue with at least the latest released version of superset.
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by hughhhh**
### SUMMARY

User now will be able to see the top 20 datasets, without having to type in the `SaveDataModal.autocomplete`

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
dataset_onload

Closes #12822

### TEST PLAN

1. Goto sql lab
2. Run a query
3. Click Explore
4. Click on `Overwrite Dataset`
5. See dropdown show dataset available

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/SqlLab/components/ResultSet.tsx [hunk 1]
```diff
@@ -159,9 +159,23 @@ export default class ResultSet extends React.PureComponent<
...
   }
 
-  componentDidMount() {
+  async componentDidMount() {
     // only do this the first time the component is rendered/mounted
     this.reRunQueryIfSessionTimeoutErrorOnMount();
+
+    const response = await makeApi({
+      method: 'GET',
+      endpoint: '/api/v1/dataset',
```
Comment (eschutho) [inline superset-frontend/src/SqlLab/components/ResultSet.tsx:168]: do we need to pass in the user id like below on line 342? What's the difference in the api response if you don't?

**Review by betodealmeida — APPROVED** [review]
Nice!
