### PR TITLE
fix: Dashboard time grain in Pivot Table

### LINKED ISSUE #24460: Bug Report: Time Grain issue on pivot-table-v2
#### How to reproduce the bug

1. Create a Pivot-Table with `Time grain filter` .
2. Try to change the Time Grain filter value.

### Expected results
606d34ab-29fc-4b46-8b53-a5d2568c2865

This output because of I manually override the request `timeGrain` of the columns in the chart/data api.

``` python
        if json_body is None:
            return self.response_400(message=_("Request is not JSON"))

        # -----------Temp fix for timeGrain
        q, col = 0, 0

        try:
            # json_body['form_data']['time_grain_sqla'] = json_body.get("form_data").get('extra_form_data').get('time_grain_sqla')
            # print(json_body.get('queries'))
            # if isinstance(json_body.get('queries')[0]['columns'][0], dict):
            #     json_body.get('queries')[0]['columns'][0]['timeGrain'] = json_body.get("form_data").get('extra_form_data').get('time_grain_sqla')
            if json_body.get('queries'):
                for query in json_body.get('queries'):
                    # print(query.get('columns'))
                    if query.get('columns'):
                        for column in query.get('columns'):
                            # print(column)
                            if column.get('timeGrain'):
                                json_body['queries'][q]['columns'][col]['timeGrain'] = json_body.get("form_data").get('extra_form_data').get('time_grain_sqla')
        except Exception:
            pass

        # --------Time Grain fix end here

        try:	        try:
            query_context = self._create_query_context_from_form(json_body)	            query_context = self._create_query_context_from_form(json_body)
            command = ChartDataCommand(query_context)
```

This is not the right fix. I just made; to create an issue and **I am unable to find where the API request made**.

### Actual results

image

### Environment

(please complete the following information):

- browser type and version: `Microsoft Edge`
- superset version: `superset version` `Superset 0.0.0-dev`
- python version: `python --version` `Python 3.10.6`
- node.js version: `node -v` `v18.16.0`
- any feature flags active:
   ```
   FEATURE_FLAGS = {
         "ALERT_REPORTS": True,
         "ENABLE_TEMPLATE_PROCESSING": True,
         "GENERIC_CHART_AXES": True
    }
   ```
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

https://apache-superset.slack.com/archives/C0170U650CQ/p1687178724798949

This is not happening when creating/editing the Chart, but while accessing the chart via dashboard.

After comparing both the `/api/v1/char/data` request, I could see the payload `queries[0].columns[0].timeGrain` value is always `P1D`.
```
{"datasource":{"id":90,"type":"table"},"force":false,"queries":[{"time_range":"Last year","filters":[{"col":"invoice_date","op":"TEMPORAL_RANGE","val":"Last year"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"invoice_date","label":"invoice_date","expressionType":"SQL"},"Product Group"],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"net_billings_in_eur","description":null,"expression":null,"filterable":true,"groupby":true,"id":823,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE PRECISION","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(net_billings_in_eur)","optionName":"metric_n50h3hxsqw_k15ceqbn8qs","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"net_billings_in_eur","description":null,"expression":null,"filterable":true,"groupby":true,"id":823,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE PRECISION","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(net_billings_in_eur)","optionName":"metric_n50h3hxsqw_k15ceqbn8qs","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{"native_filters_key":"Tm4MUjZGIx0ffpDkQ5qYluYYwDaSVdCloUd7Pc8JTc93T3vEX38BVKvP04oUhXV1"},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"90__table","viz_type":"pivot_table_v2","slice_id":299,"url_params":{"native_filters_key":"Tm4MUjZGIx0ffpDkQ5qYluYYwDaSVdCloUd7Pc8JTc93T3vEX38BVKvP04oUhXV1"},"groupbyColumns":["invoice_date"],"groupbyRows":["Product Group"],"time_grain_sqla":"P1D","temporal_columns_lookup":{"invoice_date":true},"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"net_billings_in_eur","description":null,"expression":null,"filterable":true,"groupby":true,"id":823,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE PRECISION","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(net_billings_in_eur)","optionName":"metric_n50h3hxsqw_k15ceqbn8qs","sqlExpression":null}],"metricsLayout":"COLUMNS","adhoc_filters":[{"clause":"WHERE","comparator":"Last year","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"invoice_date"}],"row_limit":10000,"series_limit_metric":null,"order_desc":true,"aggregateFunction":"Sum","valueFormat":"SMART_NUMBER","date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","conditional_formatting":[],"dashboards":[87],"extra_form_data":{"time_range":"Last year","time_grain_sqla":"P1M"},"label_colors":{},"shared_label_colors":{},"extra_filters":[],"dashboardId":87,"force":null,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}
```

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Fixes https://github.com/apache/superset/issues/24460.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before: Check the original issue.

After: The time grain is correctly applied

https://github.com/apache/superset/assets/70410625/d852f213-f6bc-4ee4-b8c3-49283f505a3a

### TESTING INSTRUCTIONS
Check the original issue for instructions.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/plugins/plugin-chart-pivot-table/src/plugin/buildQuery.ts [hunk 1]
```diff
@@ -30,7 +30,10 @@ import {
 import { PivotTableQueryFormData } from '../types';
 
 export default function buildQuery(formData: PivotTableQueryFormData) {
-  const { groupbyColumns = [], groupbyRows = [] } = formData;
+  const { groupbyColumns = [], groupbyRows = [], extra_form_data } = formData;
```
Comment (hughhhh) [inline superset-frontend/plugins/plugin-chart-pivot-table/src/plugin/buildQuery.ts:33]: can we write a small unit test to for buildQuery to verify the grains are being properly set?

Comment (michael-s-molina) [reply superset-frontend/plugins/plugin-chart-pivot-table/src/plugin/buildQuery.ts:33]: Thank you for the references @hughhhh. I added the tests with modifications. 

One tip: you can ask Chat GPT to avoid using `describe` and `it` blocks to generate tests that conform to our [best practices](https://github.com/apache/superset/wiki/Testing-Guidelines-and-Best-Practices#avoid-nesting-when-youre-testing) 😉

**Review by kgabryje — APPROVED** [review]
LGTM

**Comment by yousoph** [comment]
Thanks for the fix @michael-s-molina ! I didn't get a chance to check on the ephemeral before the merge, but I believe this was broken for tables as well and it looks like this fix was only for pivot tables, is that right?

**Comment by michael-s-molina** [comment]
> Thanks for the fix @michael-s-molina ! I didn't get a chance to check on the ephemeral before the merge, but I believe this was broken for tables as well and it looks like this fix was only for pivot tables, is that right?

Yes, it was only for pivot tables. I'll check the table too and submit a fix if it's broken.

**Comment by unnyns-307** [comment]
Hi @michael-s-molina I also found the same behavior occurs on table too.
Just FYI, I tried setting GENERIC_CHART_AXIS = FALSE and the problem is gone. Hope this might help 👍 
I also hope we could fix it to use along with this feature flag too.

**Comment by michael-s-molina** [comment]
> Hi @michael-s-molina I also found the same behavior occurs on table too. Just FYI, I tried setting GENERIC_CHART_AXIS = FALSE and the problem is gone. Hope this might help 👍 I also hope we could fix it to use along with this feature flag too.

Thank you for the details @unnyns-307. I'll fix it.
