### PR TITLE
fix: Filter bar not occupying 100% height when filter sets FF unset

### LINKED ISSUE #15218: [native-filters] filter bar not occupying 100 % height when filter sets FF unset
When enabling `DASHBOARD_NATIVE_FILTERS` but not enabling `DASHBOARD_NATIVE_FILTERS_SET`, the filter Tab doesn't occupy the full height of the screen:

#### Screenshots

With filter sets enabled:
image

With filter sets disabled:
image

#### How to reproduce the bug

1. Enable `DASHBOARD_NATIVE_FILTERS` feature flag
2. Make sure `DASHBOARD_NATIVE_FILTERS_SET` feature flag is unset
3. Go to dashboard with native filters
4. See layout problem

### Environment

master branch

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Fixes https://github.com/apache/superset/issues/15218

@villebro @kgabryje @rusackas 

### AFTER VIDEO
https://user-images.githubusercontent.com/70410625/122401870-5ded4c80-cf53-11eb-9f67-3c307d5b869b.mov

### TESTING INSTRUCTIONS
See the original issue for instructions.

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/components/DashboardBuilder/DashboardBuilder.tsx [hunk 1]
```diff
@@ -55,7 +56,8 @@ const TABS_HEIGHT = 50;
 const HEADER_HEIGHT = 72;
 const CLOSED_FILTER_BAR_WIDTH = 32;
 const OPEN_FILTER_BAR_WIDTH = 260;
-const FILTER_BAR_HEADER_HEIGHT = 128;
+const FILTER_BAR_HEADER_HEIGHT = 80;
+const FILTER_BAR_TABS_HEIGHT = 46;
```
Comment (villebro) [inline superset-frontend/src/dashboard/components/DashboardBuilder/DashboardBuilder.tsx:60]: any reason for the 2 px difference?

**Review by villebro — APPROVED** [review]
LGTM - tested with NF and NF+FS, works well with both
