### PR TITLE
fix: `IS NULL` filter operator for numeric columns

### LINKED ISSUE #13229: Table Viz errors with filters containing number column "IS NOT NULL" or "IS NULL"
On the table viz if someone adds a filter with a numeric column and the filter type "IS NOT NULL" or "IS NULL". The chart errors on [this line](https://github.com/apache/superset/blob/master/superset/connectors/sqla/models.py#L1079) with:

```
File "superset/connectors/sqla/models.py", line 1080, in get_sqla_query
    eq = utils.cast_to_num(flt["val"])
KeyError: 'val'
```
I looked at this line and I don't see anything that has changed recently so I'm assuming that this is related to some change with the table viz. But I'm not sure how it should be handled, the filter has no "val" because it is just an "IS NULL" filter.

### Expected results

Chart should load

### Actual results

Chart errors

#### How to reproduce the bug

1. Create a table chart
2. Add a filter on a numeric column with column "IS NOT NULL"
3. Run query and see error

### Environment

(please complete the following information):

- superset version: `master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

@ktmud do you have any ideas about whether a recent table change might have caused this issue?

### PR DESCRIPTION
**Pull request by ktmud**
### SUMMARY

Fixes #13229  where filters for numeric columns could not use `IS NULL` and `IS NOT NULL` operators in SIMPLE mode.

#### Before

Snip20210305_30

#### After

filter-is-null-after

### TEST PLAN

Manual testing

- Will add more unit tests once SQL query generator was refactored and split into smaller testable functions

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/explore/exploreUtils.js [hunk 1]
```diff
@@ -319,20 +320,14 @@ export const getSimpleSQLExpression = (subject, operator, comparator) => {
...
-    }
+    const comparatorArray = ensureIsArray(comparator);
     const isString =
       firstValue !== undefined && Number.isNaN(Number(firstValue));
     const quote = isString ? "'" : '';
     const [prefix, suffix] = isMulti ? ['(', ')'] : ['', ''];
     const formattedComparators = comparatorArray.map(
-      val => `${quote}${isString ? val.replace("'", "''") : val}${quote}`,
+      val =>
+        `${quote}${isString ? String(val).replace("'", "''") : val}${quote}`,
```
Comment (ktmud) [inline superset-frontend/src/explore/exploreUtils.js:330]: This fixes a rare case when `<NULL>` is used as the first filter value for a numeric column, saving the filter will throw a JS error:

null-first

File: superset/connectors/sqla/models.py [hunk 2]
```diff
@@ -1061,23 +1061,34 @@ def get_sqla_query(  # pylint: disable=too-many-arguments,too-many-locals,too-ma
                     target_column_is_numeric=col_obj.is_numeric,
                     is_list_target=is_list_target,
                 )
-                if op in (
-                    utils.FilterOperator.IN.value,
-                    utils.FilterOperator.NOT_IN.value,
-                ):
-                    cond = col_obj.get_sqla_col().in_(eq)
-                    if isinstance(eq, str) and NULL_STRING in eq:
```
Comment (ktmud) [inline superset/connectors/sqla/models.py:1069]: `NULL_STRING` is already parsed to `None` in `filter_values_handler`, so this is not needed.

File: superset/connectors/sqla/models.py [hunk 3]
```diff
@@ -1061,23 +1061,34 @@ def get_sqla_query(  # pylint: disable=too-many-arguments,too-many-locals,too-ma
...
+                        raise QueryObjectValidationError(
+                            _("Filter value list cannot be empty")
                         )
+                    if None in eq:
+                        eq = [x for x in eq if x is not None]
+                        is_null_cond = col_obj.get_sqla_col().is_(None)
+                        if eq:
+                            cond = or_(is_null_cond, col_obj.get_sqla_col().in_(eq))
+                        else:
+                            cond = is_null_cond
```
Comment (ktmud) [inline superset/connectors/sqla/models.py:1075]: Do additional check to make the generated where clause cleaner for when there are `NULL` in the `IN` list.

Previously it may generate:

```sql
WHERE abc in (NULL, 123) OR abc IS NULL
```

Now it generates:

```sql
WHERE abc in (123, ) OR abc IS NOT NULL
```

File: superset/connectors/base/models.py [hunk 4]
```diff
@@ -359,10 +359,7 @@ def handle_single_value(value: Optional[FilterValue]) -> Optional[FilterValue]:
         if is_list_target and not isinstance(values, (tuple, list)):
             values = [values]  # type: ignore
         elif not is_list_target and isinstance(values, (tuple, list)):
-            if values:
-                values = values[0]
-            else:
-                values = None
+            values = values[0] if values else None
```
Comment (bkyryliuk) [inline superset/connectors/base/models.py:362]: if values could be dangerous, as [],0, None would return false, it would be nice to be a bit more specific in the check.

File: superset/connectors/sqla/models.py [hunk 5]
```diff
@@ -1061,23 +1060,36 @@ def get_sqla_query(  # pylint: disable=too-many-arguments,too-many-locals,too-ma
...
-                    utils.FilterOperator.IN.value,
-                    utils.FilterOperator.NOT_IN.value,
-                ):
-                    cond = col_obj.get_sqla_col().in_(eq)
-                    if isinstance(eq, str) and NULL_STRING in eq:
-                        cond = or_(
-                            cond,
-                            col_obj.get_sqla_col()  # pylint: disable=singleton-comparison
-                            == None,
+                if is_list_target:
```
Comment (bkyryliuk) [inline superset/connectors/sqla/models.py:1063]: is it possible to add unit tests here?

Comment (ktmud) [reply superset/connectors/sqla/models.py:1067]: Done.

More granular logics could be handled by actual unit tests when we break down the query generator. I also added "revisit:add-tests" label to mark this as a followup item.

**Review by bkyryliuk — APPROVED** [review]

**Comment by bkyryliuk** [comment]
Thanks for the fix!

File: superset/connectors/sqla/models.py (hunk 3 above)
Comment (ktmud) [reply superset/connectors/sqla/models.py:1079]: Oh, it was a typo... Thanks for noting.
