### PR TITLE
fix: annotation modal dateRangePicker saved invalid value

### LINKED ISSUE #13958: [Annotation]Adding annotation date picker shows "Invalid date"
Adding a new annotation fails because selecting a date gives "Invalid date"

### Expected results

Dates are reflected in the UI field

### Actual results

UI field shows "Invalid date" and calendar turns into a bunch of NaN

#### Screenshots

image

image

#### How to reproduce the bug

(starting with docker-compose up)
1. Go to Settings > Annotation layers
2. Click on '+ Annotation Layer'
3. Add a name, click ADD
4. Click '+ Annotation'
5. Click 'Start date' field
6. Enter any date for start and end
7. Click OK
8. Notice field says "Invalid date" and the calendar that pops up only has NaN
9. If you click ADD anyways, an error pops up with "An error occurred while creating annotations: (end_dttm) Not a valid datetime.
(start_dttm) Not a valid datetime."

### Environment

(please complete the following information):

- superset version: f19f2c3ac884 (current master)
- python version: python 3.7.9
- node.js version: 14.16.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by zhaoyongjie**
### SUMMARY

Since moment.js cannot parse `YYY-MM-DD hh:mm a` format, an error will occur.  

Now we use a  consistent format for saving and parsing datetime object.

closes: https://github.com/apache/superset/issues/13958

#### before
image

#### After
image

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/views/CRUD/annotation/AnnotationModal.tsx [hunk 1]
```diff
@@ -311,14 +311,13 @@ const AnnotationModal: FunctionComponent<AnnotationModalProps> = ({
           <span className="required">*</span>
         </div>
         <RangePicker
-          format="YYYY-MM-DD hh:mm a"
+          format="YYYY-MM-DD HH:mm"
```
Comment (nytai) [inline superset-frontend/src/views/CRUD/annotation/AnnotationModal.tsx:314]: We should start collecting these formats in a module.

**Review by nytai — APPROVED** [review]

**Review by michael-s-molina — APPROVED** [review]
