### PR TITLE
fix(table): Use extras in queries

### LINKED ISSUE #30193: `show summary` does not correctly apply all filters
### Bug description

In the changes introduced in #28057 ([code](https://github.com/apache/superset/pull/28057/files#diff-0186dcc4a861c06db2a94660bfcd32fb3301eee43a0d9c16e8e3b592ad7f8fc1R248)), all parameters are discarded when passing extras. However, the custom SQL filters are set within the extras, leading to an issue where the show summary feature does not correctly apply these filters, as illustrated in the attached image.

### How to reproduce the bug

1. Set the filter using custom SQL.
2. Select the show summary option.
3. Observe that the summary of the query results does not apply the filter.

### Screenshots/recordings

image

### Superset version

master / latest-dev

### Python version

3.10

### Node version

18 or greater

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by Antonio-RiveroMartnez**
### SUMMARY
`Table` chart was removing the `extras` from the summary query, assuming they were only used for time grains. This PR fixes that and put the extras back in the queryObject sent as payload, now, only excluding `time_grain_sqla` if no temporal column is included in your chart.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before: Excluding extras from summary query and only adding it if no time comparison was used
before

Now: Sending extras in the total query regardless you're using time comparison
No temporal Column
now_no_temp
With temporal Column
now_temp

### TESTING INSTRUCTIONS
1. Create a `Table` Chart
2. Use no temporal column and a custom SQL filter
3. Mark the `Show summary` checkbox
4. The queries sent as payload must include the `where` in extras for both queries and not include a `time_grain_sqla`
5. Now add a temporal column to your chart and run the query again
6. The `time_grain_sqla` must be present in the extras alongside with the `where` clause

### ADDITIONAL INFORMATION

- [X] Has associated issue: https://github.com/apache/superset/issues/30193
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/plugins/plugin-chart-table/src/buildQuery.ts [hunk 1]
```diff
@@ -198,10 +198,15 @@ const buildQuery: BuildQuery<TableChartFormData> = (
         (ownState.currentPage ?? 0) * (ownState.pageSize ?? 0);
     }
 
+    if (!temporalColum) {
+      // This query is using only textual columns, so it doesn't need time grain
```
Comment (giftig) [inline superset-frontend/plugins/plugin-chart-table/src/buildQuery.ts:202]: Or numerical presumably. Probably most accurate just to say it doesn't have any temporal columns so there's no time grain.

File: superset-frontend/plugins/plugin-chart-table/test/buildQuery.test.ts [hunk 2]
```diff
@@ -114,5 +114,66 @@ describe('plugin-chart-table', () => {
...
+            subject: null,
+            operator: null,
+            comparator: null,
+            isExtra: false,
+            isNew: false,
+            datasourceWarning: false,
+            filterOptionName: 'filter_v8m9t9oq5re_ndzk6g5am7',
+          } as any,
+        ],
+      });
```
Comment (giftig) [inline superset-frontend/plugins/plugin-chart-table/test/buildQuery.test.ts:170]: There's a lot of repetition here, I see there's already `...basicFormData`, feels like the bulk of this could be similarly reused to stay DRY. It'd make it much easier to see exactly what's different between the two tests here as well.

**Review by giftig — APPROVED** [review]
Minor suggestions but LGTM

**Review by giftig — APPROVED** [review]
