### PR TITLE
fix(dashboard): table chart drag preview overflowing container

### LINKED ISSUE #26873: Drag table chart preview issue
## Screenshot

https://github.com/apache/superset/assets/1392866/fe4acbd4-16a9-43b9-9e7b-cbd2268392a3

## Description

When a table chart is dragged, the preview container appears to overflow beyond the actual chart size, likely due to the inner table chart itself overflowing.

## Design input
We should have a static image for the table chart (or hide the table component on drag preview)

### PR DESCRIPTION
**Pull request by rtexelm**
### SUMMARY

Table charts were creating preview sizes much larger than intended causing surrounding objects to be cropped into the preview when dragging. This is a known issue with `react-dnd` on chromium browsers, see [here](https://github.com/react-dnd/react-dnd/issues/832). This is a simple style fix to the parent element.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

B:
drag-overflow-ezgif com-optimize
A:
dnd-overflow-fix-ezgif com-optimize

### TESTING INSTRUCTIONS

- Edit a dashboard containing table charts
- Drag a table chart card that has scroll bars

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #26873 
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/components/dnd/DragDroppable.jsx [hunk 1]
```diff
@@ -77,6 +77,7 @@ const defaultProps = {
 const DragDroppableStyles = styled.div`
   ${({ theme }) => css`
     position: relative;
+    transform: translate3d(0, 0, 0);
```
Comment (kgabryje) [inline superset-frontend/src/dashboard/components/dnd/DragDroppable.jsx:80]: Could you add a comment with a link to the comment in react-dnd repo that provided this solution?

**Comment by kgabryje** [comment]
In the react-dnd issue that you linked there are some comments that this solution didn't work correctly. I tested it and works great, but would be great if more people could give it a try (pinging @villebro @michael-s-molina @eschutho)

**Review by justinpark — APPROVED** [review]
It looks great! I love the idea. Thanks @rtexelm for the hotfix.
LGTM other than @kgabryje comment.

**Review by kgabryje — APPROVED** [review]
LGTM!

**Review by geido — APPROVED** [review]
Tested on Safari too. Looks great

**Review by michael-s-molina — APPROVED** [review]
LGTM. Thank you for the fix!
