### PR TITLE
fix(dashboard): custom css should be removed on unmount

### LINKED ISSUE #14681: [CSS template]don't apply CSS template on menu, submenu and page background
## Screenshot
This is my custom css template
image
Return to the dashboards from my custom css template dashboard
image

## Description
1. Opening the custom css template dashboard 
2. Open the following panels: dashboards, charts, databases, datasets, SQL saved query/query history .
3. See to error

##Environment
superset version:master
## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

### PR DESCRIPTION
**Pull request by suddjian**
### SUMMARY

Unmounts custom dashboard css when the dashboard page unmounts

Cleaned up the `DashboardPage` logic a bit to be clearer

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

before (after viewing a dashboard that sets `span { background: pink }`):

Screen Shot 2021-06-07 at 12 40 12 PM

after:

Screen Shot 2021-06-07 at 12 41 20 PM

### TESTING INSTRUCTIONS

1. Turn React Crud View on
2. Navigate to a dashboard with custom css that could effect several pages
3. Navigate to any other SPA page (currently list views or homepage)

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #14681 
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by nytai — APPROVED** [review]

File: superset-frontend/src/dashboard/util/injectCustomCss.ts [hunk 1]
```diff
@@ -16,19 +16,31 @@
...
-  }
-
-  if (style.styleSheet) {
-    style.styleSheet.cssText = css;
+  if ('styleSheet' in style) {
+    // The original, non-typescript code referenced `style.styleSheet`.
+    // I can't find what sort of element would have a styleSheet property,
+    // and don't know in what situation this condition would be true,
+    // so have created this type to satisfy TS without changing behavior.
+    type MysteryStyleElement = {
```
Comment (nytai) [inline superset-frontend/src/dashboard/util/injectCustomCss.ts:38]: maybe move this type up to the module scope?
