### PR TITLE
fix: uneven list header padding (#12029)

### LINKED ISSUE #12029: [listview]: uneven top and bottom header padding
Screen Shot 2020-12-13 at 8 31 54 PM

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Adjust list header padding.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Screen Shot 2021-01-11 at 11 58 16 AM
Screen Shot 2021-01-11 at 2 21 52 PM

Closes #12029 

@junlincc 

### TEST PLAN
1 - Go to any major list (charts, dashboards, databases, etc)
2 - Check header padding

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/components/dataViewCommon/TableCollection.tsx [hunk 1]
```diff
@@ -77,11 +80,14 @@ export const Table = styled.table`
 
     span {
       white-space: nowrap;
+      display: flex;
+      align-items: center;
+      min-height: ${({ theme }) => theme.gridUnit * 6}px;
```
Comment (geido) [inline superset-frontend/src/components/dataViewCommon/TableCollection.tsx:85]: line-height might be more appropriate here

File: superset-frontend/src/components/dataViewCommon/TableCollection.tsx [hunk 2]
```diff
@@ -51,7 +52,9 @@ export const Table = styled.table`
   th {
     background: ${({ theme }) => theme.colors.grayscale.light5};
     position: sticky;
+    height: ${({ theme }) => theme.gridUnit * 11}px;
```
Comment (geido) [inline superset-frontend/src/components/dataViewCommon/TableCollection.tsx:55]: This should be unnecessary

**Review by geido — CHANGES_REQUESTED** [review]

**Comment by adam-stasiak** [comment]
tested - No issues found

**Review by geido — APPROVED** [review]

**Review by junlincc — APPROVED** [review]
LGTM, perfect!
After:
Screen Shot 2021-01-12 at 10 49 38 AM

Before:
Screen Shot 2021-01-12 at 10 50 14 AM

@nytai please take a look since we touched your area. 

NOTE⚠️: 
- This is only Product and QA approval with NO code reviews 
- This approval indicates that all UI changes meet product requirement, no noticeable regression is   introduced
- This approval indicates this PR is ready for code reviews

**Review by rusackas — APPROVED** [review]

**Comment by rusackas** [comment]
Code looks good to me. Tempted to do the usual nag about `gridUnit`, but I don't like fractional `gridUnit`s, so I'll let the `2px` go :)

I'd merge this, but would love to have @nytai's nod of approval first :D

**Review by nytai — APPROVED** [review]
