### PR TITLE
Replace pandas.DataFrame with PyArrow.Table for nullable int typing

### LINKED ISSUE #8225: Pandas casting int64 to float64, misrepresenting value
I have the following data being returned by Presto (single column, 6 rows):

```
[(None,), (1239162456494753670,), (None,), (None,), (None,), (None,)
```

Due to the missing data (`None`), Pandas infers the type as `float64`, converting the value to a wrong id:

```python
>>> column_names = ['organization_lyft_id']
>>> data = [(None,), (1239162456494753670,), (None,), (None,), (None,), (None,)]
>>> df = pd.DataFrame(list(data), columns=column_names).infer_objects()  # SupersetDataFrame
>>> print(df)
   organization_lyft_id
0                   NaN
1          1.239162e+18
2                   NaN
3                   NaN
4                   NaN
5                   NaN
>>> print(df.dtypes)
organization_lyft_id    float64
dtype: object
```

The number then shows up as `1239162456494753800` in SQL Lab.

Here's the Pandas documentation on this:

> ... pandas primarily uses NaN to represent missing data. Because NaN is a float, this forces an array of integers with any missing values to become floating point. In some cases, this may not matter much. But if your integer column is, say, an identifier, casting to float can be problematic. **Some integers cannot even be represented as floating point numbers.** (emphasis mine)

Note that if the missing data is filtered the value is inferred as an int64, and it shows up correctly in SQL Lab:

```python
>>> column_names = ['organization_lyft_id']
>>> data = [(1239162456494753670,)]
>>> df = pd.DataFrame(list(data), columns=column_names).infer_objects()  # SupersetDataFrame
>>> print(df)
   organization_lyft_id
0   1239162456494753670
>>> print(df.dtypes)
organization_lyft_id    int64
dtype: object

```

The solution is to pass a `dtype` argument when creating the Pandas data frame, built from the cursor description. I'm working on a fix for this.

### PR DESCRIPTION
**Pull request by robdiciuccio**
### CATEGORY

Choose one

- [x] Bug Fix
- [x] Enhancement (new features, refinement)
- [x] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY
Load raw query result data into a [PyArrow.Table](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html) structure, which handles nullable integer columns correctly. Convert Table to pandas.DataFrame when necessary for data manipulation.

Fixes https://github.com/apache/incubator-superset/issues/8225

**Note:** this PR also (re)sets the default configuration `RESULTS_BACKEND_USE_MSGPACK = True` based on the benchmarks below, and the coupling with `PyArrow`.

**TODO**
- [x] Finish porting `.columns` method to `SupersetTable`
- [x] Remove explicit `dtype` logic from `PrestoEngineSpec`
- [x] Fix failing tests 

### TEST PLAN

- Ensure correct query operations in SQL Lab and Explore views, via synchronous and async queries.
- Test against columns including mixed integer + NULL values.

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/incubator-superset/issues/8225
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
@betodealmeida @john-bodley 

### BENCHMARKS (2019-12-30)

_All metrics below are averages over at least three runs on a local Superset installation running with a Postgres metadata and analytics DB (Macbook Pro 2.6 GHz, 32GB). The queries run here are selecting 100K rows from the **birth_names** table in the example datasets._

- Instantiation of the new `SupersetTable` object in SQL Lab was slightly faster than `SupersetDataFrame` at **99.72444661ms** vs **124.0594076ms**, respectively.
- Memory usage for the PyArrow.Table (**5659776 bytes**) was _significantly_ lower than the Pandas DataFrame (**22259209 bytes**).
- Serialization for async queries is where the biggest performance gains are. PyArrow performed better in nearly all metrics, with the following standouts:
  - On `master`, serialization/deserialization of the dataframe via `json` takes an average of **~7750ms**
  - Pyarrow (with `msgpack` disabled) reduces this cycle to **~2850ms**
  - Enabling `msgpack` in the serialization workflow further reduces this to **~1700ms**, representing a **~78% performance improvement**.

### CODE REVIEW

**Comment by robdiciuccio** [comment]
One last issue with `datetime` timezone support to address.

**Comment by john-bodley** [comment]
@robdiciuccio an issue was reported recently at Airbnb where nullable booleans weren’t being reported correctly, i.e., `NULL` was being cast to `false` per [here](https://stackoverflow.com/questions/34520267/getting-boolean-pandas-column-that-supports-na-is-nullable). 

Is this something which will be resolved by using `PyArrow`? 

cc: @etr2460 @graceguo-supercat

**Comment by robdiciuccio** [comment]
@john-bodley `PyArrow` serialization appears to handle this case correctly. Test case added 
 in https://github.com/apache/incubator-superset/pull/8733/commits/a6e6b797209676f97a1c6c6a7ed631e2594411e5.

I'm hoping to wrap up the remaining timezone issue on this PR later this weekend or Monday (I'm out today).

File: superset/assets/spec/javascripts/sqllab/ExploreResultsButton_spec.jsx [hunk 1]
```diff
@@ -55,13 +55,11 @@ describe('ExploreResultsButton', () => {
   const mockColumns = {
     ds: {
       is_date: true,
-      is_dim: false,
```
Comment (robdiciuccio) [inline superset/assets/spec/javascripts/sqllab/ExploreResultsButton_spec.jsx]: @mistercrunch removing `is_dim` everywhere as it doesn't appear to be used any longer.

File: tests/core_tests.py [hunk 2]
```diff
@@ -719,26 +721,11 @@ def test_mssql_engine_spec_pymssql(self):
...
             list(data), [["col1"], ["col2"], ["col3"]], MssqlEngineSpec
         )
-        data = df.data
-        self.assertEqual(len(data), 2)
-        self.assertEqual(
-            data[0],
-            {"col1": 1, "col2": 1, "col3": pd.Timestamp("2017-10-19 23:39:16.660000")},
-        )
-
-    def test_mssql_engine_spec_odbc(self):
```
Comment (robdiciuccio) [inline tests/core_tests.py]: Was thinking when I ripped this out that it was no longer necessary due to transformations [here](https://github.com/apache/incubator-superset/blob/master/superset/db_engine_specs/mssql.py#L64), but it looks like additional transformation is required. cc @chinhngt

File: superset/dataframe.py [hunk 3]
```diff
@@ -14,257 +14,21 @@
...
-            if not column["agg"]:
-                column.pop("agg", None)
-            columns.append(column)
-        return columns
+def df_to_dict(dframe: pd.DataFrame) -> Dict:
+    data = dframe.to_dict(orient="records")
+    # TODO: refactor this
+    for d in data:
+        for k, v in list(d.items()):
+            # if an int is too big for Java Script to handle
```
Comment (willbarrett) [inline superset/dataframe.py]: nit: `JavaScript`

File: superset/dataframe.py [hunk 4]
```diff
@@ -14,257 +14,21 @@
...
-            total += 1
-            try:
-                pd.to_datetime(value)
-                success += 1
-            except Exception:
-                continue
-        return 100 * success / total
-
-    @staticmethod
-    def is_date(np_dtype, db_type_str):
```
Comment (robdiciuccio) [inline superset/dataframe.py]: @mistercrunch curious on your opinion of the date detection changes, mainly because I don't understand the context behind https://github.com/apache/incubator-superset/pull/5634

File: superset/dataframe.py [hunk 5]
```diff
@@ -14,257 +14,21 @@
...
+    data = dframe.to_dict(orient="records")
+    # TODO: refactor this
+    for d in data:
+        for k, v in list(d.items()):
+            # if an int is too big for Java Script to handle
+            # convert it to a string
+            if isinstance(v, int):
+                if abs(v) > JS_MAX_INTEGER:
+                    d[k] = str(v)
+    return data
```
Comment (willbarrett) [inline superset/dataframe.py]: Would it be preferable or simpler to convert all numeric types in the dataframe to strings before dict-ifying it to (I presume) send to the client?

Comment (robdiciuccio) [reply superset/dataframe.py]: Yes, we could do that, but I'm unclear on the frontend implications of shipping Ints as strings. When the column contains nullable integer values, the conversion from PyArrow to Pandas DataFrame is done via an `object` dtype (string).

File: superset/assets/spec/javascripts/sqllab/ExploreResultsButton_spec.jsx (hunk 1 above)
Comment (mistercrunch) [reply superset/assets/spec/javascripts/sqllab/ExploreResultsButton_spec.jsx]: kill!

Comment (mistercrunch) [reply superset/assets/spec/javascripts/sqllab/ExploreResultsButton_spec.jsx]: I think it may map to that right-most checkbox, and define whether things show up in `groupby` controls
Screen Shot 2019-12-12 at 11 01 42 PM

Comment (mistercrunch) [reply superset/assets/spec/javascripts/sqllab/ExploreResultsButton_spec.jsx]: Yup, it used to map to `BaseColumn.groupby`, but not anymore. Seems we can remove all refs to `is_dim`

File: superset/dataframe.py (hunk 5 above)
Comment (mistercrunch) [reply superset/dataframe.py]: It seems dangerous either way. Could JS do arrow and magically do the right thing around bigints? Didn't read, but pasting https://arrow.apache.org/docs/js/

Comment (robdiciuccio) [reply superset/dataframe.py]: We may be able to send Arrow or Msgpack-encoded data over the wire to the client in future work. In the interest of limiting scope here, I propose we stick with the existing approach for handling BigInts for now, and revisit in a fast-follow that's more focused on performance optimization.

File: superset/dataframe.py [hunk 6]
```diff
@@ -14,257 +14,23 @@
...
-                    and self.datetime_conversion_rate(sample[col])
-                    > INFER_COL_TYPES_THRESHOLD
-                ):
-                    column.update({"is_date": True, "is_dim": False, "agg": None})
-            # 'agg' is optional attribute
-            if not column["agg"]:
-                column.pop("agg", None)
-            columns.append(column)
-        return columns
+def df_to_dict(dframe: pd.DataFrame) -> Dict:
```
Comment (villebro) [inline superset/dataframe.py]: nit: similar to how `pd` generally refers to `Pandas`, `df` commonly refers to `DataFrame` (as in the method name). Also add types to Dict, e.g. `Dict[str, Any]`.

File: superset/dataframe.py [hunk 7]
```diff
@@ -14,257 +14,23 @@
...
+    data = dframe.to_dict(orient="records")
+    # TODO: refactor this
+    for d in data:
+        for k, v in list(d.items()):
+            # if an int is too big for Java Script to handle
+            # convert it to a string
+            if isinstance(v, int):
+                if abs(v) > JS_MAX_INTEGER:
+                    d[k] = str(v)
```
Comment (villebro) [inline superset/dataframe.py]:
```python
if isintance(v, int) abs(v) > JS_MAX_INTEGER:
    d[k] = str(v)
```

File: superset/table.py [hunk 8]
```diff
@@ -0,0 +1,158 @@
...
+        if s_fixed_case in seen:
+            seen[s_fixed_case] += 1
+            s += suffix + str(seen[s_fixed_case])
+        else:
+            seen[s_fixed_case] = 0
+        new_l.append(s)
+    return new_l
+
+
+class SupersetTable(object):
```
Comment (villebro) [inline superset/table.py]: py3 nit: remove `(object)`

File: superset/sql_lab.py [hunk 9]
```diff
@@ -264,12 +265,12 @@ def _serialize_payload(
...
 def _serialize_and_expand_data(
-    cdf: SupersetDataFrame,
+    result_table: SupersetTable,
     db_engine_spec: BaseEngineSpec,
     use_msgpack: Optional[bool] = False,
     expand_data: bool = False,
 ) -> Tuple[Union[bytes, str], list, list, list]:
-    selected_columns: list = cdf.columns or []
+    selected_columns: list = result_table.columns
     expanded_columns: list
```
Comment (villebro) [inline superset/sql_lab.py]: nit: I'm guessing these are `List[str]`

File: superset/sql_lab.py [hunk 10]
```diff
@@ -278,14 +279,17 @@ def _serialize_and_expand_data(
...
                 .to_buffer()
                 .to_pybytes()
             )
+
         # expand when loading data from results backend
         all_columns, expanded_columns = (selected_columns, [])
     else:
-        data = cdf.data or []
+        df = result_table.to_pandas_df()
+        data = df_to_dict(df) or []
```
Comment (villebro) [inline superset/sql_lab.py]: shouldn't this be `df_to_dict(df) or {}`?

File: superset/table.py [hunk 11]
```diff
@@ -0,0 +1,158 @@
...
+    def __init__(self, data, cursor_description, db_engine_spec):
```
Comment (villebro) [inline superset/table.py]: types would be great here

File: superset/table.py [hunk 12]
```diff
@@ -0,0 +1,158 @@
...
+                col: db_engine_spec.get_datatype(cursor_description[i][1])
+                for i, col in enumerate(column_names)
+                if cursor_description
+            }
+        except Exception as e:
+            logging.exception(e)
+
+    @classmethod
+    def pa_table_to_df(cls, pa_table):
+        return pa_table.to_pandas(integer_object_nulls=True)
```
Comment (villebro) [inline superset/table.py]: Should this be static and prefixed with `convert_` or similar?
```python
@staticmethod
def convert_table_to_df(table: pa.Table) -> pd.DataFrame:
```

File: superset/table.py [hunk 13]
```diff
@@ -0,0 +1,158 @@
...
+
+    @staticmethod
+    def is_date(db_type_str):
+        return db_type_str in ("DATETIME", "TIMESTAMP")
```
Comment (villebro) [inline superset/table.py]: types

File: superset/table.py [hunk 14]
```diff
@@ -0,0 +1,158 @@
...
+
+    @classmethod
+    def is_id(cls, column_name):
+        return column_name.startswith("id") or column_name.endswith("id")
```
Comment (villebro) [inline superset/table.py]: static and types?

File: superset/table.py [hunk 15]
```diff
@@ -0,0 +1,158 @@
...
+
+    def data_type(self, col_name: str, pa_dtype: pa.DataType):
```
Comment (villebro) [inline superset/table.py]: Is the return type here `Optional[str]`?

File: superset/table.py [hunk 16]
```diff
@@ -0,0 +1,158 @@
...
+            return set_type
+
+        mapped_type = self.convert_pa_dtype(pa_dtype)
+        if mapped_type:
+            return mapped_type
+
+        return None
+
+    @staticmethod
+    def convert_pa_dtype(pa_dtype: pa.DataType):
```
Comment (villebro) [inline superset/table.py]: return type `Optional[str]`

File: superset/table.py [hunk 17]
```diff
@@ -0,0 +1,158 @@
...
+            return "INT"
+        if pa.types.is_floating(pa_dtype):
+            return "FLOAT"
+        if pa.types.is_string(pa_dtype):
+            return "STRING"
+        if pa.types.is_temporal(pa_dtype):
+            return "DATETIME"
+        return None
+
+    def to_pandas_df(self):
```
Comment (villebro) [inline superset/table.py]: `-> pd.DataFrame`

File: superset/table.py [hunk 18]
```diff
@@ -0,0 +1,158 @@
...
+        return self.pa_table_to_df(self.table)
+
+    @property
+    def pa_table(self):
```
Comment (villebro) [inline superset/table.py]: `-> pa.Table`?

File: superset/table.py [hunk 19]
```diff
@@ -0,0 +1,158 @@
...
+        return self.table
+
+    @property
+    def size(self):
```
Comment (villebro) [inline superset/table.py]: `-> int`

File: superset/table.py [hunk 20]
```diff
@@ -0,0 +1,158 @@
...
+        return self.table.num_rows
+
+    @property
+    def columns(self):
```
Comment (villebro) [inline superset/table.py]: `-> List[Dict[str, Any]]`?

**Review by villebro — COMMENTED** [review]
Really great to to be moving from pandas to pyarrow 👍 Apologies for the nit-fest!

File: superset/dataframe.py (hunk 6 above)
Comment (robdiciuccio) [reply superset/dataframe.py]: Using `dframe` here due to a linter complaining about `df` as an argument.

File: superset/sql_lab.py (hunk 10 above)
Comment (robdiciuccio) [reply superset/sql_lab.py]: One would think, but this is calling `to_dict(orient="records")` which returns list of dicts:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_dict.html

File: tests/core_tests.py (hunk 2 above)
Comment (robdiciuccio) [reply tests/core_tests.py]: Refactored and added some additional tests around this. Should be good to go.

File: superset/dataframe.py (hunk 6 above)
Comment (villebro) [reply superset/dataframe.py]: In reference to my comment below about `df_to_dict` being expected to return a `dict`, shouldn't this in fact return a `List[Dict[str, Any]]`? Looks like mypy missed this as `data` wasn't typed below, and is hence implicitly typed `Any`.

File: superset/dataframe.py (hunk 3 above)
Comment (villebro) [reply superset/dataframe.py]: Nit pending

**Review by villebro — APPROVED** [review]
A few last minor nits, otherwise LGTM

**Comment by robdiciuccio** [comment]
Profiling info added in the description (good news!). Unless there are any additional concerns (particularly around date detection) or testing against additional analytics databases, I think this should be ready to go.

**Comment by robdiciuccio** [comment]
Spoke too soon, investigating some dashboard discrepancies with the example data.

**Comment by robdiciuccio** [comment]
Dashboard discrepancies were due to stale cache. Retested dashboards and SQL Lab with fresh example data in postgres and mysql. LGTM.

**Comment by villebro** [comment]
@mistercrunch @willbarrett I propose merging this; any comments or good to go?

File: superset/table.py [hunk 21]
```diff
@@ -0,0 +1,177 @@
...
+        if s_fixed_case in seen:
+            seen[s_fixed_case] += 1
+            s += suffix + str(seen[s_fixed_case])
+        else:
+            seen[s_fixed_case] = 0
+        new_l.append(s)
+    return new_l
+
+
+class SupersetTable:
```
Comment (mistercrunch) [inline superset/table.py]: "Table" can be confusing, how about `SupersetResultSet`

File: superset/sql_lab.py (hunk 10 above)
Comment (mistercrunch) [reply superset/sql_lab.py]: Could be renamed `df_to_dicts` or `df_to_records` for clarity

**Review by mistercrunch — APPROVED** [review]
I have 2 super minor comments, otherwise LGTM. It seems like type detection that relied on pandas magic in the past could be affected, but there's really no way to tell.

**Comment by graceguo-supercat** [comment]
Hi @robdiciuccio I am trying to deploy this feature to airbnb production. But I got many errors from **Presto** queries: 
`Unserializable object ['silver.braavos_staging.revenue_validation_detail_metrics'] of type <class 'numpy.ndarray'>`
or
`Not implemented type for list in DataFrameBlock: struct<author_type: string, locale: string>`

The full stack trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask_appbuilder/security/decorators.py", line 168, in wraps
    return f(self, *args, **kwargs)
  File "/home/grace_guo/incubator-superset/superset/utils/log.py", line 59, in wrapper
    value = f(*args, **kwargs)
  File "/home/grace_guo/incubator-superset/superset/views/core.py", line 2291, in results
    return self.results_exec(key)
  File "/home/grace_guo/incubator-superset/superset/views/core.py", line 2342, in results_exec
    json.dumps(obj, default=utils.json_iso_dttm_ser, ignore_nan=True)
  File "/usr/local/lib/python3.6/dist-packages/simplejson/__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/dist-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/dist-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/home/grace_guo/incubator-superset/superset/utils/core.py", line 383, in json_iso_dttm_ser
    "Unserializable object {} of type {}".format(obj, type(obj))
TypeError: Unserializable object ['silver.information_schema.tables'] of type <class 'numpy.ndarray'>
```

So i have to revert this feature from airbnb's release branch. Please take a look. We should also consider revert this PR from master branch.

**Comment by robdiciuccio** [comment]
@graceguo-supercat thanks for flagging. This should be fixed in https://github.com/apache/incubator-superset/pull/8946
