### PR TITLE
fix: Rename Truncate Axis to Truncate Y Axis in bar chart controls

### LINKED ISSUE #37400: Bar chart controls should say "truncate Y axis" instead of ambiguous "truncate axis"
### Bug description

The bar chart controls in 6.0.0 have two truncation options, "Truncate Axis" and "Truncate X Axis". We should make the former "Truncate Y Axis" for consistency.

### Screenshots/recordings

Image

### Superset version

6.0.0

### Python version

I don't know

### Node version

I don't know

### Browser

Firefox

### Additional context

_No response_

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by bikashbarua**
This PR renames the “Truncate Axis” control label to “Truncate Y Axis” to maintain consistency with the existing “Truncate X Axis” option in bar chart controls.

Fixes #37400

### CODE REVIEW

**Comment by rusackas** [comment]
Does this need to be made dynamic (with a substituted X/Y string in the t() function) depending on whether it's horizontal/vertical?

Also, I note it says in the control it's not recommended to use this control in bar charts... should we just ignore/hide the control in this case?

**Comment by sfirke** [comment]
> Does this need to be made dynamic (with a substituted X/Y string in the t() function) depending on whether it's horizontal/vertical?

This is a good question, the names of the controls are confusing when the chart is horizontally-rotated. But that would be a bigger thing, we would need to update all of the controls where it says Y Axis Title, etc. Would they all flip together when the horizontal checkbox is clicked? Anyway, I think that's a separate matter.

> Also, I note it says in the control it's not recommended to use this control in bar charts... should we just ignore/hide the control in this case?

My quick take is that there are legitimate uses for it and if it's commonly *mis*used, that's a bad choice by the author, not the fault of the tool that makes it possible. I think Superset's better if we keep this control.

I was just using it for a bar chart showing average customer satisfaction by category. The customer sat rating is on a scale of 1-5, so since 1 is the lowest possible value, I truncated the y-axis to start at 1.

Here's a better example, showing average golf scores. Since that scale doesn't begin at 0 it feels wrong to start the y-axis there:
1lws2d7gmzh81

**Comment by EnxDev** [comment]
Superset uses Git pre-commit hooks courtesy of [pre-commit](https://pre-commit.com/). To install run the following:

```
pip3 install -r requirements/development.txt
pre-commit install
```
A series of checks will now run when you make a git commit.

Alternatively it is possible to run pre-commit by running pre-commit manually:

`pre-commit run --all-files`

**Comment by bikashbarua** [comment]
I ran pre-commit locally (Windows / Git Bash). Core checks passed. Some hooks (helm-docs, docs sync) fail locally due to Windows/Bash tooling. The PR is scoped only to the Y-axis truncation UI change, relying on CI for remaining checks.

**Review by sfirke — APPROVED** [review]

**Comment by sfirke** [comment]
It won't let me merge because of the failing pre-commit check. The check says that prettier made changes to the file you modified. I don't see what would get changed, but anyway we're stuck. When you run pre-commit locally, does prettier modify anything? I will also try re-running the CI test.

File: superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/Regular/Bar/controlPanel.tsx [hunk 1]
```diff
@@ -243,10 +243,10 @@ function createAxisControl(axis: 'x' | 'y'): ControlSetRow[] {
         name: 'truncateYAxis',
         config: {
           type: 'CheckboxControl',
-          label: t('Truncate Axis'),
+          label: t('Truncate Y Axis'),
           default: truncateYAxis,
           renderTrigger: true,
-          description: t('It’s not recommended to truncate axis in Bar chart.'),
+          description: t('It’s not recommended to truncate Y axis in Bar chart.'),
```
Comment (SBIN2010) [inline superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/Regular/Bar/controlPanel.tsx]: Run pre-commit on this file with the command:
pre-commit run --files superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/Regular/Bar/controlPanel.tsx         
And you will see changes:

          description: t(
            'It’s not recommended to truncate Y axis in Bar chart.',
          ),

**Review by SBIN2010 — COMMENTED** [review]
I hope this helps you

File: superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/Regular/Bar/controlPanel.tsx (hunk 1 above)
Comment (sadpandajoe) [inline superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/Regular/Bar/controlPanel.tsx]:
```suggestion
          description: t(
              'It’s not recommended to truncate Y axis in Bar chart.',
          ),
```

File: superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/Regular/Bar/controlPanel.tsx [hunk 2]
```diff
@@ -243,10 +243,12 @@ function createAxisControl(axis: 'x' | 'y'): ControlSetRow[] {
         name: 'truncateYAxis',
         config: {
           type: 'CheckboxControl',
-          label: t('Truncate Axis'),
+          label: t('Truncate Y Axis'),
```
[the remark this answers is not in the document]
Comment (rusackas) [reply superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/Regular/Bar/controlPanel.tsx:246]: @bikashbarua @sadpandajoe this is the question I was asking about earlier... should we take this suggestion?
