### PR TITLE
fix(dashboard): Fill form with the latest values when undo in native filters

### LINKED ISSUE #16821: [native filter] dataset/column/advanced element disappears from the "Filters configuration and scoping" modal when user undo deleting native filter
Dataset/column/advanced elements disappears from the "Filters configuration and scoping" modal when user undo deleting native filter

#### How to reproduce the bug
1, Open the dashboard from preconditions
2, Expand the "Native filter" panel
3, Click the "Pencil" icon
4, Click the "Delete" icon next to the native filter (from preconditions)
5, Click the "Undo" button
6, See key sections are missing in the modal

### Expected results
Dataset/column/advanced elements did not disappear when undo delete

### Actual results

Dataset/column/advanced elements disappear when undo delete

#### Screenshots

https://user-images.githubusercontent.com/81597121/134593457-08b8c5d8-b918-4f77-8f00-51c9ff37b74f.mp4

### Environment

(please complete the following information):

- browser type and version:
- superset version: latest master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
This PR fixes several issues related to the undo functionality in native filters. It stores the latest form data and adds it back to the form when the user removes a filter and then undoes the removal. 

### BEFORE
See issue #16821

### AFTER

https://user-images.githubusercontent.com/60598000/134869243-74396a24-218d-4fc2-beec-27b1ed8e3879.mp4

### TESTING INSTRUCTIONS
1. Open a Dashboard with native filters enabled
2. Add a filter
3. Remove the filter
4. Undo your action and make sure the latest data was preserved

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #16821
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@jinghua-qa @junlincc

**Comment by geido** [comment]
/testenv up FEATURE_DASHBOARD_NATIVE_FILTERS=true FEATURE_DASHBOARD_CROSS_FILTERS=true FEATURE_DASHBOARD_NATIVE_FILTERS_SET=true FEATURE_DASHBOARD_FILTERS_EXPERIMENTAL=true

File: superset-frontend/src/dashboard/components/nativeFilters/FiltersConfigModal/FiltersConfigForm/FiltersConfigForm.tsx [hunk 1]
```diff
@@ -550,15 +512,21 @@ const FiltersConfigForm = (
...
   );
 
   const hasParentFilter = !!parentFilter;
 
   const hasPreFilter =
-    !!filterToEdit?.adhoc_filters || !!filterToEdit?.time_range;
+    !!formFilter?.adhoc_filters ||
+    !!formFilter?.time_range ||
+    !!filterToEdit?.adhoc_filters?.length ||
+    !!filterToEdit?.time_range;
```
Comment (villebro) [inline superset-frontend/src/dashboard/components/nativeFilters/FiltersConfigModal/FiltersConfigForm/FiltersConfigForm.tsx:526]: should we also change it to `formFilter?.adhoc_filters?.length ||` like it is later for `filterToEdit`, just in case?

**Review by villebro — APPROVED** [review]
Nice work! LGTM with one small question/comment.

File: superset-frontend/src/dashboard/components/nativeFilters/FiltersConfigModal/FiltersConfigForm/FiltersConfigForm.tsx (hunk 1 above)
Comment (geido) [reply superset-frontend/src/dashboard/components/nativeFilters/FiltersConfigModal/FiltersConfigForm/FiltersConfigForm.tsx:526]: Thanks for your feedback! It appears that when the form doesn't have any filters it will just return undefined, reason why I am only checking for that here

**Comment by michael-s-molina** [comment]
@geido If I'm not mistaken when the user removes a filter, it only marks that filter as deleted but the form values are preserved. If that's the case, why do we need the `undoFormValues` state? Can't we just use the original form?

**Comment by geido** [comment]
> @geido If I'm not mistaken when the user removes a filter, it only marks that filter as deleted but the form values are preserved. If that's the case, why do we need the `undoFormValues` state? Can't we just use the original form?

@michael-s-molina I checked that and it appears that when the filter is removed the form is also cleaned up. You won't have the most recent state of the form, hence I am storing it on removal and reapplying the values on undo.

**Comment by michael-s-molina** [comment]
> > @geido If I'm not mistaken when the user removes a filter, it only marks that filter as deleted but the form values are preserved. If that's the case, why do we need the `undoFormValues` state? Can't we just use the original form?
> 
> @michael-s-molina I checked that and it appears that when the filter is removed the form is also cleaned up. You won't have the most recent state of the form, hence I am storing it on removal and reapplying the values on undo.

Do you know where the form is being cleared? This is the handler for the delete action and it's only marking it as removed. 

```
export const createHandleTabEdit = (
  setRemovedFilters: (
    value:
      | ((
          prevState: Record<string, FilterRemoval>,
        ) => Record<string, FilterRemoval>)
      | Record<string, FilterRemoval>,
  ) => void,
  setSaveAlertVisible: Function,
  addFilter: Function,
) => (filterId: string, action: 'add' | 'remove') => {
  const completeFilterRemoval = (filterId: string) => {
    // the filter state will actually stick around in the form,
    // and the filterConfig/newFilterIds, but we use removedFilters
    // to mark it as removed.
    setRemovedFilters(removedFilters => ({
      ...removedFilters,
      [filterId]: { isPending: false },
    }));
  };

  if (action === 'remove') {
    // first set up the timer to completely remove it
    const timerId = window.setTimeout(
      () => completeFilterRemoval(filterId),
      REMOVAL_DELAY_SECS * 1000,
    );
    // mark the filter state as "removal in progress"
    setRemovedFilters(removedFilters => ({
      ...removedFilters,
      [filterId]: { isPending: true, timerId },
    }));
    setSaveAlertVisible(false);
  } else if (action === 'add') {
    addFilter();
  }
};
```

**Comment by geido** [comment]
@michael-s-molina as stated above, I confirm that the form is wiped out as soon as the form rerenders after the remove action. Any data you already have about the filter (such as the one in the `filterConfigMap` ) might be outdated as it does not contain the most recent state of the form. Thus, the only solution that seems to solve both scenarios is to store the current state of the form. I am happy to consider a different solution but it does not appear to be obvious at the moment. Let me know if anything different comes to your mind. Thank you!

**Comment by michael-s-molina** [comment]
> @michael-s-molina as stated above, I confirm that the form is wiped out as soon as the form rerenders after the remove action. Any data you already have about the filter (such as the one in the `filterConfigMap` ) might be outdated as it does not contain the most recent state of the form. Thus, the only solution that seems to solve both scenarios is to store the current state of the form. I am happy to consider a different solution but it does not appear to be obvious at the moment. Let me know if anything different comes to your mind. Thank you!

So I was reviewing and found this:

Screen Shot 2021-09-27 at 9 34 12 AM

This is the code that is clearing the form. `preserve={false}` is forcing the values to be cleared. The default value of Ant Design is `true`. If we change it to `true`, the values are preserved after restoring. The only thing is that I don’t know why this was set to `false`.

**Comment by michael-s-molina** [comment]
@geido We can investigate this in a follow-up since this is a P1. Approving for now.

**Review by michael-s-molina — APPROVED** [review]

**Comment by sadpandajoe** [comment]
🏷️ 2021.38
