### PR TITLE
Avoid clearing metric when saving from datasource editor

### LINKED ISSUE #6275: Saving datasource editor changes clears the metric in explore view
When you save a change in the datasource editor, the metric field gets cleared. Refreshing the page brings the metric back (which correctly stayed in the form_data).

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Superset version
master

### Expected results
All metric and group by fields stay after saving datasource changes.

### Actual results
Metric field gets cleared after saving data source changes.

### Steps to reproduce
Open explore, add a metric, make changes to the datasource, and save.

@mistercrunch @graceguo-supercat @john-bodley

### PR DESCRIPTION
**Pull request by michellethomas**
Clicking save from the datasource editor would clear your metrics field because we were comparing objects in MetricsControl to see if columns or saved metrics changed. We should be doing a deep compare.

Thanks @graceguo-supercat for helping track this down!

@mistercrunch @john-bodley @graceguo-supercat 

Fixes #6275

### CODE REVIEW

File: superset/assets/src/explore/components/controls/MetricsControl.jsx [hunk 1]
```diff
@@ -117,8 +117,8 @@ export default class MetricsControl extends React.PureComponent {
 
   componentWillReceiveProps(nextProps) {
     if (
-      this.props.columns !== nextProps.columns ||
-      this.props.savedMetrics !== nextProps.savedMetrics
+      JSON.stringify(this.props.columns) !== JSON.stringify(nextProps.columns) ||
```
Comment (mistercrunch) [inline superset/assets/src/explore/components/controls/MetricsControl.jsx]: I don't think `JSON.strinigfy` is good to use for deep equality:
https://stackoverflow.com/questions/15376185/is-it-fine-to-use-json-stringify-for-deep-comparisons-and-cloning

How about lodash's isEqual? https://lodash.com/docs/4.17.10#isEqual

**Review by mistercrunch — CHANGES_REQUESTED** [review]

**Review by mistercrunch — APPROVED** [review]

**Comment by mistercrunch** [comment]
LGTM
