### PR TITLE
fix: stop endless loading when dataset no longer exist

### LINKED ISSUE #16431: [dashboard] chart reload forever if delete attached dataset
if you delete a dataset that has charts attached to them, they reload forever in the dashboard

### Expected results

chart did not reload forever if attached dataset deleted

### Actual results

chart  reload forever if attached dataset deleted

#### Screenshots

Screen Shot 2021-08-24 at 12 14 34 PM

#### How to reproduce the bug

1. delete a dataset attached to the chart
2. go to dashboard with this chart
3. See error for reloading the chart forever

### Environment

(please complete the following information):

- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
This pr stops the endless loading in the dashboards when a dataset no longer exists and returns proper error info to the user. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
before

https://user-images.githubusercontent.com/17326228/131378812-5f92c50a-434c-48b3-857b-47b52c567976.mov

after

https://user-images.githubusercontent.com/17326228/131379074-cf9d01df-79c1-490e-81a2-9fd49dde63dc.mov

### TESTING INSTRUCTIONS
Delete a dataset that has associated chart in a a dashboard.
Go to the dashboard and ensure that the charts do no endlessly load.

### ADDITIONAL INFORMATION

- [x ] Has associated issue: Fixes https://github.com/apache/superset/issues/16431
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/chart/Chart.jsx [hunk 1]
```diff
@@ -178,7 +178,12 @@ class Chart extends React.PureComponent {
     const message = chartAlert || queryResponse?.message;
 
     // if datasource is still loading, don't render JS errors
-    if (chartAlert && datasource === PLACEHOLDER_DATASOURCE) {
+    if (
+      chartAlert !== undefined &&
+      chartAlert !==
+        'The dataset associated with this chart no longer exists' &&
```
Comment (ktmud) [inline superset-frontend/src/chart/Chart.jsx:184]: Can we make this a const?

**Review by ktmud — COMMENTED** [review]
Thanks for the fix!

**Review by rusackas — APPROVED** [review]
Thanks for the fix! Code LGTM.

It might at some point be worth considering a UX enhancement to this, where we surface the error more explicitly (as opposed to an "Unexpected Error" that you have to click), or potentially pop a page-level error (rather than only chart-level errors) to alert users to the problem. This is a heck of an improvement, though!

File: superset-frontend/src/chart/Chart.jsx [hunk 2]
```diff
@@ -68,6 +68,8 @@ const propTypes = {
 };
 
 const BLANK = {};
+const NONEXISTENT_DATASET =
+  'The dataset associated with this chart no longer exists';
```
Comment (ktmud) [inline superset-frontend/src/chart/Chart.jsx:72]: Since this error is [translated in the backend](https://github.com/apache/superset/blob/be7065faf8e00ea0304b5380b2347f2ea9e4b39b/superset/views/utils.py#L252), I think we should wrap this in `t(...)` as well.

**Review by ktmud — APPROVED** [review]
