### PR TITLE
fix(database-modal): fix issue where commas could not be typed into DB configuration.

### LINKED ISSUE #28252: Can't enter commas into database configuration setup
### Bug description

When attempting to enter commas in order to limit the ability to upload data to specific database schemas only, the UI doesn't accept comma keystrokes and the comma separated value list therefore cannot be created.

image

### How to reproduce the bug

My deployment:

Docker compose onto Linux VPS (Ubuntu)

Reproduction steps:

-> Click into database connections
-> Edit a database
-> Advanced options
-> Limit upload permissions to specific schemas
-> Attempt to upload desired schemas as comma separated values by typing names of desired schemas with separating commas

### Screenshots/recordings

_No response_

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by LevisNgigi**
fix(database-modal): fix issue where commas could not be typed into DB configuration.

### SUMMARY
The reducer always stripped empty strings when updating schemas_allowed_for_file_upload, so a user ending the input with a comma lost the intended trailing placeholder. Now we detect a trailing comma and preserves an empty string in the array (['']) to reflect that state, allowing the UI to keep an open slot for adding another schema.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
AFTER
Screenshot from 2025-09-25 15-01-43

### TESTING INSTRUCTIONS
Reproduction steps:

-> Click into database connections
-> Edit a database
-> Advanced options
-> Limit upload permissions to specific schemas
-> Attempt to upload desired schemas as comma separated values by typing names of desired schemas with separating commas
-> one should be able to now separate schemas using commas.

### ADDITIONAL INFORMATION

- [ x] Has associated issue: Fixes #28252
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by msyavuz — COMMENTED** [review]
I don't think it should preserve empty strings when there is a trailing comma

**Comment by LevisNgigi** [comment]
> I don't think it should preserve empty strings when there is a trailing comma

I have updated so that it is not preserved.

File: superset-frontend/src/features/databases/DatabaseModal/ExtraOptions.tsx [hunk 1]
```diff
@@ -555,11 +574,20 @@ const ExtraOptions = ({
...
+                      }
+                      onBlur={() =>
+                        onExtraInputChange({
+                          target: {
+                            type: 'text',
+                            name: 'schemas_allowed_for_file_upload',
+                            value: schemasText,
+                          },
+                        })
+                      }
```
Comment (msyavuz) [inline superset-frontend/src/features/databases/DatabaseModal/ExtraOptions.tsx:556]: A type assertion here would be simpler than adding a seperate type definition above on the function definition

```suggestion
                      onBlur={() =>
                        onExtraInputChange({
                          target: {
                            type: 'text',
                            name: 'schemas_allowed_for_file_upload',
                            value: schemasText,
                          },
                        } as ChangeEvent<HTMLInputElement>)
                      }
```

File: superset-frontend/src/features/databases/DatabaseModal/ExtraOptions.tsx [hunk 2]
```diff
@@ -555,11 +574,20 @@ const ExtraOptions = ({
                     <Input
                       type="text"
                       name="schemas_allowed_for_file_upload"
-                      value={(
-                        extraJson?.schemas_allowed_for_file_upload || []
-                      ).join(',')}
+                      value={schemasText}
                       placeholder="schema1,schema2"
-                      onChange={onExtraInputChange}
+                      onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
```
Comment (msyavuz) [inline superset-frontend/src/features/databases/DatabaseModal/ExtraOptions.tsx]:
```suggestion
                      onChange={(e) =>
```

File: superset-frontend/src/features/databases/DatabaseModal/ExtraOptions.tsx [hunk 3]
```diff
@@ -58,7 +58,17 @@ const ExtraOptions = ({
   onTextChange: EventHandler<ChangeEvent<HTMLTextAreaElement>>;
   onEditorChange: Function;
   onExtraInputChange: (
-    e: CheckboxChangeEvent | ChangeEvent<HTMLInputElement>,
+    e:
+      | CheckboxChangeEvent
+      | React.ChangeEvent<HTMLInputElement>
```
Comment (msyavuz) [inline superset-frontend/src/features/databases/DatabaseModal/ExtraOptions.tsx]:
```suggestion
      | ChangeEvent<HTMLInputElement>
```

File: superset-frontend/src/features/databases/DatabaseModal/ExtraOptions.tsx [hunk 4]
```diff
@@ -58,7 +58,17 @@ const ExtraOptions = ({
...
+      | {
+          target: {
+            type: string;
+            name: string;
+            value: string;
+            checked?: boolean;
+          };
+        },
```
Comment (msyavuz) [inline superset-frontend/src/features/databases/DatabaseModal/ExtraOptions.tsx]: We could get rid of this by just asserting the type below

**Review by msyavuz — APPROVED** [review]
LGTM with few nits

File: superset-frontend/src/features/databases/DatabaseModal/ExtraOptions.tsx (hunk 4 above)
Comment (LevisNgigi) [reply superset-frontend/src/features/databases/DatabaseModal/ExtraOptions.tsx]: done

File: superset-frontend/src/features/databases/DatabaseModal/ExtraOptions.tsx [hunk 5]
```diff
@@ -58,7 +58,7 @@ const ExtraOptions = ({
   onTextChange: EventHandler<ChangeEvent<HTMLTextAreaElement>>;
   onEditorChange: Function;
   onExtraInputChange: (
-    e: CheckboxChangeEvent | ChangeEvent<HTMLInputElement>,
+    e: CheckboxChangeEvent | React.ChangeEvent<HTMLInputElement>,
```
Comment (msyavuz) [inline superset-frontend/src/features/databases/DatabaseModal/ExtraOptions.tsx]:
```suggestion
    e: CheckboxChangeEvent | ChangeEvent<HTMLInputElement>,
```

**Review by msyavuz — APPROVED** [review]

File: superset-frontend/src/features/databases/DatabaseModal/ExtraOptions.tsx (hunk 5 above)
Comment (LevisNgigi) [reply superset-frontend/src/features/databases/DatabaseModal/ExtraOptions.tsx]: Updated
