### PR TITLE
fix(deck.gl): update view state on property changes (#17720)

### LINKED ISSUE #17720: deck.gl polygon doesn't auto zoom to changed bounds when native filter is updated
#### How to reproduce the bug

1. Create a Dashboard containing a deck.gl polygon chart (auto zoom = True, screenshot 1) with a column included in filter 
2. Open the dahsboard => the map is zoomed according to show features (screenshot 2)
3. Change native filter value
4. The map is not zoomed to the new bounding box  (screenshot 3)

### Expected results

The map should be zoomed to the new bounding box

### Actual results
The map should is not zoomed to the new bounding box

#### Screenshots
grafik
Screenshot 1

grafik
screenshot 2

grafik
screenshot 3

### Environment
- browser type and version: Firefox 94.0.1
- superset version: master head

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by hbruch**
### SUMMARY
Updates viewport state of deck.gl on filter updates

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before (screeshot 1 & 2):
grafik
grafik

After:

https://user-images.githubusercontent.com/2187389/146766468-a031dad9-b4d1-48ff-b307-dbfa2dd79417.mov

### TESTING INSTRUCTIONS
1. Create a Dashboard containing a deck.gl polygon chart (auto zoom = True) with a column included in filter 
2. Open the dahsboard => the map is zoomed according to show features (screenshot 1)
3. Change native filter value
4. The map is now zoomed to the new bounding box (see video)

### ADDITIONAL INFORMATION
- [x] Has associated issue: fixes #17720 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/plugins/legacy-preset-chart-deckgl/src/DeckGLContainer.jsx [hunk 1]
```diff
@@ -64,6 +64,12 @@ export class DeckGLContainer extends React.Component {
     };
   }
 
+  UNSAFE_componentWillReceiveProps(nextProps) {
+    if (nextProps.viewport !== this.props.viewport) {
```
Comment (villebro) [inline superset-frontend/plugins/legacy-preset-chart-deckgl/src/DeckGLContainer.jsx:68]: I believe this will cause unnecessary rerenders as the object reference may change despite its properties being unchanged. Let's use `lodash` here, something like
```javascript
import { isEqual } from 'lodash';

if (!isEqual(nextProps.viewport, this.props.viewport)) {
  ...
},
```

**Review by villebro — COMMENTED** [review]
Thanks for the fix! Works well, but minor performance improvement suggestion

File: superset-frontend/plugins/legacy-preset-chart-deckgl/src/DeckGLContainer.jsx (hunk 1 above)
Comment (hbruch) [reply superset-frontend/plugins/legacy-preset-chart-deckgl/src/DeckGLContainer.jsx]: Thanks for the hint. Is adressed by last commit (though checks failed again)...

**Comment by villebro** [comment]
@hbruch can you rebase this? I believe there may have been some CI issues when you pushed these last changes

**Comment by villebro** [comment]
@hbruch sorry about this, but there's yet some more flakiness in our CI pipeline: #17918 . Bear with us while we get it sorted..

**Comment by hbruch** [comment]
@villebro Is there anything I could do to have this merged? Thx

**Review by villebro — APPROVED** [review]
Oh, sorry about the delay!
