### PR TITLE
handle nulls in bar chart series/breakdown

### LINKED ISSUE #8672: Bar chart doesn't create a bar for a null value in the series
Bar chart doesn't create a bar for a null value in the series

### Expected results

A bar for null values in the series as well as all the set values

### Actual results

only places where the series is specified has a bar for it

#### Screenshots

Data table shows rows where the first column (the series column) is null
Screen Shot 2019-11-26 at 5 11 29 PM

But only one bar shows up

#### How to reproduce the bug

1. Set a column for series where there are null values
2. Don't see a bar for null values

### Environment

- superset version: `master`
- python version: `3.6`
- node.js version: `8.6`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by suddjian**
### CATEGORY

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

pandas removes `None` values when doing a groupby or a pivot, so we have to substitute a value for `None`s beforehand to allow null values in the bar chart's series or breakdown. There is already a string `"<NULL>"` being used to indicate nulls in a few places, so I used that and centralized it in a new `constants.py` file.

Fixes #8672 

### BEFORE/AFTER SCREENSHOTS

Before:

Screen Shot 2019-12-02 at 5 18 33 PM

After:

Screen Shot 2019-12-02 at 5 18 03 PM

### TEST PLAN

`<NULL>`

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by john-bodley — COMMENTED** [review]
It’s a real shame Pandas doesn’t handle `NaN`s in group-bys and thus hackery is required. The logic you implemented seems to be the recommended approach.

Would you mind adding a unit test for this to prevent future regressions?

File: superset/assets/src/utils/common.js [hunk 1]
```diff
@@ -19,6 +19,8 @@
 import { SupersetClient } from '@superset-ui/connection';
 import getClientErrorObject from './getClientErrorObject';
 
+export const NULLSTRING = '<NULL>';
```
Comment (etr2460) [inline superset/assets/src/utils/common.js]: nit: I think naming this `NULL_STRING` would be preferred

File: superset/constants.py [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+#
+# Unless required by applicable law or agreed to in writing,
+# software distributed under the License is distributed on an
+# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+# KIND, either express or implied.  See the License for the
+# specific language governing permissions and limitations
+# under the License.
+
+# string to use when None values *need* to be converted to/from strings
+NULLSTRING = "<NULL>"
```
Comment (etr2460) [inline superset/constants.py]: same comment here about naming

**Review by etr2460 — COMMENTED** [review]
same comment as John about a test being nice. Otherwise, lgtm with the exception of a naming nit

File: superset/viz.py [hunk 3]
```diff
@@ -1543,10 +1544,15 @@ def query_obj(self):
     def get_data(self, df):
         fd = self.form_data
         metrics = self.metric_labels
+        columns = fd.get("columns") or []
+
+        # pandas will throw away nulls when grouping/pivoting,
+        # so we substitute NULLSTRING for any nulls in the necessary columns
+        filled_cols = self.groupby + columns
+        df[filled_cols] = df[filled_cols].fillna(value=NULLSTRING)
```
[the remark this answers is not in the document]
Comment (suddjian) [reply superset/viz.py]: When I try `df[filled_cols].fillna(value=NULLSTRING, inplace=True)` I get this warning:

> SettingWithCopyWarning:
> A value is trying to be set on a copy of a slice from a DataFrame
> See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

**Comment by suddjian** [comment]
@etr2460 @john-bodley Thanks for the feedback, I added tests and changed to `NULL_STRING`. Feel free to merge if it looks good.

File: superset/assets/src/utils/common.js [hunk 4]
```diff
@@ -19,6 +19,8 @@
 import { SupersetClient } from '@superset-ui/connection';
 import getClientErrorObject from './getClientErrorObject';
 
+export const NULL_STRING = '<NULL>';
```
Comment (etr2460) [inline superset/assets/src/utils/common.js]: add a comment referencing keeping in sync between files

**Review by etr2460 — APPROVED** [review]
one nit otherwise lgtm!

File: superset/connectors/druid/models.py [hunk 5]
```diff
@@ -1363,7 +1364,7 @@ def homogenize_types(df: pd.DataFrame, groupby_cols: Iterable[str]) -> pd.DataFr
         Here we replace None with <NULL> and make the whole series a
         str instead of an object.
         """
-        df[groupby_cols] = df[groupby_cols].fillna("<NULL>").astype("unicode")
+        df[groupby_cols] = df[groupby_cols].fillna(NULL_STRING).astype("unicode")
```
Comment (john-bodley) [inline superset/connectors/druid/models.py]: Somewhat unrelated to your change but we probably don't need the `.astype("unicode")` as in Python 3 all strings are unicode.

Comment (suddjian) [reply superset/connectors/druid/models.py]: That might be fine, but I don't know pandas well enough to be sure and I don't really think it's related to this PR.
