### PR TITLE
[fix] Chart specific time controls

### LINKED ISSUE #2750: [explore] disable "granularity" control for non-timeseries visualizations
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.17.6

### Expected results
Using the timestamp column for the series, I would expect the time grain to apply, so that the series is e.g. weekly.

### Actual results
The query executed does not include any statement regarding the time grain and this is visible in the visualization.

### Steps to reproduce
Create a distribution bar chart with timestamp series.

### PR DESCRIPTION
**Pull request by john-bodley**
### CATEGORY

Choose one

- [x] Bug Fix
- [ ] Enhancement (new features, refinement)
- [ ] Refactor
- [ ] Add tests
- [ ] Build / Development Environment
- [ ] Documentation

### SUMMARY

This PR ensures that only the relevant time widgets are included depending on the chart type. Previously the granularity logic was shown even if the chart type did not support granularity, i.e., non-timeseries charts. 

This provides a number of benefits including: 

1. Improved UX: It's not apparent to the user that these controls have no impact on the chart.
2. Improved performance: The controls serve as inputs to the cache and thus the cache is invalidated when these erroneous options are changed. 
3. Cleaner form-data: The impetus for this change stemmed from a project migrating charts from Druid NoSQL to SQL where there isn't a 1:1 mapping for the time parameters. The erroneous values could deem a chart is non-migratable even though in theory is was.

Additionally this PR also removes the time controls for chart types which don't support time filtering, i.e., iFrame, Markup, etc.

Note erroneous form-data fields are removed on load in explorer but will persist in database until the slice is re-saved.

#### Before 

Screen Shot 2019-11-26 at 6 26 46 PM

#### After

Screen Shot 2019-11-26 at 6 24 49 PM

### TEST PLAN

CI.

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #2750
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS

to: @etr2460 @graceguo-supercat @michellethomas @mistercrunch @willbarrett @villebro

### CODE REVIEW

File: superset/assets/src/explore/controlPanels/sections.jsx [hunk 1]
```diff
@@ -23,7 +23,7 @@ export const druidTimeSeries = {
   label: t('Time'),
   expanded: true,
   description: t('Time related form attributes'),
-  controlSetRows: [['granularity', 'druid_time_origin'], ['time_range']],
+  controlSetRows: [['time_range']],
```
Comment (etr2460) [inline superset/assets/src/explore/controlPanels/sections.jsx]: why did you remove both of these here but only one in sqla?

Comment (etr2460) [reply superset/assets/src/explore/controlPanels/sections.jsx]: synced offline, this is good

**Review by etr2460 — APPROVED** [review]
lgtm, thanks for cleaning these unused controls!
