### PR TITLE
fix: RLS modal overflow

### LINKED ISSUE #27079: Form issue on Row level security
### Bug description

The form style is showing as broken

### How to reproduce the bug

Go to create new rule on RLS

### Screenshots/recordings

image

### Superset version

master / latest-dev

### Python version

3.10

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Fixes https://github.com/apache/superset/issues/27079 and also adjusts the description input theme.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before: modal was overflowing and the description input theme was not matching other inputs
Screenshot 2024-02-15 at 11 16 53

After: modal correctly displays a scroll when needed and the input theme is fixed
Screenshot 2024-02-15 at 11 14 40

### TESTING INSTRUCTIONS
Check that the RLS does not overflow and that the description input theme matches other inputs..

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/features/rls/RowLevelSecurityModal.tsx [hunk 1]
```diff
@@ -155,23 +152,25 @@ function RowLevelSecurityModal(props: RowLevelSecurityModalProps) {
...
 
-  // initialize
-  useEffect(() => {
-    if (!isEditMode) {
-      setCurrentRule({ ...DEAFULT_RULE });
-    } else if (rule?.id !== null && !loading && !fetchError) {
-      fetchResource(rule.id as number);
-    }
-  }, [rule]);
+  const updateRuleState = (name: string, value: any) => {
```
Comment (michael-s-molina) [inline superset-frontend/src/features/rls/RowLevelSecurityModal.tsx:155]: Just rearranging functions order to resolve warning.

File: superset-frontend/src/features/rls/RowLevelSecurityModal.tsx [hunk 2]
```diff
@@ -202,6 +201,24 @@ function RowLevelSecurityModal(props: RowLevelSecurityModalProps) {
     return { tables, roles };
   }, [resource?.tables, resource?.roles]);
 
+  // initialize
```
Comment (michael-s-molina) [inline superset-frontend/src/features/rls/RowLevelSecurityModal.tsx:204]: Just rearranging functions order to resolve warning.

File: superset-frontend/src/features/rls/RowLevelSecurityModal.tsx [hunk 3]
```diff
@@ -318,19 +328,6 @@ function RowLevelSecurityModal(props: RowLevelSecurityModalProps) {
     [],
   );
 
-  // * state validators *
```
Comment (michael-s-molina) [inline superset-frontend/src/features/rls/RowLevelSecurityModal.tsx:321]: Just rearranging functions order to resolve warning.

File: superset-frontend/src/features/rls/RowLevelSecurityModal.tsx [hunk 4]
```diff
@@ -214,13 +231,6 @@ function RowLevelSecurityModal(props: RowLevelSecurityModalProps) {
     label: string;
   };
 
-  const updateRuleState = (name: string, value: any) => {
```
Comment (michael-s-molina) [inline superset-frontend/src/features/rls/RowLevelSecurityModal.tsx:217]: Just rearranging functions order to resolve warning.

**Review by mistercrunch — APPROVED** [review]
