### PR TITLE
fix(explore): Scroll only table in Change Dataset and Edit Dataset Modals

### LINKED ISSUE #12488: [modal]scroll only on table body with sticky warning msg, tabs, header and buttons
https://user-images.githubusercontent.com/67837651/104419011-b5af0400-552c-11eb-9df7-f4dbecfe37c2.mov

https://user-images.githubusercontent.com/67837651/104419027-bcd61200-552c-11eb-9a25-ec1e4234842c.mov

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
Closes #12488  

Makes the table in the modal scrollable while keeping all the other elements sticky. 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
BEFORE Change Dataset Modal:

https://user-images.githubusercontent.com/60598000/105045601-62770d00-5a68-11eb-8091-7aa7a46d7b1a.mp4

AFTER Change Dataset Modal:

https://user-images.githubusercontent.com/60598000/105045646-6d31a200-5a68-11eb-8824-558ce38ae35d.mp4

BEFORE Edit Dataset Modal:

https://user-images.githubusercontent.com/60598000/105045693-7cb0eb00-5a68-11eb-83c2-c640ced94c88.mp4

AFTER Edit Dataset Modal:

https://user-images.githubusercontent.com/60598000/105045718-83d7f900-5a68-11eb-89d2-2bcf70724533.mp4

### ADDITIONAL INFORMATION

- [x] Has associated issue: #12488 
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@junlincc @rusackas

File: superset-frontend/src/common/components/Modal/Modal.tsx [hunk 1]
```diff
@@ -42,12 +42,15 @@ interface ModalProps {
...
   wrapProps?: object;
   height?: string;
+  scrollTableMode?: boolean;
 }
 
 interface StyledModalProps extends SupersetThemeProps {
   maxWidth?: string;
   responsive?: boolean;
   height?: string;
+  scrollTableMode?: boolean;
```
Comment (ktmud) [inline superset-frontend/src/common/components/Modal/Modal.tsx:52]: Do we really need both props for the modal? I think it's OK to keep some bottom padding when only table body is scrollable.

File: superset-frontend/src/CRUD/CollectionTable.tsx [hunk 2]
```diff
@@ -41,6 +43,7 @@ interface CRUDCollectionProps {
   ) => ReactNode)[];
   onChange?: (arg0: any) => void;
   tableColumns: Array<any>;
+  scrollTable?: boolean;
```
Comment (ktmud) [inline superset-frontend/src/CRUD/CollectionTable.tsx:46]: nit: maybe name this `stickyHeader`?

File: superset-frontend/src/CRUD/CollectionTable.tsx [hunk 3]
```diff
@@ -27,6 +27,8 @@ import './crud.less';
 interface CRUDCollectionProps {
   allowAddItem?: boolean;
   allowDeletes?: boolean;
+  allowSyncFromSource?: boolean;
+  onSyncFromSource?: () => void;
```
Comment (ktmud) [inline superset-frontend/src/CRUD/CollectionTable.tsx:31]: Both props seem to be `Datasource` table specific and should not be added to the general `CollectionTable` component.

File: superset-frontend/src/common/components/Modal/Modal.tsx (hunk 1 above)
Comment (geido) [reply superset-frontend/src/common/components/Modal/Modal.tsx:52]: You would see the white padding at the bottom overlaying the table and creating a disturbing effect for the eyes. I am happy to change the name or pass it down differently if you have a better idea though.

File: superset-frontend/src/CRUD/CollectionTable.tsx (hunk 2 above)
Comment (geido) [reply superset-frontend/src/CRUD/CollectionTable.tsx:46]: This is a behaviour that is specific to modals using tables. I am worried that `stickyHeader` might not convey the actual functionality. Something on the line `tableMode` or `stickyTableMode`?

File: superset-frontend/src/CRUD/CollectionTable.tsx (hunk 3 above)
Comment (geido) [reply superset-frontend/src/CRUD/CollectionTable.tsx:31]: I get your point about it being specific to the Datasource only though. Let me check if I can move it out while keeping the same position.

File: superset-frontend/src/CRUD/CollectionTable.tsx (hunk 2 above)
Comment (ktmud) [reply superset-frontend/src/CRUD/CollectionTable.tsx:46]: `stikyHeader` is a pretty popular pattern for large tables and not limited to modals, even within Superset. We've seen it used in SQL Lab results preview, Table viz, and Explore data preview... to name few.

Material UI has a similar API: https://material-ui.com/zh/api/table/

Comment (geido) [reply superset-frontend/src/CRUD/CollectionTable.tsx:46]: Oh I didn't know that. That's great to know! I'll change it. Thanks a lot @ktmud!

File: superset-frontend/src/common/components/Modal/Modal.tsx (hunk 1 above)
Comment (ktmud) [reply superset-frontend/src/common/components/Modal/Modal.tsx:52]: You could add a `margin-bottom: - theme.gridUnit * 4` to the scrollable table.

**Review by junlincc — APPROVED** [review]
LGTM! thanks for the PR, much better UX! @geido @ktmud @rusackas will leave it to you guys how the code should look, I would love to get this in v1.0.1 🙏

https://user-images.githubusercontent.com/67837651/105139044-9b37d600-5aaa-11eb-9a5f-231faa55bf74.mov


https://user-images.githubusercontent.com/67837651/105139050-9d019980-5aaa-11eb-88a3-3c83349a8fd1.mov

**Review by ktmud — APPROVED** [review]
LGTM with one small comment.

File: superset-frontend/src/components/TableView/TableView.tsx [hunk 4]
```diff
@@ -51,7 +52,16 @@ const EmptyWrapper = styled.div`
 
 const TableViewStyles = styled.div<{
   isPaginationSticky?: boolean;
+  scrollTable?: boolean;
 }>`
+  ${({ scrollTable, theme }) =>
+    scrollTable &&
+    `
+    height: 300px;
```
[the remark this answers is not in the document]
Comment (geido) [reply superset-frontend/src/components/TableView/TableView.tsx:60]: That's a good idea. However, there is some calculation to do to make sure the height is just right for the modal to avoid showing its own scrollbar. I'll keep this in mind for an enhancement and provide a separate PR for the sake of getting this improvement in asap
