### PR TITLE
fix: `show_filters` URL parameter is not working

### LINKED ISSUE #26758: Filters.visible= false Still shows the filters on embedded iFrame
### Bug description

`dashboardUiConfig: { // dashboard UI config: hideTitle, hideTab, hideChartControls, filters.visible, filters.expanded (optional) 
		
		
		filters: {
		expanded: false,
			visible: false
		}`

I am using the above mentioned dashboardUIConfig, however the filters screen is still visible. It is not expanded but still not hidden. 

### How to reproduce the bug

Embedd Dashboard into an iFrame

### Screenshots/recordings

_No response_

### Superset version

3.1.0

### Python version

3.10

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### LINKED ISSUE #30538: Adding show_filters= to a dashboard URL doesn't do anything
### Bug description

Adding `show_filters=0` or `=1` to the URL of a dashboard seems to have no effect.  Here are examples with a public dashboard, these both load with the filter pane:
https://analytics.a2gov.org/superset/dashboard/osi-performance-metrics/?standalone=2&show_filters=0
https://analytics.a2gov.org/superset/dashboard/osi-performance-metrics/?standalone=2&show_filters=1

The [docs](https://superset.apache.org/docs/using-superset/creating-your-first-dashboard/) say that `=0` should render the dashboard without the filter bar.

Seems like this PR might fix it? https://github.com/apache/superset/pull/29422

### Screenshots/recordings

_No response_

### Superset version

4.0.2

### Python version

I don't know

### Node version

Not applicable

### Browser

Firefox

### Additional context

Someone wrote in Slack on August 13 2024:
> Previously I used show_filters=0 in the dashboard url parameter to hide the filters when sharing the dashboard with clients. Now, this is not working. Recently upgraded to latest superset version. Can someone provide inputs on what could be the possible issue that this isn't working?

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by ghost**
### SUMMARY
The `show_filters` URL param is no longer working (logic to handle it was removed with https://github.com/apache/superset/pull/23228). 

This PR re-introduces the logic pertinent to this flow from that PR + updates `DashboardBuilder` so that it works with current `master`. 

This fix should also reflect to embedded when setting `filters.visible` to `false` through the SDK configuration.

Fixes https://github.com/apache/superset/issues/26758.
Fixes https://github.com/apache/superset/issues/30538.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Tested both with horizontal and vertical filter bar:
image

Embedded:
image

### TESTING INSTRUCTIONS
Tests added. For manual testing:
1. Create a dashboard and configure at least one filter to it.
2. Copy the dashboard URL, add `show_filters=false` as a URL parameter and access it.

### ADDITIONAL INFORMATION
- [x] Has associated issue: https://github.com/apache/superset/issues/26758, https://github.com/apache/superset/issues/30538

### CODE REVIEW

**Comment by Vitor-Avila** [comment]
Thanks for the PR, @hexcafe. Hey @michael-s-molina @john-bodley,
I believe this is a continuation of https://github.com/apache/superset/pull/25804 which was aiming to fix https://github.com/apache/superset/issues/24195 (used to work until https://github.com/apache/superset/pull/23228). 

I checked out this PR locally and tested and it works ✅ but since I'm just getting familiar with frontend I wanted to get your thoughts. 

I didn't think so, but this also works with the horizontal filter bar 🙌 

Thanks!

**Comment by michael-s-molina** [comment]
@hexcafe @Vitor-Avila Shouldn't we just revert [this part](https://github.com/apache/superset/pull/23228/files#diff-6f2c6562ff1fad0ce405b3507cddff63a25dc91c76fb8613284b9cbb241dd928) that was deleted in https://github.com/apache/superset/pull/23228?

**Comment by RoBYCoNTe** [comment]
Any news about this PR?

**Comment by grzaks** [comment]
Would be great to see this one merged into next release.

**Comment by nawar** [comment]
Can we please get this reviewed?

**Comment by Vitor-Avila** [comment]
@michael-s-molina would you prefer to have that code block restored as opposed to using the approach in this PR?

**Comment by michael-s-molina** [comment]
> @michael-s-molina would you prefer to have that code block restored as opposed to using the approach in this PR?

@Vitor-Avila It seems we should restore that code given that `nativeFiltersEnabled`, which is used for many things when calculating the dashboard state, used to depend on that parameter.

**Comment by zslegl** [comment]
Any progress on reviewing this fix?

**Review by rusackas — APPROVED** [review]
Just rebased this, and it looks fine to me. Let's see if CI (still) passes.

**Comment by rusackas** [comment]
I'm not sure if @Vitor-Avila or @michael-s-molina want to revisit restoring the old code block (which GitHub won't let me view at the moment for some reason 😢) but this PR looks pretty harmless to me in the meantime.

**Comment by Vitor-Avila** [comment]
@rusackas not sure if @hexcafe is around to assess potentially re-introducing that code. Let me check real quick if that would still work.

**Comment by Vitor-Avila** [comment]
@rusackas @michael-s-molina I restored the code from that PR locally (on top of `master`) to `superset-frontend/src/dashboard/components/DashboardBuilder/state.ts`:
* declared this `const`:
``` ts
const showNativeFilters = useSelector<RootState, boolean>(
    state => (getUrlParam(URL_PARAMS.showFilters) ?? true),
  );
```
* Updated the definition for `nativeFiltersEnabled` to:
``` ts
const nativeFiltersEnabled =
  showNativeFilters &&
  (canEdit || (!canEdit && filterValues.length !== 0));
```

Still, when loading a dashboard with `show_filters=false`, the filter bar is visible and expanded. It seems we also need a change in `superset-frontend/src/dashboard/components/DashboardBuilder/DashboardBuilder.tsx` similar to this PR:
``` tsx
const showFilterBar = !editMode && nativeFiltersEnabled;
```

Would it be better to build on top of this open PR or create a new one?

**Comment by Vitor-Avila** [comment]
@sfirke happy to help here :) just want to confirm if I should open a new/separate PR or if I should build on top of this one. I'd say the latter since we also need a similar change to @hexcafe and that should preserve his contribution to the work

**Comment by sfirke** [comment]
I think just build on this PR to preserve hexcafe's contribution while also moving it forward while you're looking at the code

**Comment by Vitor-Avila** [comment]
@rusackas @sfirke @michael-s-molina I believe this should be all good now. Could I get a new stamp? Try adding some tests, but manual tests are also encouraged haha 🙏

File: superset-frontend/src/dashboard/components/DashboardBuilder/state.ts [hunk 1]
```diff
@@ -29,6 +29,9 @@ import {
 // eslint-disable-next-line import/prefer-default-export
 export const useNativeFilters = () => {
   const [isInitialized, setIsInitialized] = useState(false);
+  const showNativeFilters = useSelector<RootState, boolean>(
+    state => getUrlParam(URL_PARAMS.showFilters) ?? true,
```
Comment (michael-s-molina) [inline superset-frontend/src/dashboard/components/DashboardBuilder/state.ts:33]: @Vitor-Avila The [original code](https://github.com/apache/superset/pull/23228/files#diff-6f2c6562ff1fad0ce405b3507cddff63a25dc91c76fb8613284b9cbb241dd928) had `&& state.dashboardInfo.metadata?.show_native_filters`. Isn't that needed anymore?

Comment (Vitor-Avila) [reply superset-frontend/src/dashboard/components/DashboardBuilder/state.ts:33]: @michael-s-molina my understanding is that the original PR fully removed `metadata.show_native_filters` (from all places). I suspect the reason for it is that this metadata config was intended to permanently hide the native filters on dashboards that had filter box, until it was fully migrated. So I don't think we need that back. If we want to bring that logic, we would need to re-update the schemas, and logic in other places too.

Not sure if you had a chance to test in that ephemeral but I believe things are working properly with these changes.

**Review by michael-s-molina — APPROVED** [review]

**Comment by Vitor-Avila** [comment]
@sfirke I noticed you created an ephemeral here -- let me know when you're good with testing and I'll merge this one. 🙌

**Comment by sfirke** [comment]
Hi @Vitor-Avila - I just tested in the ephemeral and it looks ready to merge :rocket: Thanks for this fix!

**Review by sfirke — APPROVED** [review]

**Comment by sfirke** [comment]
This actually closes two issues, I just linked the other in the top post.

**Comment by Vitor-Avila** [comment]
awesome! thanks for taking the time to test it. Just merged it
