### PR TITLE
Translate string to array for multi fields in getControlsState

### LINKED ISSUE #5011: Existing histogram slices are broken
Testing what's on master, I noticed that all of our existing histogram slices are broken with the error message `Must have at least one numeric column specified`. This error shows up when there's no data in `all_columns_x (Numeric Columns)`. In the params they all have `all_columns_x` set as a string. It looks like in the PR [here](https://github.com/apache/incubator-superset/pull/4525) this was changed to a multi field where the value would be a list. 

@mistercrunch would changing a SelectControl to multi: true break existing slices? Do we need a db migration for this or is there some other way we can catch this?

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
Existing histograms load correctly

### Actual results
Existing histograms load with the error 

### Steps to reproduce
Load a histogram created before [this](https://github.com/apache/incubator-superset/pull/4525) PR was introduced. 

@mistercrunch @ArielStv

### PR DESCRIPTION
**Pull request by michellethomas**
In the explore store.js, I'm adding logic that will handle a string value being passed to a multi control by making it an array. This would handle errors with existing slices when making a SelectControl multi. 

Fixes #5011 
@mistercrunch @graceguo-supercat

### CODE REVIEW

File: superset/assets/src/explore/store.js [hunk 1]
```diff
@@ -56,6 +56,10 @@ export function getControlsState(state, form_data) {
       delete control.mapStateToProps;
     }
 
+    if (control.multi && typeof formData[k] === 'string') {
```
Comment (hughhhh) [inline superset/assets/src/explore/store.js]: nit: `formData[k] = (control.multi && typeof formData[k] === 'string') ? [formData[k]] : formData[k]`

**Comment by hughhhh** [comment]
🚢

File: superset/assets/src/explore/store.js (hunk 1 above)
Comment (michellethomas) [reply superset/assets/src/explore/store.js]: I think we'd want to stick with `typeof formData[k] === 'string'` because formData[k] might be undefined or null and we would want to leave it as null.

Comment (mistercrunch) [reply superset/assets/src/explore/store.js]: Though I think it can be a `int` / `float` too.

Comment (michellethomas) [reply superset/assets/src/explore/store.js]: Ah ok, updated it to `formData[k] && !Array.isArray(formData[k])`.

**Comment by mistercrunch** [comment]
Actually after thinking a bit more I'm thinking while this fixes the problem in the explore view, I don't think it fixes the issue in the dashboard view.

**Comment by mistercrunch** [comment]
Maybe we need to refactor some sort of `formDataInterceptor` method that intercepts and modifies formData on the way in and executes for both Explore and Dashboard.
