### PR TITLE
fix(FilterBox): treat empty defaultValues as null

### LINKED ISSUE #13099: [Table]send empty filter value " " to query after default filter value is removed
User uses the same dataset to create a table chart, and a FilterBox with a default value in column. '
Add both to same dashboard. 
Go to dashboard, see default value and table chart ✅
User goes edit the FilterBox in Explore from Dashboard
Remove the original selected default filter value and save, go back to the same dashboard. 
See chart result is not showing after default value is removed -  see video

Expected: User should still see a chart that's not being filtered. 

Reasons: empty value " " is sent to the query, instead of no filter/where clause 
Workaround: delete the filter that had default value, and create a brand new same one, add to dashboard.. 

Not db specific. only happens on table chart. 

https://user-images.githubusercontent.com/67837651/107823877-62032680-6d35-11eb-936a-1357e2523966.mov

https://user-images.githubusercontent.com/67837651/107824879-046fd980-6d37-11eb-827a-56108e3a3dee.mov

### PR DESCRIPTION
**Pull request by ktmud**
### SUMMARY

Fixes #13099 

`FilterBox` will send empty string as filter values when a column's `defaultValue` is empty string, causing no-results for filtered charts.

The default value for filter column's `defaultValue` is `null`, but if users have edited it, it will be updated to an empty string. 

This empty string is then propagated to `extra_filters` of the affected charts. This PR will treat empty strings as `null` when constructing filter values for the dashboard.

This is the preferred fix because there may be existing `FilterBox` charts already have `defaultValue: ""` saved in their metadata.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

See  #13099 how to reproduce the bug.

### TEST PLAN

1. Manual verification following steps in #13099
2. Added a unit test 

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [x] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/visualizations/FilterBox/FilterBox.jsx [hunk 1]
```diff
@@ -356,21 +350,21 @@ class FilterBox extends React.PureComponent {
...
       });
-    const { key, label } = filterConfig;
+    const {
+      key,
+      label,
+      [FILTER_CONFIG_ATTRIBUTES.MULTIPLE]: isMultiple,
+      [FILTER_CONFIG_ATTRIBUTES.DEFAULT_VALUE]: defaultValue,
+      [FILTER_CONFIG_ATTRIBUTES.CLEARABLE]: isClearable,
+      [FILTER_CONFIG_ATTRIBUTES.SEARCH_ALL_OPTIONS]: searchAllOptions,
+    } = filterConfig;
```
Comment (ktmud) [inline superset-frontend/src/visualizations/FilterBox/FilterBox.jsx:360]: I also did some light refactoring to make the code easier to read.

File: superset-frontend/src/visualizations/FilterBox/FilterBox.jsx [hunk 2]
```diff
@@ -336,10 +328,12 @@ class FilterBox extends React.PureComponent {
...
     Object.keys(selectedValues)
-      .filter(
-        key => selectedValues.hasOwnProperty(key) && key in filtersChoices,
-      )
+      .filter(key => key in filtersChoices)
       .forEach(key => {
+        // empty values are ignored
+        if (!selectedValues[key]) {
+          return;
+        }
```
Comment (ktmud) [inline superset-frontend/src/visualizations/FilterBox/FilterBox.jsx:336]: This will fix this bug:

### Before

has-empty-value

### After

no-empty-value

File: superset-frontend/src/visualizations/constants.js [hunk 3]
```diff
@@ -1,27 +0,0 @@
...
- */
-export const TIME_CHOICES = [
-  '1 hour ago',
-  '12 hours ago',
-  '1 day ago',
-  '7 days ago',
-  '28 days ago',
-  '90 days ago',
-  '1 year ago',
-];
```
Comment (ktmud) [inline superset-frontend/src/visualizations/constants.js:27]: Bycatch: this constant is not used anywhere.

**Review by villebro — APPROVED** [review]
LGTM, thanks for also taking the time to add a test + clean up the code.

**Comment by junlincc** [comment]
Thanks for the fix and sweeping the code. 
After I select a default filter, there's no option showing in dropdown in Filterbox or Dashboard.  
Screen Shot 2021-02-14 at 7 21 29 PM
Screen Shot 2021-02-14 at 7 21 15 PM

**Comment by ktmud** [comment]
@junlincc This is because the default time range filter ("Last week") was applied to your FilterBox chart. This is a legacy behavior I'm also not a fan of, but it is unrelated to this chart.

At Airbnb, we've discussed whether to allow setting a default Time Range filter per datasource as removing this default filter may have performance impact on some datasets, but we never had the time to follow it though. Could be a nice roadmap item, though.

**Comment by junlincc** [comment]
hmm. i removed time filter but still not able to see the default value in country. @ktmud

**Comment by ktmud** [comment]
In Explore view, default values are not displayed in the rendered chart, but they will be applied in the dashboard. This is a separate bug. Feel free to create a new issue to track it, or I'll do some investigation when I have time.

**Comment by villebro** [comment]
@ktmud @junlincc I was also quite surprised by the default values not showing up on Explore (I haven't used them that much). I would vote for not putting effort into implementing default values in Explore view unless it's trivial, as the native select filter is almost ready for prime time and IMO provides a much cleaner UX than this component.

**Comment by junlincc** [comment]
> I would vote for not putting effort into implementing default values in Explore view unless it's trivial, as the native select filter is almost ready for prime time and IMO provides a much cleaner UX than this component.

I agree with @villebro . Grace and Zuzana, native filter is reaching feature parity in about 1 week. at that point, we will have our main focus on the new feature set and may not actively maintain FilterBox anymore. Now is a good time to start the migration script as we discussed before.
@graceguo-supercat @zuzana-vej @ktmud 

cc @amitmiran137 @simcha90

**Comment by junlincc** [comment]
> This is a known issue and also a separate bug.

actually it's an inconsistent behavior, I'm inclined not to fix it.

**Review by junlincc — APPROVED** [review]
I'm inclined not to fix the remaining issue.  

Thanks for the PR again!
