### PR TITLE
fix: don't show metadata for embedded dashboards

### LINKED ISSUE #30188: Superset 4.1.0RC2 - Dashboard embedding - now includes editor and last modified timestamp
### Bug description

The latest 4.1.0rc2 has in the dashboard header a username and last modified timestamp. This doesn't make sense for the embedded use case and should be hidden from the dashboard title. 

This should be hidden just like the Published tag as this is metadata that doesnt make sense outside of the superset app. 

Introduced in #27857

### How to reproduce the bug

1. Create a dashboard
2. Embed the dashboard in a page 
3. View embedded page with very superset specific metadata. 

### Screenshots/recordings

image

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by sadpandajoe**
### SUMMARY

As part of https://github.com/apache/superset/pull/27857 we started to show metadata even on embedded dashboards. This could have a potential of displaying data that embedded don't need to see. This PR will remove it if we are in embedded view.

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/30188
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/components/Header/index.jsx [hunk 1]
```diff
@@ -496,6 +496,7 @@ class Header extends PureComponent {
     const refreshWarning =
       dashboardInfo.common?.conf
         ?.SUPERSET_DASHBOARD_PERIODICAL_REFRESH_WARNING_MESSAGE;
+    const isEmbedded = !dashboardInfo?.userId;
```
Comment (mistercrunch) [inline superset-frontend/src/dashboard/components/Header/index.jsx:499]: [non blocking] curious whether there's a more explicit way to check whether we're in an embedded context?

Comment (rusackas) [reply superset-frontend/src/dashboard/components/Header/index.jsx:499]: I don't think so, but this comes up often... we need to invent this kind of state/check for myriad reasons.

**Review by Vitor-Avila — APPROVED** [review]
LGTM!

File: superset-frontend/src/dashboard/components/Header/index.jsx (hunk 1 above)
Comment (Vitor-Avila) [reply superset-frontend/src/dashboard/components/Header/index.jsx:499]: I agree it's not ideal, but this is consistent with other places we assess if it's an embedded user or not.
