### PR TITLE
fix(explore): conditional formatting value validators

### LINKED ISSUE #16169: [cell formatting]False warning of Conditional Formatting validation in Table & Pivot Table V 2
False warning in Conditional Formatting validation in Table & Pivot Table V 2.
It seems that the current compare logic is string based instead of real number based.

#### Screenshots

image

image

### Environment

- superset version: Git master

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
This PR casts  number-like strings to numbers in order to ensure correct value validation in conditional formatting.
Before, we were comparing values that were actually strings and not numbers, which caused incorrect validation errors.

I also did some refactoring to avoid unnecessary rerenders.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before: see linked issue
After:
https://user-images.githubusercontent.com/15073128/129187281-ab83bcde-870c-4715-a733-9448bdbd9c84.mov

### TESTING INSTRUCTIONS
1. Open Table or Pivot Table v2 chart
2. Add conditional formatter with "Between" operator and type left and right values. Verify that errors show up only if left value is larger than right. Try typing left value which is alphabetically "larger", but arithmetically smaller than right value in order to recreate the reported issue.

### ADDITIONAL INFORMATION

- [x] Has associated issue: fixes #16169 
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC @vnnw @junlincc @jinghua-qa

### CODE REVIEW

File: superset-frontend/src/explore/components/controls/ConditionalFormattingControl/FormattingPopoverContent.tsx [hunk 1]
```diff
@@ -57,6 +57,131 @@ const operatorOptions = [
...
+) => {
+  if (!value || !rightValue || Number(rightValue) > Number(value)) {
+    return Promise.resolve();
+  }
+  return Promise.reject(
+    new Error(t('This value should be smaller than the right target value')),
+  );
+};
+
+const targetValueRightValidator = (leftValue?: number) => (
```
Comment (villebro) [inline superset-frontend/src/explore/components/controls/ConditionalFormattingControl/FormattingPopoverContent.tsx:72]: I might be swatting a fly with a sledge hammer, but it could be nice to have a `targetValueValidator` that encapsulates the repeated logic here.

**Review by villebro — APPROVED** [review]
LGTM! Left a thought about potential DRYing, but not sure it really sits that well here.

File: superset-frontend/src/explore/components/controls/ConditionalFormattingControl/FormattingPopoverContent.tsx (hunk 1 above)
Comment (kgabryje) [reply superset-frontend/src/explore/components/controls/ConditionalFormattingControl/FormattingPopoverContent.tsx]: Done

**Comment by rosemarie-chiu** [comment]
🏷 2021.31
