### PR TITLE
fix(table): only show increase/decrease color options when time comparison enabled

### LINKED ISSUE #34141: Green for increase, Y for decrease color scheme option on the Table Chart does not work
### Bug description

Users can choose the X for increase, Y for decrease color scheme option on the Table Chart. However, it does not work.

## Reproduction
1. Create a virtual dataset with query
```sql
SELECT
  1 AS X,
  2 AS Y,
  1 - 2 AS "X-Y"
UNION ALL
SELECT
  5 AS X,
  2 AS Y,
  5 - 2 AS "X-Y"
UNION ALL
SELECT
  4 AS X,
  2 AS Y,
  4 - 2 AS "X-Y"
UNION ALL
SELECT
  1 AS X,
  5 AS Y,
  1 - 5 AS "X-Y"
UNION ALL
SELECT
  1 AS X,
  1 AS Y,
  1 - 1 AS "X-Y";
```
2. Create a table chart with this dataset
3. Go to the Customize tab, and add Conditional Formatting to the third column.
4. Choose the Green for increase, red for decrease option.

## Expected results
The "Green for increase, red for decrease" and "Red for increase, green for decrease" conditional formatting options shouldn't appear unless there is a time shift applied to the table
## Actual results
The Conditional Formatting for the X for increase, Y for decrease does not work.

### Screenshots/recordings

Image

### Superset version

master / latest-dev

### Python version

3.11

### Node version

18 or greater

### Browser

Firefox

### Additional context

_No response_

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by jesperct**
### SUMMARY
Issue: Currently, when selecting conditional formatting in a table column, we have options that do not work for non-time comparison data.

Root cause: We weren't conditionally showing time comparison specific formatting.

Fix: Add a check before deciding whether show or not custom formatting options that depend on time comparison.

Related PR: #34523

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
BEFORE:
<video src="https://github.com/user-attachments/assets/8b659dd5-c986-4dbe-b88c-31f860837681" controls></video>
AFTER:
<video src="https://github.com/user-attachments/assets/f00dcbba-edff-457c-9fba-1c3be8ae3bb0" controls></video>

### TESTING INSTRUCTIONS
1. Create a Table Chart with the following values:

 X   | Y   | X-Y  
--   | --  | --
1    | 2   | -1
5    | 2   | 3
4    | 2   | 2
1    | 5   | -4
1    | 1   | 0

2. Go to the Customize tab, and add Conditional Formatting to the third column.
3. Choose the Green for increase, red for decrease option.

Expected results: 
The "Green for increase, red for decrease" and "Red for increase, green for decrease" conditional formatting options shouldn't appear unless there is a time shift applied to the table

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #34141 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/plugins/plugin-chart-ag-grid-table/src/controlPanel.tsx [hunk 1]
```diff
@@ -40,7 +40,7 @@ import {
   isRegularMetric,
   isPercentMetric,
 } from '@superset-ui/chart-controls';
-import { t } from '@apache-superset/core';
+import { t } from '@apache-superset/core/ui/translation';
```
Comment (msyavuz) [inline superset-frontend/plugins/plugin-chart-ag-grid-table/src/controlPanel.tsx]: Is this change necessary?

**Review by msyavuz — COMMENTED** [review]
Can we check if this exist for pivot table and fix it there as well if it does?

**Review by EnxDev — COMMENTED** [review]
Manual testing looks good to me!

File: superset-frontend/plugins/plugin-chart-ag-grid-table/src/controlPanel.tsx (hunk 1 above)
Comment (jesperct) [reply superset-frontend/plugins/plugin-chart-ag-grid-table/src/controlPanel.tsx]: The original import was causing TypeScript type-checking errors because **t** is not exported in the type definitions from the root module. Using the specific path resolves the type errors while maintaining the same runtime behavior.

**Comment by jesperct** [comment]
> Can we check if this exist for pivot table and fix it there as well if it does?

Thanks for pointing that out. I checked the pivot table plugin, and it doesn't have the same issue. The pivot table's conditional formatting control doesn't include the extraColorChoices feature (the "Green for increase, red for decrease" options).

File: superset-frontend/plugins/plugin-chart-ag-grid-table/src/controlPanel.tsx (hunk 1 above)
Comment (SBIN2010) [reply superset-frontend/plugins/plugin-chart-ag-grid-table/src/controlPanel.tsx]: I've tested this myself, deployed it locally, and don't see any import issues.
I don't think these changes are necessary.

Comment (msyavuz) [reply superset-frontend/plugins/plugin-chart-ag-grid-table/src/controlPanel.tsx]: Yeah, it shouldn't cause any import issues, if it did ci would fail on master too

Comment (jesperct) [reply superset-frontend/plugins/plugin-chart-ag-grid-table/src/controlPanel.tsx]: Yeah, makes sense, not sure why I was seeing this listed as an issue in the pre-commit though, I will take a look into my local config and revert this change. thx!

Comment (EnxDev) [reply superset-frontend/plugins/plugin-chart-ag-grid-table/src/controlPanel.tsx]: Hi @JCelento, after that revert I think we can merge this PR, thanks!

Comment (jesperct) [reply superset-frontend/plugins/plugin-chart-ag-grid-table/src/controlPanel.tsx]: Hi everyone, sorry for the delay. I just updated, reverting the import changes 👍

**Review by SBIN2010 — APPROVED** [review]
LGTM! Thank you for the contribution!

**Review by EnxDev — APPROVED** [review]
