### PR TITLE
fix(dashboard): check edit permissions correctly on frontend

### LINKED ISSUE #14442: Public dashboard does not work due to JS error in findPermission.ts
Setting up a public dashboard does not work and fails on the findPermission.ts file due to JS error for undefined roles object passed as an argument.

### Expected results

A dashboard to open and without user login.

### Actual results

JavaScript error and dashboard fails to load

#### Screenshots

superset

#### How to reproduce the bug

1. Clone the repository locally
2. Add the following to the `superset_config.py` `PUBLIC_ROLE_LIKE = "Gamma"`
3. Start superset using `docker-compose up`
4. Log in as admin and edit the public roles to have all required permissions for one of the dashboards.
5. Log-out or in a private browser window try to open the public dashboard.

### Environment

- superset version: `Version: 0.999.0dev`
- python version: `Python 2.7.18`
- node.js version: `v12.18.2`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Browser stack trace

```
findPermission.ts?060b:23 Uncaught TypeError: Cannot convert undefined or null to object
    at values (<anonymous>)
    at eval (findPermission.ts?060b:23)
    at memoized (memoize-one.esm.js?5b0a:27)
    at eval (hydrate.js?ab55:354)
    at eval (index.js?b083:8)
    at eval (DashboardPage.tsx?a8fc:59)
    at commitHookEffectListMount (VM22770 react-dom.development.js:19765)
    at commitPassiveHookEffects (VM22770 react-dom.development.js:19803)
    at HTMLUnknownElement.callCallback (VM22770 react-dom.development.js:189)
    at Object.invokeGuardedCallbackDev (VM22770 react-dom.development.js:238)
eval @ findPermission.ts?060b:23
memoized @ memoize-one.esm.js?5b0a:27
eval @ hydrate.js?ab55:354
eval @ index.js?b083:8
eval @ DashboardPage.tsx?a8fc:59
commitHookEffectListMount @ react-dom.development.js?7f13:19765
commitPassiveHookEffects @ react-dom.development.js?7f13:19803
callCallback @ react-dom.development.js?7f13:189
invokeGuardedCallbackDev @ react-dom.development.js?7f13:238
invokeGuardedCallback @ react-dom.development.js?7f13:293
flushPassiveEffectsImpl @ react-dom.development.js?7f13:22885
unstable_runWithPriority @ scheduler.development.js?b589:653
runWithPriority$1 @ react-dom.development.js?7f13:11062
flushPassiveEffects @ react-dom.development.js?7f13:22852
eval @ react-dom.development.js?7f13:22731
workLoop @ scheduler.development.js?b589:597
flushWork @ scheduler.development.js?b589:552
performWorkUntilDeadline @ scheduler.development.js?b589:164
react-dom.development.js?7f13:19561 The above error occurred in the <DashboardPage> component:
    in DashboardPage (created by DashboardPageWithErrorBoundary)
    in ErrorBoundary (created by DashboardPageWithErrorBoundary)
    in DashboardPageWithErrorBoundary (created by App)
    in DynamicPluginProvider (created by App)
    in ThemeProvider (created by App)
    in Unknown (created by App)
    in Provider (created by App)
    in App
    in AppContainer
    in Unknown

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js?7f13:19561
logError @ react-dom.development.js?7f13:19598
callback @ react-dom.development.js?7f13:20778
callCallback @ react-dom.development.js?7f13:12513
commitUpdateQueue @ react-dom.development.js?7f13:12534
commitLifeCycles @ react-dom.development.js?7f13:19892
commitLayoutEffects @ react-dom.development.js?7f13:22835
callCallback @ react-dom.development.js?7f13:189
invokeGuardedCallbackDev @ react-dom.development.js?7f13:238
invokeGuardedCallback @ react-dom.development.js?7f13:293
commitRootImpl @ react-dom.development.js?7f13:22573
unstable_runWithPriority @ scheduler.development.js?b589:653
runWithPriority$1 @ react-dom.development.js?7f13:11062
commitRoot @ react-dom.development.js?7f13:22413
finishSyncRender @ react-dom.development.js?7f13:21839
performSyncWorkOnRoot @ react-dom.development.js?7f13:21825
eval @ react-dom.development.js?7f13:11112
unstable_runWithPriority @ scheduler.development.js?b589:653
runWithPriority$1 @ react-dom.development.js?7f13:11062
flushSyncCallbackQueueImpl @ react-dom.development.js?7f13:11107
flushSyncCallbackQueue @ react-dom.development.js?7f13:11095
flushPassiveEffectsImpl @ react-dom.development.js?7f13:22915
unstable_runWithPriority @ scheduler.development.js?b589:653
runWithPriority$1 @ react-dom.development.js?7f13:11062
flushPassiveEffects @ react-dom.development.js?7f13:22852
eval @ react-dom.development.js?7f13:22731
workLoop @ scheduler.development.js?b589:597
flushWork @ scheduler.development.js?b589:552
performWorkUntilDeadline @ scheduler.development.js?b589:164

```
```JavaScript
import memoizeOne from 'memoize-one';

type UserRoles = Record<string, [string, string][]>;

const findPermission = memoizeOne(
  (perm: string, view: string, roles: UserRoles) =>
    Object.values(roles).some(permissions =>
      permissions.some(([perm_, view_]) => perm_ === perm && view_ === view),
    ),
);

export default findPermission;
```
roles is undefined.

### PR DESCRIPTION
**Pull request by suddjian**
### SUMMARY

This fixes a case where users who were not owners of a dashboard were incorrectly seeing the "Edit" button. This is not a security hole as the users cannot successfully submit their edits, but it was incorrect UI that needed to be fixed.

The frontend was incorrectly inferring dashboard edit permissions. This change fixes the issue by copying logic from the backend's [check_ownership](https://github.com/apache/superset/blob/d31958cbd2e980a5c186334e718fa71ed8d12e74/superset/views/base.py#L569) function. 

The code of the frontend version implements the same check, while being much simpler than the backend version due to being a pure function, dashboard-specific, and not having parameterized function behavior.

I did this instead of changing endpoints, because the caching of the existing dashboard endpoints depends on returning the same data to all users, and because implementing a new endpoint to just return a boolean felt wrong.

### TEST PLAN

1. Log in as a user with "Alpha" role (or other non-admin role with dashboard edit permissions)
1. View a dashboard of which you are an owner - you should be able to edit
1. View a dashboard of which you are **not** an owner - you should **not** be able to edit
1. Log in as an admin: you should be able to edit any dashboard, regardless of ownership
1. Log in as a user without dashboard edit permissions (e.g. Gamma role): You should not be able to edit any dashboard, regardless of ownership

### ADDITIONAL INFORMATION

- [x] Has associated issue: fixes #14442
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
@suddjian hi Aaron, can you add manual test plan for our QA team to help test? thanks 😊

**Comment by suddjian** [comment]
Done @junlincc thank you for the heads up

File: superset-frontend/src/common/hooks/apiResources/dashboards.ts [hunk 1]
```diff
@@ -25,8 +25,9 @@ export const useDashboard = (idOrSlug: string | number) =>
     useApiV1Resource<Dashboard>(`/api/v1/dashboard/${idOrSlug}`),
     dashboard => ({
       ...dashboard,
-      metadata: JSON.parse(dashboard.json_metadata),
-      position_data: JSON.parse(dashboard.position_json),
+      metadata: dashboard.json_metadata && JSON.parse(dashboard.json_metadata),
```
Comment (pkdotson) [inline superset-frontend/src/common/hooks/apiResources/dashboards.ts:28]: should this be initialized as a empty object if dashboard comes back as undefined.

**Review by nytai — APPROVED** [review]

File: superset-frontend/src/common/hooks/apiResources/dashboards.ts (hunk 1 above)
Comment (suddjian) [reply superset-frontend/src/common/hooks/apiResources/dashboards.ts:28]: I assume you mean if the metadata is undefined (if the dashboard is undefined it will be a 404). I don't think it should be initialized like that, null is different from an empty object.

This is not actually new behavior, I just had to write this guard to appease the type system since I corrected the types of some dashboard fields to be nullable.

**Comment by suddjian** [comment]
fixes #14442

**Review by pkdotson — APPROVED** [review]
LGTM!

**Comment by michael-s-molina** [comment]
> #14442

@suddjian GitHub will not automatically close this issue because it doesn't check for comments. You should add this text to the PR description 😉
