### PR TITLE
fix: extra query in Dashboard when native filter enabled

### LINKED ISSUE #14706: [native filter] Instant filter component will generate 2x more fetch
#### How to reproduce the bug

1. Go to dashboard
2. add native filter component and add a value
3. Check `Apply changes instantly`
4. reload dashboard. You will see every charts are loaded 3 times. This issue cause dashboard load really slow.

#### Screenshots

G7lm7HcLC7

### Environment

(please complete the following information):

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

cc @junlincc @villebro This issue is reported by open source user.

### PR DESCRIPTION
**Pull request by zhaoyongjie**
### SUMMARY

fix extra query in Dashboard when `native filter` enabled and `Apply changes instantly` setting up.

closes: https://github.com/apache/superset/issues/14706

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

https://user-images.githubusercontent.com/2016594/119272353-0c91bc00-bc38-11eb-9121-6294f0c3199a.mp4

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/14706
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/components/nativeFilters/FilterBar/index.tsx [hunk 1]
```diff
@@ -187,8 +187,11 @@ const FilterBar: React.FC<FiltersBarProps> = ({
     setIsFilterSetChanged(tab !== TabIds.AllFilters);
     setDataMaskSelected(draft => {
       const children = cascadeChildren[filter.id] || [];
-      // force instant updating on initialization or for parent filters
-      if (filter.isInstant || children.length > 0) {
+      // force instant updating on initialization or for parent filters when dataMaskSelected has filter
+      if (
+        dataMaskSelected[filter.id] &&
```
Comment (zhaoyongjie) [inline superset-frontend/src/dashboard/components/nativeFilters/FilterBar/index.tsx:192]: Ensure that DataMaskSelected contains the filter, rather than the initial object(empty object).

**Review by villebro — APPROVED** [review]
LGTM and tested to work well!
