### PR TITLE
fix(dashboard): prevent table chart infinite reload loop

### LINKED ISSUE #36595: Table charts reloading non-stop
### Bug description

Pull from master and run Superset. Table charts keep reloading and firing database queries.

### Screenshots/recordings

https://github.com/user-attachments/assets/4e37d6fe-36a5-44c4-8ff7-4accda0abbaf

### Superset version

master / latest-dev

### Python version

3.11.14

### Node version

v20.19.5

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by sadpandajoe**
### SUMMARY
Fixes an infinite reload loop in Dashboard context where table charts would continuously re-query, causing hundreds/thousands of API calls per user.

**Root Cause:** The recent "Export table data with Search box" feature (PR #36281) added clientView to ownState on every filtered-row change. In Dashboard context, getRelevantDataMask passed this through unchanged, causing Dashboard.jsx to see continuous state changes and trigger re-queries in an infinite loop.

**Fix:** Strip clientView from ownState in getRelevantDataMask (the selector that extracts chart state for Dashboard). This matches the existing pattern in ExploreViewContainer which already strips clientView before comparing state changes.

```
  // Before: passed ownState through unchanged
  .map(item => [item.id, item[prop]])

  // After: strips clientView when prop is 'ownState'
  .map(item => [
    item.id,
    prop === 'ownState' ? omit(item[prop], ['clientView']) : item[prop],
  ])
```

**Why this location:** clientView is explicitly for export functionality, not for triggering re-queries. Stripping at the selector level ensures Dashboard never sees these changes as state updates.

### TESTING INSTRUCTIONS

1. Open a dashboard containing a table chart with server-side pagination disabled
2. Apply a filter or interact with the table search box
3. Open browser DevTools → Network tab
4. Verify there are NO repeated /api/v1/chart/data calls
5. Verify the "Export" functionality still works correctly (exports filtered data)

### ADDITIONAL INFORMATION

- [ ] Has associated issue: Fixes #36595
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/util/activeAllDashboardFilters.ts [hunk 1]
```diff
@@ -31,7 +32,21 @@ export const getRelevantDataMask = (
   Object.fromEntries(
     Object.values(dataMask)
       .filter(item => item[prop])
-      .map(item => [item.id, item[prop]]),
+      .map(item => {
+        const value = item[prop];
```
Comment (michael-s-molina) [inline superset-frontend/src/dashboard/util/activeAllDashboardFilters.ts:36]: Shouldn't this be handled by the chart component instead of `getRelevantDataMask`? I'm wondering if `clientView` might be useful for another caller of `getRelevantDataMask` and should just be discarded by the chart when re-rendering.

Comment (sadpandajoe) [reply superset-frontend/src/dashboard/util/activeAllDashboardFilters.ts:36]: I think modifying the table chart plugin (separate package) to conditionally write `clientView` based on context could potentially be more complex and could introduce regressions. Also this mirrors how `Explore` does it

Comment (michael-s-molina) [reply superset-frontend/src/dashboard/util/activeAllDashboardFilters.ts:36]: I think we have two options:

1. Given the "relevant" word on `getRelevantDataMask`, we might consider that `clientView` is not relevant and your solution would be correct. This means that `clientView` is never relevant for any caller of this function which might be true given that there's only one caller currently (`DashboardPage.tsx`).
2. If `clientView` might be useful for other callers, we could change `DashboardPage.tsx` and omit the property there:

```
const selectRelevantDatamask = createSelector(
  (state: RootState) => state.dataMask,
  dataMask => omit(getRelevantDataMask(dataMask, 'ownState'), ['clientView']),
);
```

I'm good with either solution, so I'm approving the PR.

**Review by michael-s-molina — APPROVED** [review]

**Comment by rusackas** [comment]
OMG THANK YOU. @SBIN2010 and I were just talking about this yesterday...

**Comment by SkinnyPigeon** [comment]
Hey @rusackas, @sadpandajoe 👋. Do we have an estimate for when this will be released? This has been a real issue for us for a month or so and we'd love to get this out to our teams

**Comment by rusackas** [comment]
Looks like it's on Preset, but for Superset, it'll likely be part of 6.0.1 or 6.1.0, whichever comes first (both are being worked on, but it's a volunteer thing to build/fix/test these releases, so we do our best)

**Comment by rusackas** [comment]
@sadpandajoe might have a more detailed answer.
