### PR TITLE
fix: Tooltip no longer highlights hovered data series

### LINKED ISSUE #24738: "Rich tooltip" no longer highlights hovered-over data series in stacked barchart
The "rich tooltip" that lists all the series in a stacked bar chart when hovering over a column no longer highlights the series the mouse pointer is hovering over. This makes it very hard to identify which series the user is looking at and what the value is. This behaviour has changed between version 2.1.0 and the "latest" docker image. I assume this is not a deliberate change as it is a loss of usability for stacked bar charts.

#### How to reproduce the bug

1. For a stacked bar chart with "Rich tooltip" option enabled, hover pointed over a chart data item in a stacked column
2. Observe the tooltip with listing of each data series in the column and the amounts for each for that column

### Expected results

The data series listed in the tool tip is highlights text describing the series that the pointer is hovering over to differentiate it from the other series

### Actual results

Each data series listed in the tool tip is presented the same way, without differentiating between the series that the pointer is hovering over and all the other series.

#### Screenshots
Latest behaviour (incorrect):
latest

2.1.0 behaviour (correct):

Sorry, mouse pointer was not captured by the screenshot. It is actually hovering over the "DairyEggs" series in each case.

### Environment
- Chrome 114.0.5735.198 (Linux)
- superset version: Docker apache/superset:aa01b51177a59dd0dcf4e66221a58e2331591716
- python version: As per docker image
- node.js version: As per docker image
- any feature flags active: None

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Fixes https://github.com/apache/superset/issues/24738.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Screenshot 2023-07-20 at 15 39 14

Screenshot 2023-07-20 at 15 32 45

### TESTING INSTRUCTIONS
Check if hovered series are highlighted.

### ADDITIONAL INFORMATION
- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts [hunk 1]
```diff
@@ -576,7 +577,12 @@ export default function transformProps(
               ? tooltipFormatter
               : tooltipFormatterSecondary,
           });
-          rows.push(`<span style="opacity: 0.7">${content}</span>`);
+          const { focusedSeries } = ownState;
+          if (key === focusedSeries) {
+            rows.push(`<span style="font-weight: 700">${content}</span>`);
+          } else {
+            rows.push(`<span style="opacity: 0.7">${content}</span>`);
+          }
```
Comment (justinpark) [inline superset-frontend/plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts:585]: not critical but it looks like it always pushes content span but only applies different styles. So this might be better like

```suggestion
          const contentStyle = key === focusedSeries ? 'font-weight: 700' : 'opacity: 0.7';
          rows.push(`<span style="${contentStyle}">${content}</span>`);
```

**Review by justinpark — APPROVED** [review]
My suggestion doesn't belong to the major fix of this. LGTM

**Review by mistercrunch — APPROVED** [review]
