### PR TITLE
fix: can't drop column when name overlap

### LINKED ISSUE #16458: [dragndrop]invalid temporal column stuck in the drop zone
attempted to create a time series chart with a calculated temporal column from invalid time format, after dropping the calculated column, there's no way to swap it out with other time columns(that are invalid). 
1) the invalid calculated column shouldn't be droppable at the first place, 2)given that the drop zone is not smart enough to detect all invalid temporal columns, maybe we should not lock it, should allow user to clear the field instead. 

https://user-images.githubusercontent.com/67837651/130907202-3c9bb68b-1795-4fa2-be58-522745be54f9.mov

https://user-images.githubusercontent.com/67837651/130907861-c73583ff-b56e-4659-8a6e-dce74aad41b3.mov

### PR DESCRIPTION
**Pull request by zhaoyongjie**
### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

closes: https://github.com/apache/superset/issues/16458
Currently, OptionSelector.getValues() can return `string array`, `string` and `undefined`, the `OptionSelector.has()` method determine if it contains by `includes(value)`. If it encounter the string case, it is clearly a faulty logic.

#### After

https://user-images.githubusercontent.com/2016594/131109770-2877692f-afa9-4e5a-b560-d4e108b3bd45.mov

#### Before

https://user-images.githubusercontent.com/2016594/131110102-8bf93f0c-a19c-4157-b9cc-55c6fbebac8c.mov

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/16458
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/explore/components/controls/DndColumnSelectControl/utils/optionSelector.ts [hunk 1]
```diff
@@ -67,9 +67,10 @@ export class OptionSelector {
     return !!this.getValues()?.includes(value);
   }
 
-  getValues(): string[] | string | undefined {
+  getValues(): string[] | undefined {
+    // ensure an array type return value
     if (!this.multi) {
-      return this.values.length > 0 ? this.values[0].column_name : undefined;
+      return this.values.length > 0 ? [this.values[0].column_name] : undefined;
```
Comment (villebro) [inline superset-frontend/src/explore/components/controls/DndColumnSelectControl/utils/optionSelector.ts:73]: I assume the current return type `string[] | string | undefined` is there to make it fully compatible with the non-dnd control, which returns `string` when not in `multi` mode. Am I right @kgabryje?

File: superset-frontend/src/explore/components/controls/DndColumnSelectControl/DndColumnSelect.tsx [hunk 2]
```diff
@@ -59,8 +59,9 @@ export function DndColumnSelect(props: DndColumnSelectProps) {
     }
     if (
       typeof value === 'string' &&
-      typeof optionSelectorValues === 'string' &&
-      value !== optionSelectorValues
+      Array.isArray(optionSelectorValues) &&
+      optionSelectorValues.length === 1 &&
+      value !== optionSelectorValues[0]
```
Comment (villebro) [inline superset-frontend/src/explore/components/controls/DndColumnSelectControl/DndColumnSelect.tsx:64]: I looked at `OptionSelector.has` - I agree that should probably be changed to something like

```typescript
  has(value: string): boolean {
    return ensureIsArray(this.getValues()).includes(value);
  }
```

Would changing that solve this problem?

**Review by villebro — COMMENTED** [review]
Some comments - would appreciate a review/testing round from @kgabryje

File: superset-frontend/src/explore/components/controls/DndColumnSelectControl/utils/optionSelector.ts (hunk 1 above)
Comment (kgabryje) [reply superset-frontend/src/explore/components/controls/DndColumnSelectControl/utils/optionSelector.ts:73]: i think it's not really about compatibility between dnd and non-dnd, but what chart's logic expects - I think charts expect a string for a single value controls and an array for multi value controls. I tested this PR with Bubble Chart and I'm getting an error after changing a value in a non-multi control
CC @zhaoyongjie 
image

Comment (villebro) [reply superset-frontend/src/explore/components/controls/DndColumnSelectControl/utils/optionSelector.ts:73]: Right - I think v1 charts won't mind, but `viz.py` definitely has lots of logic that either assumes control values are either arrays or strings.

File: superset-frontend/src/explore/components/controls/DndColumnSelectControl/DndColumnSelect.tsx (hunk 2 above)
Comment (zhaoyongjie) [reply superset-frontend/src/explore/components/controls/DndColumnSelectControl/DndColumnSelect.tsx]: Done. thanks

File: superset-frontend/src/explore/components/controls/DndColumnSelectControl/utils/optionSelector.ts (hunk 1 above)
Comment (zhaoyongjie) [reply superset-frontend/src/explore/components/controls/DndColumnSelectControl/utils/optionSelector.ts]: Sorry, I overlooked that part of the logic. fixed

**Review by villebro — APPROVED** [review]
