### PR TITLE
fix(frontend/docker, ci): fix borked Docker build due to Lerna v8 uplift

### LINKED ISSUE #29658: superset_node build failure @nx/nx-linux-x64-gnu missing module
### Bug description

When trying to deploy using docker compose, I'm receiving a missing module error. It appears this bug first emerged in PR https://github.com/apache/superset/pull/29419 specifically commit hash: c30ca534a38f624bfc87fcfa1c1161b542115822

### How to reproduce the bug

Checkout latest master branch
Clear the docker cache of previous superset images
Rebuild images with docker compose build
Run docker compose up 

### Screenshots/recordings

image

### Superset version

master / latest-dev

### Python version

3.10

### Node version

18 or greater

### Browser

Chrome

### Additional context

As a workaround to other build errors, I've edited Dockerfile line 27 from
`ARG NPM_BUILD_CMD="build"`
to
`ARG NPM_BUILD_CMD="build-dev"`

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by hainenber**
fix(frontend/docker, ci): fix borked Docker build due to Lerna v8 uplift

### SUMMARY
Closes #29658

Remove `--no-optional` in `docker-frontend.sh` to allow installing `@nx` optional dependencies which is necessary for Lerna v8

Also upgrading `prop-types` to next minor version to assess reproducibility of issue raised in PR https://github.com/apache/superset/pull/29723

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: docker/docker-frontend.sh [hunk 1]
```diff
@@ -26,7 +26,7 @@ fi
 if [ "$BUILD_SUPERSET_FRONTEND_IN_DOCKER" = "true" ]; then
     cd /app/superset-frontend
     npm install -f --no-optional --global webpack webpack-cli
-    npm install -f --no-optional
+    npm install -f
```
Comment (hainenber) [inline docker/docker-frontend.sh:29]: @mistercrunch I saw this flag was added previously but unsure the context. I believe there's a historical reason for it? 👀

**Comment by hainenber** [comment]
@eschutho I'm not able to reproduce your CI issue as this PR's `frontend-build` has installed FE dependencies with success 👀 

https://github.com/apache/superset/actions/runs/10120546422/job/27990411018?pr=29725

File: docker/docker-frontend.sh (hunk 1 above)
Comment (mistercrunch) [reply docker/docker-frontend.sh:29]: I did some git archeology and it looks like --no-optional goes back to https://github.com/apache/superset/pull/10766 (2020) and there's not a clear explanation. I vote going vanilla and doing a very simple `npm install` instead of those 2 lines. Webpack packages should install as its just a `devDependencies`, and they'll install normally as long as we don't specify --production, which we don't want to do here.

Comment (mistercrunch) [reply docker/docker-frontend.sh:29]: tagging @eschutho as I believe she ran in an issue similar to the one you're fixing here.

Comment (rusackas) [reply docker/docker-frontend.sh:29]: Hmm... looks like @craig-rueda added that [a looooong time ago](https://github.com/apache/superset/commit/45f4c689a2ae1e56666c36340c4b27f9f05b5903#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R76). I'm not sure if there are any consequences to its removal ¯\\\_(ツ)_/¯

Comment (rusackas) [reply docker/docker-frontend.sh:29]: eek... duplicated effort. That's what I get for revisiting an open tab without refreshing.

Comment (mistercrunch) [reply docker/docker-frontend.sh:29]: @rusackas I really think it's ok to remove this `--no-optional` as it's non-standard and in this context would only apply `BUILD_SUPERSET_FRONTEND_IN_DOCKER" = "true"` which really should align with other build context (if you're running a dev env outside docker for instance).

**Comment by mistercrunch** [comment]
My vote is to replace those two lines with a single, simple `npm install`

**Review by rusackas — APPROVED** [review]

**Comment by mistercrunch** [comment]
The webpack install is not necessary, simplifying further here https://github.com/apache/superset/pull/29779

File: docker/docker-frontend.sh (hunk 1 above)
Comment (eschutho) [reply docker/docker-frontend.sh:29]: This lgtm. I'll remove the pinned optional dependencies in my pr.

**Comment by sadpandajoe** [comment]
@supersetbot unlabel 4.1
