### PR TITLE
fix: auto-complete of tables and names are not working in SQL lab

### LINKED ISSUE #19008: Table name autocomplete broken in SQL Lab
Currently table names are not added to autocomplete in SQL Lab

#### How to reproduce the bug

1. Go to SQL Lab
2. Choose the Examples database and related schema (Pubic for Postgres)
3. Check a name of a table ("Flights" should be present)
4. Type "select * from Fli" in the Editor and notice that "Flights" doesn't appear in the dropdown

### Expected results

All table names should be added to the autocomplete dropdown

### Actual results

No tables are visible in the autocomplete dropdown

#### Screenshots

In the database, we see that the table "Flights" is present:
image

 However, the table isn't available in the autocomplete dropdown:
image

### Environment

(please complete the following information):

- browser type and version:
- superset version: master
- python version: Python 3.8
- node.js version: Node 16
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by diegomedina248**
### SUMMARY
Currently table names are not added to autocomplete in SQL Lab

When the schema is selected, then a query is made to fetch the tables for the database/schema combination.
Those options were not properly propagated and stored in the reducer, thus the tables never appeared.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:

https://user-images.githubusercontent.com/17252075/158382853-7bb64c55-a70d-484b-a3af-7e6a1c54bcc3.mov

After:

https://user-images.githubusercontent.com/17252075/158382643-dfabf74f-974f-4189-b31d-6b370cbb2e59.mov

### TESTING INSTRUCTIONS
1. Go to SQL Lab
2. Choose the Examples database and related schema (Pubic for Postgres)
3. Check a name of a table ("Flights" should be present)
4. Type "select * from Fli" in the Editor and notice that "Flights" doesn't appear in the dropdown

### ADDITIONAL INFORMATION
Fixes https://github.com/apache/superset/issues/19008

- [x] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/components/TableSelector/index.tsx [hunk 1]
```diff
@@ -208,15 +208,14 @@ const TableSelector: FunctionComponent<TableSelectorProps> = ({
...
-          }
+
+          onTablesLoad?.(json.options);
           setTableOptions(options);
           setCurrentTable(currentTable);
           setLoadingTables(false);
           if (forceRefresh) addSuccessToast('List updated');
         })
-        .catch(e => {
+        .catch(() => {
```
Comment (rusackas) [inline superset-frontend/src/components/TableSelector/index.tsx:218]: Thanks for the extra cleanup along the way!

**Review by rusackas — APPROVED** [review]
Looks (and works) great! Thank you!

**Comment by sadpandajoe** [comment]
🏷️  preset:2022.11
