### PR TITLE
fix(explore): Fix column number calculation

### LINKED ISSUE #14605: [cosmetic] deck.gl scatterplot explore panel have some elements overlap
## Screenshot

Screen Shot 2021-05-12 at 3 59 55 PM

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
Fixes #14605 

It decreases the min-width of a Select which is necessary when 3 or more columns are present. It also excludes the `ColorMapControl` from the column number calculation as its content is `null` / invisible to the end-user.

### BEFORE
Screen Shot 2021-05-17 at 18 07 22

### AFTER
Screen Shot 2021-05-17 at 18 01 56

### TEST PLAN
1. Open a deck.gl Scatterplot
2. Make sure that elements are not overlapping in the Point Color config

### ADDITIONAL INFORMATION

- [x] Has associated issue: #14605 
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/explore/components/ControlRow.tsx [hunk 1]
```diff
@@ -16,17 +16,19 @@
...
-  controls: ExpandedControlItem[];
-}) {
-  const colSize = NUM_COLUMNS / controls.length;
+type Control = React.ReactElement | null;
+
+export default function ControlRow({ controls }: { controls: Control[] }) {
+  // ColorMapControl renders null and should not be counted
+  // in the columns number
+  const countableControls = controls.filter(
+    control => !['ColorMapControl'].includes(control?.props.type),
```
Comment (geido) [inline superset-frontend/src/explore/components/ControlRow.tsx:29]: Specific check required as this needs to be rendered but the component itself is null (within)/invisible to the end-user.

**Comment by geido** [comment]
@junlincc @rusackas

**Review by rusackas — APPROVED** [review]
LGTM
