### PR TITLE
Filter add/remove fix

### LINKED ISSUE #764: removing / adding a filter creates wrong query
With caravel 0.10.0 I create a new slice for sql alchemy table with two filters. I run the query and i have three of them in the uri, the first one *flt_col_0* is spurious but does not create problems:

```
&flt_col_0=casa_editrice&flt_op_0=in&flt_eq_0=&flt_col_1=metrica&flt_op_1=in&flt_eq_1=consegna&flt_col_2=tipologia_utente&flt_op_2=in&flt_eq_2=studente
```

Then i remove the first filter and add it again as a new one:

```
&flt_col_0=casa_editrice&flt_op_0=in&flt_eq_0=&flt_col_2=metrica&flt_op_2=in&flt_eq_2=consegna&flt_col_2=tipologia_utente&flt_op_2=in&flt_eq_2=studente
```

And the new one has the same name *flt_col_2* of the old one  so my query filters only for the first column.

### PR DESCRIPTION
**Pull request by georgeke**
Currently we only 'fix' the ids for newly added filters. Instead, it should be for all filters that have been added. 

This fixes https://github.com/airbnb/caravel/issues/764

### CODE REVIEW

File: caravel/assets/javascripts/explore/explore.jsx [hunk 1]
```diff
@@ -40,7 +40,7 @@ function prepForm() {
 
     ["col", "op", "eq"].forEach(function (fieldMiddle) {
       var fieldName = fieldPrefix + "_" + fieldMiddle;
-      $filter.find("#" + fieldName + "_0")
+      $filter.find("[id^='" + fieldName + "_']")
```
Comment (ascott) [inline caravel/assets/javascripts/explore/explore.jsx]: single quotes are optional here

**Comment by ascott** [comment]
lgtm
