### PR TITLE
fix(dashboard): fix dataset search in filter config modal

### LINKED ISSUE #35674: [6.0.0rc2] When editing a filter and selecting a dataset, frontend filter does not take effect
### Bug description

When editing a filter and selecting a dataset, the frontend filter does not take effect, but the interface is returned correctly and the frontend is not rendered correctly.

### Screenshots/recordings

Image

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by rebenitez1802**
### SUMMARY

 Fixes dataset dropdown search in the native filter configuration modal. Search was not working because the component was filtering on a React component instead of plain text.

  Added `customLabel` field with the table name and configured `optionFilterProps` to enable client-side filtering, matching the pattern used in ChartCreation.

### TESTING INSTRUCTIONS

1. Open any dashboard in edit mode
2. Click "Add/Edit Filters"
3. Click "Add Filter" or edit existing filter
4. Click on the Dataset dropdown
5. Type a dataset name (e.g., "wb_")
6. Verify the dropdown filters results correctly

### ADDITIONAL INFORMATION

- [X] Has associated issue: Fixes #35674
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/components/nativeFilters/FiltersConfigModal/FiltersConfigForm/DatasetSelect.tsx [hunk 1]
```diff
@@ -68,9 +68,11 @@ const DatasetSelect = ({ onChange, value }: DatasetSelectProps) => {
         const list: {
           label: string | ReactNode;
           value: string | number;
+          customLabel: string;
         }[] = response.json.result.map((item: Dataset) => ({
           label: DatasetSelectLabel(item),
           value: item.id,
+          customLabel: item.table_name,
```
Comment (michael-s-molina) [inline superset-frontend/src/dashboard/components/nativeFilters/FiltersConfigModal/FiltersConfigForm/DatasetSelect.tsx]: @msyavuz @rebenitez1802 Previously, you could load the Select options with [label and customLabel](https://github.com/apache/superset/blob/49df35d01298c997b79a3369d754815dc25a2742/superset-frontend/src/components/Select/utils.tsx#L210). `label` was used to searching and `customLabel` to rendering the option using a React component. There were multiple places using the `customLabel` logic. We need to check if the Ant Design migration broke this logic.

Comment (michael-s-molina) [reply superset-frontend/src/dashboard/components/nativeFilters/FiltersConfigModal/FiltersConfigForm/DatasetSelect.tsx]: This PR is actually inverting the previous logic.

Comment (rebenitez1802) [reply superset-frontend/src/dashboard/components/nativeFilters/FiltersConfigModal/FiltersConfigForm/DatasetSelect.tsx]: Thanks for the comment, I removed customLabel and also fixed the same on Chart creation that was also using customLabel pattern.

**Review by betodealmeida — APPROVED** [review]
