### PR TITLE
[bugfix] Fix color scheme picker

### LINKED ISSUE #5889: Empty "Color Scheme" dropdown
@kristw is this related to your recent work on colors? https://github.com/apache/incubator-superset/pull/5815

screen shot 2018-09-13 at 12 11 00 pm

### PR DESCRIPTION
**Pull request by kristw**
Support dynamic choices by passing function instead of value to fix #5889 
This will ensure that the `ColorSchemeControl` will always get the latest schemes registered to `ColorSchemeManager`

@mistercrunch @williaster @graceguo-supercat

### CODE REVIEW

File: superset/assets/src/explore/components/controls/ColorSchemeControl.jsx [hunk 1]
```diff
@@ -41,9 +47,9 @@ export default class ColorSchemeControl extends React.PureComponent {
   }
 
   renderOption(key) {
-    const currentScheme = key.value ?
-      this.props.schemes[key.value] :
-      this.props.schemes[defaultProps.value];
+    const { schemes } = this.props;
+    const schemeLookup = _.isFunction(schemes) ? schemes() : schemes;
+    const currentScheme = schemeLookup[key.value || defaultProps];
```
Comment (williaster) [inline superset/assets/src/explore/components/controls/ColorSchemeControl.jsx]: should this be `defaultProps.value`?

**Review by williaster — APPROVED** [review]
LGTM after resolving the `defaultProps` vs `defaultProps.value` question.

**Comment by kristw** [comment]
Nice catch. Thanks @williaster .
