### PR TITLE
fix: Remove export CSV in old filter box

### LINKED ISSUE #14189: AttributeError: 'NoneType' object has no attribute 'index' - Export CSV on filter box
An error happens when trying to export a filter box to CSV.

### Expected results

My opinion would be to discard the Export CSV button for filter BOX since, it has never worked and no one seems to have ever required it.

### Actual results

An html page with an error message when clicking on the Export CSV button

#### Screenshots

Capture d’écran 2021-04-16 à 11 07 55

#### How to reproduce the bug

1. Click on the Export CSV button of a filter box

Capture d’écran 2021-04-16 à 11 12 44

2. See error

Capture d’écran 2021-04-16 à 11 07 55

### Environment

- docker image : `apache/superset:1.0.1`
- superset version: `1.0.1`
- python version: `3.7`
- node.js version: `unknown`

### Checklist

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
```
Traceback (most recent call last):
  File "/app/superset/views/base.py", line 181, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 164, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/utils/cache.py", line 152, in wrapper
    return f(*args, **kwargs)
  File "/app/superset/views/utils.py", line 451, in wrapper
    return f(*args, **kwargs)
  File "/app/superset/views/core.py", line 618, in explore_json
    return self.generate_json(viz_obj, response_type)
  File "/app/superset/views/core.py", line 440, in generate_json
    viz_obj.get_csv(),
  File "/app/superset/viz.py", line 622, in get_csv
    include_index = not isinstance(df.index, pd.RangeIndex)
AttributeError: 'NoneType' object has no attribute 'index'
```
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.
An existing issue which has been closed due to inactivity : #7734 

### Additional context

RAS

### PR DESCRIPTION
**Pull request by duynguyenhoang**
### SUMMARY
There is no reason to export Filter box to CSV, we should remove Export CSV link as well as Export Full CSV link in filter box.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before
image

After
image

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #14189
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by villebro — APPROVED** [review]
LGTM, thanks for the fix!

File: superset-frontend/src/dashboard/components/SliceHeaderControls/index.tsx [hunk 1]
```diff
@@ -328,16 +328,20 @@ class SliceHeaderControls extends React.PureComponent<
           {t('Download as image')}
         </Menu.Item>
 
-        {this.props.supersetCanCSV && (
-          <Menu.Item key={MENU_KEYS.EXPORT_CSV}>{t('Export CSV')}</Menu.Item>
-        )}
-        {isFeatureEnabled(FeatureFlag.ALLOW_FULL_CSV_EXPORT) &&
+        {this.props.slice.viz_type !== 'filter_box' &&
```
Comment (villebro) [inline superset-frontend/src/dashboard/components/SliceHeaderControls/index.tsx:331]: Future improvement idea: maybe we should have a property `enableExportCSV` on `ChartMetadata` which defaults to `true`
