### PR TITLE
fix(dashboard): Show the filters popover behind the dashboard header when scrolling

### LINKED ISSUE #15873: [dashboard][native-filter]Filter indicator overlay in Dashboard on scroll
## Screenshot

Screen Shot 2021-07-23 at 11 06 09 AM

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
This PR fixes the z-index of the dashboard header to make sure that the Filters Popover does not show over the Dashboard header.

Fixes: #15873

### BEFORE
Screen Shot 2021-07-23 at 11 06 09 AM

Screen Shot 2021-07-28 at 23 18 47

### AFTER

https://user-images.githubusercontent.com/60598000/127392326-1514fc13-2b79-4632-83d6-6833ffbac9e6.mp4

### TESTING INSTRUCTIONS
1. Open a dashboard
2. Open the filters of a chart
3. Scroll down
4. Make sure the filters popover does not appear over the dashboard header

### ADDITIONAL INFORMATION

- [x] Has associated issue: #15873
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@rosemarie-chiu @jinghua-qa

**Comment by rusackas** [comment]
Works for the second issue depicted in the topic as well:
image

File: superset-frontend/src/dashboard/components/DashboardBuilder/DashboardBuilder.tsx [hunk 1]
```diff
@@ -283,6 +285,13 @@ const DashboardBuilder: FC<DashboardBuilderProps> = () => {
         </DragDroppable>
       </StyledHeader>
       <StyledContent fullSizeChartId={fullSizeChartId}>
+        <Global
+          styles={css`
```
Comment (rusackas) [inline superset-frontend/src/dashboard/components/DashboardBuilder/DashboardBuilder.tsx:289]: I wonder if `styles` is any more performant than `css` or if we should just make this `css` for future consistency/themability. ¯\\\_(ツ)_/¯

**Review by rusackas — APPROVED** [review]
One little nit, but not a blocker. 

Really appreciate the inline comments for the rationale about the z-index values, btw. Seeing more need every day to add a z-index registry (a bunch of defined "layers") to the Theme.

**Comment by geido** [comment]
I will appreciate an eye from @michael-s-molina as well on this as he worked on similar issues in the past

**Review by michael-s-molina — APPROVED** [review]
LGTM. I did some tests with the native filters enabled and it's working as intended.

**Review by rosemarie-chiu — APPROVED** [review]
LGTM on UI
