### PR TITLE
fix(filter-box): don't add empty filter to filtersChoices

### LINKED ISSUE #10672: Filter Box UI regression after upgrading to 0.37.0
I upgraded superset from 0.35.2 to 0.37.0. After the upgrade, I am noticing a regression in the UI for multi-select FilterBox. After selecting and removing a value, an additional Null item seems to get added to the list. 

### Expected results

The filter list should not contain invalid values

### Actual results

The filter list contains an additional `NULL` value

#### Screenshots

Default
Select Any Value
Deselect
Select Null

Selecting the invalid value sends requests with null as the selected value. 

`    "extra_filters": [
        {
            "col": "region",
            "op": "in",
            "val": [
                null
            ]
        }
    ] `

#### How to reproduce the bug

I am able to reproduce consistently on any dashboard with multi select filters. Please refer to screen shots based on the sample dashboards as an example.

### Environment

(please complete the following information):

- superset version: 0.37.0
- python version:  3.6.12
- node.js version: `node -v` 
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by villebro**
### SUMMARY
When a FilterBox is cleared out, a null filter is added to the list of filter choices. This ensures that null valued selections are not added to `filtersChoices`. I think this regression was caused by #10210

### SCREENSHOTS
See linked issue for steps to reproduce.

### TEST PLAN
CI + new test

### ADDITIONAL INFORMATION

- [x] Has associated issue: Closes #10672
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by graceguo-supercat — APPROVED** [review]
LGTM

**Comment by graceguo-supercat** [comment]
thanks for the fix!

**Comment by willbarrett** [comment]
Can we add a test?

File: superset-frontend/spec/javascripts/explore/components/FilterBox_spec.jsx [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+            metric: 'sum__COUNT',
+            multiple: true,
+          },
+        ]}
+        origSelectedValues={{}}
+      />,
+    );
+    const inst = wrapper.instance();
+    inst.setState({ selectedValues: { name: null } });
+    expect(inst.props.filtersChoices.name.length).toEqual(2);
```
Comment (villebro) [inline superset-frontend/spec/javascripts/explore/components/FilterBox_spec.jsx:52]: without the fix, this would have failed with `inst.props.filtersChoices.name.length === 3`
