### PR TITLE
fix(explore): drag & drop column select component triggering onChange unnecessarily

### LINKED ISSUE #16016: [drag & drop][Calendar Heatmap]Example chart 'Calendar Heatmap' is not shown automatically with d&d on
Example chart 'Calendar Heatmap' is not shown automatically with d&d on , user need to click 'Run' to show the example chart. When d&d is off, this example chart show automatically after open in explore.

### Expected results

Example chart 'Calendar Heatmap' show in explore

### Actual results

Example chart 'Calendar Heatmap' did show in explore, user need to click 'Run' to show

#### Screenshots

https://user-images.githubusercontent.com/81597121/127823568-44d0af0c-0b2d-47d5-9f2d-288620c02ac6.mov

#### How to reproduce the bug

1. Go to chart list
2. Select example chart 'Calendar Heatmap' show in explore
3. See error

### Environment

(please complete the following information):

- superset version: `latest master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by suddjian**
### SUMMARY

Fixes #16016

The example had a value for the `granularity_sqla` field that was not found in the dataset. When that happens, the mechanism that is meant to detect changes in dataset thinks that there has been a change. The fix for this is to only begin checking for dataset changes after the first render.

### AFTER

Chart appears as normal rather than requiring user to click Run.

Screen Shot 2021-08-04 at 1 48 46 PM

### TESTING INSTRUCTIONS

Open the Calendar Heatmap example chart.

### ADDITIONAL INFORMATION

- [x] Has associated issue: #16016
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/explore/components/controls/DndColumnSelectControl/DndColumnSelect.tsx [hunk 1]
```diff
@@ -65,8 +66,13 @@ export const DndColumnSelect = (props: LabelProps) => {
     ) {
       onChange(optionSelectorValues);
     }
-    // eslint-disable-next-line react-hooks/exhaustive-deps
-  }, [JSON.stringify(value), JSON.stringify(optionSelector.getValues())]);
+    // when options change, that means that the dataset has changed
+    // so we have to check if values are still applicable.
+  }, [options, value, optionSelector]);
```
Comment (kgabryje) [inline superset-frontend/src/explore/components/controls/DndColumnSelectControl/DndColumnSelect.tsx:71]: If options change, we'll get a new instance of optionSelector, so I don't think we need to include it in dependency array here

**Review by kgabryje — APPROVED** [review]
1 small nit, other than that LGTM

**Review by geido — APPROVED** [review]
LGTM!

**Comment by junlincc** [comment]
seeing a missing chart in the slack dashboard.  i dont think it's related, but it's probably a good idea to double check? 
Screen Shot 2021-08-05 at 10 45 10 AM

File: superset-frontend/src/explore/components/controls/DndColumnSelectControl/DndColumnSelect.tsx (hunk 1 above)
Comment (suddjian) [reply superset-frontend/src/explore/components/controls/DndColumnSelectControl/DndColumnSelect.tsx:71]: That's true but I felt like appeasing the linter

**Comment by suddjian** [comment]
missing image is unrelated, that's cdn.brandfolder.com's problem

**Comment by rosemarie-chiu** [comment]
🏷 2021.31
