### PR TITLE
fix(dashboard): show correct roles for dashboard access dropdown

### LINKED ISSUE #21538: Unable to see roles in drop down in edit dashboard
We have defined  few roles as per department but we can't see list of roles in the dropdown after superset upgrade to 2.0
super_set_roles

### PR DESCRIPTION
**Pull request by mayurnewase**
### SUMMARY

Fixes: #21538 
regression from https://github.com/apache/superset/pull/20837

### TESTING INSTRUCTIONS

Enable `DASHBOARD_RBAC` feature flag
Add 1 role
Add 1 active and 1 inactive user
Create 1 dashboard
Click on edit dashboard from actions
Check owners dropdown shows only active users
Check roles dropdown shows all roles available

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/21538
- [x] Required feature flags: DASHBOARD_RBAC
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/components/PropertiesModal/index.tsx [hunk 1]
```diff
@@ -123,23 +123,35 @@ const PropertiesModal = ({
...
       const query = rison.encode({
         filter: input,
         page,
         page_size: pageSize,
       });
       return SupersetClient.get({
         endpoint: `/api/v1/dashboard/related/${accessType}?q=${query}`,
-      }).then(response => ({
-        data: response.json.result
-          .filter((item: { extra: { active: boolean } }) => item.extra.active)
```
Comment (zephyring) [inline superset-frontend/src/dashboard/components/PropertiesModal/index.tsx:136]: maybe we can check if item.extra.active attribute is there and if yes then leverage that otherwise not

Comment (mayurnewase) [reply superset-frontend/src/dashboard/components/PropertiesModal/index.tsx:136]: sure, ok.
will update it in a bit.

**Comment by mayurnewase** [comment]
DO NOT MERGE YET, ADDING FEW TESTS.

**Review by zephyring — APPROVED** [review]

**Comment by michael-s-molina** [comment]
@mayurnewase @zephyring https://github.com/apache/superset/pull/20837 also modified the owners in `src/components/Datasource/DatasourceEditor`. Shouldn't the same fix be applied there?

**Comment by mayurnewase** [comment]
@michael-s-molina datasource editor only has owner selection, so it correctly filters only active users.
I don't think we need any change there.

**Review by michael-s-molina — APPROVED** [review]
LGTM

**Comment by mayurnewase** [comment]
thanks.
