### PR TITLE
fix: datasource modal doesn't save schema 

### LINKED ISSUE #11380: Datasource edit doesn't save schema, only saves new dataset name
On chart explore, when you click on change dataset, and try to edit the datasource (table) name, the table name change works as expected but unless you edit schema, the existing schema doesn't get saved causing the chart to break.

### Expected results

Both schema and table name should change.

### Actual results

Only table name changes.

#### Screenshots

Step 1: my table name (before change)
Screen Shot 2020-10-21 at 6 38 34 PM

Step 2: try to edit table name, schema is same - do not edit schema
Screen Shot 2020-10-21 at 6 37 46 PM

Step 3: This is the result: New table name is displayed with NO SCHEMA. if you run chart, it breaks.
Screen Shot 2020-10-21 at 6 37 53 PM

#### How to reproduce the bug

1. Go to 'Chart Explore'
2. Click on 'Change Dataset'
3. Enter new table name, keep same schema
4. Click on Save
5. See issue

### Environment

(please complete the following information):

- superset version: master
### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by lilykuang**
### SUMMARY

- quick fix datasource editor doesn't save schema on chart explore

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

After:
https://www.loom.com/share/b7876f4c526442378e4cfed81d110c47
### ADDITIONAL INFORMATION

- [x] Has associated issue: #11380
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/datasource/DatasourceModal.tsx [hunk 1]
```diff
@@ -88,9 +88,9 @@ const DatasourceModal: FunctionComponent<DatasourceModalProps> = ({
   const onConfirmSave = () => {
     // Pull out extra fields into the extra object
     const schema =
-      currentDatasource.schema ||
+      currentDatasource.tableSelector?.schema ||
       currentDatasource.databaseSelector?.schema ||
-      currentDatasource.tableSelector?.schema;
+      currentDatasource.schema;
```
Comment (lilykuang) [inline superset-frontend/src/datasource/DatasourceModal.tsx:94]: this is a quick fix, there is probably a better way to do this.

**Review by nytai — APPROVED** [review]
LGTM as a quick fix

**Review by riahk — APPROVED** [review]
