### PR TITLE
fix(dashboard): Remove edit from url params when discarding changes

### LINKED ISSUE #15673: [dashboard] can not discard changes in a empty dashboard
After create a new dashboard through through global + button or +dashboard button, click on 'DISCARD CHANGE' has no effect

### Expected results

click on 'DISCARD CHANGE' will bring user out of dashboard edit mode

### Actual results

click on 'DISCARD CHANGE' has no effect, user still at dashboard edit mode

#### Screenshots

https://user-images.githubusercontent.com/81597121/125559236-ebb18f6a-851f-4206-a88c-fde7ab410335.mov

#### How to reproduce the bug

1. Click on global + button and create new dashboard or click on +dashboard in dashboard page
2. Do not add anything to the new dashboard and click on 'DISCARD CHANGE' in dashboard edit mode
3.See error

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
It removes the `edit` param from the URL when discarding the changes of a newly created dashboard in order to exit the edit mode.

Fixes #15673 

### BEFORE

https://user-images.githubusercontent.com/60598000/125814297-5638f4ee-b2a7-4550-8c93-b8652bb2be9d.mov

### AFTER

https://user-images.githubusercontent.com/60598000/125814640-e1812885-3988-4ff2-b720-854dcea460af.mp4

### TESTING INSTRUCTIONS
1. Click on the global + button and create a new dashboard or click on the + dashboard from dashboard page list
2. Do not add anything to the new dashboard and click on 'DISCARD CHANGE' in dashboard edit mode
3. Observe the behavior

### ADDITIONAL INFORMATION

- [x] Has associated issue: #15673 
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@jinghua-qa @junlincc

File: superset-frontend/src/dashboard/components/Header/index.jsx [hunk 1]
```diff
@@ -129,7 +129,10 @@ const StyledDashboardHeader = styled.div`
 
 class Header extends React.PureComponent {
   static discardChanges() {
-    window.location.reload();
+    const url = new URL(window.location.href);
+
+    url.searchParams.delete('edit');
+    window.location.replace(url);
```
Comment (suddjian) [inline superset-frontend/src/dashboard/components/Header/index.jsx:135]: We should use react router for this instead, if possible.

Comment (geido) [reply superset-frontend/src/dashboard/components/Header/index.jsx:135]: I agree. However, the original implementation used window reload for simplicity, otherwise we would need to implement a method to remove ptogrammatically any component that was added to the dashboard and that wasn't saved yet. As this is a P1 bug, I think we should fix the original problem first and consider making a better implementation in a later stage.

Comment (rusackas) [reply superset-frontend/src/dashboard/components/Header/index.jsx:135]: I'm also curious if there might be any expectation for the back button to work. If so, it might be worth trying `window.location.assign(url)` or `window.location = url` or `window.location.href = url` (which all do the same thing)

Comment (geido) [reply superset-frontend/src/dashboard/components/Header/index.jsx]: @rusackas Changing to `assign` allows to go back to the edit mode indeed which is what you are looking for, I guess. If the expectation is to undo the "discard changes" action instead, the back button won't be able to achieve that. Every component added and then discarded will be gone when going back.

**Review by suddjian — APPROVED** [review]

**Review by pkdotson — APPROVED** [review]
LGTM!

**Review by rosemarie-chiu — APPROVED** [review]
LGTM!
CleanShot 2021-07-22 at 11 59 21
