### PR TITLE
fix(theming): Theming visual fixes

### LINKED ISSUE #34260: Dark Mode: Text formatting and Visibility Issue in UI
## Screenshot

Markdown Element:
Image

In Edit Mode:
Image

In Chart Creation:
Light Mode:
Image

Dark Mode:
Image

## Description
In Dark Mode, the when the background changes correspondingly the text color doesn't change.

### PR DESCRIPTION
**Pull request by msyavuz**
### SUMMARY

Fixes for various theming visuals

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

1. Filters overlapping with action buttons:
Before:
image
After:
image

2. UploadDataModal fixes to titles, collapse sizes and remove metadata
Before:
image

After:
image

3. Secondary buttons contrast
Before:
image

After:
image

4. Delete modal spacing
Before:
image
After:
image

5. Async Ace Editor
Before:
image

After:
image

6. Explore columns and metrics
Before:

image

After:
image

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #34260 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/components/nativeFilters/FilterBar/ActionButtons/index.tsx [hunk 1]
```diff
@@ -75,13 +74,9 @@ const verticalStyle = (theme: SupersetTheme, width: number) => css`
 
   background: linear-gradient(
     ${rgba(theme.colors.grayscale.light5, 0)},
-    ${theme.colors.grayscale.light5} 60%
+    ${theme.colors.grayscale.light5} 20%
```
Comment (mistercrunch) [inline superset-frontend/src/dashboard/components/nativeFilters/FilterBar/ActionButtons/index.tsx]: let's use one of the `colorBg.*` for this. Guessing `colorBgLayout` or `colorBgContainer` (?)

Comment (mistercrunch) [reply superset-frontend/src/dashboard/components/nativeFilters/FilterBar/ActionButtons/index.tsx]: we still have the task to deprecate all `theme.colors.*` in the repo ...

Comment (msyavuz) [reply superset-frontend/src/dashboard/components/nativeFilters/FilterBar/ActionButtons/index.tsx]: Right, this file has some more of those. I might as well touch them while at it. Done!

File: superset-frontend/packages/superset-ui-core/src/components/Button/index.tsx [hunk 2]
```diff
@@ -134,6 +133,11 @@ export function Button(props: ButtonProps) {
         '& > span > :first-of-type': {
           marginRight: firstChildMargin,
         },
+        ':not(:hover)': effectiveButtonStyle === 'secondary' && {
+          // Increase contrast for secondary buttons
+          backgroundColor: `${tinycolor(theme.colorPrimaryBg).darken(2).toHexString()} !important`,
```
Comment (mistercrunch) [inline superset-frontend/packages/superset-ui-core/src/components/Button/index.tsx]: ideally here we use `colorPrimary.*` instead of darken/lighten

Comment (mistercrunch) [reply superset-frontend/packages/superset-ui-core/src/components/Button/index.tsx]: can we use these?

Image

**Review by mistercrunch — APPROVED** [review]
Minor comment on leveraging `colorPrimary.*` tokens instead of lighten/darken, but approving regadless. Please use the right tokens if they exist or the best one as proxy if they don't

File: superset-frontend/packages/superset-ui-core/src/components/Button/index.tsx (hunk 2 above)
Comment (msyavuz) [reply superset-frontend/packages/superset-ui-core/src/components/Button/index.tsx]: I looked into this but using colorPrimaryHover or Border for the background of secondary button seemed off semantically. ~Do you think it's better than using lighten/darken?~ Nevermind saw the comment below

Comment (mistercrunch) [reply superset-frontend/packages/superset-ui-core/src/components/Button/index.tsx]: feel free to move forward with this, could extend the framework with extra semantics for `color.*Bg{something}` if there's a clear need for more semantics ....

**Comment by mistercrunch** [comment]
One option would be to add a TODO or NOTE of some kind when we abuse the semantics for a particular shade by using a proxy.

**Comment by msyavuz** [comment]
What i am finding out now is that we don't really have a good option when it comes to contrast for secondary button:

image

I went with the lightest and darkest here, which is slightly better than what we had before. I think we might need to extend the framework for buttons specifically since we are customizing it so much to our needs. Altering the algorithm for our default themes also should work.

**Comment by mistercrunch** [comment]
> I think we might need to extend the framework for buttons specifically since we are customizing it so much to our needs.

Curious what semantic you would introduce? something like `colorPrimaryBgSecondary`? Noting that it might be a bit of a mess since the `darkAlgorithm` is what generates a lot of the shading with builtin logic. Might be better to establish design constraints, telling @kasiazjc she has to work with the shades/tokens in the framework (?)

**Comment by msyavuz** [comment]
If we need a secondary button we can introduce seed tokens for it and extend the algorithm to produce necessary map tokens (in the default themes). `colorSecondary` `colorSecondaryBg` etc. It will mean diversion from Antd but we already do that. 

Also since user's will use Ant Design's theme editor to customize their theme, none of the options seem good enough:

1. Introduce `colorSecondary` as a seed token: Doesn't exist on the theme editor
2. Use semantically incorrect tokens: Unexpected colors that doesn't reflect in theme editor.
3. Lighten/Darken: Same thing as the first one but smaller impact.

So yes, design constraints seem like the easier/most straightforward option out of these
