### PR TITLE
fix(handlebars): remove serverPaginationControlSetRow from control pa…

### LINKED ISSUE #29657: Handlebars chart - pagination support
### Bug description

When enabling "SERVER PAGINATION" option in Handlebars chart, these is no impact on the chart generated.

Expected result: Pagination list and "show entries" option menu, same as for Table chart.

Each time we click on different page, I would expect to viewer re-render with updated 'data' variable.

### How to reproduce the bug

Any dataset with more than 10 rows is not properly paginated in Handlebars chart

### Screenshots/recordings

_No response_

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by LisaHusband**
### SUMMARY
fix(handlebars): remove serverPaginationControlSetRow from control panel config

This PR removes the `serverPaginationControlSetRow` from the Handlebars chart control panel configuration to fix pagination UI issues when "SERVER PAGINATION" option is enabled but has no effect.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:
图片
After:
图片

### TESTING INSTRUCTIONS
1. Run Superset and open a Handlebars chart with a dataset exceeding 10 rows.
2. Verify that the pagination controls related to server pagination do not appear.
3. Confirm the chart data renders correctly without pagination UI interference.

### ADDITIONAL INFORMATION
- [x] Has associated issue: Fixes #29657  
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by LisaHusband** [comment]
Hi @msyavuz 
I’ve made the changes as you suggested — removed serverPaginationControlSetRow and its references from plugin-chart-handlebars. Tested it locally and submitted a fresh PR. Thanks a lot for your helpful feedback!

File: superset-frontend/plugins/plugin-chart-handlebars/src/plugin/controlPanel.tsx [hunk 1]
```diff
@@ -57,7 +54,7 @@ const config: ControlPanelConfig = {
         [percentMetricsControlSetItem],
         [timeSeriesLimitMetricControlSetItem, orderByControlSetItem],
         [orderDescendingControlSetItem],
-        serverPaginationControlSetRow,
+        // serverPaginationControlSetRow,
```
Comment (msyavuz) [inline superset-frontend/plugins/plugin-chart-handlebars/src/plugin/controlPanel.tsx]:
```suggestion
```

File: superset-frontend/plugins/plugin-chart-handlebars/src/plugin/controlPanel.tsx [hunk 2]
```diff
@@ -38,10 +38,7 @@ import {
   orderByControlSetItem,
   orderDescendingControlSetItem,
 } from './controls/orderBy';
-import {
-  serverPageLengthControlSetItem,
-  serverPaginationControlSetRow,
-} from './controls/pagination';
+import { serverPageLengthControlSetItem } from './controls/pagination';
```
Comment (msyavuz) [inline superset-frontend/plugins/plugin-chart-handlebars/src/plugin/controlPanel.tsx]: I believe this can be removed as well as the file containing these functions:
`plugins/plugin-chart-handlebars/src/plugin/controls/pagination.tsx`

**Review by msyavuz — COMMENTED** [review]
Thanks a lot for the pr! I think we can merge this after cleanup. Feel free to continue work on this pr though, you don't need to close this and open another one.

File: superset-frontend/plugins/plugin-chart-handlebars/src/plugin/controlPanel.tsx (hunk 2 above)
Comment (LisaHusband) [reply superset-frontend/plugins/plugin-chart-handlebars/src/plugin/controlPanel.tsx]: Thank you for the feedback!
I’ll keep working on this PR and update it accordingly.By the way, the previous PR was automatically closed because both the main branch and my branch had changes that were not merged yet. Regarding the removal of the API implementation, I wonder if this API might still be needed or implemented by someone else in the future. So for now, should we keep its implementation temporarily?

Comment (msyavuz) [reply superset-frontend/plugins/plugin-chart-handlebars/src/plugin/controlPanel.tsx]: I don't think it's necessary to keep this just for documentation. There is always these pr's to reference if we need to implement it again. Also github will close pr's if you reverted the changes in the pr. Nothing to pull 😄

Comment (LisaHusband) [reply superset-frontend/plugins/plugin-chart-handlebars/src/plugin/controlPanel.tsx]: ok, i will delete it ,soon

Comment (LisaHusband) [reply superset-frontend/plugins/plugin-chart-handlebars/src/plugin/controlPanel.tsx]: > I don't think it's necessary to keep this just for documentation. There is always these pr's to reference if we need to implement it again. Also github will close pr's if you reverted the changes in the pr. Nothing to pull 😄

Oh, I see! No wonder my PRs keep getting mysteriously closed 😄

**Review by msyavuz — APPROVED** [review]
