### PR TITLE
fix: pie chart orientation description error

### LINKED ISSUE #21513: bug: chart-plugin-echarts does not show Orientation description correctly
When enable `Show legend` in pie chart, The description of Orientation is shown the same as `Legend type`

#### How to reproduce the bug

1. Create a pie chart
2. Go to `CUSTOMIZE`
3. Click Orientation's description

### Expected results
Show correct description

### Actual results
Orientation show `Legend type` description

#### Why this happends
Someone may copy and paste code but forgot to correct the description 

图片

#### Screenshots
图片

### Environment

- browser type and version: firefox
- superset version: `2.0.0`
- python version: `3.8.13`
- node.js version: `v16.17.0`
- any feature flags active: no

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

no any other context about the problem

### PR DESCRIPTION
**Pull request by LiuBodong**
Fix orientation description error

fix(charts) pie chart orientation description error

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before
图片

After
图片

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [x] Changes UI

Fixes #21513

### CODE REVIEW

File: superset-frontend/plugins/plugin-chart-echarts/src/controls.tsx [hunk 1]
```diff
@@ -87,7 +87,7 @@ const legendOrientationControl: ControlSetItem = {
     ],
     default: legendOrientation,
     renderTrigger: true,
-    description: t('Legend type'),
+    description: t('Orientation'),
```
Comment (stephenLYZ) [inline superset-frontend/plugins/plugin-chart-echarts/src/controls.tsx:90]: Thanks for the fix! Just one nit:
```suggestion
    description: t('Legend Orientation'),
```

**Review by stephenLYZ — APPROVED** [review]
