### PR TITLE
fix(Filters): Apply native & cross filters on common columns

### LINKED ISSUE #30061: Cross-filtering is reloading unaffected charts
### Bug description

When a user applies a cross-filter, charts that belong to different datasets and are not affected by the cross filter are being reloaded. Each reloaded chart fires a server-side request for data, decreasing the dashboard's performance and wasting resources.

### How to reproduce the bug

1 - Create a dashboard with charts from multiple datasets
2 - Apply a cross filter on a chart
3 - Check that charts that belong to different datasets are reloaded

### Screenshots/recordings

https://github.com/user-attachments/assets/12ec3fac-177c-45c5-97e3-6d0b453a6d51

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

Also present in 4.1.0 RC2

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
When in scope (global or specific) charts that are not applicable to the filter (do not share the same datasource or columns) were being applied anyway, causing unnecessary queries. This PR checks that the charts have columns in common or will exclude the charts.

### AFTER

https://github.com/user-attachments/assets/fe58ccbc-b689-4470-a85d-a8b494e9633c

https://github.com/user-attachments/assets/9a45c284-ac44-4f4e-960b-e66c0c5ed46d

### TESTING INSTRUCTIONS
1. Create a native filter that has no common columns with a chart
2. Add the chart in scope
3. Apply the filter
4. The chart should not reload and emit a query

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/util/getRelatedCharts.ts [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+): number[] {
+  const sourceSlice = slices[filterKey];
+  if (!sourceSlice) return [];
+
+  const sourceDatasource = datasources[sourceSlice.datasource];
+  if (!sourceDatasource) return [];
+
+  return Object.values(slices)
+    .filter(slice => {
+      if (slice.slice_id === Number[filterKey]) return false;
```
Comment (justinpark) [inline superset-frontend/src/dashboard/util/getRelatedCharts.ts:63]: Do you intend to `Number(filterKey)`?

File: superset-frontend/src/dashboard/util/getRelatedCharts.ts [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+            col.column_name === column?.name ||
+            col.column_name === column?.displayName,
+        )
+      );
+    })
+    .map(slice => slice.slice_id);
+}
+function getRelatedChartsForCrossFilter(
+  filterKey: string,
+  slices: Slice[],
```
Comment (justinpark) [inline superset-frontend/src/dashboard/util/getRelatedCharts.ts:52]: It appears slices is a Record not a list.

```suggestion
  slices: Record<string, Slice>,
```

File: superset-frontend/src/dashboard/util/getRelatedCharts.ts [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+          targetColumn => sourceColumn.column_name === targetColumn.column_name,
+        ),
+      );
+    })
+    .map(slice => slice.slice_id);
+}
+
+export function getRelatedCharts(
+  filters: Object,
+  slices: Slice[],
```
Comment (justinpark) [inline superset-frontend/src/dashboard/util/getRelatedCharts.ts:79]:
```suggestion
  slices: Record<string, Slice>,
```

File: superset-frontend/src/dashboard/util/getRelatedCharts.ts [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+function getRelatedChartsForSelectFilter(
+  filter: Filter,
+  slices: Slice[],
+  datasources: DatasourcesState,
+) {
+  return Object.values(slices)
+    .filter(({ datasource }) => {
+      const chartDatasource = datasources[datasource];
+      if (!chartDatasource) return false;
+      const { column, datasetId } = filter.targets[0];
```
Comment (justinpark) [inline superset-frontend/src/dashboard/util/getRelatedCharts.ts:37]: Let's make this safe in case of the empty case.
```suggestion
      const { column, datasetId } = filter.targets[0] ?? {};
```

File: superset-frontend/src/dashboard/util/activeAllDashboardFilters.ts [hunk 5]
```diff
@@ -54,9 +54,13 @@ export const getAllActiveFilters = ({
       chartConfiguration?.[filterId]?.crossFilters?.chartsInScope ??
       allSliceIds ??
       [];
+    const filterType = nativeFilters?.[filterId]?.filterType ?? null;
```
Comment (justinpark) [inline superset-frontend/src/dashboard/util/activeAllDashboardFilters.ts:57]: Do we have a handling for `null` case? Otherwise let's skip
```suggestion
    const filterType = nativeFilters?.[filterId]?.filterType;
```

**Comment by geido** [comment]
Just realized that highlighting a filter that is not applicable should also be added as an enhancement for this PR. Working on that.

File: superset-frontend/src/dashboard/util/getRelatedCharts.ts [hunk 6]
```diff
@@ -0,0 +1,112 @@
+/**
```
Comment (michael-s-molina) [inline superset-frontend/src/dashboard/util/getRelatedCharts.ts:1]: Thanks for creating this file to keep the logic in one place.

File: superset-frontend/src/dashboard/util/getRelatedCharts.ts [hunk 7]
```diff
@@ -0,0 +1,112 @@
...
+  return Object.values(slices)
+    .filter(slice => {
+      if (slice.slice_id === Number(filterKey)) return false;
+      const targetDatasource = datasources[slice.datasource];
+      if (!targetDatasource) return false;
+      if (targetDatasource === sourceDatasource) return true;
+
+      return sourceDatasource.columns.some(sourceColumn =>
+        targetDatasource.columns.some(
+          targetColumn => sourceColumn.column_name === targetColumn.column_name,
```
Comment (michael-s-molina) [inline superset-frontend/src/dashboard/util/getRelatedCharts.ts:70]: We apply cross filters for charts from different datasets but with the same column name? What ensures that the values are the same? For example, I might have `product` defined in different datasets but the values are completely different.

File: superset-frontend/src/dashboard/util/getRelatedCharts.ts [hunk 8]
```diff
@@ -0,0 +1,112 @@
...
+export function getRelatedCharts(
+  filters: Object,
+  slices: Record<string, Slice>,
+  datasources: DatasourcesState,
+) {
+  return Object.entries(filters).reduce((acc, [filterKey, filter]) => {
+    if (filter.filterType === 'filter_select') {
+      return {
+        ...acc,
+        [filterKey]: getRelatedChartsForSelectFilter(
```
Comment (michael-s-molina) [inline superset-frontend/src/dashboard/util/getRelatedCharts.ts:86]: Is the scope not being considered then determining the related charts?

File: superset-frontend/src/dashboard/util/getRelatedCharts.ts (hunk 7 above)
Comment (geido) [reply superset-frontend/src/dashboard/util/getRelatedCharts.ts:70]: The intent of these changes it to limit the number of unnecessary queries we send to the backend for processing. Right now we are sending any query as long as it is in scope. This is trying to prevent some of those. I believe making sure that filters are actually applicable by comparing the underlying data structures is still responsibility of the backend.

Comment (michael-s-molina) [reply superset-frontend/src/dashboard/util/getRelatedCharts.ts:70]: > The intent of these changes it to limit the number of unnecessary queries we send to the backend for processing.

I was understanding that we were going to achieve this by limiting the number of unnecessary requests to server. Given that each chart fires a request to server, if they don't belong to the same dataset or are out of scope, then that request would not be fired and the chart would not be loaded.

Comment (geido) [reply superset-frontend/src/dashboard/util/getRelatedCharts.ts:70]: @michael-s-molina I think we still want to allow that columns that belong to different datasets but share the same name might work? I think this was a functionality that also the UI seems to suggest and I don't think we should change it now without revising the functionality more holistically. I believe these changes will already limit a bunch of requests and be an improvement in that sense.

Screenshot 2024-10-03 at 17 29 19

Screenshot 2024-10-03 at 17 28 57

Comment (michael-s-molina) [reply superset-frontend/src/dashboard/util/getRelatedCharts.ts:70]: I didn't know this was already allowed. I agree it's important that these changes keep the compatibility.

File: superset-frontend/src/dashboard/util/getRelatedCharts.ts (hunk 8 above)
Comment (geido) [reply superset-frontend/src/dashboard/util/getRelatedCharts.ts:99]: Good catch

File: superset-frontend/src/dashboard/util/getRelatedCharts.ts [hunk 9]
```diff
@@ -80,12 +80,25 @@ export function getRelatedCharts(
   datasources: DatasourcesState,
 ) {
   return Object.entries(filters).reduce((acc, [filterKey, filter]) => {
+    const chartsInScope = filter.chartsInScope
```
Comment (kgabryje) [inline superset-frontend/src/dashboard/util/getRelatedCharts.ts:83]: `filter.chartsInScope?.filter(
           (chartId: number) => !filter.scope.excluded.includes(chartId),
         ) ?? filter.scope`

File: superset-frontend/src/dashboard/util/getRelatedCharts.ts [hunk 10]
```diff
@@ -103,7 +103,7 @@ export function getRelatedCharts(
         ),
       };
     }
-    if (!filter.filterType) {
+    if (!filter.filterType && Object.keys(slices).includes(filterKey)) {
```
Comment (kgabryje) [inline superset-frontend/src/dashboard/util/getRelatedCharts.ts:106]: nit: we could probably simplify `Object.keys(slices).includes(filterKey)` to just `slices[filterKey]`

File: superset-frontend/src/dashboard/util/getRelatedCharts.ts (hunk 9 above)
Comment (geido) [reply superset-frontend/src/dashboard/util/getRelatedCharts.ts:83]: Thanks. I think from looking at the unit tests there is an issue with this logic too. I am fixing it up.

**Review by kgabryje — APPROVED** [review]

**Comment by geido** [comment]
Holding on this while testing more cases

**Comment by michael-s-molina** [comment]
Some things I observed while testing

https://github.com/user-attachments/assets/5c8e861b-7f47-44a8-bb79-e291573d3315

- The first 2 charts should be affected by the filter but there's no filter indicator
- If you check the query, the filter was applied but the chart was not reloaded

**Comment by michael-s-molina** [comment]
In this example, the last 2 charts are from different datasets but both have a `gender` column. Initially, the filter is correctly applied to both datasets but if I remove the last chart from the filter scope, it's still being affected.


https://github.com/user-attachments/assets/76dd859f-3adc-4c6b-b58d-347a2238c97f

**Review by michael-s-molina — CHANGES_REQUESTED** [review]
I found some problems while testing with the ephemeral environment.

**Comment by geido** [comment]
> I found some problems while testing with the ephemeral environment.

Thanks @michael-s-molina, I could not see many of these issues locally due to https://github.com/apache/superset/pull/30569 as I was under the false impression that I was testing the latest state of the code. I reverted that PR and now looking at these problems. Thanks for catching them!

**Review by michael-s-molina — APPROVED** [review]
I did my set of tests and was not able to find problems! Even datasets with calculated columns worked.

Nice work @geido. This PR should significantly reduce the number of requests to the server, reducing costs and improving performance. Thank you!

Given that this PR touches a critical part of Superset, it would be good to have more approvals before merging the PR.

**Comment by sadpandajoe** [comment]
https://github.com/user-attachments/assets/7d08eec0-7d40-4df3-a124-87c60ae16096

I'm getting an unexpected server error on the FCC examples dashboard. Steps to repro:
1. go to the SQL lab
2. run a `select *` query on the fcc data
3. save it as a new dataset
4. create a new chart with the virtual dataset
5. add the chart to the fcc dashboard
6. go to the dashboard
7. click on a slice of it

File: superset-frontend/packages/superset-ui-core/src/query/types/Dashboard.ts [hunk 11]
```diff
@@ -80,6 +80,24 @@ export type Filter = {
...
+export type AppliedCrossFilterType = {
+  filterType: undefined;
+  targets: number[];
+  scope: number[];
+} & AppliedFilter;
+
+export type AppliedNativeFilterType = {
+  filterType: 'filter_select';
+  scope?: number[] | NativeFilterScope; // TODO: inconsistent usage
+  targets: [Partial<NativeFilterTarget>];
```
Comment (justinpark) [inline superset-frontend/packages/superset-ui-core/src/query/types/Dashboard.ts:98]: Do you intent to have this?

```suggestion
  targets: Partial<NativeFilterTarget>[];
```

**Review by justinpark — APPROVED** [review]
LGTM other than one minor type issue.

File: superset-frontend/src/dashboard/util/getRelatedCharts.ts [hunk 12]
```diff
@@ -0,0 +1,200 @@
...
+  isAppliedCrossFilterType,
+  isAppliedNativeFilterType,
+  isNativeFilter,
+} from '@superset-ui/core';
+import { Slice } from 'src/types/Chart';
+import { DatasourcesState } from '../types';
+
+function checkForExpression(formData?: Record<string, any>) {
+  const groupby = ensureIsArray(formData?.groupby) ?? [];
+  const allColumns = ensureIsArray(formData?.all_columns) ?? [];
```
Comment (michael-s-molina) [inline superset-frontend/src/dashboard/util/getRelatedCharts.ts:34]:
```suggestion
  const groupby = ensureIsArray(formData?.groupby);
  const allColumns = ensureIsArray(formData?.all_columns);
```

**Review by michael-s-molina — APPROVED** [review]

**Comment by sadpandajoe** [comment]
Just a quick question, should it affect all charts if it's from the same database table even if one is virtual? Example here: http://35.88.232.227:8080/superset/dashboard/11/?native_filters_key=vORa9YtGn5rLPgi2AjgirnIJB_30m_cpUE3kzlqWFgMGjPIw3CKoFrTKjNNAUkan

1. go to sql lab
2. run the query 
```
SELECT * 
FROM covid_vaccines 
WHERE country_name = "United States"
```
3. save as a new dataset
4. copy one of the charts that use covid_vaccines
5. switch the dataset to the copied one
6. put this on the covid vaccines dashboard
7. do a cross filter on the newly created dataset chart

right now following this step, all charts are affected by the virtual dataset.

**Review by sadpandajoe — APPROVED** [review]
Spoke with @yousoph and it sounds like my case is invalid so going to approve.

**Comment by Mainer-g00t** [comment]
All our dashboards utilize cross-filters across various virtual datasets, and we use Jinja to capture and apply filters, even if the filtered columns in the filter are not present in the dataset.
For example: 
- dataset & chart 1: city, number of habitants
- dataset & chart 2: profession, number of proffesionals
We filter between both using the filter in the WHERE statement. The reason for having different datasets is that the cardinality in our tables is very high and a single dataset ruins performance.

I'm afraid that if this is applied automatically to every case could basically break all of our dashboards

**Comment by fmannhardt** [comment]
Not sure if this should go here or to a new issue (and I won't manage to find time to create a reproducible example in the next week). However, I re-tested this feature together with cross filters and the following setup:
- A renamed column (colum_a AS "Colum A") is used as source for the cross filter from chart A (with data source A)
- A second chart B from a different data source B has the same underlying column (column_a) but this column is only used in a filter of that chart that is based on an JINJA expression (using  get_filters() as explained here: https://superset.apache.org/docs/configuration/sql-templating/)
- Result is that the cross filter on chart A does not affect chart B.

I looked through the code and it, in fact, does not consider searching for JINJA in the filter of other charts.

**Comment by villebro** [comment]
I didn't review these changes, but it was my understanding that
1. by default, native and cross filters will only be scoped to charts using the same dataset
2. If one wants the filters to apply to charts that aren't using the same dataset, one simply adds them to the filter scope

Similar to the comments above, I know of many use cases where there's jinja logic that intercepts filters for columns that aren't present in the dataset, and use those to modify the chart query somehow. I'm not sure if this has been explicitly stated as a feature that Superset supports, but I think this use case has been well established for a longer time already, hence I feel removing it will be problematic.

Does this PR break said workflow? I'm happy to jump on a sync call to discuss this if needed.

**Comment by villebro** [comment]
@Mainer-g00t @fmannhardt as you raised concerns here, did you find that this PR broke your use cases?

**Comment by villebro** [comment]
> > @Mainer-g00t @fmannhardt as you raised concerns here, did you find that this PR broke your use cases?
> 
> Yes, it does. In our case, charts export filters that are picked up by jinja logic to filter dataset with data that is not part of the columns in the dataset. Specifically, our dataset looks like:
> 
> * customer (1k), products (1k), providers(1k), metrics...
> 
> This leads to a roughly 500M row table. We split it in 3 datasets, one for each dimension and use x-filters to select on the other datasets. ie, clicking on one customer on the first table will filter all products and providers for that customer and so on.
> 
> This allows us to display relationships in big datasets breaking it up in dimensions and using x-filters

Just to confirm, have you tested the changes here and can confirm that they do indeed break your use case? Because to me it seems like you should still be able to do the same cross filtering even after this change, as long as you've defined your filter scopes correctly.

**Comment by Mainer-g00t** [comment]
> > > @Mainer-g00t @fmannhardt as you raised concerns here, did you find that this PR broke your use cases?
> > 
> > 
> > Yes, it does. In our case, charts export filters that are picked up by jinja logic to filter dataset with data that is not part of the columns in the dataset. Specifically, our dataset looks like:
> > 
> > * customer (1k), products (1k), providers(1k), metrics...
> > 
> > This leads to a roughly 500M row table. We split it in 3 datasets, one for each dimension and use x-filters to select on the other datasets. ie, clicking on one customer on the first table will filter all products and providers for that customer and so on.
> > This allows us to display relationships in big datasets breaking it up in dimensions and using x-filters
> 
> Just to confirm, have you tested the changes here and can confirm that they do indeed break your use case? Because to me it seems like you should still be able to do the same cross filtering even after this change, as long as you've defined your filter scopes correctly.

Yes, we just tested it on 4.1 and breaks cross filtering for us. It does not apply filters if the column is not in the dataset even when it is used in the WHERE statement with jinja

**Comment by fmannhardt** [comment]
Thanks. Just to confirm it does break our use case in 4.1rc3 for two underlying reasons:

(1) The column filtering is renamed with a label (colx as X). So, cross filtering does consider it as X.

(2) We used JINJA to create a custom filter condition based on selected filters (on X) but since there there is no column X in the dataset, it won't do the filtering on the chart. Btw, it does filter correctly when clicking on show the data as table or as SQL statement. So, the filtering is inconsistent.

I think the code checking for expressions (quoted above) simply does not check there WHERE filters defined on the charts. It may also have issues with custom charts.
________________________________

**Comment by michael-s-molina** [comment]
Hi @fmannhardt @Mainer-g00t @geido. May I suggest opening a specific GitHub issue for this so we can track it [here](https://github.com/orgs/apache/projects/418)?

**Comment by Mainer-g00t** [comment]
> Hi @fmannhardt @Mainer-g00t @geido. May I suggest opening a specific GitHub issue for this so we can track it [here](https://github.com/orgs/apache/projects/418)?

Hello, sure, I'll try to do it today with an example of the behaviour before and after the change

**Comment by fbgeobit** [comment]
Hi @michael-s-molina , 
We opened a new issue with use case commented by @Mainer-g00t : https://github.com/apache/superset/issues/30687

Thanks

**Comment by michael-s-molina** [comment]
Thank you! I added the issue to the [4.1 board](https://github.com/orgs/apache/projects/418).
