### PR TITLE
fix(css): transparent linear gradient not working in safari

### LINKED ISSUE #20047: [native-filter] The bottom of the left sidebar looks weird in the safari.
## Screenshot
image

### PR DESCRIPTION
**Pull request by stephenLYZ**
### SUMMARY

This PR fixes the problem that transparent linear gradient not working in safari. refer to https://css-tricks.com/thing-know-gradients-transparent-black/.
### before

image

### after

image

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #20047
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/packages/superset-ui-core/src/style/index.tsx [hunk 1]
```diff
@@ -160,6 +160,7 @@ const defaultTheme = {
   },
   transitionTiming: 0.3,
   gridUnit: 4,
+  transparent: 'rgba(255, 255, 255, 0)',
```
Comment (rusackas) [inline superset-frontend/packages/superset-ui-core/src/style/index.tsx:163]: Heads up to @michael-s-molina @geido that we might want to consider this in our Theme discussions. We might want to consider a means to add "opacity stops" that we support for some use cases, and a means to use them as alpha channel values on any given theme color, or perhaps as a styling mixin of some sort. The reason being that this approach works great while we're in light/white theming mode, but if we switched to dark mode or something, then we'd again see weird grays as out gradient transitions toward transparent white.

Comment (rusackas) [reply superset-frontend/packages/superset-ui-core/src/style/index.tsx:163]: @stephenLYZ I think we can allow this for now, but if you can think of a way to generalize alpha channel transparency for colors in a more generalized way, I think we'd be interested :)

File: superset-frontend/src/dashboard/components/nativeFilters/FilterBar/ActionButtons/index.tsx [hunk 2]
```diff
@@ -53,7 +53,10 @@ const ActionButtonsContainer = styled.div`
     padding: ${theme.gridUnit * 4}px;
     padding-top: ${theme.gridUnit * 6}px;
 
-    background: linear-gradient(transparent, white 25%);
+    background: linear-gradient(
+      ${theme.transparent},
+      ${theme.colors.grayscale.light5} ${theme.opacity.mediumLight}
```
Comment (rusackas) [inline superset-frontend/src/dashboard/components/nativeFilters/FilterBar/ActionButtons/index.tsx:58]:
```suggestion
      ${theme.colors.grayscale.light5} 0,
      ${theme.colors.grayscale.light5} ${theme.opacity.mediumLight}
```
Would this work just as well? Then we can use any color as our transparent color, rather than just white, right?

File: superset-frontend/packages/superset-ui-core/src/style/index.tsx (hunk 1 above)
Comment (stephenLYZ) [reply superset-frontend/packages/superset-ui-core/src/style/index.tsx:163]: Yeah. The way I've come up with is to convert the theme hex color to rgba via an external method, such as `emotion-rgba`:

```
rgba(theme.colors.grayscale.light5, 0)
```

File: superset-frontend/src/dashboard/components/nativeFilters/FilterBar/ActionButtons/index.tsx (hunk 2 above)
Comment (stephenLYZ) [reply superset-frontend/src/dashboard/components/nativeFilters/FilterBar/ActionButtons/index.tsx]: Thanks! I tried it but unfortunately it does not work 😂

**Review by rusackas — APPROVED** [review]
I did not know we were already using that emotion-rgba lib. Nifty!

File: superset-frontend/packages/superset-ui-core/src/style/index.tsx (hunk 1 above)
Comment (rusackas) [reply superset-frontend/packages/superset-ui-core/src/style/index.tsx]: Seems reasonable/extendable to me! Cool!
