### PR TITLE
fix(theming): Fix visual regressions from theming P7

### LINKED ISSUE #32773: A space is missing for the "+ SQL Query" button
## Screenshot

Image

## Description

On Welcome screen, a space is missing for the "+ SQL Query" button
Others buttons are OK

### LINKED ISSUE #34228: "Update chart" button blocks last form fields in Explore sidebar
### Bug description

In the Explore view, the "Update chart" button is sticky and overlaps the last few controls in the sidebar. This makes it impossible to access or edit certain chart options, especially when multiple filters or complex settings are used.

Steps to Reproduce
- Open any chart in the Explore view with multiple filters so that it is scrollable
- Scroll down to the bottom of the control panel
- Observe that the "Update chart" button overlaps the last field and prevents interaction

### Screenshots/recordings

Image

### Superset version

master / latest-dev

### Python version

3.11

### Node version

18 or greater

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by EnxDev**
### SUMMARY

This PR fixes various regressions introduced by the `theming project` and introduces a new reusable component, `ModalTitleWithIcon`, to standardize the rendering of modal titles across the application.

✅ What's Included

- Fixed styling inconsistencies and regressions caused by recent theming changes.
- Added ModalTitleWithIcon to unify and simplify modal title implementations.
- Supports both static and edit/add dynamic titles via editModeConfig.
- Allows passing custom icons, ensuring consistent layout and spacing.
- Replaced duplicated JSX title blocks with this new component across multiple modals.
- #fix #34228
- #fix #32773

🎯 Why

- To clean up duplicated code and ensure consistent UX across modals.
- To provide a single source of truth for icon size, spacing, and typography in modal headers.
- To make future changes to modal titles easier and less error

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

- Before
before-1

- After
after-1

- Before
before-2

- After
after-2

- Before
before-3

- After
after-3

- Before
Screenshot 2025-07-18 153058

- After

after-4

- Before
before-5

- After
after-5

- Before

before-6

- After
after-6

- Before
before-7

- After
after-7

- Before
before-8

- After
after-8

- Before
before-10

- After
after-10

- Before
before-11

- After
after-11

- Before
before-12

- After
after-12

- Before
before-13

- After
after-13
after-13-1

- Before
before-1

- After
after-1

- Before
before-2

- After
after-2

- Before
Screenshot 2025-07-23 144534

- After
Screenshot 2025-07-23 144517

- Before
Screenshot 2025-07-24 102852

- After
Screenshot 2025-07-24 103018

### TESTING INSTRUCTIONS

- All tests should pass

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/components/ModalTitleWithIcon/index.tsx [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+  /**
+   * Test ID used for end-to-end or unit testing (e.g. Cypress, Testing Library).
+   */
+  dataTestId?: string;
+
+  /**
+   * Ant Design Typography title level (default: 5)
+   */
+  level?: 1 | 2 | 3 | 4 | 5;
+};
```
Comment (msyavuz) [inline superset-frontend/src/components/ModalTitleWithIcon/index.tsx]:
```ts
interface ModalTitleWithIconProps extends TypographyProps {
  isEditMode?: boolean;
  title?: string | React.ReactNode;
  icon?: IconType;
}
```
Something like this might be better

File: superset-frontend/src/components/ModalTitleWithIcon/index.tsx [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+    )
+  ) : null;
+
+  return (
+    <Typography.Title level={level} css={titleStyles} data-test={dataTestId}>
+      {renderedIcon}
+      {typeof renderedTitle === 'string' ? t(renderedTitle) : renderedTitle}
+    </Typography.Title>
+  );
+};
```
Comment (msyavuz) [inline superset-frontend/src/components/ModalTitleWithIcon/index.tsx]: Since we are already get title and determine the icon based on the `isEditMode` prop, we don't need to provide `titleEdit` and `titleAdd` as well. just a title prop would be fine to expose to parents.

File: superset-frontend/src/features/roles/RoleListDuplicateModal.tsx [hunk 3]
```diff
@@ -58,7 +59,13 @@ function RoleListDuplicateModal({
     <FormModal
       show={show}
       onHide={onHide}
-      title={t('Duplicate role %(name)s', { name })}
+      name={t('Duplicate role %(name)s', { name })}
+      title={
+        <ModalTitleWithIcon
+          title={t('Duplicate role %(name)s', { name })}
```
Comment (msyavuz) [inline superset-frontend/src/features/roles/RoleListDuplicateModal.tsx:65]: This gets translated twice which would mess up the parameters

File: superset-frontend/src/components/ModalTitleWithIcon/index.tsx (hunk 2 above)
Comment (EnxDev) [reply superset-frontend/src/components/ModalTitleWithIcon/index.tsx]: The initial idea was to provide a more rigid structure, but as we progressed and encountered all the different use cases, the component ended up becoming too bloated. At this point, I believe it's better to proceed this way, thanks!

File: superset-frontend/src/features/roles/RoleListDuplicateModal.tsx (hunk 3 above)
Comment (EnxDev) [reply superset-frontend/src/features/roles/RoleListDuplicateModal.tsx:65]: Good catch!

File: superset-frontend/src/components/ModalTitleWithIcon/index.tsx (hunk 1 above)
Comment (EnxDev) [reply superset-frontend/src/components/ModalTitleWithIcon/index.tsx]: I don't think we need all the properties in this case

```
type ModalTitleWithIconProps = Omit<TitleProps, 'title'> & {
  isEditMode?: boolean;
  title: React.ReactNode;
  icon?: IconType;
};
```

**Review by mistercrunch — APPROVED** [review]
Excited to get this merged! Looks like only one unit test is failing
