### PR TITLE
fix(plugins): display correct tooltip (fixes #3342)

### LINKED ISSUE #3342: Chord popups contain wrong information
### Superset version
Superset 0.19.0

### Expected results
When clicked on Chord diagram bean, it shows the correct flow from source to target

### Actual results
It shows just opposite numbers - from target to source

### Steps to reproduce

1) create a chord diagram, set source and target
2) click on diagram and notice that source and target in popup are switched places

I attach the source data and chord screen to show
table1
hord1

### PR DESCRIPTION
**Pull request by jonaschn**
### SUMMARY
Fixes #3342
Display the correct tooltip information for chord charts (source and target values were switched)

### BEFORE
image

### AFTER
image

### TESTING INSTRUCTIONS
Example SQL Dataset:
```sql
SELECT 'Alice' AS source, 'Bob' AS target, 5 AS interactions UNION ALL
SELECT 'Alice', 'Charlie', 3 UNION ALL
SELECT 'Bob', 'Charlie', 2 UNION ALL
SELECT 'Charlie', 'David', 1  UNION ALL
SELECT 'Bob', 'David', 4
```

### ADDITIONAL INFORMATION

- [x] Has associated issue: #3342
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/plugins/legacy-plugin-chart-chord/src/Chord.js [hunk 1]
```diff
@@ -130,9 +130,9 @@ function Chord(element, props) {
     .text(
       d =>
         `${nodes[d.source.index]} → ${nodes[d.target.index]}: ${f(
```
Comment (jonaschn) [inline superset-frontend/plugins/legacy-plugin-chart-chord/src/Chord.js:132]: The diff looks a bit misleading.
I simply swapped `d.source.value` and `d.target.value` (line 133 and 135)

**Comment by rusackas** [comment]
Agreed that it was wrong and that this fixes _the display_ of the chart, but I'm _so_ confused by the meaning of the diff. I mean, yes - swapping it swaps it, and that works. But now the code (modified by the diff) is
`${nodes[d.target.index]} → ${nodes[d.source.index]}` which displays the `source` column then `→` then the `target` column. How is this now _displaying_ correctly but with the items _named_ incorrectly? 🤯

**Review by rusackas — APPROVED** [review]

**Comment by jonaschn** [comment]
Thanks for merging. When do you expect to release this change?
Will it be part of 4.1.0?
I would really appreciate it because our users were constantly confused.
