### PR TITLE
[explore] proper filtering of NULLs and ''

### LINKED ISSUE #4297: [Filter Box] Boolean values show up blank in selector
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Expected results
Should show true/false

### Actual results
Shows blank

### Steps to reproduce
Add boolean type column to filter section

screen shot 2018-01-25 at 7 00 35 pm

### PR DESCRIPTION
**Pull request by mistercrunch**
screen shot 2018-03-19 at 11 21 00 pm

closes https://github.com/apache/incubator-superset/issues/4297

### CODE REVIEW

**Comment by hughhhh** [comment]
Definitely need this!!

**Comment by hughhhh** [comment]
Did some work on the druid side. 

https://github.com/hughhhh/incubator-superset/commit/3bc3bd46d05a96335f9663745f68429f10b5eff3

File: superset/assets/javascripts/components/AlteredSliceTag.jsx [hunk 1]
```diff
@@ -61,7 +61,7 @@ export default class AlteredSliceTag extends React.Component {
         return '[]';
       }
       return value.map((v) => {
-        const filterVal = v.val.constructor === Array ? `[${v.val.join(', ')}]` : v.val;
+        const filterVal = v.val && v.val.constructor === Array ? `[${v.val.join(', ')}]` : v.val;
```
Comment (jeffreythewang) [inline superset/assets/javascripts/components/AlteredSliceTag.jsx]: might be my unfamiliarity, but why not use `Array.isArray` like in other parts of the code?

**Review by jeffreythewang — COMMENTED** [review]
I had a [WIP] idea (https://github.com/tc-dc/superset/pull/8) for handling nulls that involves showing a tooltip next to the label, to distinguish between actual `null` values and `"null"` string values.

(I've only tested with druid, and so far only have it such that `Enable Filter Select` must be on.)

File: superset/assets/javascripts/components/AlteredSliceTag.jsx (hunk 1 above)
Comment (mistercrunch) [reply superset/assets/javascripts/components/AlteredSliceTag.jsx]: Didn't write that line but FWIW someone on StackOverflow says it's the best way
https://stackoverflow.com/questions/767486/how-do-you-check-if-a-variable-is-an-array-in-javascript

File: superset/connectors/base/models.py [hunk 2]
```diff
@@ -185,6 +186,34 @@ def data(self):
             'verbose_map': verbose_map,
         }
 
+    @staticmethod
+    def filter_values_handler(
+            values, target_column_is_numeric=False, is_list_target=False):
+        def handle_single_value(v):
+            # backward compatibility with previous <select> components
+            if isinstance(v, basestring):
+                v = v.strip().strip("'").strip('"')
```
Comment (betodealmeida) [inline superset/connectors/base/models.py]: You can do a single strip to remove whitespace and single/double quotes:

```python
v = v.strip(' \'"')
```

Or, to also take care of tabs and line feeds:

```python
v = v.strip('\t\n \'"')
```

File: superset/connectors/base/models.py [hunk 3]
```diff
@@ -185,6 +186,34 @@ def data(self):
...
+                    # where a column data type might have changed
+                    v = utils.string_to_num(v)
+            if v == '<NULL>':
+                return None
+            elif v == '<empty string>':
+                return ''
+            return v
+        if isinstance(values, (list, tuple)):
+            values = [handle_single_value(v) for v in values]
+        values = handle_single_value(values)
```
Comment (betodealmeida) [inline superset/connectors/base/models.py]: This is a bit confusing... I'd add the second call to an `else` block (unless I'm missing something):

```python
if isinstance(values, (list, tuple)):
    values = [handle_single_value(v) for v in values]
else:
    values = handle_single_value(values)
```

File: superset/connectors/base/models.py [hunk 4]
```diff
@@ -185,6 +186,34 @@ def data(self):
...
+        if is_list_target and not isinstance(values, (tuple, list)):
+            values = [values]
```
Comment (betodealmeida) [inline superset/connectors/base/models.py]: What if `is_list_target` is true but `values` is a tuple? In this case it would return a tuple, is that ok?

File: superset/connectors/druid/models.py [hunk 5]
```diff
@@ -1322,40 +1339,30 @@ def increment_timestamp(ts):
...
-
             is_numeric_col = col in num_cols
-            if is_numeric_col:
-                if op in ('in', 'not in'):
-                    eq = [utils.string_to_num(v) for v in eq]
-                else:
-                    eq = utils.string_to_num(eq)
-
+            eq = cls.filter_values_handler(
+                eq, is_list_target=op in ('in', 'not in'),
```
Comment (betodealmeida) [inline superset/connectors/druid/models.py]: This is a bit hard to read, can we define `is_list_target` outside the function call, like you did for `is_numeric_col`?

File: superset/connectors/sqla/models.py [hunk 6]
```diff
@@ -565,28 +564,20 @@ def get_sqla_query(  # sqla
...
+            if not all([flt.get(s) for s in ['col', 'op']]):
                 continue
             col = flt['col']
             op = flt['op']
-            eq = flt['val']
             col_obj = cols.get(col)
+            eq = self.filter_values_handler(
+                flt.get('val'),
+                target_column_is_numeric=col_obj.is_num,
+                is_list_target=op in ('in', 'not in'))
```
Comment (betodealmeida) [inline superset/connectors/sqla/models.py]: Same as above here.

File: superset/viz.py [hunk 7]
```diff
@@ -1693,6 +1693,8 @@ def run_extra_queries(self):
         for flt in filters:
             qry['groupby'] = [flt]
             df = self.get_df_payload(query_obj=qry).get('df')
+            print(df)
+            print(df.dtypes)
```
Comment (betodealmeida) [inline superset/viz.py]: `d2d`

File: tests/druid_func_tests.py [hunk 8]
```diff
@@ -119,14 +119,15 @@ def test_get_filters_handles_arrays_for_string_types(self):
         filtr = {'col': 'A', 'op': '==', 'val': ['a', 'b']}
         res = DruidDatasource.get_filters([filtr], [])
         self.assertEqual('a', res.filter['filter']['value'])
+
         filtr = {'col': 'A', 'op': '==', 'val': []}
         res = DruidDatasource.get_filters([filtr], [])
-        self.assertEqual('', res.filter['filter']['value'])
+        self.assertEqual(None, res.filter['filter']['value'])
```
Comment (betodealmeida) [inline tests/druid_func_tests.py]: Use `assertIsNone` instead.

File: tests/druid_func_tests.py [hunk 9]
```diff
@@ -119,14 +119,15 @@ def test_get_filters_handles_arrays_for_string_types(self):
...
 
     def test_get_filters_handles_none_for_string_types(self):
         filtr = {'col': 'A', 'op': '==', 'val': None}
         res = DruidDatasource.get_filters([filtr], [])
-        self.assertEqual('', res.filter['filter']['value'])
+        self.assertEqual(None, res)
```
Comment (betodealmeida) [inline tests/druid_func_tests.py]: Ditto.

File: superset/connectors/base/models.py (hunk 2 above)
Comment (mistercrunch) [reply superset/connectors/base/models.py]: oh neat

File: superset/connectors/base/models.py (hunk 4 above)
Comment (mistercrunch) [reply superset/connectors/base/models.py]: The variable should probably be called `is_iterable_target`, both tuple and list will work here.
