### PR TITLE
[dashboard][bugfix][save as] re-direct to copied dashboard upon saveas

### LINKED ISSUE #6188: [dashboard] Dashboard save as doesn't re-direct to the copied dashboard
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
master

### Expected results
When you copy a dashboard, you should be redirected to the copy

### Actual results
The copy is created, but redirect does not happen.

### Steps to reproduce
Just copy a dashboard

### PR DESCRIPTION
**Pull request by williaster**
🐛 Fixes #6188 where you are **not** re-directed upon copying a dashboard. Introduced by [this line](https://github.com/apache/incubator-superset/pull/5854/files#diff-9a43c7c6ad146ab5c8e32af81616a26bR135) in the SupersetClient refactor 🙄 

**after fix**
save-as-dashboard

@graceguo-supercat @kristw @michellethomas

### CODE REVIEW

File: superset/assets/src/dashboard/actions/sliceEntities.js [hunk 1]
```diff
@@ -64,22 +67,21 @@ export function fetchAllSlices(userId) {
...
-        .catch(error =>
-          Promise.all([
-            dispatch(
-              fetchAllSlicesFailed(
-                error.error ||
-                  error.statusText ||
-                  t('Could not fetch all saved charts'),
+        .catch(errorResponse =>
+          getClientErrorObject(errorResponse).then(({ error }) =>
+            Promise.all([
```
Comment (kristw) [inline superset/assets/src/dashboard/actions/sliceEntities.js]: `Promise.all` seems unnecessary.
Is anybody expecting the result from the dispatches?
Might be better to return the errorObject, or no need to return at all.

```js
.catch(errorResponse => 
  getClientErrorObject(errorResponse).then(({ error }) => {
    dispatch(...);
    dispatch(...);
  });
```

```js
.catch(errorResponse => {
  const errorObjectPromise = getClientErrorObject(errorResponse);
  errorObject.then(({ error }) => {
    dispatch(...);
    dispatch(...);
  });
  return errorObjectPromise;
}
```

**Review by kristw — APPROVED** [review]
