### PR TITLE
fix: Empty tab component in Dashboard cannot be deleted

### LINKED ISSUE #14820: [Tab]sub-level tabs can not be removed
Expected behavior 
User can click on Trash icon in the action bar to delete dashboard components 

https://user-images.githubusercontent.com/67837651/119538546-0f77d400-bd40-11eb-88a1-b39944b5a996.mov

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
Adds a min-height to the tabs component so that when empty the user can still reach the trash icon to delete the component from the dashboard

### BEFORE

https://user-images.githubusercontent.com/60598000/119870962-9dafae00-bf2a-11eb-967e-125cb883d0ff.mp4

### AFTER

https://user-images.githubusercontent.com/60598000/119871058-bfa93080-bf2a-11eb-8091-d74389979ac8.mp4

### TESTING INSTRUCTIONS
1. Open a dashboard
2. Add a tab component
3. Delete all the tabs
4. Make sure you can reach the trash icon far left when hovering the tab component

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #14820
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@junlincc @rusackas

**Review by michael-s-molina — APPROVED** [review]

File: superset-frontend/src/dashboard/components/gridComponents/Tabs.jsx [hunk 1]
```diff
@@ -89,6 +89,10 @@ const StyledTabsContainer = styled.div`
   .ant-tabs {
     overflow: visible;
 
+    .ant-tabs-nav-wrap {
+      min-height: ${({ theme }) => theme.gridUnit * 12.5}px;
```
Comment (suddjian) [inline superset-frontend/src/dashboard/components/gridComponents/Tabs.jsx:93]: Nit, non-blocking: Why this `12.5` value here? Could we round it to a whole value?

**Review by suddjian — APPROVED** [review]

File: superset-frontend/src/dashboard/components/gridComponents/Tabs.jsx (hunk 1 above)
Comment (geido) [reply superset-frontend/src/dashboard/components/gridComponents/Tabs.jsx:93]: Hello @suddjian. Thanks for your feedback. This is to make it exactly 50px which should be the default height of the tabs component.

Comment (suddjian) [reply superset-frontend/src/dashboard/components/gridComponents/Tabs.jsx:93]: If this is meant to match the tabs component, it would be nice to have them both reference the same constant value instead of magic numbers that happen to match up.

**Review by rusackas — APPROVED** [review]
Agree with @suddjian's comments... I'm not a fan of fractional gridUnits or "magic numbers" so I'm supportive of a follow-up PR t either add a constant that both refer to. It could potentially be exported by the tab component (open to suggestions there). It _could_ export the pixel height, but it would be better, I think, to export a number of gridUnits, which could then be used here, and by the Tab component itself. 12 or 13 gridUnits for both should do nicely, whichever looks better. Tagging this PR for a revisit.
