### PR TITLE
fix: Cascading filter popover widens automatically

### LINKED ISSUE #15354: [native-filters] cascading filter popover widens automatically
Cascading filter popover grows by itself

### Expected results

The cascading popover stays static

### Actual results

The popover grows by itself:
https://user-images.githubusercontent.com/33317356/123226205-1b3fed00-d4dc-11eb-9edb-bf5ab44825e9.mp4

#### How to reproduce the bug

1. Create parent and child filter
2. Open dashboard
3. Open popover

### Environment

master

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Fixes https://github.com/apache/superset/issues/15354

@rusackas @villebro 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Screen Shot 2021-06-25 at 2 22 35 PM
Screen Shot 2021-06-28 at 8 36 31 AM

### TESTING INSTRUCTIONS
Check the original issue for instructions.

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/components/nativeFilters/FilterBar/CascadeFilters/CascadeFilterControl/index.tsx [hunk 1]
```diff
@@ -53,28 +49,26 @@ const CascadeFilterControl: React.FC<CascadeFilterControlProps> = ({
...
+      dataMaskSelected={dataMaskSelected}
+      filter={filter}
+      directPathToChild={directPathToChild}
+      onFilterSelectionChange={onFilterSelectionChange}
+    />
+    <StyledDiv>
       {filter.cascadeChildren?.map(childFilter => (
-        <li key={childFilter.id}>
+        <>
+          <Icons.CaretDownOutlined iconSize="s" />
```
Comment (villebro) [inline superset-frontend/src/dashboard/components/nativeFilters/FilterBar/CascadeFilters/CascadeFilterControl/index.tsx:61]: I personally think the caret is not needed here, as it is just a static component that occupies a fair amount of vertical space and doesn't really add a lot of information.

**Review by villebro — COMMENTED** [review]
Thanks for the fix! One comment about the added caret. Also, we should probably have a quick discussion about whether or not we want to remove the indentation. I understand that the original design removes valuable horizontal real estate that can cause trouble if there are deeply nested filter, but it would be good to hear other people's thoughts on how to best relay information about the cascading hierarchy.

File: superset-frontend/src/dashboard/components/nativeFilters/FilterBar/CascadeFilters/CascadeFilterControl/index.tsx (hunk 1 above)
Comment (michael-s-molina) [reply superset-frontend/src/dashboard/components/nativeFilters/FilterBar/CascadeFilters/CascadeFilterControl/index.tsx:61]: I'm not against removing the query, it was my first design choice. The order can be enough to show hierarchy. About the indentation though, I really think that is not a good solution to keep inputs with different widths. Also, it will break if the user adds a bunch o nesting.

**Review by villebro — APPROVED** [review]
LGTM 👍  Let's try to squeeze in an engineering+design session at some point to refine the cascading functionality (deep nesting vs current shallow nesting) + design (popover, indentation etc)
