### PR TITLE
fix: multiple issues with FilterPopover

### LINKED ISSUE #11411: Charts: Filters Custom SQL Where/Having dropdown never selecting
When trying to set a custom SQL filter on a chart, selecting the dropdown and changing it renders the dropdown box useless. It never selects having or where when you click on it. Thus, it does not allow you to save the custom SQL query because its a required field

### Expected results

Show the selected dropdown choice [where/having] and allow the user to save the custom sql filter

### Actual results

custom SQL filter never is able to be saved if you try to change where/having

#### Screenshots

Screen Shot 2020-10-23 at 10 06 18 AM
Screen Shot 2020-10-23 at 10 07 51 AM

#### How to reproduce the bug

1. Go to Chart
2. Click on Filters
3. Add a filter
4. Click Custom SQL
5. Change dropdown from where to having

### Environment

(please complete the following information):

- superset version: `superset version` 0.37.2
- python version: `python --version` 3.6.9
- node.js version: `node -v` 8.10.0
- npm version: `npm -v` 3.5.2

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by mistercrunch**
### SUMMARY
closes https://github.com/apache/incubator-superset/issues/11411, https://github.com/apache/incubator-superset/issues/11394

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Screen Shot 2020-10-23 at 9 00 06 AM

### TEST PLAN
manually tested, tested both HAVING and WHERE, going back and forth

### CODE REVIEW

File: superset-frontend/src/explore/components/AdhocFilterEditPopover.jsx [hunk 1]
```diff
@@ -178,21 +179,22 @@ export default class AdhocFilterEditPopover extends React.Component {
           </Tab>
         </Tabs>
         <div>
+          <Button buttonSize="small" onClick={this.props.onClose} cta>
```
Comment (mistercrunch) [inline superset-frontend/src/explore/components/AdhocFilterEditPopover.jsx:182]: i18n, flip button (`Save` to the right and primary)

File: superset-frontend/src/explore/components/AdhocFilterOption.jsx [hunk 2]
```diff
@@ -60,7 +60,6 @@ class AdhocFilterOption extends React.PureComponent {
     // isNew is used to indicate whether to automatically open the overlay
     // once the overlay has been opened, the metric/filter will never be
     // considered new again.
-    this.props.adhocFilter.isNew = false;
```
Comment (mistercrunch) [inline superset-frontend/src/explore/components/AdhocFilterOption.jsx:63]: mutating a prop? that wasn't ok!

File: superset-frontend/cypress-base/cypress/integration/explore/advanced.test.ts [hunk 3]
```diff
@@ -87,7 +87,7 @@ describe('Annotations', () => {
         .within(() => {
           cy.get('input').type('y=1400000');
         });
-      cy.get('button').contains('OK').click();
+      cy.get('button').contains('OK').click({ force: true });
```
Comment (mistercrunch) [inline superset-frontend/cypress-base/cypress/integration/explore/advanced.test.ts:90]: Screen Shot 2020-10-23 at 6 34 01 PM

Comment (mistercrunch) [reply superset-frontend/cypress-base/cypress/integration/explore/advanced.test.ts:90]: bycatch, random cypress/CI failure

File: superset-frontend/src/explore/components/AdhocFilterOption.jsx (hunk 2 above)
Comment (kgabryje) [reply superset-frontend/src/explore/components/AdhocFilterOption.jsx:63]: As I wrote in https://github.com/apache/incubator-superset/pull/11428, although mutating a prop certainly isn't ok, it might not be that simple to fix it. I encountered many problems with auto-opening popup when I tried to copy your solution or to make a new state variable. I think replacing that ugly line requires a more serious refactor

**Comment by mistercrunch** [comment]
@kgabryje do you want to take it from here? Sounds like you know about some edges I did not encounter.

File: superset-frontend/src/explore/components/AdhocFilterOption.jsx (hunk 2 above)
Comment (ktmud) [reply superset-frontend/src/explore/components/AdhocFilterOption.jsx:63]: Mutating the prop of the object passed to the component was the simplest and most efficient way to update the select option state without forcing rerenders, and it's probably not as bad as it seems because we know no other places depend on this prop.

If you want to eliminate the need of mutating a prop, you should propagate the updated `adhocFilter` back to the select options by triggering the `onChange` event on `AdhocFilterControl` (which could have its own problem because of rerenders).

Comment (kgabryje) [reply superset-frontend/src/explore/components/AdhocFilterOption.jsx:63]: I tried triggering `onChange` and just like you said, rerenders caused a whole bunch of new issues. So I think we can keep it as it is

**Comment by kgabryje** [comment]
@mistercrunch Beside the changes in `AdhocFilterOption`, the rest looks good to me. After we merge this PR and mine, there will be 1 issue related to Popup refactor left and I can take it.

File: superset-frontend/src/explore/components/AdhocFilterOption.jsx (hunk 2 above)
Comment (mistercrunch) [reply superset-frontend/src/explore/components/AdhocFilterOption.jsx]: Ok, punted on changes to that file in favor of https://github.com/apache/incubator-superset/pull/11428

**Review by nytai — APPROVED** [review]
