### PR TITLE
fix: preserve correct column order when table layout is changed with time comparison enabled

### LINKED ISSUE #34134: Changing the Layout of the table chart produces misaligning of column names displayed
### Bug description

When you create an aggregated Table chart and activate the Time comparison section, once you add the chart to a dashboard and use the option to change its layout, the column names get displayed in an incorrect order, producing confusion when you read the data.

## Reproduction:
1. Create a table chart with some aggregated data
2. Assign a date filter interval
3. Assign an option to the Time Comparison section
4. Add multiple metrics
5. Change the table layout by hiding some comparison types

## Expected results
When you change the Layout of the table, the column names should not move

## Actual results
The column names are overlapped in an incorrect order

### Screenshots/recordings

_No response_

### Superset version

master / latest-dev

### Python version

3.11

### Node version

18 or greater

### Browser

Firefox

### Additional context

_No response_

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by payose**
SUMMARY
This PR fixes a bug where the column names in an aggregated Table chart get displayed in the wrong order after changing the layout, especially when the Time Comparison feature is enabled. The issue was causing column headers to become misaligned or overlapped, leading to confusion when interpreting the data.

Fixes #34134
Fixes #34300

Design decisions:
Introduced logic to consistently map metric columns and time comparison columns in the correct order during layout updates.

Ensured the internal data structure reflects the original metric ordering regardless of layout toggles.

BEFORE/AFTER SCREENSHOTS
Before:
image

Column names appear in the wrong order or overlapped after layout change.

After:

image

Column names remain consistent and correctly ordered even after changing the layout.

TESTING INSTRUCTIONS
- [ ] Create a Table chart with aggregated data and multiple metrics.
- [ ] Assign a date filter interval.
- [ ] Enable the Time Comparison feature (e.g., “Previous period” or “1 year ago”).
- [ ] Add the chart to a dashboard.
- [ ] Use the dashboard layout editor to hide/show comparison columns.
- [ ] Verify that the column names remain correctly ordered and are not overlapping.

ADDITIONAL INFORMATION
Has associated issue: Fixes #34134

### CODE REVIEW

File: superset-frontend/plugins/plugin-chart-table/src/TableChart.tsx [hunk 1]
```diff
@@ -629,7 +629,11 @@ export default function TableChart<D extends DataRecord = DataRecord>(
       const startPosition = value[0];
       const colSpan = value.length;
       // Retrieve the originalLabel from the first column in this group
-      const originalLabel = columnsMeta[value[0]]?.originalLabel || key;
+      const firstColumnInGroup = filteredColumnsMeta[value[0]];
```
Comment (msyavuz) [inline superset-frontend/plugins/plugin-chart-table/src/TableChart.tsx]: Can't we use startPosition here?
```suggestion
      const firstColumnInGroup = filteredColumnsMeta[startPosition];
```

**Review by msyavuz — COMMENTED** [review]
Works great, Thanks! Just a nit

**Review by msyavuz — APPROVED** [review]
LGTM, Thanks!
