### PR TITLE
fix: Unable to create alerts/report after introduced creation_method

### LINKED ISSUE #15759: [Alerts/Reports] bug: Unable to create alerts/report without creation_method
We introduced new `creation_method` flag in #15685 and we haven't update the Alerts/Reports page which cause error while creating new report. 

### Expected results

Alerts/Reports are created with `creation_method=alerts_reports`

### Actual results

Unable to create Alerts/Reports

#### How to reproduce the bug

1. Go to http://localhost:9000/alert/list/ to create new Alert
2. Click on '+ Alert'
3. Fill all needed information 
4. See error `An error occurred while creating reports: (creation_method) Missing data for required field.`

### Environment

(please complete the following information):

- superset version: master at commit e9383e6d002d41002a985c9e931a4898635402ba
- python version: 3.7
- node.js version: v14.15.5

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by duynguyenhoang**
### SUMMARY
Add default creation_method='alerts_reports' in Alerts/Reports page

### ADDITIONAL INFORMATION

- [x] Has associated issue: 
  - [x] Fixes #15759, 
  - [x] Relates to #15685
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by graceguo-supercat — APPROVED** [review]
LGTM

File: superset-frontend/src/views/CRUD/alert/AlertReportModal.tsx [hunk 1]
```diff
@@ -123,6 +123,7 @@ const DEFAULT_WORKING_TIMEOUT = 3600;
 const DEFAULT_CRON_VALUE = '0 * * * *'; // every hour
 const DEFAULT_ALERT = {
   active: true,
+  creation_method: 'alerts_reports',
```
Comment (john-bodley) [inline superset-frontend/src/views/CRUD/alert/AlertReportModal.tsx:126]: @duynguyenhoang because this fixes a regression is it possible to add a unit test?
