### PR TITLE
fix: Safari is not showing scroll bars in Explore

### LINKED ISSUE #16072: [Explore][Safari] Scroll bar is gone when open explore in Safari
Scroll bar is gone when open explore in Safari

### Expected results

User can scroll up and down in data panel

### Actual results

User can not scroll up and down in data panel when open in Safari

#### Screenshots

https://user-images.githubusercontent.com/81597121/128250323-7e4f10c1-0431-4a84-8736-ff046011efa7.mov

#### How to reproduce the bug

1. Open superset in Safari
2. go to explore
3. try scroll up and down

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Fix https://github.com/apache/superset/issues/16072

@junlincc @jinghua-qa @rusackas 

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/70410625/128354308-b59a6557-f8bd-4bab-8e1b-70167adc626b.mov

https://user-images.githubusercontent.com/70410625/128354409-dda33190-f0f0-4356-b262-96782e20452d.mov

### TESTING INSTRUCTIONS
See the original issue for instructions.

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/explore/components/ExploreViewContainer.jsx [hunk 1]
```diff
@@ -458,7 +459,7 @@ function ExploreViewContainer(props) {
           #app {
             flex-basis: 100%;
             overflow: hidden;
-            height: 100vh;
+            height: 100%;
```
Comment (michael-s-molina) [inline superset-frontend/src/explore/components/ExploreViewContainer.jsx:462]: The `#app` should account for `#app-menu` height. That's why I change it to percentage and set the `body` to `100vh`.

**Comment by junlincc** [comment]
thank you so much for the quick fix! 
https://user-images.githubusercontent.com/67837651/128408432-6f035ca2-de27-4d85-96f5-efabb4311fa8.mov

looks like the top padding is missing?

**Review by junlincc — DISMISSED** [review]
padding above run buttons is missing 😅

**Comment by michael-s-molina** [comment]
@junlincc I wasn't able to reproduce this behavior in the test env. Tested in Safari and Chrome. 🤔 

https://user-images.githubusercontent.com/70410625/128420570-1a9d165a-49ed-455b-a5f2-7e12f94c8fd2.mov

**Comment by kgabryje** [comment]
@junlincc I'm not able to reproduce as well

**Review by rusackas — APPROVED** [review]
LGTM!

**Comment by michael-s-molina** [comment]
@junlincc Can you unblock?

**Comment by rosemarie-chiu** [comment]
🏷 2021.31
