### PR TITLE
Syncing the timeout param from backend

### LINKED ISSUE #3030: flawed logic in the new visualization timeout
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.18.5

### Expected results

adhere to webserver/worker's timeouts e.g. as per the `-t` flag to `superset runserver`, or if superset is behind a reverse-proxy to that proxy's timeout

### Actual results

adhere to hardcoded value in javascript client - 45 seconds

### Steps to reproduce

`superset runserver -t 300` will still show that a 60s query times out, because the timeout is set to 45 seconds in `constants.js`, despite 60 < 300

*NOTE* problem stems from https://github.com/airbnb/superset/pull/2763 which, for reasons that I cannot see nor guess, did not address the core problem: handle the `504 Gateway Time-out` status code of the ajax call and instead implemented a client-side timeout / ping @graceguo-supercat

### PR DESCRIPTION
**Pull request by mistercrunch**
Before, the client-side timeout was hard coded and not aligned with the backend's setting. You would have to recompile the JS bundle with a different value if you wanted to change it.

Now the value set in `superset_config.py` is sent to the client and the client will timeout regardless of it gets a web response or not.

fixes https://github.com/apache/incubator-superset/issues/3030 (I think?)

### CODE REVIEW

**Comment by xrmx** [comment]
A couple of late comments:
- docs/faq.rst needs update as it still references QUERY_TIMEOUT_THRESHOLD
- why a default is needed in superset/assets/spec/javascripts/sqllab/VisualizeModal_spec.jsx if we are reading it from the config? And if we need it why 45 and not 60 as the backend?

**Comment by andreineculau** [comment]
yup, I was going to make the same comment as @xrmx above - why is a default needed in the first place?

**Comment by mistercrunch** [comment]
2 - @andreineculau @xrmx it's a fixture for the unit test

**Comment by maxsonic** [comment]
@mistercrunch I got the timeout in the slice panel. It seems that the default timeout in the runQuery is 60s and it is not synced with the timeout set in the superset_config.py.

image

**Comment by xrmx** [comment]
@maxsonic that's a default, the caller should be updated

**Comment by tuziluobu** [comment]
What's the value which the client will timeout regardless of it gets a web response  set in superset_config.py ？

File: superset/assets/javascripts/SqlLab/components/VisualizeModal.jsx [hunk 1]
```diff
@@ -133,12 +133,13 @@ class VisualizeModal extends React.PureComponent {
   }
   buildVisualizeAdvise() {
     let advise;
+    const timeout = this.props.timeout;
     const queryDuration = moment.duration(this.props.query.endDttm - this.props.query.startDttm);
-    if (Math.round(queryDuration.asMilliseconds()) > QUERY_TIMEOUT_THRESHOLD) {
```
Comment (sidSingla) [inline superset/assets/javascripts/SqlLab/components/VisualizeModal.jsx]: Can anyone tell which is the new constant supplanting QUERY_TIMEOUT_THRESHOLD.

Comment (xrmx) [reply superset/assets/javascripts/SqlLab/components/VisualizeModal.jsx]: SUPERSET_WEBSERVER_TIMEOUT

Comment (sidSingla) [reply superset/assets/javascripts/SqlLab/components/VisualizeModal.jsx]: Thanks @xrmx . why this name got changed ?

**Comment by tuziluobu** [comment]
"Query timeout - visualization query are set to timeout at 60 seconds. Perhaps your data has grown, your database is under unusual load, or you are simply querying a data source that is to large to be processed within the timeout range. If that is the case, we recommend that you summarize your data further."

please How to resolve the problem？ I set SUPERSET_WEBSERVER_TIMEOUT=600 in superset_config.py,but It's  not work。
