### PR TITLE
fix(dashboard): recursive parent on dashboard components

### LINKED ISSUE #16436: Issue adding chart to dashboard in version 1.3
In version 1.3 when adding a chart to a dashboard via dashboard edit mode, it throws an error in an arbitrary fashion. So cannot share exact steps to recreate the issue.
Add chart to dashbaord

### Stacktrace
`Traceback (most recent call last):`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/superset/views/base.py", line 204, in wraps
    return f(self, *args, **kwargs)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/superset/utils/log.py", line 241, in wrapper
    value = f(*args, **kwargs)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/superset/utils/cache.py", line 167, in wrapper
    return f(*args, **kwargs)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/superset/views/utils.py", line 472, in wrapper
    return f(*args, **kwargs)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/superset/views/core.py", line 664, in explore_json
    return self.generate_json(viz_obj, response_type)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/superset/views/core.py", line 462, in generate_json
    payload = viz_obj.get_payload()`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/superset/viz.py", line 455, in get_payload
    payload["data"] = self.get_data(df)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/superset/viz.py", line 936, in get_data
    df = df.stack(0).unstack().reindex(level=-1, columns=metrics)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/pandas/util/_decorators.py", line 312, in wrapper
    return func(*args, **kwargs)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/pandas/core/frame.py", line 4176, in reindex
    return super().reindex(**kwargs)`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/pandas/core/generic.py", line 4811, in reindex
    return self._reindex_axes(`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/pandas/core/frame.py", line 4016, in _reindex_axes
    frame = frame._reindex_columns(`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/pandas/core/frame.py", line 4058, in _reindex_columns
    new_columns, indexer = self.columns.reindex(`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3509, in reindex
    _, indexer, _ = self._join_level(`
`File "/home/ubuntu/superset1.1/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3880, in _join_level
    assert isinstance(left, MultiIndex)`
`AssertionError`
`2021-08-24 07:31:36,933:ERROR:superset.views.base:`

### Environment
- superset version: `1.3`
- python version: `3.9`
- pip install method

cc: @villebro

### PR DESCRIPTION
**Pull request by villebro**
### SUMMARY
When a component is dropped directly under a tab in the dashboard editor and the cross filter feature flag is enabled, the following error sometimes appears:
image

This is caused by the dashboard creating a wrapper component that marks itself as its parent, causing an infinite loop when traversing all children in the cross filter indicator. The reason for this was a logical error in the code, where the wrapper id was supposed to be added to the wrapped component, but ended up being added to the wrapper itself. Tests are added to check for this going forward.

### DETAILS

When dropping a a component on the dashboard that requires wrapping (in this case dropping a markdown component directly on a tab, but could also be a chart, or column object: https://github.com/apache/superset/blob/87baac7650bdb6a8f8f82cf4992567a2c5c73cba/superset-frontend/src/dashboard/util/shouldWrapChildInRow.js#L27-L39), the component is wrapped in a wrapper component (in this case a ROW component). However, the wrapper adds itself as it's own parent, while it should add itself to the wrapped component:
image

Interestingly enough, after saving the dashboard, the layout metadata is fixed:
- the wrapped component correctly references the wrapper as its closest parent
- the wrapper no longer references itself

See the screenshot below for the post-save state:
image

With the changes in this PR, the parents are correct after creation, i.e. won't change after saving.

This bug exposed several problems in the associated code, causing unnecessary performance problems. However, these should be fixed in follow-up PRs.

### TESTING INSTRUCTIONS
Local testing

### ADDITIONAL INFORMATION

- [x] Has associated issue: closes #16436
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by michael-s-molina — APPROVED** [review]
LGTM. Thanks for the detailed description.

**Comment by geido** [comment]
/testenv up FEATURE_DASHBOARD_NATIVE_FILTERS=true FEATURE_DASHBOARD_CROSS_FILTERS=true FEATURE_DASHBOARD_NATIVE_FILTERS_SET=true FEATURE_DASHBOARD_FILTERS_EXPERIMENTAL=true

File: superset-frontend/src/dashboard/util/newEntitiesFromDrop.js [hunk 1]
```diff
@@ -51,8 +51,8 @@ export default function newEntitiesFromDrop({ dropResult, layout }) {
     rowWrapper.children = [newDropChild.id];
     rowWrapper.parents = (dropEntity.parents || []).concat(dropEntity.id);
     newEntities[rowWrapper.id] = rowWrapper;
-    newDropChild = rowWrapper;
     newDropChild.parents = rowWrapper.parents.concat(rowWrapper.id);
+    newDropChild = rowWrapper;
```
Comment (villebro) [inline superset-frontend/src/dashboard/util/newEntitiesFromDrop.js:55]: The intent here was clearly to add the wrapper as the parent to the wrapped component - due to the incorrect order here the wrapper's id was incorrectly added to the wrapper's parents, not the wrapped component's ids.

**Review by michael-s-molina — APPROVED** [review]

**Comment by geido** [comment]
/testenv up FEATURE_DASHBOARD_NATIVE_FILTERS=true FEATURE_DASHBOARD_CROSS_FILTERS=true FEATURE_DASHBOARD_NATIVE_FILTERS_SET=true FEATURE_DASHBOARD_FILTERS_EXPERIMENTAL=true

**Comment by junlincc** [comment]
Tested by adding charts to different level of tabs in the sales dashboard, with charts, components being added and removed a few times, not seeing errors. Thank you for the fix! @villebro 
Curious to know why this issue is not reproducible consistently?

**Review by geido — APPROVED** [review]
LGTM!

**Comment by kgabryje** [comment]
Thanks for a very detailed description of the issue!
