### PR TITLE
[Bugfix]: Fixing bug in label generation for multiple groupbys

### LINKED ISSUE #3590: label for first group by clause in time series - bar chart is always undefined
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.20.1

### Expected results

the first label in the legend is the same as the group clause

### Actual results

the first group by clause label is undefined

### Steps to reproduce

Create a time series bar chart with multiple group by clauses, the first will have an undefined label

### PR DESCRIPTION
**Pull request by fabianmenges**
Fixes: #3590 
Relates to:  #3504 #3563 #3566

I guess I started this so I'll take 99% of the blame here:

## History:

1. #3504 caused a bug where the metric names would be displayed in the legend even when there was only one metric.
2. #3563 fixed that bug, but caused #3590 where the legend for multiple group by s does not get generated correctly
3. #3566 would have fixed both issues but came too late

So we either apply this fix or roll back #3563 and apply #3566 

Hopefully this is the last issue :(

### CODE REVIEW

File: superset/assets/visualizations/nvd3_vis.js [hunk 1]
```diff
@@ -77,17 +77,16 @@ function getMaxLabelSize(container, axisClass) {
...
-  if (verbose_map) {
-    if (Array.isArray(column) && column.length) {
-      label = verbose_map[column[0]];
-      if (column.length > 1) {
-        label += `, ${column.slice(1).join(', ')}`;
-      }
-    } else {
-      label = verbose_map[column];
+  if (Array.isArray(column) && column.length) {
+    label = verbose_map[column[0]] || column[0];
```
Comment (mistercrunch) [inline superset/assets/visualizations/nvd3_vis.js]: Is it a safe assumption that metric is always in position 0? 

`const label = column.map(s => verbose_map[s] || s).join(', ')` may be more elegant but it may "verbosify" dimension members instead of metrics (collisions are probably rare and not super problematic). This problem exist here too as in this current case column[0] could be a metric or a dimension member anyhow.

Now I'm thinking verbosifying could be done in the backend where we know what is a metric or a dim member (this info is lost on the frontend). I know I said to verbosify it in the frontend earlier. What I wanted to avoid was using verbose names in dataframe column headers...

In any case I'll merge this to fix the bug and we can revisit later if needed.

Comment (fabianmenges) [reply superset/assets/visualizations/nvd3_vis.js]: Yeah, so my change for renaming on the backend is still around somewhere #3437.

Anyways your change #3563 as well as the original code also assumed it in the first position. 
There are some advantages (that we currently don't use) to do it in the front end. 
E.g. we could have a checkbox that would you switch between them or you could have custom verbose maps per slice instead of per datasource. And updating the charts would not require requests to the application.

So if we document and define that metrics always have to come before groupys we should be fine doing it in the UI.
