### PR TITLE
fix: Reordering echart props to fix confidence interval in Mixed Charts

### LINKED ISSUE #30554: Confidence Interval Does not work properly for Mixed Charts
### Bug description

I’ve noticed that the confidence intervals in charts do not display correctly at all after Superset 3. There was also an issue previously that it wouldn’t show negative values of confidence intervals. The way to set them up is using (name_yhat for actual value; nameyhat_upper for upper bound; and name_yhat_lower for lower bound). However, they now result in unexpected behaviour. 

Prior to the superset 3.0, the intervals would only work for positive values. If an interval goes into the negative it is not plotted, and only the positive values are. If the full chart is in the negative domain the confidence interval is plotted in the positive area.

[What is currently being sent](https://echarts.apache.org/examples/en/editor.html?version=5.5.0&code=PYBwLglsB2AEC8sDeAoW7YCICuBnApgKoAqAwpgFyxgBO2-ANGhpgOY0QAmlyzGLAYxhgAhhGgAZEQCN8AGx616Tfv0xz8AMzA8AzAFYVq9Jg6sAFjqoAmAAxHjmMKB4AWe31WZpwMM4C2PHaeAL4OWAAeAIIRELg8qMYmYACeIPg8mABuInL0mOFq0CL--ADiIiA8AIyGnkUl-BLAAiKQMJn-XJwaBfUsIrG4UrIKVEhh_SZd0MA0xBACANYJk0lYMwCS0GD4NDljsB7rmDOZnG0iALLifSf-g-eXV4-h4ZgpMXE8ANpTvOs1J8hiN5AAlXxtKDQHjHQHJNIZKjZXL5QpJU7iOYLZardGOGZzADKIDkEDAEnESOQa3hWEGcVBhwm-K8xVKFSqVFqrIapWarXaMORXU4PQyvIGZNY0BxS3iVE0uQI_1pxkSdI-X2GMnBkKFsMlCPSmQOaP-akJ80WK3GasBmFwpPJlOg1I1dJYuHMwAA7jwlXIVZ77fcsTQSWSKVS8RaBiDdczQxjchAZXKFbBA8GkiFPABdd7OYBySBcgEpkDpaCcYjAABCwE4KUUdEY_0dPv9VCU7ZOtDTrD2mQZ8TennU-CHNYSHbmEHwO0yPo4AC9hLk7hjvX7W8oO6kTcjcAIaCWFKzHfJ8AJnDRfnGTLkL4-sOIsnsCJh_oWOwQNLecxMrOnqYJowgAGIlBAcgtsiADk2y7DQ8EMLAAAS8gfpArRoVEHCbkaWDgTsRIQKu1LVNYRGYEIchzJkADEABsrFsVu8LeHMnB7KQJYMciLFsax37rMmyQuFQcKOGYliGh2FyiA-oERBxDq-OYw4_uOagEBw-CZn86weg6XCZBEAD6FkpOYbQWdgVbDjR7LUpgqk0YpIjKZ6GBGT5xjWHU_kBbYr78L-wWwH5kXoNYADsRHrMEkURcF0UxdYAAciVJMlwWpf56WRdYACcOUhWFGAFT5RXBbo0kZaFKXlVFlXGLo1QtfweX-dVnq1f5ujUW1qg9T5fV0gNPm6K4XUYGNnoTfCU2egYc2xU1-UtStdLuOtsALXS-avktXgAI70DQKTbDxqlSTRwJxDd-B3UcNHkvg_hEqkvTjCNtH8fegnVBBUSZaQJVqaBoAiAI5JwbA1SvuJXiHq5ZJulD27-MAGkBsqfaagOrBDjQrr4AAoh-S49m2NG4KIuLIu5r6OozSzfTQbRTgjmDPljjgY_g30pL9Fb-ZgMNw6ksLIzRIg0PgIgi2LJnQyAsPw7CAB01hy6zn0gLZuDfH9kXqFSKvuiNai-lwYDmJkPhyDx94jXmIb012RIpP4zv40GhOcbgvvO2RFE8MxNFyImIHBZ2u6KgTLWYCAwAmwayLOFUyOqqyasYmZzNWTZdn0b6Tmsy55kC14nneYVNvzUFMXoNUm29dtTexQl3eIx341d63sXZX37cjad6w7fCpX7ePzUjdPgL1XPA-LUPw8davE8b63Q3bwvkVL-sM0H1ti992tY9r0du8xXt18TydNEXXs101i98mgY9uDPa9DUnA-l9H61tzZ0QElgRirh9CuApnFcgKcpZaykvrUCaNMhC1rrpHGeMk6BxosTUm5MqaLisNQOmrMGaw1tJELBXp2ac25qwXm_No6WxAXHCWSCZYoM9gbfwRsRAm0zAXTiQsracJipgO2nAHZOxLK7USwUPZ0hRrpb2ocSwBwIPTTRchw7UijqzGOoxJGgR3N2LMyd_ppwztCTI2clHwhUcYFGoivBF1oc5RoNcPKXAbjVPugU576B3hfYeB1e4RNqGEo-QTR7RNCYfNKQSypjySefOJESV7pNiSk7JnVcnJMbtk4aiS8klM3rNIpmT8mbxbq3GJxTAkRIfuUlKz9Wavyun_L-mof69PuqzIBEizbx3AUDSB-goikGqJlSGiCNbSwRjfVxBDEQYJjPTHBci8E6NZoQvYxDqZkN7PTBhtAmG81wI0E2Mo6EmHERwsZXClnIMRqgzUhtjam3Fj5C2bpRl_PNjI3ZWBnaKPdinEZzzgXx24QjJGkUXGAjUV6DRfstG033OYvRBjI7R1ji8_5FjtFB3-bY8k9is4uFzmJfOwzuDIg0pXUC1dmUO1ZZqeuVBj6-SCQ0mKSLamVNbvFOeFSWnDyyhK5p_VUmypFVKveADgrCs7uEzehTomSvlaUxVGqslVINYPTVe9BWRXVaao1rc2nDytYtTpoFunv1ujUB62pBlvWGbsYBotQHjMBkxCCEE4oQVcK4B5XgEU1E-ZxdBx5BTISjY6HZjs9nkv7GYIhVISE03ITizUVDliMN2MwzINzSh3JhGwwFsL3EnBjdyONDpvlCN-Q2jETz_VmPjqC9N4KFFaWRS2k4FifaYsOGcyheLyKGMJaY4l5iuxkpTpSzOWBHF0tzAWIsuM5A-Feu4pwklvUnFkmQi1LBNBKzANgRWvbHCeQAFq40CEu_pnqP6vWzJmom5JVZ90wOuYA76sAgf8LABWSso0nGkNQzIisGZzHwLACDTifIorEqqHSLAX1vt-MdEIABuIAA)

[What should actually be sent](https://echarts.apache.org/examples/en/editor.html?version=5.5.0&code=PYBwLglsB2AEC8sDeAoWsCuBnApgVQBUBhALljACcMcAaNWAcwogBMzV10BjGMAQwjQAMnwBGOADZlK1Op1gScAMzBkAzAFY5nZgwAWq2ACYADNvRhQZACxn66UcDCWAtmVP0AvtoAeAQR8ILHZ7cgBPEBwyAHJIFxxo81hoPniAcT4QMgBGLVCU-KFgLj5IGBiXVhZFRNC-QKwRcSlkb1DK6GAKAgguAGt2NvkOgEloMBwKADc-FrthwRiWUr4AWUFa4fqlldX66K9tMICgsgBtUI55WGOGpskAJSdSqGgyeeuwCKjYaJmJaiba4dLo9fqDJLoEEUADKIAkEDAQkEPyQQ2u9SC9xaaMhyVSOAyWVguTxBRwRRKZTev0qLGqCTxswgDGgYL6wVgSlmuFC6PQV3ktyxYkez2p7zxX0iMX-gLx0PZENC6Cw8MRyOgqJVnCwemAAHcyNyJLzrrB-ZxoXCEUiUcrzZjGqKcZb0MzWezOSazZxPPQALraSzACSQYmC2CZSLQFgEYAAIWALDC0iotFCesNadkoUoLIYkxiToO6HRikLsZC8i6EBw4xi-uYAC9eLMgar9UbyOmktKftEsFwKKGJB3YLhFFxLBRztFZmOaL9BFNJrhokHM5IcNOutjq9clLwAGKpCASVOwABE0TGEwoiVgAAlJKvICUl35mLMr3ij-MYQgZsfmyIw8R4CQuhiABiAA2eCEPHBwuhYSYiFDKDfjghD4NLP0-ysWAPnQXQDElUJln4OcfEfaInD0SYN0OehcGYHBOQueRI3QVgYh8AB9fiwj0Up-Mgg1GLJAk-KQ2BKL4c4dXQM4jC0EkTE3c1lKMAB2Jdsg0vFtIADn0wylNgFSAE4zM0rSzjUMx1Ls80HOyWyjMstQwOczyHOsDyLIctSDJc64zlsWydTC9AAEdqAoMIxlQnxyPNYUsGSnBUqIvFERwFwYS-RQD3NCDMOiaDrA0awAFEdKIWT0FAPguERS9sh1N1whlX4ES1WSsBcYB6ONHkM3NfMGELChNRwWrVwbHtc3NLB-HBX4aLxNbWr6IqKFKHAGEvecJEXHV-pwIqwhK5ALJatqvneLq8QKkARKwU47q0hQUWu27uOuA1WDAPQYkcCRUIfCz_XNbqswNGEwhcCGxtNCbriwZGIcA4CyFgvEJBdUrMa7NHcE8kBgE-iVfksEA8PkWH8MuHVeM2wThNEjAQEiB8pPiGS8XkxSfpUkLzLF3TAql0zfKCowbPlsXHJl-y1Hc5X1Z80K_LUAKtdczQ1dcyLnOivF4smJLY2ytLrgyrKcuIzh8sK4rtR-8rZyw7Jjz8YyiCsprYAe9qchenV-xiS7BuG0auXGqVdBmuaFvrQwZAx-Qdo26Itp1XO9soQ7juLM7ZMu_7Pa0sOnqIyPHQoHA-GrkmaxAVrw6IgA6IxG-uN6Pq-wH0Crj326BkGwd-CGocZ65maZ7auyRlHQ3J7PdWx0NcZ-AmLuJ76tIRzfKepxFXhiemF7LPkkkB9n89k8khZ1EXLIVkKNBizgVL0kkP8_JGDlrkX-2klZgL1k5KBQUNb6SAXAnWiCVYG1gSrb-4DLJmzARbHUVtEpO3tkKE4mVbbOzyhMd2N0a5lQwj7SqGg_BEGyMZYOnk66XhMAPeQ0c-oojjiNUGZ8o4p0mGnRamdeyF3WsXA6Ewy6_CwAST6rJK5_Qnsfc0nCI5w1ei4d6fBPqclHr9LUbctFaWBiwYRs9Qzzxhp5N2FjTHNU7o9DqMMeG6lXjvFoWdtp-L3vjQmR9TGn0Tujc-NMr501ALfC099WbmifvRSSOpX6_DSfzd-KxRb2VUvpLB_8inANAcUxWpS4EwOKfAkktSda1LQbUkKxSzaOQDHg80BCbYpRyHiR25DiGuyoS4iy3sYLHmPDpY81hrAhx0SSbxFhvgxCHKUe8giE4-i3hYMRs0UTpyWgEmRu19qlxOso-IqjoDqPMZo0xizOp6J1EPIxI8LLjxoZPeQ1jbHRDnoxLxLzVq-PXv46Rq0glAX3qE5oPyJxk0iRTCyVMYnlDiQzLqfJAzBhGhIRwOVIz02GaRQweR5BKBbmADAzdJ7yQAFojTcJYkhDQiHIt2ZwSAYAAYWXQK2YALLoiCpcFGZufAQ4OF2jEZua0ug4FgKKhJd84Y4rLNoRlzLzidM8AAbiAA)

Modifying the order of the inputs currently has an impact on how the behaviour of the mixed charts works due to a bug in echarts. This aims to resolve that issue on superset's end

### Screenshots/recordings

_No response_

### Superset version

3.1.3

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by geotab-data-platform**
### SUMMARY

The root cause of this problem lies within the order of the arguments sent to the echarts library. When working with time-series data, Echarts enforces specific constraints on how the x-axis bounds are configured. These constraints include:
In other words, the Echarts Library accepts input in this specific format and will malfunction otherwise. Superset does not create the Echarts modal with the options in this order.
 
*  The `xaxis.type` option must be explicitly set to `'time'`.
*  The `upper` and `lower` bound values must be equal to the lower bound.
*  The `upper` bound must be defined before the `lower` bound in the options object.

Currently, the code in Superset that generates the Echarts configuration does not adhere to this required format, leading to the observed malfunction. This pull request rectifies this issue by reordering the `upper` and `lower` bound arguments before they are passed to the Echarts library.

[What is currently being sent](https://echarts.apache.org/examples/en/editor.html?version=5.5.0&code=PYBwLglsB2AEC8sDeAoW7YCICuBnApgKoAqAwpgFyxgBO2-ANGhpgOY0QAmlyzGLAYxhgAhhGgAZEQCN8AGx616Tfv0xz8AMzA8AzAFYVq9Jg6sAFjqoAmAAxHjmMKB4AWe31WZpwMM4C2PHaeAL4OWAAeAIIRELg8qMYmYACeIPg8mABuInL0mOFq0CL--ADiIiA8AIyGnkUl-BLAAiKQMJn-XJwaBfUsIrG4UrIKVEhh_SZd0MA0xBACANYJk0lYMwCS0GD4NDljsB7rmDOZnG0iALLifSf-g-eXV4-h4ZgpMXE8ANpTvOs1J8hiN5AAlXxtKDQHjHQHJNIZKjZXL5QpJU7iOYLZardGOGZzADKIDkEDAEnESOQa3hWEGcVBhwm-K8xVKFSqVFqrIapWarXaMORXU4PQyvIGZNY0BxS3iVE0uQI_1pxkSdI-X2GMnBkKFsMlCPSmQOaP-akJ80WK3GasBmFwpPJlOg1I1dJYuHMwAA7jwlXIVZ77fcsTQSWSKVS8RaBiDdczQxjchAZXKFbBA8GkiFPABdd7OYBySBcgEpkDpaCcYjAABCwE4KUUdEY_0dPv9VCU7ZOtDTrD2mQZ8TennU-CHNYSHbmEHwO0yPo4AC9hLk7hjvX7W8oO6kTcjcAIaCWFKzHfJ8AJnDRfnGTLkL4-sOIsnsCJh_oWOwQNLecxMrOnqYJowgAGIlBAcgtsiADk2y7DQ8EMLAAAS8gfpArRoVEHCbkaWDgTsRIQKu1LVNYRGYEIchzJkADEABsrFsVu8LeHMnB7KQJYMciLFsax37rMmyQuFQcKOGYliGh2FyiA-oERBxDq-OYw4_uOagEBw-CZn86weg6XCZBEAD6FkpOYbQWdgVbDjR7LUpgqk0YpIjKZ6GBGT5xjWHU_kBbYr78L-wWwH5kXoNYADsRHrMEkURcF0UxdYAAciVJMlwWpf56WRdYACcOUhWFGAFT5RXBbo0kZaFKXlVFlXGLo1QtfweX-dVnq1f5ujUW1qg9T5fV0gNPm6K4XUYGNnoTfCU2egYc2xU1-UtStdLuOtsALXS-avktXgAI70DQKTbDxqlSTRwJxDd-B3UcNHkvg_hEqkvTjCNtH8fegnVBBUSZaQJVqaBoAiAI5JwbA1SvuJXiHq5ZJulD27-MAGkBsqfaagOrBDjQrr4AAoh-S49m2NG4KIuLIu5r6OozSzfTQbRTgjmDPljjgY_g30pL9Fb-ZgMNw6ksLIzRIg0PgIgi2LJnQyAsPw7CAB01hy6zn0gLZuDfH9kXqFSKvuiNai-lwYDmJkPhyDx94jXmIb012RIpP4zv40GhOcbgvvO2RFE8MxNFyImIHBZ2u6KgTLWYCAwAmwayLOFUyOqqyasYmZzNWTZdn0b6Tmsy55kC14nneYVNvzUFMXoNUm29dtTexQl3eIx341d63sXZX37cjad6w7fCpX7ePzUjdPgL1XPA-LUPw8davE8b63Q3bwvkVL-sM0H1ti992tY9r0du8xXt18TydNEXXs101i98mgY9uDPa9DUnA-l9H61tzZ0QElgRirh9CuApnFcgKcpZaykvrUCaNMhC1rrpHGeMk6BxosTUm5MqaLisNQOmrMGaw1tJELBXp2ac25qwXm_No6WxAXHCWSCZYoM9gbfwRsRAm0zAXTiQsracJipgO2nAHZOxLK7USwUPZ0hRrpb2ocSwBwIPTTRchw7UijqzGOoxJGgR3N2LMyd_ppwztCTI2clHwhUcYFGoivBF1oc5RoNcPKXAbjVPugU576B3hfYeB1e4RNqGEo-QTR7RNCYfNKQSypjySefOJESV7pNiSk7JnVcnJMbtk4aiS8klM3rNIpmT8mbxbq3GJxTAkRIfuUlKz9Wavyun_L-mof69PuqzIBEizbx3AUDSB-goikGqJlSGiCNbSwRjfVxBDEQYJjPTHBci8E6NZoQvYxDqZkN7PTBhtAmG81wI0E2Mo6EmHERwsZXClnIMRqgzUhtjam3Fj5C2bpRl_PNjI3ZWBnaKPdinEZzzgXx24QjJGkUXGAjUV6DRfstG033OYvRBjI7R1ji8_5FjtFB3-bY8k9is4uFzmJfOwzuDIg0pXUC1dmUO1ZZqeuVBj6-SCQ0mKSLamVNbvFOeFSWnDyyhK5p_VUmypFVKveADgrCs7uEzehTomSvlaUxVGqslVINYPTVe9BWRXVaao1rc2nDytYtTpoFunv1ujUB62pBlvWGbsYBotQHjMBkxCCEE4oQVcK4B5XgEU1E-ZxdBx5BTISjY6HZjs9nkv7GYIhVISE03ITizUVDliMN2MwzINzSh3JhGwwFsL3EnBjdyONDpvlCN-Q2jETz_VmPjqC9N4KFFaWRS2k4FifaYsOGcyheLyKGMJaY4l5iuxkpTpSzOWBHF0tzAWIsuM5A-Feu4pwklvUnFkmQi1LBNBKzANgRWvbHCeQAFq40CEu_pnqP6vWzJmom5JVZ90wOuYA76sAgf8LABWSso0nGkNQzIisGZzHwLACDTifIorEqqHSLAX1vt-MdEIABuIAA)

[What should actually be sent](https://echarts.apache.org/examples/en/editor.html?version=5.5.0&code=PYBwLglsB2AEC8sDeAoWsCuBnApgVQBUBhALljACcMcAaNWAcwogBMzV10BjGMAQwjQAMnwBGOADZlK1Op1gScAMzBkAzAFY5nZgwAWq2ACYADNvRhQZACxn66UcDCWAtmVP0AvtoAeAQR8ILHZ7cgBPEBwyAHJIFxxo81hoPniAcT4QMgBGLVCU-KFgLj5IGBiXVhZFRNC-QKwRcSlkb1DK6GAKAgguAGt2NvkOgEloMBwKADc-FrthwRiWUr4AWUFa4fqlldX66K9tMICgsgBtUI55WGOGpskAJSdSqGgyeeuwCKjYaJmJaiba4dLo9fqDJLoEEUADKIAkEDAQkEPyQQ2u9SC9xaaMhyVSOAyWVguTxBRwRRKZTev0qLGqCTxswgDGgYL6wVgSlmuFC6PQV3ktyxYkez2p7zxX0iMX-gLx0PZENC6Cw8MRyOgqJVnCwemAAHcyNyJLzrrB-ZxoXCEUiUcrzZjGqKcZb0MzWezOSazZxPPQALraSzACSQYmC2CZSLQFgEYAAIWALDC0iotFCesNadkoUoLIYkxiToO6HRikLsZC8i6EBw4xi-uYAC9eLMgar9UbyOmktKftEsFwKKGJB3YLhFFxLBRztFZmOaL9BFNJrhokHM5IcNOutjq9clLwAGKpCASVOwABE0TGEwoiVgAAlJKvICUl35mLMr3ij-MYQgZsfmyIw8R4CQuhiABiAA2eCEPHBwuhYSYiFDKDfjghD4NLP0-ysWAPnQXQDElUJln4OcfEfaInD0SYN0OehcGYHBOQueRI3QVgYh8AB9fiwj0Up-Mgg1GLJAk-KQ2BKL4c4dXQM4jC0EkTE3c1lKMAB2Jdsg0vFtIADn0wylNgFSAE4zM0rSzjUMx1Ls80HOyWyjMstQwOczyHOsDyLIctSDJc64zlsWydTC9AAEdqAoMIxlQnxyPNYUsGSnBUqIvFERwFwYS-RQD3NCDMOiaDrA0awAFEdKIWT0FAPguERS9sh1N1whlX4ES1WSsBcYB6ONHkM3NfMGELChNRwWrVwbHtc3NLB-HBX4aLxNbWr6IqKFKHAGEvecJEXHV-pwIqwhK5ALJatqvneLq8QKkARKwU47q0hQUWu27uOuA1WDAPQYkcCRUIfCz_XNbqswNGEwhcCGxtNCbriwZGIcA4CyFgvEJBdUrMa7NHcE8kBgE-iVfksEA8PkWH8MuHVeM2wThNEjAQEiB8pPiGS8XkxSfpUkLzLF3TAql0zfKCowbPlsXHJl-y1Hc5X1Z80K_LUAKtdczQ1dcyLnOivF4smJLY2ytLrgyrKcuIzh8sK4rtR-8rZyw7Jjz8YyiCsprYAe9qchenV-xiS7BuG0auXGqVdBmuaFvrQwZAx-Qdo26Itp1XO9soQ7juLM7ZMu_7Pa0sOnqIyPHQoHA-GrkmaxAVrw6IgA6IxG-uN6Pq-wH0Crj326BkGwd-CGocZ65maZ7auyRlHQ3J7PdWx0NcZ-AmLuJ76tIRzfKepxFXhiemF7LPkkkB9n89k8khZ1EXLIVkKNBizgVL0kkP8_JGDlrkX-2klZgL1k5KBQUNb6SAXAnWiCVYG1gSrb-4DLJmzARbHUVtEpO3tkKE4mVbbOzyhMd2N0a5lQwj7SqGg_BEGyMZYOnk66XhMAPeQ0c-oojjiNUGZ8o4p0mGnRamdeyF3WsXA6Ewy6_CwAST6rJK5_Qnsfc0nCI5w1ei4d6fBPqclHr9LUbctFaWBiwYRs9Qzzxhp5N2FjTHNU7o9DqMMeG6lXjvFoWdtp-L3vjQmR9TGn0Tujc-NMr501ALfC099WbmifvRSSOpX6_DSfzd-KxRb2VUvpLB_8inANAcUxWpS4EwOKfAkktSda1LQbUkKxSzaOQDHg80BCbYpRyHiR25DiGuyoS4iy3sYLHmPDpY81hrAhx0SSbxFhvgxCHKUe8giE4-i3hYMRs0UTpyWgEmRu19qlxOso-IqjoDqPMZo0xizOp6J1EPIxI8LLjxoZPeQ1jbHRDnoxLxLzVq-PXv46Rq0glAX3qE5oPyJxk0iRTCyVMYnlDiQzLqfJAzBhGhIRwOVIz02GaRQweR5BKBbmADAzdJ7yQAFojTcJYkhDQiHIt2ZwSAYAAYWXQK2YALLoiCpcFGZufAQ4OF2jEZua0ug4FgKKhJd84Y4rLNoRlzLzidM8AAbiAA)

### TESTING INSTRUCTIONS
create a mixed chart on the explore menu using confidence intervals where the names__yhat_lower bound is negative at least once.

Verify that confidence Intervals behave as Intended.

**names__yhat**: trend/point estimate
**names__yhat_lower**: lower confidence level
**names__yhat_upper**: upper confidence level 

### ADDITIONAL INFORMATION
Fixes #30554 
- [x] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
@geido I don't see this PR changing enforcing or updating the `xaxis.type = 'time'` issue, despite it being changed in the "after" example. Is this not changed here?

**Comment by vedantprajapati17** [comment]
xaxis type defaults to "value" if not reordered and there are negative bound values. When its ordered properly, it uses "time".

**Comment by geotab-data-platform** [comment]
@villebro any updates?

**Comment by villebro** [comment]
@vedantprajapati17 I am unable to properly review this PR due to the following:
- I'm unable to reproduce the issue without dedicating considerable time for this. For instance, the fact that the before/after payloads aren't diffable (one is JS, the other is JSON) doesn't help.
- I still don't understand how `xaxis.type` changes as a consequence of this PR, despite there being no such change in the PR.

Also, we would need a minimal unit test to validate that `reorderForecastSeries` works as expected. This both helps understand how the function works, and will help refactoring and protect against regressions going forward.

**Comment by villebro** [comment]
@geotab-data-platform please let me know if you need help with this. I'd love to pull this fix in, but in the absence of more clarity on how this fix works it will be difficult to merge this.

**Comment by geotab-data-platform** [comment]
Hi @villebro, 
Please see attached the current behaviour vs after the fix.

## Settings Used:
Chart Type: Mixed Chart
yhat = 1
yhat_lower = -10
yhat_upper = 5
query b = 10

image
image
image

## Current Behaviour

image

As you can see, the confidence interval ranges between (0,15) instead of (-10,5).

## After the fix
Setting the same values we get the following response with correct confidence intervals (-10,5).

image

When you do not reorder the props and send them to echarts as a json to generate the chart, the echarts package will default to an x axis that uses value and not time. Additionally, the props must be ordered in the that specific order as the behaviour will not be as expected otherwise and confidence bands will not be correct.

**Comment by vedantprajapati17** [comment]
@villebro any updates?

File: superset-frontend/plugins/plugin-chart-echarts/src/utils/forecast.ts [hunk 1]
```diff
@@ -150,3 +150,34 @@ export function rebaseForecastDatum(
...
+  ) {
+    return row;
+  }
+
+  return row.sort((a, b) => {
+    // Extract the forecast series context from the id to determine the order
+    const aContext = extractForecastSeriesContext(a.id);
+    const bContext = extractForecastSeriesContext(b.id);
+
+    const aOrder = sortOrder[aContext.type] || Number.MAX_SAFE_INTEGER; // Put other metrics at the end
```
Comment (rusackas) [inline superset-frontend/plugins/plugin-chart-echarts/src/utils/forecast.ts:178]: Not sure how guaranteed the context and type are, so you could add safeguards if you think it's warranted:

`const aOrder = (aContext?.type && sortOrder[aContext.type]) || Number.MAX_SAFE_INTEGER;`

File: superset-frontend/plugins/plugin-chart-echarts/src/utils/forecast.ts [hunk 2]
```diff
@@ -150,3 +150,34 @@ export function rebaseForecastDatum(
     return newRow;
   });
 }
+
+// For Confidence Bands, forecast series on mixed charts require the series sent in the following sortOrder:
+export function reorderForecastSeries(row: any[]): any[] {
```
Comment (rusackas) [inline superset-frontend/plugins/plugin-chart-echarts/src/utils/forecast.ts:155]: Not sure how well-defined of a type we can have here, but it'd be nice to avoid "any"

**Comment by rusackas** [comment]
Running CI... 🤞

**Comment by rusackas** [comment]
Sorry for the delay. I think we're still just agonizing over how this works and whether it's safe to merge, or might just cause some other edge case to appear. If it's possible to add some form of tests (unit tests or end to end tests) that would help immensely.

**Comment by vedantprajapati** [comment]
> Sorry for the delay. I think we're still just agonizing over how this works and whether it's safe to merge, or might just cause some other edge case to appear. If it's possible to add some form of tests (unit tests or end to end tests) that would help immensely.

It's difficult to validate whether or not a canvas html component looks one way compared to another. Especially when all this function just reorders the series that is being sent. ie no data is removed or added. I can add unit tests validating that the order is changed correctly? @rusackas

**Comment by rusackas** [comment]
I think the unit test would help... at least it would harden the feature against someone accidentally changing the code in a way that reverts the functionality.

**Comment by vedantprajapati** [comment]
tests added

**Comment by vedantprajapati** [comment]
are we good to merge this?

**Review by villebro — APPROVED** [review]
Looks great, thanks for the tests! Fingers crossed for CI..

**Comment by vedantprajapati** [comment]
> Looks great, thanks for the tests! Fingers crossed for CI..

had to do a quick lint fix. resolved

**Comment by villebro** [comment]
Restarted CI

**Comment by vedantprajapati** [comment]
feel free to merge 🥳
