### PR TITLE
fix: Add locale for DatePicker component

### LINKED ISSUE #20062: Impossible to have translation for DatePicker
Adding code to activate translation in DatePicker component

### PR DESCRIPTION
**Pull request by aehanno**
### SUMMARY
Adding french translation for DatePicker component

### ADDITIONAL INFORMATION
fix https://github.com/apache/superset/issues/20062

### CODE REVIEW

File: superset-frontend/src/explore/components/controls/DateFilterControl/components/CustomFrame.tsx [hunk 1]
```diff
@@ -132,6 +139,7 @@ export function CustomFrame(props: FrameComponentProps) {
                   onChange('sinceDatetime', datetime.format(MOMENT_FORMAT))
                 }
                 allowClear={false}
+                locale={locale}
```
Comment (zhaoyongjie) [inline superset-frontend/src/explore/components/controls/DateFilterControl/components/CustomFrame.tsx:142]: Thanks for the contribution! Could we make translation more generic? For example, we can define a map constant that mapping from `bootstrapData.common.local` to the `antd locale`. feel free to leave messages if you need help.

Comment (aehanno) [reply superset-frontend/src/explore/components/controls/DateFilterControl/components/CustomFrame.tsx:142]: Thanks for the review, I agree it will be better with mapping.
I just wonder where I can put this map and I don't really see how I can integrate an import in a map

Comment (aehanno) [reply superset-frontend/src/explore/components/controls/DateFilterControl/components/CustomFrame.tsx]: Hey @zhaoyongjie, I change the process to choose dynamicly the locale.
I use a list instead of import all local we need
Just for french translation, there is a bug in antd. We can't distinguish the fr from france and belgium properly so I add a if for now

**Comment by aehanno** [comment]
Hello @zhaoyongjie, just to know if you got time to check on my changes

**Comment by zhaoyongjie** [comment]
@aehanno Sorry for the waiting. I will review PR tomorrow. Thanks for your patience.

**Comment by mathieudruart** [comment]
Hi @zhaoyongjie any news on this PR ?

**Comment by mathieudruart** [comment]
Hi @zhaoyongjie is it possible to review this PR ? Thank you !

**Comment by nytai** [comment]
triggering CI

**Comment by mathieudruart** [comment]
Hi @nyta we pushed a correction, is it possible trigger CI ?

**Comment by zhaoyongjie** [comment]
Hi @mathieudruart, Thank you for the patient. I have pushed a [branch](https://github.com/apache/superset/commits/add-translation-for-DatePicker) to the repo base on your current branch, you should just 1) rebase the master branch 2) cheery-pick the latest [commit](https://github.com/apache/superset/commit/9ebf3c3c00ecc80aa4747e9113a055423d47ffa3) to this for unblocking the CI.

**Review by zhaoyongjie — APPROVED** [review]
lgtm, thanks for the new feature.
