### PR TITLE
fix: opacity color formating

### LINKED ISSUE #36098: [6.0] Conditional Formatting on tables is missing gradient
### Bug description

Regression on 6.0: 

1. Create a table chart type 
2. Add a custom conditional formatting - you can see the bug by using > x or value < x < value 
3. Select "alert" or "success" or "error" for the color scheme

Current behavior: 
The color is applied to the cells with no gradient 

Image
Image

Expected: 
before 6.0, the color would be applied with a gradient 

Image

### Screenshots/recordings

_No response_

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by SBIN2010**
### SUMMARY

This PR fix #36098

Fixed data type checking which caused opacity to be set to 1

Added test cases for the getOpacity function. Fixed it -> test .

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Снимок экрана от 2025-11-13 17-37-22

### TESTING INSTRUCTIONS

1)Create a table chart type
2)Add a custom conditional formatting - you can see the bug by using > x or value < x < value
3)Select "alert" or "success" or "error" for the color scheme

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/packages/superset-ui-chart-controls/src/utils/getColorFormatters.ts [hunk 1]
```diff
@@ -38,20 +38,20 @@ export const getOpacity = (
...
-    typeof extremeValue !== 'number' ||
-    typeof value !== 'number'
-  ) {
+  if (extremeValue === cutoffPoint || typeof value !== 'number') {
     return maxOpacity;
   }
+  const numCutoffPoint =
+    typeof cutoffPoint === 'string' ? parseFloat(cutoffPoint) : cutoffPoint;
+  const numExtremeValue =
+    typeof extremeValue === 'string' ? parseFloat(extremeValue) : extremeValue;
```
Comment (sadpandajoe) [inline superset-frontend/packages/superset-ui-chart-controls/src/utils/getColorFormatters.ts:47]: Should we guard in case if `numCutoffPoint` or `numExtremeValue` doesn't return a number? I see we check for a string but what about `NaN`

**Comment by sadpandajoe** [comment]
@SBIN2010 I know this is a fairly small change, but can we add some tests to make sure opacity returned correctly for different value types? Like if we use string and combo of string and number? Ok to move this to do a follow up pr if you want.

File: superset-frontend/packages/superset-ui-chart-controls/src/utils/getColorFormatters.ts (hunk 1 above)
Comment (sadpandajoe) [reply superset-frontend/packages/superset-ui-chart-controls/src/utils/getColorFormatters.ts:47]: Looks like Copilot had a similar comment and was marked resolved. Can we add tests for these cases to ensure maxOpacity is still returned correctly if tests don't already exist?

Comment (SBIN2010) [reply superset-frontend/packages/superset-ui-chart-controls/src/utils/getColorFormatters.ts:47]: Added a check for Nan

**Review by rusackas — APPROVED** [review]
LGTM! Thanks for addressing the comments.
