### PR TITLE
fix: Sort Metrics by ID DESC (order of creation) in the Datasource Editor

### LINKED ISSUE #12802: [explore]metrics list order should not change after editing metrics
Currently, after user editing a metric in Edit dataset modal in Explore, the edited metric jump to the bottom of the metric list. 
it create a few issues: 
1) when the metric list is long, by dropping to the bottom, user might take a while to find it or think the most recent edited metic is lost. 
2) every time users edit a single metric, they see a different order of metric list showing in the panel, which can be confusing

Proposed short-term change: the metric list should be arranged in the order of creation time

https://user-images.githubusercontent.com/67837651/106104741-aff21a80-60f7-11eb-9f5d-4d874b1bd152.mov

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
This PR changes the order of the Metrics in the Datasource Editor to show at the top the most recently created items.

Fixes: #12802

### BEFORE
https://user-images.githubusercontent.com/67837651/106104741-aff21a80-60f7-11eb-9f5d-4d874b1bd152.mov

### AFTER
https://user-images.githubusercontent.com/60598000/127626161-e2fe4319-1b54-4bc8-a82f-35036f016ff0.mp4

### TESTING INSTRUCTIONS
1. Go to Explore
2. Open the Edit Dataset modal
3. Go to metrics and add a new or update an existing one
4. Save
5. Open the Edit Dataset modal again and observe the order of the Metrics

### ADDITIONAL INFORMATION

- [x] Has associated issue: #12802
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by geido** [comment]
@junlincc @rosemarie-chiu @jinghua-qa The solution that I could apply with only changing the frontend code is to always show at the top the newly created or the most recently updated ones. This should solve point 1. of the issue. As for point 2, the order would still be changing when editing an existing item. However, the edited item would now show at the top of the list and is immediately visible to the user.

If we want the list to be exclusively ordered by the creation date and ignore the update time instead, a backend change will probably be required and this PR can be ignored.

Thanks

File: superset-frontend/src/datasource/DatasourceEditor.jsx [hunk 1]
```diff
@@ -557,6 +557,10 @@ class DatasourceEditor extends React.PureComponent {
     this.setState({ activeTabKey });
   }
 
+  sortMetrics(metrics) {
+    return metrics.sort(({ id: a }, { id: b }) => b - a);
+  }
+
```
Comment (michael-s-molina) [inline superset-frontend/src/datasource/DatasourceEditor.jsx:563]: The sort by id will only work when we change the metric's name because a new id is generated. If we change any other field, the id is preserved, and the sort will fail.

https://user-images.githubusercontent.com/70410625/127668858-32439238-d0a1-442e-97b6-fea56a05ee25.mp4

Comment (geido) [reply superset-frontend/src/datasource/DatasourceEditor.jsx:563]: This is actually good news as we don't want that the list is sorted based on the update date but only based on creation. So changing the name will be the only deviation. I will update my comment for the PO to take a decision.

**Comment by junlincc** [comment]
Thanks for the improvement! this is good enough improvement for now, eventually we wanna redesign this modal, lots of other issues like the discoverability of input field, place of cursor, and styling all needs work. ideally we should add sort as well. LGTM!

**Review by michael-s-molina — APPROVED** [review]

**Review by jinghua-qa — APPROVED** [review]
Verified new added and new edited metric will be on top of the list, which is better than the old behavior especially with long metric list.LGTM!

https://user-images.githubusercontent.com/81597121/127691435-c9ebb736-d07f-4c73-8cf4-f9ebd46acc2d.mov
