### PR TITLE
fix(native-filters): Fix clear all button

### LINKED ISSUE #15361: [native filter] 'Clear All' will show error in value filter
when setup a value filter + numerical filter in a dashboard, set both filter 'Apply changes instantly', then select value for each filter and then click 'Clear All', value filter will show error of too many updates

### Expected results
value filter and numerical filter can be clear 

### Actual results

value filter show error, numerical filter can be clear to origin state

#### Screenshots

Screen Shot 2021-06-24 at 3 04 35 AM

https://user-images.githubusercontent.com/81597121/123245951-270abf80-d49a-11eb-859b-0e95a2e2489d.mov

#### How to reproduce the bug

1. Go to USA birth name dashboard
2. Setup a value filter, select 'apply change instantly'
3. Setup a numerical filter, select 'apply change instantly'
4. go to dashboard and select some value for both filter and see changes 
5. click 'Clear All' and see error in value dashboard

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by simcha90**
### SUMMARY
Fix for: https://github.com/apache/superset/issues/15361

When user clicks `Clear All` we now update redux instead of local state

### ADDITIONAL INFORMATION

- [x] Has associated issue: closes #15361
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/components/nativeFilters/FilterBar/Header/index.tsx [hunk 1]
```diff
@@ -21,14 +21,15 @@ import { styled, t, useTheme } from '@superset-ui/core';
...
-import { useSelector } from 'react-redux';
+import { useDispatch, useSelector } from 'react-redux';
 import { getInitialDataMask } from 'src/dataMask/reducer';
 import { DataMaskState, DataMaskStateWithId } from 'src/dataMask/types';
 import FilterConfigurationLink from 'src/dashboard/components/nativeFilters/FilterBar/FilterConfigurationLink';
 import { useFilters } from 'src/dashboard/components/nativeFilters/FilterBar/state';
 import { Filter } from 'src/dashboard/components/nativeFilters/types';
 import { getFilterBarTestId } from '..';
 import { RootState } from '../../../../types';
+import { updateDataMask } from '../../../../../dataMask/actions';
```
Comment (villebro) [inline superset-frontend/src/dashboard/components/nativeFilters/FilterBar/Header/index.tsx:32]: nit:
```suggestion
import { updateDataMask } from 'src/dataMask/actions';
```

**Review by villebro — APPROVED** [review]
LGTM and tested to work with one small nit.
