### PR TITLE
fix: Changing language doesn't affect echarts charts

### LINKED ISSUE #30131: Changing languages doesn't affect echarts charts.
### Bug description

When you switch language in Superset, some charts still have untranslated buttons.
For example Pie chart has 'All' and 'Inv' buttons, that are always on English 

### How to reproduce the bug

1. Add Pie chart to your dashboard
2. Go to dashboard page
3. Change language to other than English
4. 'All' and 'Inv' buttons are not translated

### Screenshots/recordings

Language set to Russian, buttons are on English:
image

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by jpchev**
### SUMMARY
this is to propagate the current locale up to the echarts configuration.

fixes: #30131 
### TESTING INSTRUCTIONS
switch the locale and verify that charts have the correct locale (for example in months name and in buttons)

### CODE REVIEW

File: superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx [hunk 1]
```diff
@@ -123,10 +127,14 @@
     getEchartInstance: () => chartRef.current,
   }));
 
+  const localeObj = useSelector((state: ExplorePageState) => state?.common?.locale);
```
[the remark this answers is not in the document]
Comment (jpchev) [reply superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx:130]: done

[the remark this answers is not in the document]
Comment (jpchev) [reply superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx:130]: done

File: superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx [hunk 2]
```diff
@@ -27,6 +27,10 @@ import {
   Ref,
 } from 'react';
 
+import { useSelector } from 'react-redux';
+import { ExplorePageState } from 'src/explore/types';
+import * as echarts from 'echarts/core';
```
Comment (justinpark) [inline superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx:32]: Please avoid the full module import.

```suggestion
import { registerLocale } from 'echarts/core';
```

Comment (rusackas) [reply superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx]: Nice catch. I'll see about adding a lint rule for this.

Comment (jpchev) [reply superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx]: I made the change as suggested

**Review by pomegranited — COMMENTED** [review]
Thank you for submitting this PR @jpchev , you beat me to it :)
With just a few small changes, this is working well for me.

File: superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx [hunk 3]
```diff
@@ -123,10 +127,22 @@ function Echart(
...
+    echarts.registerLocale(localeObj.toUpperCase(), lang);
+  } catch (e) {
+    console.warn(`Locale ${localeObj} not supported in ECharts`);
+  }
+
   useEffect(() => {
     if (!divRef.current) return;
     if (!chartRef.current) {
-      chartRef.current = init(divRef.current);
+      chartRef.current = init(divRef.current, undefined, { locale: localeObj });
```
[the remark this answers is not in the document]
Comment (jpchev) [reply superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx]: I've applied the changes, thank you. If it is ok, can we merge the PR?

[the remark this answers is not in the document]
Comment (pomegranited) [reply superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx]: Thank you @jpchev , those look great :) I don't have access to merge this, but will leave my review to support it.

Here's some guidance @rusackas gave me on debugging the pre-commit checks that are failing here too: https://github.com/apache/superset/pull/31692#issuecomment-2569817382

**Review by pomegranited — APPROVED** [review]
:+1: This change is working great! Thank you @jpchev :)

- [x] I tested this by combining it with https://github.com/apache/superset/pull/31692 to test changing languages while viewing and editing the Pie Chart echart. I verified that this change ensures the "Inv" and "All" buttons on that echart are now translated as expected.
- [x] I read through the code

https://github.com/user-attachments/assets/e508a49c-fbff-481c-803d-f37760dfee91

File: superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (jpchev) [reply superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx]: I pushed the changes to make the 'prettier' check happy

[the remark this answers is not in the document]
Comment (jpchev) [reply superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx]: now the pre-commit check passes, thank you

**Comment by rusackas** [comment]
@villebro might be most qualified to look at this one, if he has time.

**Comment by jpchev** [comment]
> @villebro might be most qualified to look at this one, if he has time. That said, there are some failing tests that could use attention, and a more descritive PR title could help too :D

sorry for the cryptic title, I've put the title of the issue it fixes.
Also, I see one of the check fails because I used the 'require' import

https://github.com/apache/superset/actions/runs/12825802735/job/35764682648?pr=31751#step:4:4582

I know it's not recommended, but I don't know how to dynamically import a js file without using 'require'.
There is an async alternative, but that would make the code much less clear, in my opinion.

File: superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx [hunk 4]
```diff
@@ -123,10 +127,20 @@ function Echart(
...
+  const locale = useSelector(
+    (state: ExplorePageState) => state?.common?.locale ?? 'en',
+  ).toUpperCase();
+  try {
+    const lang = require(`echarts/lib/i18n/lang${locale}`).default;
+    registerLocale(locale, lang);
+  } catch (e) {
+    console.warn(`Locale ${locale} not supported in ECharts`);
+  }
+
```
[the remark this answers is not in the document]
Comment (pomegranited) [reply superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx:139]: Reply is here: https://github.com/apache/superset/issues/30131#issuecomment-2608728573

But it doesn't work :(

[the remark this answers is not in the document]
Comment (jpchev) [reply superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx:139]: Yes, I tried something similar, without success. That's why I went for require.

[the remark this answers is not in the document]
Comment (pomegranited) [reply superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx:139]: @jpchev I found the culprit! `handleSizeChange` wasn't running because of race conditions on render.

See https://github.com/jpchev/superset/pull/2

**Comment by jpchev** [comment]
@pomegranited I fixed almost all the checks, there is this one left which I don't how to treat https://github.com/apache/superset/actions/runs/12949242972/job/36119814005?pr=31751

do you have an idea? It seems there are errors also on files not impacted by changes in this PR,
for instance

`
@superset-ui/plugin-chart-echarts: ../../scripts/tsc.sh: line 25: exit: ../../src/components/Icons/Icon.tsx(23,29): error TS2307: Cannot find module 'src/assets/images/icons/transparent.svg' or its corresponding type declarations.`

File: superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx [hunk 5]
```diff
@@ -27,8 +27,11 @@ import {
   Ref,
 } from 'react';
 
+import { useSelector } from 'react-redux';
+import { ExplorePageState } from 'src/explore/types';
```
Comment (pomegranited) [inline superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx:31]: @jpchev I think the issue is actually here, because it introduces a dependency between the echart plugin and the superset-frontend code, and so the typescript compiler (tsc) doesn't know how to deal with it.

You can work around it by removing this import:
```suggestion
```

And defining that interface inline below (under the rest of the imports):

```typescript
// Define this interface here to avoid creating a dependency back to superset-frontend, 
// and to appease the compiler.
// ref: superset-frontend/src/explore/types
interface ExplorePageState {
  common: {
    locale: string;
  };
};
```

File: superset-frontend/plugins/plugin-chart-echarts/package.json [hunk 6]
```diff
@@ -24,9 +24,11 @@
     "lib"
   ],
   "dependencies": {
+    "@types/react-redux": "^7.1.34",
     "d3-array": "^1.2.0",
+    "dayjs": "^1.11.13",
     "lodash": "^4.17.21",
-    "dayjs": "^1.11.13"
+    "superset": "^2.0.1"
```
Comment (pomegranited) [inline superset-frontend/plugins/plugin-chart-echarts/package.json:31]: Could you revert these changes? I don't think they're needed.

File: superset-frontend/package-lock.json [hunk 7]
```diff
@@ -50218,6 +50218,14 @@
       "version": "4.2.0",
       "license": "MIT"
     },
+    "node_modules/superset": {
```
Comment (pomegranited) [inline superset-frontend/package-lock.json:50221]: Could you revert these changes? I don't think they're needed.

File: superset-frontend/plugins/plugin-chart-echarts/package.json (hunk 6 above)
Comment (jpchev) [reply superset-frontend/plugins/plugin-chart-echarts/package.json]: done

**Comment by jpchev** [comment]
@pomegranited can you please help me in resolving the conflict on superset-frontend/package-lock.json ? I've committed its latest version present on the master branch

**Comment by jpchev** [comment]
@pomegranited all checks passes now

File: superset-frontend/plugins/plugin-chart-echarts/package.json [hunk 8]
```diff
@@ -24,9 +24,10 @@
     "lib"
   ],
   "dependencies": {
+    "@types/react-redux": "^7.1.34",
     "d3-array": "^1.2.0",
-    "lodash": "^4.17.21",
-    "dayjs": "^1.11.13"
+    "dayjs": "^1.11.13",
+    "lodash": "^4.17.21"
```
Comment (pomegranited) [inline superset-frontend/plugins/plugin-chart-echarts/package.json:30]: Hmm.. this PR actually adds a dependency on `react-redux`, not just its `@types/react-redux`.. plus, the version pinned here is slightly higher than the ["@types/react-redux": "^7.1.10"](https://github.com/apache/superset/blob/master/superset-frontend/package.json#L273C13-L273C24) used in superset-frontend.

Could you update this change to use `"@types/react-redux": "^7.1.10"` instead, and also add ["react-redux": "^7.2.9"](https://github.com/apache/superset/blob/master/superset-frontend/package.json#L187C6-L187C17)?

I think this really only matters for people who are running the echarts plugin by itself, but would still be good to keep this file correct.

```diff
@@ -27,10 +27,12 @@
     "access": "public"
   },
   "dependencies": {
+    "@types/react-redux": "^7.1.34",
     "d3-array": "^1.2.0",
     "echarts": "^5.4.1",
     "lodash": "^4.17.21",
-    "moment": "^2.30.1"
+    "moment": "^2.30.1",
+    "react-redux": "^7.2.9"
   },
   "peerDependencies": {
     "@superset-ui/chart-controls": "*",
```

Steps to achieve this:

```
git checkout master superset-frontend/plugins/plugin-chart-echarts/package.json
cd superset-frontend
nvm use
npm install "react-redux@^7.2.9" "@types/react-redux@^7.1.10"
```

**Comment by jpchev** [comment]
all tests pass now,
but due to a merge conflict I had to remove all my commits and push again, 
and that closed the PR, so I have to reopen again and that requires again your approval.

@villebro @michael-s-molina could you please have a look if it is ok?

Thank you

**Comment by jpchev** [comment]
@pomegranited do you have news? It seems this PR can be merged, all tests pass and we fixed all the detected issues

**Comment by pomegranited** [comment]
@jpchev I have no news -- we're just waiting for upstream to review and merge here.

File: superset-frontend/plugins/plugin-chart-echarts/package.json [hunk 9]
```diff
@@ -24,9 +24,10 @@
     "lib"
   ],
   "dependencies": {
+    "@types/react-redux": "^7.1.10",
     "d3-array": "^1.2.0",
-    "lodash": "^4.17.21",
-    "dayjs": "^1.11.13"
+    "dayjs": "^1.11.13",
+    "lodash": "^4.17.21"
```
Comment (villebro) [inline superset-frontend/plugins/plugin-chart-echarts/package.json:30]: not your fault, but isn't `lodash` a peer dependency?

File: superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx [hunk 10]
```diff
@@ -61,6 +63,15 @@ import {
...
 import { EchartsHandler, EchartsProps, EchartsStylesProps } from '../types';
 
+// Define this interface here to avoid creating a dependency back to superset-frontend,
+// and to appease the compiler.
+// ref: superset-frontend/src/explore/types
+interface ExplorePageState {
+  common: {
+    locale: string;
+  };
+}
```
Comment (villebro) [inline superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx:73]: Oof.. I agree with the workaround here, but could we rephrase the comment to a `// TODO:` to move the type to `@superset-ui/core`?

File: superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx [hunk 11]
```diff
@@ -123,24 +134,52 @@ function Echart(
     getEchartInstance: () => chartRef.current,
   }));
 
+  const locale = useSelector(
+    (state: ExplorePageState) => state?.common?.locale ?? 'en',
```
Comment (villebro) [inline superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx:138]: nit: Instead of having a magic string in the codebase, it would be nice to move this to `src/constants.ts` as `DEFAULT_LOCALE = 'en';` or similar.

**Review by villebro — COMMENTED** [review]
Thanks for taking this up! A few comments, LMKWYT.

**Comment by rusackas** [comment]
This is looking great! Re-running a failing (and probably just flaky) CI check.

File: superset-frontend/plugins/plugin-chart-echarts/package.json [hunk 12]
```diff
@@ -24,6 +24,7 @@
     "lib"
   ],
   "dependencies": {
+    "@types/react-redux": "^7.1.10",
```
Comment (villebro) [inline superset-frontend/plugins/plugin-chart-echarts/package.json:27]: shouldn't this be `devDependencies`?

**Review by villebro — COMMENTED** [review]
One last comment

**Comment by jpchev** [comment]
@villebro I see few tests failing, but they don't seem to fail due to changes in this PR

**Comment by sadpandajoe** [comment]
@jpchev looks like pre-commits are failing, but I think we fixed this in master already. Can you rebase against master?

File: superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx (hunk 2 above)
Comment (justinpark) [reply superset-frontend/plugins/plugin-chart-echarts/src/components/Echart.tsx]: Thanks for update. LGTM

**Comment by jpchev** [comment]
@villebro do you know if there is anything I'm missing on this PR to have it reviewed?

**Comment by jpchev** [comment]
@geido can you please have a look at this PR?

File: superset-frontend/plugins/plugin-chart-echarts/package.json [hunk 13]
```diff
@@ -26,7 +26,8 @@
   "dependencies": {
     "d3-array": "^1.2.0",
     "lodash": "^4.17.21",
-    "dayjs": "^1.11.13"
+    "dayjs": "^1.11.13",
+    "@types/react-redux": "^7.1.10"
```
Comment (villebro) [inline superset-frontend/plugins/plugin-chart-echarts/package.json:30]: I think this should be in `devDependencies`

**Review by villebro — COMMENTED** [review]
LGTM except for the dev dependency being in regular dependencies

**Review by villebro — APPROVED** [review]
LGTM!

**Comment by villebro** [comment]
@jpchev my apologies, for some reason it appears to require having the type package under regular dependencies 🤔 My apologies (not sure why this is, I need to investigate this in more detail..) Anyway, please revert that change and I'll merge when CI is green again.

**Comment by jpchev** [comment]
@villebro ok, thank you, I reverted the change in order to have the type under `dependencies`.
