### PR TITLE
Fix time range filter dropdown

### LINKED ISSUE #6114: Time filter dropdown doesn't show current value, always shows defaults
This is more of a ux issue. When using the time range filter dropdown on a chart with existing values, the dropdown doesn't default to showing the values.

The time range section lists the current values, but when you click into the dropdown it always brings up the "Defaults" tab with "Last day" selected. It's a little confusing to not see the current values show up in the dropdown.

image
image

When you enter in a value the dropdown will always default to showing that value, but not if you refresh the page. Can we always have the dropdown show the current value? @betodealmeida do you think this is possible?

image

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
master

### Expected results
Go to num births trend chart
Click into "time range"
Dropdown modal shows the "Custom" tab with "Start/end" selected

### Actual results
Dropdown modal shows the "Defaults" tab with "Last day" selected

### Steps to reproduce
Go to num births trend chart
Click into "time range"
Dropdown modal shows the "Defaults" tab with "Last day" selected

### PR DESCRIPTION
**Pull request by michellethomas**
When on a chart with custom time range, the time range dropdown doesn't open in the custom tab, it always opens in the default tab. I fixed the issue by moving the logic in `componentDidMount` for setting state to `componentWillMount`.

While looking into that issue, I noticed another. If you start out on the custom tab and go to the default tab where a radio button has already been set, when you hit OK without clicking another button the filter doesn't get updated correctly. The radio buttons only update the `type` field  in state if you click a button, so if the value is already selected, it won't change the type. I fixed it by keeping track of the current tab so in `close()` we can use the common filter if the type has not been set but the tab is default.

Here's a video of the second issue (the "Last day" filter doesn't get set correctly):
superset_time_filter_before

Fixes #6114

@betodealmeida

### CODE REVIEW

**Comment by michellethomas** [comment]
@graceguo-supercat @kristw PR fixes a few issues with the time filter dropdown

File: superset/assets/src/explore/components/controls/DateFilterControl.jsx [hunk 1]
```diff
@@ -156,18 +163,24 @@ export default class DateFilterControl extends React.Component {
...
     this.toggleCalendar = this.toggleCalendar.bind(this);
+    this.changeTab = this.changeTab.bind(this);
   }
-  componentDidMount() {
+
+  componentWillMount() {
     const value = this.props.value;
     if (value.indexOf(SEPARATOR) >= 0) {
-      this.state = { ...this.state, ...getStateFromSeparator(value) };
+      this.setState({ ...this.state, ...getStateFromSeparator(value) });
```
Comment (kristw) [inline superset/assets/src/explore/components/controls/DateFilterControl.jsx]:
```
this.setState(getStateFromSeparator(value);
```

This will combine with existing state already. No need to combine with `this.state` manually.

File: superset/assets/src/explore/components/controls/DateFilterControl.jsx [hunk 2]
```diff
@@ -285,9 +308,10 @@ export default class DateFilterControl extends React.Component {
       <Popover id="filter-popover" placement="top" positionTop={0}>
         <div style={{ width: '250px' }}>
           <Tabs
-            defaultActiveKey={this.state.type === TYPES.DEFAULTS ? 1 : 2}
+            defaultActiveKey={this.state.tab === TABS.DEFAULTS ? 1 : 2}
             id="type"
             className="time-filter-tabs"
+            onSelect={() => this.changeTab()}
```
Comment (kristw) [inline superset/assets/src/explore/components/controls/DateFilterControl.jsx]:
```
onSelect={this.changeTab}
```

`this.changeTab` is already `bind` to `this` so can use without wrapping in arrow function

File: superset/assets/src/explore/components/controls/DateFilterControl.jsx [hunk 3]
```diff
@@ -156,18 +163,24 @@ export default class DateFilterControl extends React.Component {
     this.setTypeCustomRange = this.setTypeCustomRange.bind(this);
     this.setTypeCustomStartEnd = this.setTypeCustomStartEnd.bind(this);
     this.toggleCalendar = this.toggleCalendar.bind(this);
+    this.changeTab = this.changeTab.bind(this);
   }
-  componentDidMount() {
+
+  componentWillMount() {
```
Comment (kristw) [inline superset/assets/src/explore/components/controls/DateFilterControl.jsx]: I am not sure if we need to do this in `componentWillMount`.
Will we mount/unmount multiple times?
Perhaps do it in the constructor instead if it is only initialization?

File: superset/assets/src/explore/components/controls/DateFilterControl.jsx (hunk 1 above)
Comment (michellethomas) [reply superset/assets/src/explore/components/controls/DateFilterControl.jsx]: Oh thanks forgot to remove this. 🤦‍♀️

File: superset/assets/src/explore/components/controls/DateFilterControl.jsx (hunk 3 above)
Comment (michellethomas) [reply superset/assets/src/explore/components/controls/DateFilterControl.jsx]: That's a good suggestion and seems to work fine, thanks

**Review by kristw — APPROVED** [review]
