### PR TITLE
[Explore] Altered Slice Tag

### LINKED ISSUE #3616: Carry over dashboard filters to explore: empty fields transferred
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.3

This issue is addressing the changes introduced by #3461

### Expected results
Only currently active dashboard filters are transferred to the explore view and added to the already existing filters of the corresponding slice.

### Actual results
Dashboard filters that were previously applied and then dropped again leave empty entries in the URL parameters which are then carried over to the explore view of the slice. This results in filter entries with empty arguments.

Furthermore, any time filters set on the dashboard result in entries in the filter list in explore view with empty column selection.
However, I guess due to #3610, I cannot currently reproduce this behavior. Nevertheless, I wanted you to be aware that this may also happen.

### Steps to reproduce
Apply time filters on a dashboard; apply and then drop and other filter and afterwards click _Explore chart_ on any slice.

### PR DESCRIPTION
**Pull request by Mogball**
Based on a suggesting by @mistercrunch in https://github.com/apache/incubator-superset/issues/3617, this PR implements an `AlteredSliceTag` which is displayed next to the slice title in the `explore` view when the current controls do not match the saved slice controls:

screen shot 2017-10-13 at 10 57 46 am

Users can click the tag to open a modal summarizing the differences:

screen shot 2017-10-13 at 10 59 48 am

Most importantly, exploring a slice from a dashboard with dashboard filters will show the slice as `altered` with the applied filters as differences.

Also fixes https://github.com/apache/incubator-superset/issues/3616

### CODE REVIEW

File: superset/assets/javascripts/explore/components/ChartContainer.jsx [hunk 1]
```diff
@@ -145,6 +146,25 @@ class ChartContainer extends React.PureComponent {
     };
   }
 
+  isAltered() {
```
Comment (mistercrunch) [inline superset/assets/javascripts/explore/components/ChartContainer.jsx]: What about using a deep equality function like http://underscorejs.org/#isEqual instead?

File: superset/assets/javascripts/components/AlteredSliceTag.jsx [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+        triggerNode={this.renderTriggerNode()}
+        modalTitle={t('Slice changes')}
+        bsSize="large"
+        modalBody={this.renderModalBody()}
+      />
+    );
+  }
+}
+
+AlteredSliceTag.propTypes = {
```
Comment (mistercrunch) [inline superset/assets/javascripts/components/AlteredSliceTag.jsx]: Please put `propTypes` at the top of the file as in most other modules

File: superset/assets/javascripts/explore/components/ChartContainer.jsx [hunk 3]
```diff
@@ -145,6 +146,25 @@ class ChartContainer extends React.PureComponent {
...
+    for (const fdKey of fdKeys) {
+      // Ignore values that are undefined/nonexisting in either
+      if (!fd[fdKey] && !bfd[fdKey]) {
+        continue;
+      }
+      if (JSON.stringify(fd[fdKey]) !== JSON.stringify(bfd[fdKey])) {
+        differing[fdKey] = { before: bfd[fdKey], after: fd[fdKey] };
+      }
+    }
+    return differing;
```
Comment (mistercrunch) [inline superset/assets/javascripts/explore/components/ChartContainer.jsx]: I'd expect a `isSomething` method to return a bool by naming conventions, rename the function to something like `getDiffs`.

File: superset/assets/javascripts/components/AlteredSliceTag.jsx (hunk 2 above)
Comment (mistercrunch) [reply superset/assets/javascripts/components/AlteredSliceTag.jsx]: Also what about if the component received `origFormData` and `currentFormData` instead, and the logic to check the differences can live in this component here.

File: superset/assets/javascripts/components/AlteredSliceTag.jsx [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+    } else if (controls[key] && controls[key].type === 'CollectionControl') {
+      return value.map(v => JSON.stringify(v)).join(', ');
+    } else if (typeof value === 'boolean') {
+      return value ? 'true' : 'false';
+    } else if (value.constructor === Array) {
+      return value.length ? value.join(', ') : '[]';
+    } else if (value.constructor === Object) {
+      return JSON.stringify(value);
+    }
+    return value;
```
Comment (mistercrunch) [inline superset/assets/javascripts/components/AlteredSliceTag.jsx]: I'm thinking the catchall could be a `JSON.stringify` though I'm not 100 sure of the implications. There's a guarantee that controls' values are always serializable since they make it through the redux store.

File: superset/assets/javascripts/explore/components/ChartContainer.jsx [hunk 5]
```diff
@@ -145,6 +146,25 @@ class ChartContainer extends React.PureComponent {
     };
   }
 
+  isAltered() {
+    // Returns all properties that differ in the
+    // current form data and the base form data
+    const fd = this.props.formData || {};
+    const bfd = (this.props.slice && this.props.slice.form_data) || {};
```
Comment (mistercrunch) [inline superset/assets/javascripts/explore/components/ChartContainer.jsx]: Here you may want to use the `currentFormData` as the driver of which keys should exist. `slice.form_data` may have unused / deprecated keys that don't affect how the slice is rendered...

**Review by mistercrunch — CHANGES_REQUESTED** [review]
Looking forward to this feature!

**Comment by Mogball** [comment]
Putting `getDiffs` in `AlteredSliceTag` means we can unit test it as well!

**Review by mistercrunch — APPROVED** [review]

**Comment by mistercrunch** [comment]
Ok this is ready to merge upon fixing conflicts.

**Comment by Mogball** [comment]
@mistercrunch  done
