### PR TITLE
fix: removed dashboard from main page in "All" tab, refreshes dashboard list

### LINKED ISSUE #35819: Delete dashboard in main page doesnt reload interface
### Bug description

On the main page, there is an option to delete a Dashboard:

Image

Clicking "Delete" creates an AJAX connection that removes the panel from the database and works correctly:

Image

The object is deleted from the database, but the HTML element is not. It's still there:

Image

No JavaScript errors are reported in the console:

Image

### Screenshots/recordings

_No response_

### Superset version

v6.0.0 rc2

### Python version

3.11

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by SBIN2010**
### SUMMARY

This PR fix #35819

After deleting the dashboard, getData was added.

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/views/CRUD/utils.tsx [hunk 1]
```diff
@@ -333,6 +334,8 @@ export function handleDashboardDelete(
         ],
       };
       if (dashboardFilter === 'Mine') refreshData(filters);
+      else if (dashboardFilter === 'Other' && getData)
+        getData(dashboardFilter as TableTab);
```
Comment (sadpandajoe) [inline superset-frontend/src/views/CRUD/utils.tsx:338]: Should we have `TableTab.Other` and `TableTab.Mine` instead of just Other and Mine listed here?

**Comment by sadpandajoe** [comment]
Are we missing tests here? A test where the default tab is `Other` and we assert `getData/fetchData` is called on delete would be good to validate this fix.

**Review by sadpandajoe — APPROVED** [review]
