### PR TITLE
fix(explore): Metric control breaks when saved metric deleted from dataset

### LINKED ISSUE #14034: [Explore] Single metric selector is inoperable if the referenced metric no longer exists
If a metric is removed from a datasource the single metric widget is inoperable if saved slice or URL references the previously defined metric. Note this isn't a problem for visualization types which support multiple metrics.

### Expected results

The metric widget to render correctly.

### Actual results

The metric widget in inoperable (see attached screenshot).

#### Screenshots

Screen Shot 2021-04-09 at 8 24 04 AM

#### How to reproduce the bug

1. Using the example data visit the "Number of Girls" chart.
2. Edit the datasource by deleting the `sum_num` metric and then clicking `SAVE`.
3. Reload the page.
4. Verify the METRIC widget is inoperable (see screenshot).

### Environment

(please complete the following information):

- superset version: `master`
- python version: `3.7`
- node.js version: `14`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
When user added a saved metric to Metric control, then removed that metric in dataset, it left the Metric control in a broken state.
The reason for that was a faulty logic in a function responsible for synchronising currently added metrics with current state of the dataset.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before: see linked issue
After:

https://user-images.githubusercontent.com/15073128/142855861-40142f9a-01cf-4e28-bcf3-0e8ca2be3925.mov

### TESTING INSTRUCTIONS
1. Add a saved metric to Metric control and run query
2. Delete that saved metric from dataset
3. Verify that the deleted metric was removed from Metric control and the control is still operable (user is able to add another metric and successfully run query)

### ADDITIONAL INFORMATION
- [x] Has associated issue: fixes #14034
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC @junlincc @john-bodley @jinghua-qa

### CODE REVIEW

File: superset-frontend/src/explore/components/controls/DndColumnSelectControl/DndMetricSelect.tsx [hunk 1]
```diff
@@ -96,16 +96,17 @@ const getMetricsMatchingCurrentDataset = (
     return values;
   }
   return values.reduce((acc: ValueType[], metric) => {
-    if (
-      (typeof metric === 'string' || (metric as Metric).metric_name) &&
-      (areSavedMetricsEqual ||
+    if (typeof metric === 'string' || (metric as Metric).metric_name) {
```
Comment (villebro) [inline superset-frontend/src/explore/components/controls/DndColumnSelectControl/DndMetricSelect.tsx:99]: Consideration: now that we have those nifty new type guards, would we be able to introduce those in this PR?

Also, could we add the return type on line 90 (I'm guessing it's now `ValueType[]`)?

**Review by villebro — APPROVED** [review]
Took a while to figure out why this changed anything before noticing it was a reducer 😆  LGTM with a few optional non-blocking improvement proposals + big thanks for the test!

File: superset-frontend/src/explore/components/controls/DndColumnSelectControl/DndMetricSelect.tsx (hunk 1 above)
Comment (kgabryje) [reply superset-frontend/src/explore/components/controls/DndColumnSelectControl/DndMetricSelect.tsx:99]: I'd love to do that, but it seems that we miss `isAdhocMetric` type guard. Also, our `isSavedMetric` checks if value is a string, so it won't cover the `(metric as Metric).metric_name` case. Maybe we can circle back to it once monorepo is merged and we can easily add new type guards?

Comment (villebro) [reply superset-frontend/src/explore/components/controls/DndColumnSelectControl/DndMetricSelect.tsx:99]: yes, absolutely, let's do that 👍
