### PR TITLE
fix(explore): CUSTOM SQL tab should automatically update

### LINKED ISSUE #12512: [explore] switch between SIMPLE and CUSTOM SQL in ad hoc filter
ezgif-4-cd50b8c2a1f0

Expected behavior:
select filter value in the SIMPLE tab should automatically update SQL expression in the CUSTOM tab

Actual behavior: 
Users have to click the input field to update the change 

To reproduce
- create a chart in Explore
- create a filter in SIMPLE 
- switch to CUSTOM SQL without clicking SAVE or CLOSE
- switch back to SIMPLE, change the filter value
- switch to CUSTOM again see expression

### PR DESCRIPTION
**Pull request by stephenLYZ**
### SUMMARY

Before that, the value in the ace editor will only be re-rendered when focus or leaving the popup. It has been updated to the latest value, but it is not rendered. What we need to do is to resize it once when switching to the tab page（trigger componentDidUpdate method by passing new props）, and the value will be automatically synchronized at this time.
#### Before
image
#### after 
Kapture 2021-04-16 at 22 04 31

### ADDITIONAL INFORMATION

- [x] Has associated issue:  Fixes #12512
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/explore/components/controls/FilterControl/AdhocFilterEditPopover/index.jsx [hunk 1]
```diff
@@ -64,11 +64,13 @@ export default class AdhocFilterEditPopover extends React.Component {
     this.onMouseUp = this.onMouseUp.bind(this);
     this.onAdhocFilterChange = this.onAdhocFilterChange.bind(this);
     this.adjustHeight = this.adjustHeight.bind(this);
+    this.onTabChange = this.onTabChange.bind(this);
 
     this.state = {
       adhocFilter: this.props.adhocFilter,
       width: startingWidth,
       height: startingHeight,
+      activeKey: this.props.adhocFilter.expressionType,
```
Comment (zhaoyongjie) [inline superset-frontend/src/explore/components/controls/FilterControl/AdhocFilterEditPopover/index.jsx:73]:
```suggestion
      activeKey: this.props?.adhocFilter?.expressionType || 'SIMPLE',
```

**Review by zhaoyongjie — APPROVED** [review]
LGTM! a minor suggestion.
