### PR TITLE
fix: SelectControl default sort numeric choices by value

### LINKED ISSUE #35008: Sorting in filter values
### Bug description

The version is 6.0.0rc1 (but it was the same in 5)
The order of int values is incorrect:
Image

as far as it's Int type, I expect: 1,2,3...

### Screenshots/recordings

_No response_

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
The numeric choices passed to SelectControl were being sorted alphabetically, leading to confusing order of the items. This PR implements sorting by value if ALL values passed through `props.choices` or `props.options` are numeric.
We can still pass `sortComparator` prop which overrides the default logic, so it's possible to create a control with custom order of items.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before:

image

After:

image

### TESTING INSTRUCTIONS
1. Open Table chart
2. Verify that `Server page length` and `Row limit` controls have their options sorted by value, not alphabetically

### ADDITIONAL INFORMATION

- [ ] Has associated issue: Fixes #35008
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/explore/components/controls/SelectControl.jsx [hunk 1]
```diff
@@ -87,6 +87,56 @@ const defaultProps = {
   valueKey: 'value',
 };
 
+const numberComparator = (a, b) => {
+  const aVal = typeof a.value === 'number' ? a.value : parseFloat(a.value);
```
Comment (Antonio-RiveroMartnez) [inline superset-frontend/src/explore/components/controls/SelectControl.jsx]: Isn't the type already checked in `areAllChoiceValuesNumbers` and `areAllOptionValuesNumbers`?

File: superset-frontend/src/explore/components/controls/SelectControl.jsx [hunk 2]
```diff
@@ -87,6 +87,56 @@ const defaultProps = {
...
+  const bVal = typeof b.value === 'number' ? b.value : parseFloat(b.value);
+  return aVal - bVal;
+};
+
+export const areAllChoiceValuesNumbers = (choices, valueKey = 'value') => {
```
Comment (Antonio-RiveroMartnez) [inline superset-frontend/src/explore/components/controls/SelectControl.jsx]: this method and `areAllOptionValuesNumbers` seems very similar, and seems like this could work for both cases? so might be good to just have one `areAllValuesNumbers(...)`?

File: superset-frontend/src/explore/components/controls/SelectControl.jsx [hunk 3]
```diff
@@ -87,6 +87,56 @@ const defaultProps = {
...
+
+export const areAllOptionValuesNumbers = (options, valueKey = 'value') => {
+  if (!options || options.length === 0) {
+    return false;
+  }
+  return options.every(o => typeof o[valueKey] === 'number');
+};
+
+export const getSortComparator = (
+  choices,
```
Comment (Antonio-RiveroMartnez) [inline superset-frontend/src/explore/components/controls/SelectControl.jsx:109]: nit: Could have add some types here?

Comment (kgabryje) [reply superset-frontend/src/explore/components/controls/SelectControl.jsx:109]: Nope, it's a jsx file 🙂

File: superset-frontend/src/explore/components/controls/SelectControl.jsx (hunk 2 above)
Comment (kgabryje) [reply superset-frontend/src/explore/components/controls/SelectControl.jsx]: done!

File: superset-frontend/src/explore/components/controls/SelectControl.jsx (hunk 1 above)
Comment (kgabryje) [reply superset-frontend/src/explore/components/controls/SelectControl.jsx]: done!

File: superset-frontend/src/explore/components/controls/SelectControl.jsx (hunk 3 above)
Comment (Antonio-RiveroMartnez) [reply superset-frontend/src/explore/components/controls/SelectControl.jsx:109]: Oh my bad, didn't look at that 😓

**Review by Antonio-RiveroMartnez — APPROVED** [review]
lgtm
