### PR TITLE
fix(explore): flaky Change dataset modal 

### LINKED ISSUE #12389: [Explore]flaky Change dataset modal
ezgif-3-1f57266d4bcb

User is not able to change dataset in the Change Dataset modal as the list is constantly flaking when there's search input in the search bar
 🤦🏾‍♀️

likely caused by https://github.com/apache/superset/pull/12006 

latest master 01/09/2021 @ 5:58pm (UTC)

### PR DESCRIPTION
**Pull request by geido**
### SUMMARY
Closes #12389 

The debounce effect was retriggered all the time causing the fetch to be called in an infinite loop.
### BEFORE
ezgif-3-1f57266d4bcb

### AFTER
First-Time-Developer-Commute-Time

### TEST PLAN
1. Open a chart
2. Change the dataset
3. Search for a dataset
4. Make sure the search does not retrigger all the time

### ADDITIONAL INFORMATION

- [x] Has associated issue: #12389 
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
@geido thanks for the quick fix! 
one more ask, when user is deleting search input, they should get a list of increasing options. can you add that functionality to search? we are using it in the Datapanel search as well.

File: superset-frontend/src/explore/exploreUtils.js [hunk 1]
```diff
@@ -288,8 +288,9 @@ export const exploreChart = formData => {
   postForm(url, formData);
 };
 
-export const useDebouncedEffect = (effect, delay) => {
-  const callback = useCallback(effect, [effect]);
+export const useDebouncedEffect = (effect, delay, deps) => {
+  // eslint-disable-next-line react-hooks/exhaustive-deps
+  const callback = useCallback(effect, deps);
```
Comment (michael-s-molina) [inline superset-frontend/src/explore/exploreUtils.js:293]:
```suggestion
  const callback = useCallback(effect, [effect, deps]);
```

File: superset-frontend/src/explore/exploreUtils.js [hunk 2]
```diff
@@ -288,8 +288,9 @@ export const exploreChart = formData => {
   postForm(url, formData);
 };
 
-export const useDebouncedEffect = (effect, delay) => {
-  const callback = useCallback(effect, [effect]);
+export const useDebouncedEffect = (effect, delay, deps) => {
+  // eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (michael-s-molina) [inline superset-frontend/src/explore/exploreUtils.js:292]:
```suggestion
```

**Review by michael-s-molina — CHANGES_REQUESTED** [review]

**Review by villebro — APPROVED** [review]

**Review by junlincc — APPROVED** [review]
@geido let's open a new PR to implement the enhancement on search! many thanks for fixing this P0 issue!!! 

FYI @eschutho @betodealmeida  this issue is likely caused by https://github.com/apache/superset/pull/12006

File: superset-frontend/src/explore/exploreUtils.js (hunk 1 above)
Comment (geido) [reply superset-frontend/src/explore/exploreUtils.js:293]: This will cause the issue to happen again unofrtunately

File: superset-frontend/src/explore/exploreUtils.js (hunk 2 above)
Comment (geido) [reply superset-frontend/src/explore/exploreUtils.js:292]: Required as per my previous comment
