### PR TITLE
fix: Show cross filter option only when cross filter is enabled

### LINKED ISSUE #16341: [cross filter]cross-filtering scoping option should hide when x-filerting function is not enabled in Explore
cross-filtering scoping option should hided when x-filerting function is not enabled in Explore 

### Expected results

when cross filter is not enable in explore, chart 3 dot menu will not show cross-filtering scoping option

### Actual results

cross-filtering scoping option show when the chart is not enable for x-filtering

#### Screenshots
Screen Shot 2021-08-18 at 4 16 38 PM

#### How to reproduce the bug

1. open a time-series chart in explore and do not select emit dashboard cross filter
2. add chart to dashboard and open chart 3 dot menu
3. See error

### Environment

(please complete the following information):

- superset version: latest master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Fixes https://github.com/apache/superset/issues/16341

@junlincc @jinghua-qa @rusackas 

### AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/70410625/130330118-f7ea77c8-01e8-4edf-8715-7ce6002df0a7.mov

### TESTING INSTRUCTIONS
Check the original issue for instructions.

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/components/SliceHeaderControls/index.tsx [hunk 1]
```diff
@@ -229,6 +230,7 @@ class SliceHeaderControls extends React.PureComponent<
         value.behaviors?.includes(Behavior.INTERACTIVE_CHART),
       )
       .find(([key]) => key === slice.viz_type);
+    const emitCrossFilter = slice.form_data?.emit_filter;
```
Comment (kgabryje) [inline superset-frontend/src/dashboard/components/SliceHeaderControls/index.tsx:233]: Can we name it sth like `canEmitCrossFilter`? It might be mistaken for a function that emits a cross filter

Comment (michael-s-molina) [reply superset-frontend/src/dashboard/components/SliceHeaderControls/index.tsx]: Yes. Changed.

**Review by villebro — APPROVED** [review]
Nice, I hadn't noticed this shortcoming 👍
