### PR TITLE
fix: Prevent undo functionality from referencing incorrect dashboard edits

### LINKED ISSUE #31344: Hitting undo on a dashboard shows last edited dashboard
### Bug description

Repro steps

1. Go to a dashboard (A) and edit it and save
2. Go to dashboard list
3. Select another dashboard (B) and hit edit
4. Click on the undo button

Actual results: 
Undo will show dashboard A even though you are on dashboard B. 
Making additional changes on the dashboard will allow the user to incorrectly save the changes. 

Expected results: 
Undo button shouldn't be enabled if there are no actions made yet on the second dashboard. 
Undoing in one dashboard should never load a different dashboard 

### Screenshots/recordings

https://github.com/user-attachments/assets/998cdc0e-290d-4f3d-92f6-5243bbcfb7e5

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by fardin-developer**
Fixes #31344

## Description
This PR fixes a bug where the "Undo" button displays actions from a previously edited dashboard after switching to a new one. The issue occurred because the dashboardLayout.past array, which stores the undo history, was not cleared when switching between dashboards or entering edit mode.

### Before
[https://drive.google.com/file/d/1ddAJXwsBFAmTHtpjKqo-fRAzk6fu4aek/view?usp=sharing](url)

### After
[https://drive.google.com/file/d/1fvomN09d4G_87We-YfOaAurMTTcQ7dAO/view?usp=sharing](url)
## Key Changes:
Reset Dashboard History:

Introduced the resetDashboardPast function to ensure the dashboardLayout.past array is cleared when toggling edit mode.
Edit Button Update:

Updated the "Edit Dashboard" button to call the resetDashboardPast function via boundActionCreators.clearDashboardHistory() when clicked.

## Reproduction Steps

- Navigate to a dashboard (Dashboard A).
- Click "Edit" and make changes. Save the dashboard.
- Navigate to the dashboard list and select another dashboard (Dashboard B).
- Click "Edit" on Dashboard B.
- Press the "Undo" button.

### Expected Behavior:

- The undo button should be disabled when first editing Dashboard B.
- Undo actions should not reflect changes made in Dashboard A.

### CODE REVIEW

File: superset-frontend/src/dashboard/actions/dashboardLayout.js [hunk 1]
```diff
@@ -267,6 +267,13 @@ export function handleComponentDrop(dropResult) {
   };
 }
 
+export function resetDashboardPast() {
+  return (dispatch, getState) => {
+    const { dashboardLayout } = getState();
+    dashboardLayout.past = []; // Set `past` as an empty array
+  };
+}
```
[the remark this answers is not in the document]
Comment (geido) [reply superset-frontend/src/dashboard/actions/dashboardLayout.js:275]: @fardin-developer I don't think you should edit the state here? Why not in the reducers?

[the remark this answers is not in the document]
Comment (fardin-developer) [reply superset-frontend/src/dashboard/actions/dashboardLayout.js:275]: You  are right, I should edit in reducer but I have not seen anything like dashboardLayoutReducer or something similar so I  made afunction to make DashboardLayout.past as an empty array.

File: superset-frontend/src/dashboard/actions/dashboardLayout.js
Comment (fardin-developer) [inline superset-frontend/src/dashboard/actions/dashboardLayout.js:1]: clearing history from redux undo

File: superset-frontend/src/dashboard/components/Header/index.jsx [hunk 2]
```diff
@@ -668,6 +673,7 @@ const Header = () => {
       NavExtension,
       boundActionCreators.onRedo,
       boundActionCreators.onUndo,
+      boundActionCreators.clearDashboardHistory(),
```
Comment (justinpark) [inline superset-frontend/src/dashboard/components/Header/index.jsx:676]: You're executing the function in the dependent list 
```suggestion
      boundActionCreators.clearDashboardHistory,
```

**Comment by kgabryje** [comment]
Looks great, once Justin’s comment is addressed it’s good to merge

File: superset-frontend/src/dashboard/components/Header/index.jsx [hunk 3]
```diff
@@ -651,7 +653,10 @@ const Header = () => {
             {userCanEdit && (
               <Button
                 buttonStyle="secondary"
-                onClick={toggleEditMode}
+                onClick={() => {
+                  toggleEditMode();
+                  boundActionCreators.clearDashboardHistory(); // Resets the `past` as an empty array
```
Comment (kgabryje) [inline superset-frontend/src/dashboard/components/Header/index.jsx:658]: a unit test seems to be failing on this line

**Review by justinpark — APPROVED** [review]

**Comment by rusackas** [comment]
Looks like everything discussed is in order. Thanks for the contribution!

**Comment by geido** [comment]
The PR is missing unit tests. It would be great to add them in a follow-up PR. Thanks for your contribution @fardin-developer !
