### PR TITLE
fix: misaligned LimitControl buttons and port jsx->tsx

### LINKED ISSUE #10525: Row Limit popover in SQL Lab is oddly formated
As titled. The buttons should be in the same row

#### Screenshots

image

### Environment

(please complete the following information):

- superset version: `master`

cc @rusackas @mistercrunch

### PR DESCRIPTION
**Pull request by mistercrunch**
Screen Shot 2020-08-05 at 10 03 08 PM

closes: https://github.com/apache/incubator-superset/issues/10525

### CODE REVIEW

File: superset-frontend/src/SqlLab/components/LimitControl.tsx [hunk 1]
```diff
@@ -30,15 +29,27 @@ import { t } from '@superset-ui/translation';
...
+  maxRow: number;
+  onChange: (value: number) => void;
+}
+
+interface LimitControlState {
+  textValue: string;
+  showOverlay: boolean;
+}
+
+const popoverStyle = {
```
Comment (etr2460) [inline superset-frontend/src/SqlLab/components/LimitControl.tsx:44]: instead of this, let's make a `PopoverDiv` component with `styled` and apply the styling that way?

File: superset-frontend/src/SqlLab/components/LimitControl.tsx [hunk 2]
```diff
@@ -99,18 +110,21 @@ export default class LimitControl extends React.PureComponent {
               value={textValue}
               placeholder={t(`Max: ${this.props.maxRow}`)}
               bsSize="small"
-              onChange={e => this.setState({ textValue: e.target.value })}
+              // @ts-ignore
```
Comment (etr2460) [inline superset-frontend/src/SqlLab/components/LimitControl.tsx:113]: Why do we need the ts ignore here?

File: superset-frontend/src/SqlLab/components/LimitControl.tsx [hunk 3]
```diff
@@ -99,18 +110,21 @@ export default class LimitControl extends React.PureComponent {
               value={textValue}
               placeholder={t(`Max: ${this.props.maxRow}`)}
```
Comment (etr2460) [inline superset-frontend/src/SqlLab/components/LimitControl.tsx:111]: while you're in here, wanna fix the translation string here too?

File: superset-frontend/src/SqlLab/components/LimitControl.tsx [hunk 4]
```diff
@@ -88,7 +99,7 @@ export default class LimitControl extends React.PureComponent {
         : '');
     return (
       <Popover id="sqllab-limit-results">
-        <div style={{ width: '100px' }}>
+        <div style={popoverStyle}>
           <ControlHeader
             label={t('Row limit')}
             validationErrors={!isValid ? [t(errorMsg)] : []}
```
Comment (etr2460) [inline superset-frontend/src/SqlLab/components/LimitControl.tsx:105]: The translation function here probably doesn't do anything

File: superset-frontend/src/SqlLab/components/LimitControl.tsx (hunk 2 above)
Comment (mistercrunch) [reply superset-frontend/src/SqlLab/components/LimitControl.tsx:113]: Following the pattern in other files `src/explore/components/PropertiesModal.tsx`

**Review by etr2460 — APPROVED** [review]
