### PR TITLE
fix: Side menu of the dashboard component will scroll out of dashboard

### LINKED ISSUE #15862: [cosmetic][dashboard edit] side menu of the dashboard component will scroll out of dashboard
## Screenshot

https://user-images.githubusercontent.com/81597121/126758633-73a0ebb0-fff0-49a8-b71c-068b7b5a7754.mov

## Description

side menu of the dashboard component will scroll out of dashboard

### PR DESCRIPTION
**Pull request by michael-s-molina**
### SUMMARY
Fixes https://github.com/apache/superset/issues/15862

@junlincc @jinghua-qa

### AFTER SCREENSHOTS OR ANIMATED GIF
https://user-images.githubusercontent.com/70410625/126901989-84217155-c073-4b92-a2fa-494b7c82c9f0.mp4

### TESTING INSTRUCTIONS
See the original issue for instructions.

### ADDITIONAL INFORMATION
- [x] Has associated issue:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/components/DashboardBuilder/DashboardBuilder.tsx [hunk 1]
```diff
@@ -69,10 +69,11 @@ const StyledDiv = styled.div`
   flex: 1;
 `;
 
+// @z-index-above-dashboard-charts + 1 = 11
```
Comment (rusackas) [inline superset-frontend/src/dashboard/components/DashboardBuilder/DashboardBuilder.tsx:72]: We should probably start a z-index registry somewhere. The comment is appreciated in the meantime.

**Review by rusackas — APPROVED** [review]
