### PR TITLE
fix(chart): ensure samples data is displayed

### LINKED ISSUE #16661: [explore][sample table] Sample table show ' no data' when there are rows retrieved
Sample table show ' no data' when there are rows retrieved, i tried Echarts seems this issue is observed in different chart types

### Expected results

Sample chart will show data when there are rows retrieved

### Actual results

Sample chart showed no data when there are rows retrieved

#### Screenshots
Screen Shot 2021-09-10 at 12 49 19 AM

#### How to reproduce the bug

1. open dataset 'cleaned_sales_data'
2. select time-series area chart and create a chart
3. go to sample table

### Environment

(please complete the following information):

- superset version: latest master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active: d&d, d&d hybrid, UX_beta

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by pkdotson**
### SUMMARY
This pr fixes an issue where the view samples tab does not show the sample data. This problem was seen because the column names weren't updated for the samples tab since the old legacy endpoint does not return columns.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
after
https://user-images.githubusercontent.com/17326228/135015945-ba291b18-3526-4d94-866f-9b980af24f3d.mov

### TESTING INSTRUCTIONS
Open up charts that use both legacy and new /chart enpoints and ensure that the VIEW SAMPLES show up in the datatables pane. 

### ADDITIONAL INFORMATION

- [x ] Has associated issue: Fixes https://github.com/apache/superset/issues/16661
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/explore/components/DataTablesPane/index.tsx [hunk 1]
```diff
@@ -189,10 +247,29 @@ export const DataTablesPane = ({
           } else {
             setData(prevData => ({
               ...prevData,
+              // [{....}]
```
Comment (kgabryje) [inline superset-frontend/src/explore/components/DataTablesPane/index.tsx:250]: comment to be removed?

**Comment by kgabryje** [comment]
Can we add some unit tests?

**Review by jinghua-qa — APPROVED** [review]
LGTM
Screen Shot 2021-11-08 at 2 24 10 PM

File: superset-frontend/src/explore/components/DataTablesPane/index.tsx [hunk 2]
```diff
@@ -192,7 +250,25 @@ export const DataTablesPane = ({
               [resultType]: json.result[0].data,
             }));
           }
-
+          const checkCols = json?.result[0]?.data?.length
+            ? Object.keys(json.result[0].data[0])
+            : null;
+          if (!json.result[0].colnames && checkCols?.length) {
+            let tabKey: string = RESULT_TYPES.results;
+            if (resultType === RESULT_TYPES.samples) {
```
Comment (kgabryje) [inline superset-frontend/src/explore/components/DataTablesPane/index.tsx:258]: I'm wondering if we could simplify the logic here? For example, `tabKey` variable seems redundant. Also, I'm not sure if `resultType === RESULT_TYPES.samples` check is necessary.
Can't we do this instead?
```
setColumnNames(prevColumnNames => ({
              ...prevColumnNames,
              [resultType]: json.result[0].colnames || checkCols,
            }));
```

File: superset-frontend/src/explore/components/DataTablesPane/index.tsx [hunk 3]
```diff
@@ -192,7 +250,25 @@ export const DataTablesPane = ({
...
+              tabKey = RESULT_TYPES.samples;
+            }
+            setColumnNames({
```
Comment (kgabryje) [inline superset-frontend/src/explore/components/DataTablesPane/index.tsx:261]: We should use function syntax when we update state using the old state
```setColumnNames(prevColumnNames => ({
    ...prevColumnNames,
    [tabKey]: checkCols,
}));
```
https://reactjs.org/docs/hooks-reference.html#functional-updates

**Review by kgabryje — COMMENTED** [review]
Looks nice! I left a comment with a suggestion how to simplify the logic of setting column names

**Review by kgabryje — APPROVED** [review]
LGTM
