### PR TITLE
fix: Fixing untranslated FR strings

### LINKED ISSUE #20060: Missing French Translation
Issues to add french translation missing

Step : 

- [ ]  The additional French translations
- [ ] Fixing the untranslated strings
- [ ] using gettext instead of lazy_gettext
- [ ] translate variable
- [ ] translate changed_on_delta_humanized

### PR DESCRIPTION
**Pull request by aehanno**
### SUMMARY

Fixing the untranslated strings

### Add Information
Fixes https://github.com/apache/superset/issues/20060

### CODE REVIEW

**Review by villebro — CHANGES_REQUESTED** [review]
Left a few comments

**Comment by ETselikov** [comment]
@aehanno Hi! We are looking forward into improving translations as the same places you address in this PR. Are you planning on finishing your work here and merging it into master?

**Comment by aehanno** [comment]
> @aehanno Hi! We are looking forward into improving translations as the same places you address in this PR. Are you planning on finishing your work here and merging it into master?

Hi @ETselikov, I'm a little block on this change https://github.com/apache/superset/pull/20078#discussion_r986497228
I don't have the list of values of the variable name

If you have any idea, I will do the change and merge my branch

File: superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx [hunk 1]
```diff
@@ -47,7 +48,7 @@ function displayHeaderCell(
       >
         {ArrowIcon}
       </span>
-      <span className="toggle-val">{parseLabel(name)}</span>
+      <span className="toggle-val">{t(parseLabel(name))}</span>
```
[the remark this answers is not in the document]
Comment (Always-prog) [reply superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx:51]: Hello @villebro @aehanno!
We should not translate the results of the parseLabel function, because users can just set the verbose name of the column/metric in the dataset or manual SQL, excluding the string 'metric' that appears in the top left corner.
image

To translate that metric, we can just add a translation for the METRIC_KEY constant at superset-frontend/plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx:59, and it will work properly.
Result of translating METRIC_KEY:
image

[the remark this answers is not in the document]
Comment (aehanno) [reply superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx]: I just do the correction, thanks

**Comment by aehanno** [comment]
Hi @villebro, I just do the changes you request

can you do a review of the new code to merge the PR after

Thanks

File: superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx [hunk 2]
```diff
@@ -20,12 +20,15 @@
 import React from 'react';
 import { t } from '@superset-ui/core';
 import PropTypes from 'prop-types';
-import { t } from '@superset-ui/core';
 import { PivotData, flatKey } from './utilities';
 import { Styles } from './Styles';
 
 const parseLabel = value => {
```
Comment (Always-prog) [inline superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx:26]: We do not need to change the parseLabel function. Instead, we can simply translate the METRIC_KEY constant in superset-frontend/plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx:58

File: superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx [hunk 3]
```diff
@@ -24,7 +24,11 @@ import { PivotData, flatKey } from './utilities';
...
```
Comment (Always-prog) [inline superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx:26]: We do not need to change the parseLabel function. Instead, we can simply translate the METRIC_KEY constant in superset-frontend/plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx:58

File: superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx [hunk 4]
```diff
@@ -24,7 +24,11 @@ import { PivotData, flatKey } from './utilities';
...
-  if (typeof value === 'number' || typeof value === 'string') {
+  if (typeof value === 'string') {
+    if (value === 'metric') return t('metric');
```
Comment (Always-prog) [inline superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx:28]: We do not need to change the parseLabel function. Instead, we can simply translate the METRIC_KEY constant in superset-frontend/plugins/plugin-chart-pivot-table/src/PivotTableChart.tsx:58

Comment (aehanno) [reply superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx:28]: When I put t('metric') for the METRIC_KEY constant, I don't see the trnaslation in the chart

Comment (Always-prog) [reply superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx:28]: Because you need to rebuild pot file, then rebuild po files and build messages.json again.

Comment (Always-prog) [reply superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx]: Ok, let me test it.

Comment (Always-prog) [reply superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx]: It works on me, but anyway you need to build .pot file and .po files.
Here's instructions: https://superset.apache.org/docs/contributing/translations/

Comment (aehanno) [reply superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx]: Oh okay, I did it but not so easy to work with this generation because that remove some translation

Comment (aehanno) [reply superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx]: I don't know why I have still warning for prettier as I launch this command before push `npx prettier --update ../superset/translations/**/LC_MESSAGES/*.json`

File: superset-frontend/src/explore/components/useExploreAdditionalActionsMenu/index.jsx [hunk 5]
```diff
@@ -313,7 +313,7 @@ export const useExploreAdditionalActionsMenu = (
               icon={<Icons.FileOutlined css={iconReset} />}
               disabled={!canDownloadCSV}
             >
-              {t('Export to .CSV')}
+              {t('test')}
```
Comment (Always-prog) [inline superset-frontend/src/explore/components/useExploreAdditionalActionsMenu/index.jsx:316]: Here must be Export to .CSV

File: superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx (hunk 4 above)
Comment (Always-prog) [reply superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx]: Hello.
I think we can ignore that warning.

Comment (aehanno) [reply superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx]: Okay because, I got a job in error becuse of that

Comment (Always-prog) [reply superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx]: Where did you receive information that the messages.json files need to be refactored with Prettier? As I understand it, they can be pushed as builded. And your previous commits with changed messages.json passed all tests.

Comment (Always-prog) [reply superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx]: I builded your mo files on my and found that after building everything is fine. With or without Prettier refactoring, there are no warnings. 
However, the messages.json files that you pushed are still getting warnings from Prettier on my. Can you please check your translation using the `npm run check-translation` command on your computer before pushing and make it works?
Maybe you don't need to refactor messages.json by prettier?

Comment (aehanno) [reply superset-frontend/plugins/plugin-chart-pivot-table/src/react-pivottable/TableRenderers.jsx]: It's what I did and I have this return 
Capture d’écran du 2023-02-01 17-53-41

**Comment by aehanno** [comment]
HI @villebro, if you can check, if it's okay for you

**Comment by aehanno** [comment]
Hi @Always-prog  and @villebro, I update the PR with master and check your comments, it's possible for you to check that to closed this ticket as soon as possible ?
Thank you

**Comment by rusackas** [comment]
@villebro @michael-s-molina can you confirm or deny a concern here? It looks like this PR is editing the JSON files, which were (or could be) generated from the `.po` files, according to the docs: https://superset.apache.org/docs/contributing/translations/

Is it a risky/bad idea to make these updates this way? Should people be editing the `.po` files rather than `.json`?

**Comment by aehanno** [comment]
> @villebro @michael-s-molina can you confirm or deny a concern here? It looks like this PR is editing the JSON files, which were (or could be) generated from the `.po` files, according to the docs: https://superset.apache.org/docs/contributing/translations/
> 
> Is it a risky/bad idea to make these updates this way? Should people be editing the `.po` files rather than `.json`?

Hi @rusackas, I used the script po2json.sh to generate json file from po file but All the translation with "#, fuzzy" are not display in the json file.
It's normal or not ?

Thanks for your answer

**Comment by rusackas** [comment]
Oh, ok, if this JSON was generated by the script, I think we're good. I feared you hand-edited the JSON and opened a PR (it wouldn't be the first time that's happened).

**Review by rusackas — APPROVED** [review]

**Comment by aehanno** [comment]
> Left a few comments

HI @villebro, I need your review to move this ticket forward.

Thanks

**Comment by rusackas** [comment]
@villebro the merging is blocked awaiting your review. Holler if you think there's more to work on here :) Thanks!

**Review by villebro — APPROVED** [review]

**Comment by aehanno** [comment]
Thanks @villebro and @rusackas for approvals. Do you know what's the next step to merge this PR now ?
