### PR TITLE
fix: bug in tooltip timeseries chart in calculated total with annotation layer

### LINKED ISSUE #31735: Annotation layer using formula is included in the sum of the rich tool tip
### Bug description

1. Create a bar chart
2. Add a Annotation Layer using Formula 
3. Ensure that rich tool tip is enabled 
4. When hovering over the bar chart the value from the annotation layer is included in the rich tooltip and is included in the total value. 

### Screenshots/recordings

image

### Superset version

4.1.1

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

Assuming that some users are using the annotation layers to create baselines and/or goals it would be great if either:
1) The annotation layer value was not included in the tooltip, or;
2) Annotation layers has an option to not include the values in the rich tooltip. 

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by SBIN2010**
This PR fixed #31735 

### SUMMARY

Annotation layers are no longer counted towards total and percentage calculations.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

BEFORE
Снимок экрана от 2025-09-18 00-46-24

AFTER
Снимок экрана от 2025-09-18 00-18-47

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts [hunk 1]
```diff
@@ -582,9 +582,21 @@ export default function transformProps(
...
+        const filteredForecastValue = forecastValue.filter(
+          (item: any) =>
+            !annotationLayers.some(
+              (annotation: any) => item.seriesName === annotation.name,
+            ),
+        );
         const forecastValues: Record<string, ForecastValue> =
           extractForecastValuesFromTooltipParams(forecastValue, isHorizontal);
 
+        const filteredForecastValues: Record<string, ForecastValue> =
```
Comment (mistercrunch) [inline superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts:600]: No biggy but I was surprised to see types re-stated here, looked up the function definition and types are defined there.

**Review by mistercrunch — APPROVED** [review]
minor nit, otherwise LGTM

File: superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts (hunk 1 above)
Comment (SBIN2010) [reply superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/transformProps.ts:600]: I agree, any should be replaced with the correct type., 👍

**Review by rusackas — APPROVED** [review]

**Comment by sfirke** [comment]
Thank you for fixing this! My users will be excited. And thanks Joe for tagging it into 6.0.
