### PR TITLE
fix(Mixed Timeseries Chart): Custom Metric Label 

### LINKED ISSUE #17586: [mixed time-series] Metric name is shown in legend instead of label
#### How to reproduce the bug

1. Create a metric with a custom label
2. Use this metric in Mixed Time-series Chart

### Expected results

Custom label for metric is shown in legend.

### Actual results

Metric name is shown in legend.

#### Screenshots

image

### Environment

(please complete the following information):

- browser type and version: Chrome 96
- superset version: `master`
- python version: `3.9`
- node.js version: `14.15.5`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This issue is not present in other time-series echarts

### PR DESCRIPTION
**Pull request by Yahyakiani**
### SUMMARY

Bug Fix
This PR fixes the problem in which custom metric name is shown in legend instead of custom metric label inside Mixed Time series charts. Reference: Issue #17586

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

before
after

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [x] Fixes #17586
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by stephenLYZ — APPROVED** [review]
LGTM. Thanks for the fix!

**Comment by zhaoyongjie** [comment]
Hi @Yahyakiani , Thanks for the fix. Could you mind fixing the lint?

**Comment by Yahyakiani** [comment]
> Hi @Yahyakiani , Thanks for the fix. Could you mind fixing the lint?

Is anything else required on this issue ?

**Comment by zhaoyongjie** [comment]
> Is anything else required on this issue ?

The CI need to be fix.
image

**Comment by Yahyakiani** [comment]
> 

What steps could I perform to resolve it? Because I have tried running lint but it seems to make no difference.

**Comment by Yahyakiani** [comment]
> > Is anything else required on this issue ?
> 
> The CI need to be fixed. image

What steps could I perform to resolve it? Because I have tried running lint but it seems to make no difference.

**Comment by villebro** [comment]
@Yahyakiani these linting errors are blocking CI:
image
Let me know if you need help resolving them

**Comment by Yahyakiani** [comment]
> @Yahyakiani these linting errors are blocking CI: image Let me know if you need help resolving them

@villebro Actually I ran lint locally multiple times. It seems to run without error and on saving the file there are no changes.
lint1
eslint

**Comment by villebro** [comment]
@Yahyakiani ok let me checkout your PR locally and see if I can repro the problem

**Comment by stephenLYZ** [comment]
@Yahyakiani hey, I think you may need to lint all files instead of one file under superset-frontend.

File: superset-frontend/packages/superset-ui-core/src/query/types/QueryFormData.ts [hunk 1]
```diff
@@ -146,7 +147,7 @@ export type ExtraFormData = ExtraFormDataAppend & ExtraFormDataOverride;
 
 export interface BaseFormData extends TimeRange, FormDataResidual {
   /** datasource identifier ${id}_${type} */
-  datasource: string;
+  datasource: Datasource;
```
Comment (villebro) [inline superset-frontend/packages/superset-ui-core/src/query/types/QueryFormData.ts:150]: TL;DR: this should be unchanged.

I believe this should remain as `string` - this will change in Superset 2.0, but right now `datasource` in the chart metadata is stored as a string, e.g. `1__table`, which represents the primary keys of a base datasource object in the backend. That can then be fetched from the backend, and when that's done, it then becomes a full `Datasource` object, something like
```javascript
{
  id: 1,
  type: 'string',
  name: 'my_table',
  ...
}
```
which is later returned in `chartProps`.

**Review by villebro — COMMENTED** [review]
The issues aren't directly "linting" errors per se, but actually type errors. See my comment below.

File: superset-frontend/packages/superset-ui-core/src/query/types/QueryFormData.ts (hunk 1 above)
Comment (Yahyakiani) [reply superset-frontend/packages/superset-ui-core/src/query/types/QueryFormData.ts]: Thanks @villebro. Found the issue and was successfully able to resolve it.
Did the following: 
1. Reverted the Type change and applied the fix
3. Ran Lint on the `superset-frontend` folder
4. Retested the UI after changes

res

File: superset-frontend/plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts [hunk 2]
```diff
@@ -121,10 +129,12 @@ export default function transformProps(
   }: EchartsMixedTimeseriesFormData = { ...DEFAULT_FORM_DATA, ...formData };
 
   const colorScale = CategoricalColorNamespace.getScale(colorScheme as string);
-  const rawSeriesA = extractTimeseriesSeries(rebaseTimeseriesDatum(data1), {
+  const rebasedDataA = rebaseTimeseriesDatum(data1, extractedDataSource);
```
Comment (villebro) [inline superset-frontend/plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts:132]: Does this really work? Looking at the code, I think we should be passing `verboseMap`, not `datasource`: https://github.com/apache/superset/blob/04e3cfa6077faa84b07948fc6071e94d82a4a000/superset-frontend/plugins/plugin-chart-echarts/src/utils/prophet.ts#L112-L115

So seems this is the correct solution:
```suggestion
  const rebasedDataA = rebaseTimeseriesDatum(data1, extractedDataSource?.verboseMap);
```

File: superset-frontend/plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts [hunk 3]
```diff
@@ -121,10 +129,12 @@ export default function transformProps(
...
+  const rawSeriesA = extractTimeseriesSeries(rebasedDataA, {
     fillNeighborValue: stack ? 0 : undefined,
   });
-  const rawSeriesB = extractTimeseriesSeries(rebaseTimeseriesDatum(data2), {
+  const rebasedDataB = rebaseTimeseriesDatum(data2, extractedDataSource);
```
Comment (villebro) [inline superset-frontend/plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts:136]: Same here

**Review by villebro — COMMENTED** [review]
Fix seems mostly correct, but one question

File: superset-frontend/plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts (hunk 2 above)
Comment (Yahyakiani) [reply superset-frontend/plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts:132]: @villebro This leads to this typescript error `Property 'verboseMap' does not exist on type string` due to the following definition of `datasource`. Leading back to where Its type must be changed to an `Object`.
data

Comment (villebro) [reply superset-frontend/plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts:132]: @Yahyakiani oh, ok, now I see. Let me take a new look, it appears some type/interface declarations are incorrect somewhere after all.

Comment (villebro) [reply superset-frontend/plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts:132]: @Yahyakiani Ok, it seems there was an error in the original `transformProps` signature; `chartProps` isn't `EchartsMixedTimeseriesFormData`, but `EchartsMixedTimeseriesProps`. After changing that and making some modifications this should probably work (I didn't test, but it seems to pass lint):

```diff
diff --git a/superset-frontend/plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts b/superset-frontend/plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts
index 0f0fc2a72a..c287ab90c7 100644
--- a/superset-frontend/plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts
+++ b/superset-frontend/plugins/plugin-chart-echarts/src/MixedTimeseries/transformProps.ts
@@ -33,6 +33,7 @@ import {
   DEFAULT_FORM_DATA,
   EchartsMixedTimeseriesFormData,
   EchartsMixedTimeseriesChartTransformedProps,
+  EchartsMixedTimeseriesProps,
 } from './types';
 import { ForecastSeriesEnum } from '../types';
 import { parseYAxisBound } from '../utils/controls';
@@ -63,7 +64,7 @@ import {
 import { TIMESERIES_CONSTANTS } from '../constants';

 export default function transformProps(
-  chartProps: EchartsMixedTimeseriesFormData,
+  chartProps: EchartsMixedTimeseriesProps,
 ): EchartsMixedTimeseriesChartTransformedProps {
   const {
     width,
@@ -74,11 +75,11 @@ export default function transformProps(
     filterState,
     datasource,
   } = chartProps;
+  const { verboseMap = {} } = datasource;
   const { annotation_data: annotationData_ } = queriesData[0];
   const annotationData = annotationData_ || {};
-  const extractedDataSource = datasource || {};
-  const data1: TimeseriesDataRecord[] = queriesData[0].data || [];
-  const data2: TimeseriesDataRecord[] = queriesData[1].data || [];
+  const data1 = (queriesData[0].data || []) as TimeseriesDataRecord[];
+  const data2 = (queriesData[1].data || []) as TimeseriesDataRecord[];

   const {
     area,
@@ -129,14 +130,18 @@ export default function transformProps(
   }: EchartsMixedTimeseriesFormData = { ...DEFAULT_FORM_DATA, ...formData };

   const colorScale = CategoricalColorNamespace.getScale(colorScheme as string);
-  const rebasedDataA = rebaseTimeseriesDatum(data1, extractedDataSource);
-  const rawSeriesA = extractTimeseriesSeries(rebasedDataA, {
-    fillNeighborValue: stack ? 0 : undefined,
-  });
-  const rebasedDataB = rebaseTimeseriesDatum(data2, extractedDataSource);
-  const rawSeriesB = extractTimeseriesSeries(rebasedDataB, {
-    fillNeighborValue: stackB ? 0 : undefined,
-  });
+  const rawSeriesA = extractTimeseriesSeries(
+    rebaseTimeseriesDatum(data1, verboseMap),
+    {
+      fillNeighborValue: stack ? 0 : undefined,
+    },
+  );
+  const rawSeriesB = extractTimeseriesSeries(
+    rebaseTimeseriesDatum(data2, verboseMap),
+    {
+      fillNeighborValue: stackB ? 0 : undefined,
+    },
+  );

   const series: SeriesOption[] = [];
   const formatter = getNumberFormatter(contributionMode ? ',.0%' : yAxisFormat);
```

**Review by villebro — APPROVED** [review]
LGTM, thanks for the fix and diligently iterating on this!
