### PR TITLE
fix(native-filters): show human readable time grain label in indicator

### LINKED ISSUE #15361: [native filter] 'Clear All' will show error in value filter
when setup a value filter + numerical filter in a dashboard, set both filter 'Apply changes instantly', then select value for each filter and then click 'Clear All', value filter will show error of too many updates

### Expected results
value filter and numerical filter can be clear 

### Actual results

value filter show error, numerical filter can be clear to origin state

#### Screenshots

Screen Shot 2021-06-24 at 3 04 35 AM

https://user-images.githubusercontent.com/81597121/123245951-270abf80-d49a-11eb-859b-0e95a2e2489d.mov

#### How to reproduce the bug

1. Go to USA birth name dashboard
2. Setup a value filter, select 'apply change instantly'
3. Setup a numerical filter, select 'apply change instantly'
4. go to dashboard and select some value for both filter and see changes 
5. click 'Clear All' and see error in value dashboard

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by villebro**
### SUMMARY
Currently when using a time grain native filter, the ISO-8601 time duration is shown in the filter indicator. Instead of showing the technical duration in the indicator (e.g. `PT1H`), it is preferable to show the human readable filter value (e.g. "Hour").

### AFTER
Now the human readable label is displayed in the filter indicator:
image

### BEFORE
Previously the ISO-8601 time duration was shown in the filter indicator
image

### ADDITIONAL INFORMATION

- [x] Has associated issue: closes #15361
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/filters/components/TimeGrain/TimeGrainFilterPlugin.tsx [hunk 1]
```diff
@@ -52,10 +52,22 @@ export default function PluginFilterTimegrain(
...
+  const durationMap = useMemo(
+    () =>
+      data.reduce((agg, row) => {
+        const { duration, name } = row as { duration: string; name: string };
+        return {
+          ...agg,
+          [duration]: name,
+        };
+      }, {} as { [key in string]: string }),
+    [JSON.stringify(data)],
```
Comment (simcha90) [inline superset-frontend/src/filters/components/TimeGrain/TimeGrainFilterPlugin.tsx:64]: may be simplify:
```
data.reduce((agg, row) => ({
          ...agg,
          [row.duration]: row.name
      }), {} as { [key in string]: string }),
```

**Review by simcha90 — APPROVED** [review]

**Comment by rosemarie-chiu** [comment]
🏷 2021.25
