### PR TITLE
fix(Context-Menu): Fixing Context Menu for Table Chart with Html Content

### LINKED ISSUE #33771: Using Drill by in a dashboard doesn't work in columns created with <a> tags
## Description
If you create a chart (e.g. Table Chart) with a custom SQL query that has an `<a>`, the resulting chart can be created and nested in a dashboard and you won’t be able to use the Drill by feature with it because nothing appears.

## How to reproduce the bug
1. Create a Table chart 
2. Use as dimension a column that has a `<a>` tag applied in the Custom SQL section. It could be something like this `'<a href="https://www.google.com/search?q='  || Product_Category || '">' || Product_Category || '</a>'`
3. Save the chart in a dashboard and then use the Drill by feature in that column

Image

## Expected results
The prompted window after using Drill by shows you the details of the category

## Actual results
The prompted window after using Drill by doesn’t show anything

Image

## Known Workarounds
No workarounds are currently known

### Screenshots/recordings

_No response_

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

_No response_

### Checklist

- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by amaannawab923**
### SUMMARY

[screen-capture (45).webm](https://github.com/user-attachments/assets/a6748193-fcf8-4f2c-9d96-7e4df6f6149e)

Fixes: https://github.com/apache/superset/issues/33771

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/plugins/plugin-chart-table/src/TableChart.tsx [hunk 1]
```diff
@@ -243,6 +243,24 @@ function SelectPageSize({
 const getNoResultsMessage = (filter: string) =>
   filter ? t('No matching records found') : t('No records found');
 
+const isHtml = (value: any): boolean => {
```
Comment (mistercrunch) [inline superset-frontend/plugins/plugin-chart-table/src/TableChart.tsx]: comment crafted with Claude -> 

---
Hi @amaannawab923, thanks for working on this fix!

  For handling HTML content in table cells, we already have comprehensive HTML utilities available in the codebase that should be used:

  📍 HTML Utilities Location: @superset-ui/core/src/utils/html

  Key functions available:
  - removeHTMLTags(str) - Strips all HTML tags from a string (useful for getting plain text for context menu operations)
  - sanitizeHtml(htmlString) - Safely sanitizes HTML content using XSS filtering
  - isProbablyHTML(text) - Detects if a string contains valid HTML
  - safeHtmlSpan(possiblyHtmlString) - Returns a safe React component for rendering HTML

  The table chart already uses these utilities in superset-frontend/plugins/plugin-chart-table/src/utils/formatValue.ts:54 for sanitizing HTML content when allowRenderHtml is enabled.

  For the context menu issue with HTML <a> tags, you might want to use removeHTMLTags() to extract the plain text value for drill-down operations. This is already being done in the drill detail menu items (see
  DrillDetailMenuItems.tsx:93).

  Example usage:
  import { removeHTMLTags } from '@superset-ui/core';

  // When handling context menu for HTML cells
  const plainTextValue = removeHTMLTags(htmlCellValue);

  This approach ensures consistency with how HTML is handled throughout the codebase and maintains proper security sanitization.

**Comment by mistercrunch** [comment]
Converting to draft until adjusted / ready for another round of review

**Comment by amaannawab923** [comment]
> Converting to draft until adjusted / ready for another round of review

Did the changes as per recommendation @mistercrunch

File: superset-frontend/plugins/plugin-chart-table/src/TableChart.tsx [hunk 2]
```diff
@@ -251,6 +253,13 @@ function SelectPageSize({
 const getNoResultsMessage = (filter: string) =>
   filter ? t('No matching records found') : t('No records found');
 
+const sanitizeHtmlValue = (value: DataRecordValue): DataRecordValue => {
```
Comment (mistercrunch) [inline superset-frontend/plugins/plugin-chart-table/src/TableChart.tsx]: can't use the sanitizeHtml from the utils? Guessing this is different? does this function belongs in the utils or is it component-specific?

Comment (amaannawab923) [reply superset-frontend/plugins/plugin-chart-table/src/TableChart.tsx]: Yes this is different , its about extracting value from Html Tag -> 
Input : 
< /a href="https://www.google.com/search?q=United Kingdom">United Kingdom<\/a>"

Expected Output:
United Kingdom

Sanitise Html function would just sanitise that html to remove malicious code 

For now , i guess this is component specific , because it will only come to use here in Table

Comment (amaannawab923) [reply superset-frontend/plugins/plugin-chart-table/src/TableChart.tsx]: I think the function name is causing confusion with html sanitisation , should probably rename it to , ExtractTextFromHtml

File: superset-frontend/plugins/plugin-chart-table/src/TableChart.tsx [hunk 3]
```diff
@@ -251,6 +253,13 @@ function SelectPageSize({
...
+  if (typeof value === 'string' && isProbablyHTML(value)) {
+    return removeHTMLTags(value);
+  }
```
[the remark this answers is not in the document]
Comment (mistercrunch) [reply superset-frontend/plugins/plugin-chart-table/src/TableChart.tsx]: assuming it's generic enough and can be reused elsewhere, let's move the function definition to the html utils module

[the remark this answers is not in the document]
Comment (amaannawab923) [reply superset-frontend/plugins/plugin-chart-table/src/TableChart.tsx]: Done

**Comment by mistercrunch** [comment]
Add simple covering unit tests and I think this is mergeable!

**Comment by amaannawab923** [comment]
> Add simple covering unit tests and I think this is mergeable!

Done ! Added Unit tests & Thanks for the review

**Review by mistercrunch — APPROVED** [review]
LGTM

**Comment by mistercrunch** [comment]
@msyavuz why the hold?

**Comment by msyavuz** [comment]
@mistercrunch The issue has a bounty assigned. We need to remove that before this get's merged.
