### PR TITLE
fix(explore): #10098 boolean filter not working

### LINKED ISSUE #10098: Filter on bool column not working properly in SQL Lab -> Explore
When a query in SQL Lab is executed and a filter is applied to a boolean column, it errors out on datatype comparison (boolean vs string). 
Note - the behavior
### Expected results
The filter should work - the generated query should not enclose the field value in single quotes. 

### Actual results
The query generated encloses the filter value in single quotes so the where clause generated looks (some_bool_flag = 'true') and this that in turn generates type mismatch

#### How to reproduce the bug

1. Go to SQL Lab -> SQL Editor
2. Write a query that returns a boolean column
3. Execute the query
4. Click on Explore
5. Scroll down to filters
6. Add a filter on a boolean column and make sure you stay in Simple (not Custom SQL)
7. Use equals and set filter value to "true" (without double quotes)
8. Execute the query to see the error messge
9. Click on menu -> View query to inspect that the filter value was enclosed in single quotes

### Environment

(please complete the following information):

- superset version: `superset version
0.34.1
- python version: `python --version`
Python 3.6.9
- node.js version: `node -v`
v12.18.0
- npm version: `npm -v`
6.14.4
### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
I have no control over the environment :(
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

When the filter is entered using the Custom SQL instead of Simple, it works fine

### PR DESCRIPTION
**Pull request by m-ajay**
### SUMMARY
Fixes #10098.
When the column type is boolean/number type, show `IS TRUE` and `IS FALSE` options.

Screen Shot 2021-05-11 at 1 23 37 PM

### TEST PLAN
CI and manual test

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by junlincc** [comment]
hi ajay, thanks for contributing to the quality bash! please make sure to include screenshot and description in your pr and change the title. e.g. fix(explore): filter on boolean column ...

File: superset-frontend/src/explore/components/controls/FilterControl/AdhocFilterEditPopoverSimpleTabContent/index.jsx [hunk 1]
```diff
@@ -236,18 +237,42 @@ export default class AdhocFilterEditPopoverSimpleTabContent extends React.Compon
...
+        ].indexOf(operator) >= 0
+      );
+    }
+    if (dataSourceType === 'druid' && !isColumnNumber) {
+      return (
+        [...BOOLEAN_ONLY_OPERATORS, ...TABLE_ONLY_OPERATORS].indexOf(operator) <
+        0
+      );
+    }
+    if (dataSourceType === 'table' && !isColumnNumber) {
```
Comment (graceguo-supercat) [inline superset-frontend/src/explore/components/controls/FilterControl/AdhocFilterEditPopoverSimpleTabContent/index.jsx:267]: For calculated column, which could be number, string, date, or unset type, we probably show IS_TRUE, IS_FALSE as option?

**Review by ktmud — COMMENTED** [review]
I don't think we need to add additional comparators. Superset should be smart enough to know a column is boolean or not. 

The [`col_spec`](https://github.com/apache/superset/blob/c760030b839591c6913a8cf1243e822f4b328c98/superset/connectors/sqla/models.py#L1165) accessed earlier already has an indication whether a column is `Boolean`. You can just handle the filter value differently based on this information.

**Comment by ktmud** [comment]
The easier fix is probably convert string value "true"/"false" to booleans [here](https://github.com/apache/superset/blob/13f7e0d75589230db0324c9c3afa3421d76dbd56/superset/connectors/base/models.py).

An optional work is to update the frontend to change the input from text input to select.

**Comment by ktmud** [comment]
IIRC, currently the value input would query the backend for available options, we can probably just give it a fixed options if we detect the column type is `boolean`.

**Review by graceguo-supercat — APPROVED** [review]
LGTM

File: superset-frontend/src/explore/components/controls/FilterControl/AdhocFilterEditPopoverSimpleTabContent/index.jsx [hunk 2]
```diff
@@ -236,16 +237,45 @@ export default class AdhocFilterEditPopoverSimpleTabContent extends React.Compon
...
+      );
+    }
+    if (isColumnNumber || isColumnFunction) {
+      if (dataSourceType === 'druid') {
+        return !(TABLE_ONLY_OPERATORS.indexOf(operator) >= 0);
+      }
+      if (dataSourceType === 'table') {
+        return !(DRUID_ONLY_OPERATORS.indexOf(operator) >= 0);
+      }
+    }
```
Comment (ktmud) [inline superset-frontend/src/explore/components/controls/FilterControl/AdhocFilterEditPopoverSimpleTabContent/index.jsx:269]: I think this whole section can be simplified as

```ts
if (operator === OPERATORS['IS TRUE'] || operator === OPERATORS['IS FALSE'])) {
    return isColumnBoolean || isColumnBoolean;
}
if (isColumnBoolean) {
    return operator === OPERATORS['IS NULL'] || operator === OPERATORS['IS NOT NULL'];
}
```

**Review by geido — APPROVED** [review]
LGTM!

File: superset-frontend/src/explore/components/controls/FilterControl/AdhocFilterEditPopoverSimpleTabContent/index.jsx [hunk 3]
```diff
@@ -236,16 +237,39 @@ export default class AdhocFilterEditPopoverSimpleTabContent extends React.Compon
...
       (this.props.datasource.type === 'druid' &&
-        TABLE_ONLY_OPERATORS.indexOf(operator) >= 0) ||
+        [...BOOLEAN_ONLY_OPERATORS, ...TABLE_ONLY_OPERATORS].indexOf(
+          operator,
+        ) >= 0) ||
       (this.props.datasource.type === 'table' &&
-        DRUID_ONLY_OPERATORS.indexOf(operator) >= 0) ||
+        [...BOOLEAN_ONLY_OPERATORS, ...DRUID_ONLY_OPERATORS].indexOf(
+          operator,
+        ) >= 0) ||
```
Comment (ktmud) [inline superset-frontend/src/explore/components/controls/FilterControl/AdhocFilterEditPopoverSimpleTabContent/index.jsx:272]: You can revert changes in these two lines, too, since you've checked boolean operators above.

File: superset-frontend/src/explore/constants.ts [hunk 4]
```diff
@@ -42,11 +42,18 @@ export const OPERATORS = {
...
 };
+
 export const OPERATORS_OPTIONS = Object.values(OPERATORS);
 
 export const TABLE_ONLY_OPERATORS = [OPERATORS.LIKE];
 export const DRUID_ONLY_OPERATORS = [OPERATORS.REGEX];
+export const BOOLEAN_ONLY_OPERATORS = [
+  OPERATORS['IS TRUE'],
+  OPERATORS['IS FALSE'],
+];
```
Comment (ktmud) [inline superset-frontend/src/explore/constants.ts:56]: This variable could also be deleted.

**Review by ktmud — APPROVED** [review]
LGTM with just a couple of notes on cleanups.

**Comment by junlincc** [comment]
@m-ajay thanks again for the fix! i believe boolean filter is broken in filter box as well, does this cover that as well?
