### PR TITLE
fix(native-filters): apply default value correctly when it's set

### LINKED ISSUE #17950: [native filter] "Filter has default value" isn't applied and visible after save
"default value" in Native Filter isn't applied and visible after save

#### How to reproduce the bug

Repro steps
1, Expand native filter sidebar
2, Click pencil edit icon and create a new filter
3, Check mark "filter has default value"
4, Fill out all require field
5, Select a default value and save
6, Observe filter value field and see error

### Expected results

Default value filter must be apply immediately and default values must be visible in input field

### Actual results

Default filter value is not applied and is not visible on input

#### Screenshots

https://user-images.githubusercontent.com/81597121/148420519-bb73bc10-eeee-4483-b874-33112122b0b3.mov

### Environment

(please complete the following information):

- browser type and version:
- superset version: master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
Due to a mistake in passing arguments to `dataMask/reducer/fillNativeFilters` function (we were passing undefined variable instead of data mask), default value wasn't applied correctly to native filters. This PR fixes this issue.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before: see linked issue
After:

https://user-images.githubusercontent.com/15073128/148766331-f3c5c33c-846a-4154-855e-45d2d9e43ac3.mov

### TESTING INSTRUCTIONS
Follow the repro steps from linked issue

### ADDITIONAL INFORMATION

- [x] Has associated issue: fixes #17950 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC @jinghua-qa @rosemarie-chiu @rusackas 

https://app.shortcut.com/preset/story/34609/native-filter-filter-has-default-value-isn-t-applied-and-visible-after-save

### CODE REVIEW

File: superset-frontend/src/dataMask/reducer.ts [hunk 1]
```diff
@@ -139,8 +139,6 @@ const dataMaskReducer = produce(
           action.filterConfig ?? [],
           cleanState,
           draft,
-          // @ts-ignore
-          action.data.dataMask,
```
Comment (villebro) [inline superset-frontend/src/dataMask/reducer.ts:143]: Do we have the same issue on line 134?

**Review by villebro — COMMENTED** [review]
LGTM - also wondering if there is another instance of this bug a few lines above?

File: superset-frontend/src/dataMask/reducer.ts (hunk 1 above)
Comment (kgabryje) [reply superset-frontend/src/dataMask/reducer.ts:143]: No, in line 134 `action` object does have `data.dataMask` field.

**Review by villebro — APPROVED** [review]
Ok thanks; LGTM!

**Review by geido — APPROVED** [review]
LGTM! Thanks for the fix

**Review by jinghua-qa — APPROVED** [review]
LGTM

**Comment by rosemarie-chiu** [comment]
🏷 2022.1
