### PR TITLE
fix(native-filters): Don't send unnecessary PUT request on dashboard render

### LINKED ISSUE #15125: [native-filters] interacting w native filter sidebar should not change dashboard ownership
Simply expand / retract native filter sidebar should not make you the owner of the dashboard
### Steps
1. Observe that you are not the owner of the dashboard in test
2. Open the dashboard
3. Expand and retract native filter 
4. Return to dashboard list

### Expected results
There should be no ownership change on the dashboard

### Actual results
I became the owner of the dashboard

https://user-images.githubusercontent.com/52086618/121752140-61e91c80-cac4-11eb-984f-dfb2ec1bac12.mp4

### PR DESCRIPTION
**Pull request by kgabryje**
### SUMMARY
When dashboard first renders, we calculate tabs and charts in scope of each native filter. Before, we used to send a PUT request with the results, which also modified dashboard's metadata. This PR fixes that behaviour by saving the results only in redux, without sending them to the backend. Also, now we run the calculations only if the native filters feature flag is enabled
This PR is related to an issue raised by @graceguo-supercat in comments https://github.com/apache/superset/pull/14933#discussion_r650331375 and https://github.com/apache/superset/pull/14933#issuecomment-860168672. The problem with setting properties `show_native_filters` and `native_filter_configuration` was not caused directly by PR https://github.com/apache/superset/pull/14933, but the problem was elevated by that PR because of sending unnecessary PUT request. The root of the issue will be handled in a separate PR by @villebro.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Notice that in "AFTER" screenshot there's no request to `/dashboard` endpoint which modifies metadata.
Before:
image

After:
image

### TESTING INSTRUCTIONS
0. Set `DASHBOARD_NATIVE_FILTERS` feature flag to True
1. Add some native filters
2. Reload the dashboard
3. Verify that `SET_FILTER_SCOPES` action was dispatched and no request to `/dashboard` endpoint was made
4. Verify that highlighting tabs and charts in scope of filters works as before
5. Unset `DASHBOARD_NATIVE_FILTERS` feature flag
6. Verify that `SET_FILTER_SCOPES` action was NOT dispatched

### ADDITIONAL INFORMATION

- [x] Has associated issue: closes #15125
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

CC: @villebro @graceguo-supercat

### CODE REVIEW

File: superset-frontend/src/dashboard/actions/nativeFilters.ts [hunk 1]
```diff
@@ -49,6 +49,11 @@ export interface SetFilterConfigFail {
   type: typeof SET_FILTER_CONFIG_FAIL;
   filterConfig: FilterConfiguration;
 }
+export const SET_FILTER_SCOPES = 'SET_FILTER_SCOPES';
+export interface SetFilterScopes {
+  type: typeof SET_FILTER_SCOPES;
+  filterConfig: FilterConfiguration;
+}
```
Comment (villebro) [inline superset-frontend/src/dashboard/actions/nativeFilters.ts:56]: To avoid potential confusion with the scopes defined in metadata, it could be nice to call this (and related variables/functions) something more explicit, like `SET_IN_SCOPE_STATUS_OF_FILTERS`.

**Review by villebro — APPROVED** [review]
Thanks for the quick fix! Works like expected, but one minor non-blocking comment regarding naming.

File: superset-frontend/src/dashboard/actions/nativeFilters.ts (hunk 1 above)
Comment (kgabryje) [reply superset-frontend/src/dashboard/actions/nativeFilters.ts]: Good point, done!
