### PR TITLE
fix(Chart Annotation modal): Table and Superset annotation options will paginate, exceeding previous max limit 100

### LINKED ISSUE #25421: Annotation Layer modal doesn't list all table charts when there are more than 100 tables
When creating a chart, users are able to add Annotation Layers that can be set to be powered by an existing table chart. However, the dropdown selector to specify a chart isn't returning all table charts available in the Workspace.

#### How to reproduce the bug

1. Make sure you have over 100 charts (duplicate dashboards to get to 100 more quickly if needed) 
2. Create a new Table Chart -- make sure the name starts with Z to see the bug more easily 
3. Try to use this table chart as an annotation layer source on another chart, like a Mixed chart or a time series chart 

### Expected results

When searching for a chart when adding annotations, the new chart appears 

### Actual results

image
The new chart doesn't appear in the chart list 

### Environment

(please complete the following information):

- browser type and version: 
- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

It seems that the endpoint to fetch the charts is only returning 100 results - there doesn't seem to be pagination and it also doesn't seem to be filtering by viz_type = table, which might also reduce the number of charts that would be returned.

### PR DESCRIPTION
**Pull request by rtexelm**
### SUMMARY

Replace the SelectControl component with an AsyncSelect component when choosing the source of the annotation. This addresses the response limiting table options to 100 max. There are relevant changes to the process of fetching and where the fetch is being made in the file.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

BEFORE:
limited-charts
AFTER:
all-charts

### TESTING INSTRUCTIONS

- Create 100+ annotations or Tables. Saving dashboards as duplicates and selecting the duplicate charts box will speed this process up.
- Charts must be **created by you** (annotation options are filtered by `'chart_owned_created_favored_by_me'`)
- Create a new chart
- Click the "Add Annotation" button
- Choose an Annotation type requiring a query, e.g. "Event"
- Scroll through the options to verify display of all 100+ charts

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes #25421 
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 1]
```diff
@@ -194,29 +210,26 @@ class AnnotationLayer extends React.PureComponent {
       hideLine,
       // refData
       isNew: !name,
-      isLoadingOptions: true,
-      valueOptions: [],
+      optionsFetch: this.asyncFetch.bind(this),
```
Comment (Antonio-RiveroMartnez) [inline superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:213]: We should not be setting a function in the state nor we should be binding here

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 2]
```diff
@@ -194,29 +210,26 @@ class AnnotationLayer extends React.PureComponent {
...
-    this.fetchOptions(annotationType, sourceType, isLoadingOptions);
+    this.fetchAppliedChart();
   }
 
-  componentDidUpdate(prevProps, prevState) {
-    if (prevState.sourceType !== this.state.sourceType) {
-      this.fetchOptions(this.state.annotationType, this.state.sourceType, true);
-    }
+  componentDidUpdate() {
+    this.fetchAppliedChart();
```
Comment (Antonio-RiveroMartnez) [inline superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:232]: Do we want/need to fetch this on every update of the component?

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 3]
```diff
@@ -279,17 +292,26 @@ class AnnotationLayer extends React.PureComponent {
...
   handleAnnotationSourceType(sourceType) {
     const { sourceType: prevSourceType } = this.state;
 
     if (prevSourceType !== sourceType) {
-      this.setState({ sourceType, value: null, isLoadingOptions: true });
+      this.setState({
+        sourceType,
+        value: null,
+        valueOptions: {},
+        optionsFetch: this.asyncFetch.bind(this),
```
Comment (Antonio-RiveroMartnez) [inline superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:307]: Same as above

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 4]
```diff
@@ -298,73 +320,149 @@ class AnnotationLayer extends React.PureComponent {
...
-        const queryParams = rison.encode({
-          filters: [
-            {
-              col: 'id',
-              opr: 'chart_owned_created_favored_by_me',
-              value: true,
+  asyncFetch = async (search, page, pageSize) => {
+    const { annotationType, sourceType } = this.state;
+
+    // Bypassing eslint no-unused-vars error
```
Comment (Antonio-RiveroMartnez) [inline superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:326]: Curious about why was this disabled?

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 5]
```diff
@@ -298,73 +320,149 @@ class AnnotationLayer extends React.PureComponent {
...
+    return {
+      data: [],
+      totalCount: 0,
+    };
+  };
+
+  fetchAppliedChart() {
+    const { value, valueOptions, sourceType } = this.state;
+    const id = value;
+    if (id && !valueOptions[id] && requiresQuery(sourceType)) {
```
Comment (Antonio-RiveroMartnez) [inline superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:425]: You could move this conditional to the `didUpdate` so you don't call this function is not met?

**Review by Antonio-RiveroMartnez — COMMENTED** [review]
Thanks for taking care of this 💪 !

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 6]
```diff
@@ -109,6 +109,22 @@ const NotFoundContentWrapper = styled.div`
   }
 `;
 
+/* TODO remove if we don't use it
```
[the remark this answers is not in the document]
Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:112]: Not totally leftover, this was style I retrieved from the SelectControl component but it looks like the AsyncSelect might not need any additional styling, I just want to make doubly sure before I remove it

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx (hunk 1 above)
Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:213]: This and the setting in handleAnnotationSourceType were a way to update the asyncFetch function so that the options don't persist between sourceType changes. This was the only reliable way I could find so far to trigger the re-render. I'll look into a more correct way but any suggestions would help

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx (hunk 4 above)
Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:326]: eslint was causing an error because search was never being used anywhere but it's part of the necessary args for AsyncSelect's fetchOptions function

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx (hunk 1 above)
Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:213]: Found a solution using the key prop on AsyncSelect

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 7]
```diff
@@ -298,73 +320,149 @@ class AnnotationLayer extends React.PureComponent {
...
+
+      const { result, count } = json;
+
+      const layersObj = {};
+      result.forEach(layer => {
+        layersObj[layer.id] = {
+          value: layer.id,
+          label: layer.name,
+        };
+      });
```
[the remark this answers is not in the document]
Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:347]: Kind of a pain to use the map if I'm trying to create an object directly, I'll change it to use reduce which is consistent with what I did to the charts

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 8]
```diff
@@ -279,17 +292,26 @@ class AnnotationLayer extends React.PureComponent {
...
+        valueOptions: {},
+        optionsFetch: this.asyncFetch.bind(this),
+      });
     }
   }
 
   handleValue(value) {
     this.setState({
-      value,
+      value: value.value,
```
[the remark this answers is not in the document]
Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:314]: Putting the function to fetch in state was a solution to having it re-render when changing the `sourcetype`, otherwise the options persisted. I'm changing it to use the key prop on `AsyncSelect` instead, removing the function from state.

Also I realized using `value.value` is major problem when setting a formula as the value is then just a string

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 9]
```diff
@@ -462,20 +528,16 @@ class AnnotationLayer extends React.PureComponent {
...
+          /* key to force re-render on sourceType change */
+          key={sourceType}
           ariaLabel={t('Annotation layer value')}
           name="annotation-layer-value"
-          showHeader
-          hovered
-          description={description}
-          label={label}
+          header={this.renderChartHeader(label, description, value)}
           placeholder=""
```
Comment (michael-s-molina) [inline superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:537]: Any reason to disable the default placeholder?

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 10]
```diff
@@ -298,74 +306,142 @@ class AnnotationLayer extends React.PureComponent {
...
+        acc[layer.id] = {
+          value: layer.id,
+          label: layer.name,
+        };
+        return acc;
+      }, {});
+
+      const layersArray = Object.values(layersObj);
+
+      this.setState(prevState => ({
```
Comment (michael-s-molina) [inline superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:340]: You shouldn't have a `setState` inside the async function. To fix this, instead of caching all the options loaded by the select and augmenting this state with chart data, you can have a specific state entry to store that information. You can use the annotation layer id as the key and chart data as the value.

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 11]
```diff
@@ -298,74 +306,142 @@ class AnnotationLayer extends React.PureComponent {
...
-              col: 'id',
-              opr: 'chart_owned_created_favored_by_me',
-              value: true,
+  handleTextValue(inputValue) {
+    this.setState({
+      value: inputValue,
+    });
+  }
+
+  asyncFetch = async (_, page, pageSize) => {
```
Comment (michael-s-molina) [inline superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:315]: The first parameter is the search input and it's currently being ignored. Any reason for disabling search?

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 12]
```diff
@@ -298,74 +306,142 @@ class AnnotationLayer extends React.PureComponent {
...
+        valueOptions: { ...prevState.valueOptions, ...layersObj },
+      }));
+
+      return {
+        data: layersArray,
+        totalCount: count,
+      };
+    }
+
+    if (requiresQuery(sourceType)) {
```
Comment (michael-s-molina) [inline superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:350]: It would be a good idea to break this function into 2: one for `sourceType === ANNOTATION_SOURCE_TYPES.NATIVE` and another for `requiresQuery(sourceType)`

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 13]
```diff
@@ -298,74 +306,142 @@ class AnnotationLayer extends React.PureComponent {
...
+        },
+      ],
+    });
+    SupersetClient.get({
+      endpoint: `/api/v1/chart/?q=${queryParams}`,
+    }).then(({ json }) => {
+      const { result } = json;
+      const chart = result[0];
+      this.setState(prevState => ({
+        valueOptions: {
```
Comment (michael-s-molina) [inline superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:427]: See my previous comment. This should be stored in its own state entry.

**Review by michael-s-molina — CHANGES_REQUESTED** [review]
Thank you for the fix @rtexelm and for adding tests! I left some first-pass comments.

**Comment by michael-s-molina** [comment]
In order to fix the failing Docker CI you just need to rebase your PR 😉

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx (hunk 9 above)
Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:537]: No this was just holdover from the SelectControl component I neglected to review, I'll take it out

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx (hunk 11 above)
Comment (michael-s-molina) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:315]: The problem is that this shouldn't be an unused var. You should have something like this:

```
const queryParams = rison.encode({
  filters: [{ col: 'name', opr: 'ct', value: search }],
  page,
  page_size: pageSize,
});
```

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx (hunk 10 above)
Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:340]: Could you elaborate on this one a little more? Do you mean get rid of the `valueOptions` state and save only the selected single chart in a state entry?

Comment (michael-s-molina) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:340]: Yes. You don't need to store the options in the state, they are already maintained by the Select component. You need the chart data information associated with a particular option. You can have a state entry specifically for that like a map of option id and chart data to support multiple charts considering that users might change selected options while interacting with the component.

Comment (michael-s-molina) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:340]: @rtexelm I'll try to explain my comment in more depth:

If you check the `asyncFetch` function, you'll see that there's a call to the chart endpoint:

```
const { json } = await SupersetClient.get({
   endpoint: `/api/v1/chart/?q=${queryParams}`,
});
```

If you check what's actually being used from the result you'll see `chart.id`, `chart.slice_name`, `chart.form_data` and `chart.viz_type`. So the first step is to change `queryParams` to only select these columns, using the `columns` key, to avoid fetching more data than needed.

You need the slice information when selecting an option to use in `renderSliceConfiguration`. Here you have 2 options:

1 - Instead of loading `chart.form_data` for all charts in `asyncFetch`, you could load only the `id`, `slice_name` and `viz_type`, and fire another query to load the `form_data` when a user selects a chart, keeping the previous loaded charts in case a user changes the selection. That's what I meant by:

> You can have a state entry specifically for that like a map of option id and chart data to support multiple charts considering that users might change selected options while interacting with the component.

2 - If you want to fire only one query, loading all `form_data` at once, even if probably only one will be used, you don't need a separate state to store that. The `onChange` event of the Select component sends the `value` as the first parameter and the `option` as the second parameter. Your `option` already contains the slice:

```
{
   value: chart.id,
   label: chart.slice_name,
   slice: {...}
}
```

Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx]: @michael-s-molina I'm not sure if this newest revision is close to what you were thinking but I can always continue to refine it

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx (hunk 12 above)
Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx]: hopefully I addressed this correctly

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 14]
```diff
@@ -276,96 +306,224 @@ class AnnotationLayer extends React.PureComponent {
...
+
+    if (sourceType === ANNOTATION_SOURCE_TYPES.NATIVE) {
+      return this.fetchNativeAnnotations(search, page, pageSize);
     }
+
+    if (requiresQuery(sourceType)) {
+      return this.fetchCharts(search, page, pageSize);
+    }
+
+    return {
```
Comment (michael-s-molina) [inline superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:432]: It's weird that `fetchOptions` could return:
```
return {
  data: [],
  totalCount: 0,
};

```
I think it would be better to not render the select depending on `sourceType`.

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 15]
```diff
@@ -276,96 +306,224 @@ class AnnotationLayer extends React.PureComponent {
...
+        {
+          col: 'id',
+          opr: 'eq',
+          value: id,
+        },
+      ],
+      columns: ['form_data'],
+    });
+    SupersetClient.get({
+      endpoint: `/api/v1/chart/?q=${queryParams}`,
```
Comment (michael-s-molina) [inline superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:450]: Did you use the endpoint `/api/v1/chart/ `instead of `/api/v1/chart/<id>` because you can't only query for the `form_data`?

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 16]
```diff
@@ -194,28 +194,44 @@ class AnnotationLayer extends React.PureComponent {
       hideLine,
       // refData
       isNew: !name,
-      isLoadingOptions: true,
-      valueOptions: [],
+      valueOptions: {},
```
Comment (michael-s-molina) [inline superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:197]: `valueOptions` is not being set anymore. You can remove it.

**Review by michael-s-molina — CHANGES_REQUESTED** [review]
Thanks for addressing the comments @rtexelm.

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx (hunk 15 above)
Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:450]: Yes, the properties contained in `form_data` were nested and spread in the response to `/api/v1/chart/<id>` in such a way that `?q=queryParams` seemed like a more efficient method. In fact, I'm not sure how to properly query for this information according to superset guidelines, I followed the patterns already established in this component. The only doc I could find on the subject [is here](https://github.com/apache/superset/blob/master/CONTRIBUTING.md#query) after you mentioned the `columns` keyword.

Comment (michael-s-molina) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:450]: @rtexelm You can use [Superset's Swagger](https://superset.apache.org/docs/api/) to check the API. It looks like `/api/v1/chart/<id>` supports `columns` too so it would be good to call that endpoint 😉

Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:442]: @michael-s-molina wow, this is exactly what I was looking for! Who would have guessed the information is precisely where it should be? haha 🫠  thank you sincerely, I was just scouring the codebase this whole time

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx (hunk 16 above)
Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx]: Getting errors when this isn't initialized in state upon editing an older Annotation

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx (hunk 15 above)
Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:442]: spoke too soon, looks like `form_data` is nested in the `query_context`. not sure how to isolate that using the `/${id}` endpoint if it's possible

Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx]: @michael-s-molina I was able to fix this, thought there was an issue with the result object but it was just my mistake. Curious if it this looks good, when you have a moment.

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx (hunk 16 above)
Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx]: Forgot to remove `prevState` param from `setState`, should be good now

File: superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx [hunk 17]
```diff
@@ -415,29 +557,20 @@ class AnnotationLayer extends React.PureComponent {
...
   renderValueConfiguration() {
-    const {
-      annotationType,
-      sourceType,
-      value,
-      valueOptions,
-      isLoadingOptions,
-    } = this.state;
+    const { annotationType, sourceType, value, valueOptions } = this.state;
+    const validValue = valueOptions?.[value] ?? null;
```
Comment (michael-s-molina) [inline superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:573]: `valueOptions` is just being read here to get the actual `value`. Your state already have a `value` property so I think you can remove all references to `valueOptions`.

Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:573]: I'm using 'valueOptions' to store the object passed to `handleSelectValue` which contains the id and label. This addresses a bug in which the dropdown field appears blank after first selecting/mounting a saved annotation when feeding it the id alone (the `value` in state).

Comment (michael-s-molina) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:573]: Why don't you change the `value` to be an object with `id` and `label`?

Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:573]: `value` has to be kept strictly as the id to suit the way the annotation is being applied to the chart.

Comment (michael-s-molina) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:573]: I'm not sure if I understood. In places where you need the id, you can use `value.id` and in places where you need the id/label pair, you can use `value`. Is there something I'm missing?

Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:573]: I'm thinking of the `applyAnnotation` function where the `value` is being taken from state and can only be the id of the native annotation or chart in order for the annotation to be applied in `AnnotationLayerControl`. If it contains an object the annotation errors. I ran into this when trying to get rid of valueOptions much earlier on and thought best to leave `value` as is to avoid increasing the scope of the changes. Looking at it now, I could change `newAnnotation.value` to be `value.id` if you think that's a better idea?

Comment (michael-s-molina) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx:573]: I think you can set

```
newAnnotation.id = value.id;
```

The same way you manually set `color`. You just need to remove `value` from `annotationFields`. What I'm trying to achieve is to simplify the state where the value is set in just one place.

Comment (rtexelm) [reply superset-frontend/src/explore/components/controls/AnnotationLayerControl/AnnotationLayer.jsx]: Pushed a commit to address this, let me know what you think. Added a comment to explain the change in type of `value`

**Review by michael-s-molina — COMMENTED** [review]
Thanks for addressing the comments @rtexelm!

**Review by michael-s-molina — APPROVED** [review]
Code LGTM. It would be nice to spin up a test env and get other eyes too @geido @kgabryje
