### PR TITLE
fix(dashboard): Prevent char overflow when displaying chart description

### LINKED ISSUE #12643: [dashboard] Toggle Chart Description results in chart overflowing it's area
When a user clicks on "Toggle chart description", the description gets displayed bellow the chart title, and the chart shifts downwards, resulting in the bottom of the chart (the x axis and legend) overflowing out of the chart area

### Expected results
Chart doesn't overflows

### Actual results
Chart overflows

#### Screenshots
Before "Toggle Chart description"
Screen Shot 2021-01-20 at 7 54 13 PM

After "Toggle Chart description"
Screen Shot 2021-01-20 at 7 54 06 PM

#### How to reproduce the bug

1. Go to Dashboard
2. Click on '...' on a chart which has a description (can be added in chart explore edit properties)
3. Click on "Toggle Chart description"
4. See issue

### Environment
latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by m-ajay**
### SUMMARY
Fixes #12643
### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Before
screenshot-before
After
Screen Shot 2021-05-04 at 2 02 42 PM

### TEST PLAN
CI and manual test

### ADDITIONAL INFORMATION

- [x] Has associated issue:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/dashboard/components/gridComponents/Chart.jsx [hunk 1]
```diff
@@ -164,6 +164,14 @@ export default class Chart extends React.Component {
     clearTimeout(this.resizeTimeout);
   }
 
+  componentDidUpdate(prevProps) {
+    // refresh chart when user toggles the description.
+    // fix for https://github.com/apache/superset/issues/12643
+    if (prevProps.isExpanded !== this.props.isExpanded) {
+      this.forceUpdate();
+    }
```
Comment (graceguo-supercat) [inline superset-frontend/src/dashboard/components/gridComponents/Chart.jsx:172]: forceUpdate() is a solution but we should try to avoid all uses of forceUpdate() and only read from this.props and this.state in render().

So i suggest we do this:
- add `descriptionHeight` in component state, initial value = 0
- in `componentDidUpdate`, set descriptionHeight state like 
```
      const descriptionHeight =
        this.props.isExpanded && this.descriptionRef
          ? this.descriptionRef.offsetHeight
          : 0;
```
- in `shouldComponentUpdate`, if descriptionHeight state is changed, just like height state is change,  should return true:
```
if (
      nextState.width !== this.state.width ||
      nextState.height !== this.state.height ||
      nextState.descriptionHeight !== this.state.descriptionHeight
    ) {
      return true;
    }
```
- for `getChartHeight()` function , get chart content height by height and descriptionHeight:
```
  getChartHeight() {
    const headerHeight = this.getHeaderHeight();
    return this.state.height - headerHeight - this.state.descriptionHeight;
  }
```

**Comment by michael-s-molina** [comment]
@m-ajay Can you change the PR description from "This fixes issue #12643" to "Fixes #12643" so that the issue is automatically closed when we merge this PR?

**Review by graceguo-supercat — APPROVED** [review]
LGTM

**Comment by graceguo-supercat** [comment]
giphy
