### PR TITLE
fix(echarts): Series style hidden for line charts

### LINKED ISSUE #27302: "Series Style" control not working
### Bug description

There is control in Line Chart called "Series style". When you select any of the option it includes the chart is not re-rendered, nothing happens.

### How to reproduce the bug

1. Create Line Chart.
2. Go to "Customize" tab.
3. Search for "Series style" control.
4. Select any option.
5. Nothing happens.

### Screenshots/recordings

image

### Superset version

3.1.1

### Python version

Not applicable

### Node version

Not applicable

### Browser

Not applicable

### Additional context

_No response_

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by vedantprajapati**
# fix(echarts): Series style hidden for line charts

### SUMMARY

This change aims to hide visibility for the series style for line charts as that field is not functional for line charts while it does for others. 

Fixes #27302

### ADDITIONAL INFORMATION

- [X] Has associated issue: https://github.com/apache/superset/issues/27302
- [ ] Required feature flags:
- [X] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by vedantprajapati** [comment]
Hi @geido! Any thoughts on this MR?

File: superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/Regular/Line/controlPanel.tsx [hunk 1]
```diff
@@ -88,6 +88,7 @@ const config: ControlPanelConfig = {
                 [EchartsTimeseriesSeriesType.End, t('Step - end')],
               ],
               description: t('Series chart type (line, bar etc)'),
+              visibility: () => false,
```
Comment (msyavuz) [inline superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/Regular/Line/controlPanel.tsx]: If we don't want this control, can't we just remove it from the array instead? Am i missing something?

File: superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/removeSeriesStyle.tsx [hunk 2]
```diff
@@ -0,0 +1,30 @@
+import controlPanel from './Regular/Line/controlPanel';
```
Comment (msyavuz) [inline superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/removeSeriesStyle.tsx]: All files should have apache license on top. I don't think we need this file though

**Review by msyavuz — COMMENTED** [review]
Thanks for this!

File: superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/removeSeriesStyle.tsx (hunk 2 above)
Comment (vedantprajapati) [reply superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/removeSeriesStyle.tsx]: this file was used in our branch to generalize a control panel without series style in case we want to go this route. we use this component in our branch

Comment (vedantprajapati) [reply superset-frontend/plugins/plugin-chart-echarts/src/Timeseries/removeSeriesStyle.tsx]: but sure, I can remove it

**Comment by rusackas** [comment]
Looks like we need some tests here? @msyavuz did you take a look at the ephemeral already?

**Comment by msyavuz** [comment]
My last review comment still holds, we should just remove the control instead of visibility false

**Comment by JZ6** [comment]
@vedantprajapati

**Comment by msyavuz** [comment]
Just needs pre-commit and maybe a rebase, otherwise LGTM

**Comment by vedantprajapati** [comment]
@geido is this good for merge?

**Comment by sfirke** [comment]
@msyavuz bump - can you review?

**Review by msyavuz — APPROVED** [review]
LGTM! Thought i approved this one my bad!
