### PR TITLE
[SQLLab] Fix the usage of Redux DevTools Enhancer

### LINKED ISSUE #1223: JS error when loading SQL Labs
Caravel version: master (96844c5c12c22e03bdbee61634c5b7dc138d19c5)
Browser version: Chrome 53.0.2785.143 (64-bit)

When loading SQL labs, I got the following error
```
Uncaught TypeError: 
Cannot read property 'apply' of undefined(anonymous function) @ compose.js:36
createStore @ createStore.js:65
(anonymous function) @ index.jsx:17
__webpack_require__ @ bootstrap 09560df…?abe2***:19
(anonymous function) @ bootstrap 09560df…?abe2***:39
(anonymous function) @ bootstrap 09560df…?abe2***:39
```

Any ideas what's going on?

### PR DESCRIPTION
**Pull request by zalmoxisus**
The issue caused by not having the extension installed could be solved by using

``` js
enhancerWithPersistState = compose(
      persistState(),
      window.devToolsExtension && window.devToolsExtension() || noop => noop
    );
```

However, it was really confusing. So, [we're deprecating the enhancer](https://github.com/zalmoxisus/redux-devtools-extension/issues/220) in favour of a more clear API.

I'm happy that Airbnb devs found the extension useful. If you have any other suggestions about it, let me know (since we're both building tools for development).

Fixes #1223, #1228, #1238.

### CODE REVIEW

File: caravel/assets/javascripts/reduxUtils.js [hunk 1]
```diff
@@ -67,9 +67,8 @@ export function addToArr(state, arrKey, obj) {
 export function enhancer() {
   let enhancerWithPersistState = compose(persistState());
   if (process.env.NODE_ENV === 'dev') {
-    enhancerWithPersistState = compose(
-      persistState(), window.devToolsExtension && window.devToolsExtension()
-    );
+    const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
```
Comment (mistercrunch) [inline caravel/assets/javascripts/reduxUtils.js]: this triggers the linter, breaks the build, to fix please add `/* eslint-disable no-underscore-dangle */` on the line right above

**Comment by mistercrunch** [comment]
Nice thanks for the pro-active fix!
