### PR TITLE
[SQLLab] Fix updating the database state.

### LINKED ISSUE #1220: Stale run_sync cache in the SQL Lab
Once I enable the DB that was disables to run the sync queries - the run button doesn't appear:
screen shot 2016-09-29 at 10 15 47 am

screen shot 2016-09-29 at 10 16 13 am

### PR DESCRIPTION
**Pull request by bkyryliuk**
Resolves: https://github.com/airbnb/caravel/issues/1220
Database changes were not propagated to the redux state, it caused client inability to show the run query button for the activated dbs and also to display newly added databases.

In addition, looks like `componentDidMount` is sufficient and may be better than `componentWillMount`as the latter is supposed to be synchronous and called on the server:
http://stackoverflow.com/questions/29899116/what-is-the-difference-between-componentwillmount-and-componentdidmount-in-react

Reviewers:
- @mistercrunch 
- @ascott 
- @vera-liu

### CODE REVIEW

**Comment by vera-liu** [comment]
LGTM! Thanks for fixing this Bogdan!

File: caravel/assets/javascripts/SqlLab/components/DatabaseSelect.jsx [hunk 1]
```diff
@@ -11,7 +14,7 @@ class DatabaseSelect extends React.Component {
       databaseId: null,
     };
   }
-  componentWillMount() {
+  componentDidMount() {
```
Comment (ascott) [inline caravel/assets/javascripts/SqlLab/components/DatabaseSelect.jsx]: componentDidMount is usually used for code that requires that the dom has been rendered, while `componentWillMount` gets called right before the component is rendered. in this case, you're right, we can use either.

**Comment by ascott** [comment]
LGTM

**Comment by bkyryliuk** [comment]
thanks @vera-liu  and @ascott  for the review
