### PR TITLE
fix(explore): time picker can not be switched between now and specific

### LINKED ISSUE #12780: [explore]time picker switch from NOW to Specific time range
Uploading Screen Recording 2021-01-26 at 2.07.48 PM.mov…

Actual:

User can switch form Now to Specific time range in the popover 

Expected:

User have to switch to other time range setting(e.g. relative) first, then can switch to Specific 

#### Screenshots

https://user-images.githubusercontent.com/67837651/105912349-3582a700-5fe0-11eb-9da3-cd3ee877fe36.mov

#### How to reproduce the bug

1. Go to Explore
2. Click on Time Picker pill and select Custom from dropdown
3. Select Now from the End dropdown 
4. Switch from Now to Specific time range 

lastest master

### PR DESCRIPTION
**Pull request by zhaoyongjie**
### SUMMARY

fix time picker can not be switched between "now" and "specific".
closes: https://github.com/apache/superset/issues/12780

### before
https://user-images.githubusercontent.com/67837651/105912349-3582a700-5fe0-11eb-9da3-cd3ee877fe36.mov

### fixed
https://user-images.githubusercontent.com/2016594/106006571-53d7c800-60f0-11eb-8c90-cef3aa216846.mp4

### TEST PLAN

1. open new timepicker 
2. switch to custom frame
3. select "now"(or "midnight") for start(or "end")
4. able to switch to "specific date/time"

### ADDITIONAL INFORMATION

- [x] Has associated issue: https://github.com/apache/superset/issues/12780
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/explore/components/controls/DateFilterControl/frame/CustomFrame.tsx [hunk 1]
```diff
@@ -36,23 +36,17 @@ import {
...
+  customTimeRangeEncode,
+  dttmToMoment,
+} from '../utils';
 import {
   CustomRangeKey,
   SelectOptionType,
   FrameComponentProps,
 } from '../types';
 
-const dttmToMoment = (dttm: string): Moment => {
```
Comment (zhaoyongjie) [inline superset-frontend/src/explore/components/controls/DateFilterControl/frame/CustomFrame.tsx:46]: move these to utils.js

File: superset-frontend/src/explore/components/controls/DateFilterControl/utils.ts [hunk 2]
```diff
@@ -183,31 +197,27 @@ export const customTimeRangeEncode = (customRange: CustomRangeType): string => {
   } = { ...customRange };
   // specific : specific
   if (SPECIFIC_MODE.includes(sinceMode) && SPECIFIC_MODE.includes(untilMode)) {
-    const since = sinceMode === 'specific' ? sinceDatetime : sinceMode;
-    const until = untilMode === 'specific' ? untilDatetime : untilMode;
+    const since = sinceMode === 'specific' ? dttmToString(sinceDatetime) : sinceMode; // eslint-disable-line
```
Comment (zhaoyongjie) [inline superset-frontend/src/explore/components/controls/DateFilterControl/utils.ts:200]: from "now/midnight" switch to "specific", "since" requires materialization from "now" to "YYYY-mm-ddThh:mm:ss".

**Comment by adam-stasiak** [comment]
Tested manually works fine 🟢 
Tested on chrome,safari,firefox - ok

**Comment by zhaoyongjie** [comment]
Thanks for the quick testing

**Review by graceguo-supercat — APPROVED** [review]
LGTM

File: superset-frontend/src/explore/components/controls/DateFilterControl/utils.ts (hunk 2 above)
Comment (etr2460) [inline superset-frontend/src/explore/components/controls/DateFilterControl/utils.ts:200]: Why do all of these lines have `eslint-disable-line` on them? Can we either not introduce linting errors, or only disable the specific rule that's failing here?

Comment (villebro) [reply superset-frontend/src/explore/components/controls/DateFilterControl/utils.ts:200]: I guess this comes down to personal preference (these lines are easier to read as one-liners, but the linter wants to break them up). I've personally come to appreciate uniformity over legibility. I'd vote for removing the `eslint-disable-line`s here and fixing the linting errors.

**Review by villebro — APPROVED** [review]
LGTM, but I'd prefer to reformat according to the linter's preference.

File: superset-frontend/src/explore/components/controls/DateFilterControl/utils.ts (hunk 2 above)
Comment (etr2460) [reply superset-frontend/src/explore/components/controls/DateFilterControl/utils.ts:200]: oh yeah, if it's only formatting, then 100% let's follow the linter. @zhaoyongjie mind updating?

**Review by junlincc — APPROVED** [review]
approve as product/design/QA sign off. 

tried switching between all different settings ✅
apologize that we didn't catch it earlier ..

File: superset-frontend/src/explore/components/controls/DateFilterControl/utils.ts (hunk 2 above)
Comment (zhaoyongjie) [reply superset-frontend/src/explore/components/controls/DateFilterControl/utils.ts:200]: glad to follow to linting rules and make the change, however, I still believe breaking the lines is unnecessary. It makes it harder to read this code, especially in the case where we want to compare since and until side by side.

but I am still willing to follow everyone's conventions. 

###  ⇓ disable linting
```
...
  // specific : specific
  if (SPECIFIC_MODE.includes(sinceMode) && SPECIFIC_MODE.includes(untilMode)) {
    const since = sinceMode === 'specific' ? dttmToString(sinceDatetime) : sinceMode; // eslint-disable-line
    const until = untilMode === 'specific' ? dttmToString(untilDatetime) : untilMode; // eslint-disable-line
    return `${since} : ${until}`;
  }

  // specific : relative
  if (SPECIFIC_MODE.includes(sinceMode) && untilMode === 'relative') {
    const since = sinceMode === 'specific' ? dttmToString(sinceDatetime) : sinceMode; // eslint-disable-line
    const until = `DATEADD(DATETIME("${since}"), ${untilGrainValue}, ${untilGrain})`; // eslint-disable-line
    return `${since} : ${until}`;
  }

  // relative : specific
  if (sinceMode === 'relative' && SPECIFIC_MODE.includes(untilMode)) {
    const until = untilMode === 'specific' ? dttmToString(untilDatetime) : untilMode; // eslint-disable-line
    const since = `DATEADD(DATETIME("${until}"), ${-Math.abs(sinceGrainValue)}, ${sinceGrain})`; // eslint-disable-line
    return `${since} : ${until}`;
  }

  // relative : relative
  const since = `DATEADD(DATETIME("${anchorValue}"), ${-Math.abs(sinceGrainValue)}, ${sinceGrain})`; // eslint-disable-line
  const until = `DATEADD(DATETIME("${anchorValue}"), ${untilGrainValue}, ${untilGrain})`;
  return `${since} : ${until}`;
...
```

### ⇓ enable linting
```
...
  // specific : specific
  if (SPECIFIC_MODE.includes(sinceMode) && SPECIFIC_MODE.includes(untilMode)) {
    const since =
      sinceMode === 'specific' ? dttmToString(sinceDatetime) : sinceMode;
    const until =
      untilMode === 'specific' ? dttmToString(untilDatetime) : untilMode;
    return `${since} : ${until}`;
  }

  // specific : relative
  if (SPECIFIC_MODE.includes(sinceMode) && untilMode === 'relative') {
    const since =
      sinceMode === 'specific' ? dttmToString(sinceDatetime) : sinceMode;
    const until = `DATEADD(DATETIME("${since}"), ${untilGrainValue}, ${untilGrain})`;
    return `${since} : ${until}`;
  }

  // relative : specific
  if (sinceMode === 'relative' && SPECIFIC_MODE.includes(untilMode)) {
    const until =
      untilMode === 'specific' ? dttmToString(untilDatetime) : untilMode;
    const since = `DATEADD(DATETIME("${until}"), ${-Math.abs(
      sinceGrainValue,
    )}, ${sinceGrain})`;
    return `${since} : ${until}`;
  }

  // relative : relative
  const since = `DATEADD(DATETIME("${anchorValue}"), ${-Math.abs(
    sinceGrainValue,
  )}, ${sinceGrain})`;
  const until = `DATEADD(DATETIME("${anchorValue}"), ${untilGrainValue}, ${untilGrain})`;
  return `${since} : ${until}`;
...
```

**Comment by zhaoyongjie** [comment]
> LGTM, but I'd prefer to reformat according to the linter's preference.

I removed `eslint-disable-line` and fix this linting issue.

File: superset-frontend/src/explore/components/controls/DateFilterControl/utils.ts [hunk 3]
```diff
@@ -60,6 +61,19 @@ const defaultCustomRange: CustomRangeType = {
...
+  if (dttm === 'today') {
+    return moment().utc().startOf('day');
+  }
+  return moment(dttm);
+};
+
+export const dttmToString = (dttm: string): string =>
+  dttmToMoment(dttm).format(MOMENT_FORMAT);
+
 export const customTimeRangeDecode = (
```
Comment (ktmud) [inline superset-frontend/src/explore/components/controls/DateFilterControl/utils.ts:77]: Style nit: can we break `utils.ts` into separate files under a `utils` folder? These functions are complex enough to warrant a separate file.

File: superset-frontend/src/explore/components/controls/DateFilterControl/utils.ts (hunk 2 above)
Comment (ktmud) [reply superset-frontend/src/explore/components/controls/DateFilterControl/utils.ts]:
```ts
export const customTimeRangeEncode = (customRange: CustomRangeType): string => {
  const {
    sinceDatetime,
    sinceMode,
    sinceGrain,
    sinceGrainValue,
    untilDatetime,
    untilMode,
    untilGrain,
    untilGrainValue,
    anchorValue,
  } = { ...customRange };
  let since: string = sinceMode;
  let until: string = untilMode;

  if (since === 'specific') {
    since = dttmToString(sinceDatetime);
  }
  if (until === 'specific') {
    until = dttmToString(untilDatetime);
  }

  if (since === 'relative' && until === 'relative') {
    since = `DATEADD(DATETIME("${anchorValue}"), ${-Math.abs(
      sinceGrainValue,
    )}, ${sinceGrain})`;
    until = `DATEADD(DATETIME("${anchorValue}"), ${untilGrainValue}, ${untilGrain})`;
  }

  if (since === 'relative') {
    since = `DATEADD(DATETIME("${until}"), ${-Math.abs(
      sinceGrainValue,
    )}, ${sinceGrain})`;
  }

  if (until === 'relative') {
    until = `DATEADD(DATETIME("${since}"), ${untilGrainValue}, ${untilGrain})`;
  }

  return `${since} : ${until}`;
};
```

@zhaoyongjie would this be cleaner? It passes all your test cases.

**Comment by ktmud** [comment]
BTW, I found this line: https://github.com/apache/superset/blob/6731cd0be6852c890a5e856e79470d08eb760437/superset-frontend/src/explore/components/controls/DateFilterControl/types.ts#L60

could probably be updated to 

```
  untilMode: DateTimeModeType;
```

File: superset-frontend/spec/javascripts/explore/components/DateFilterControl/utils_spec.ts [hunk 4]
```diff
@@ -0,0 +1,339 @@
...
+
+  describe('customTimeRangeDecode', () => {
+    it('1) default value', () => {
+      expect(
+        customTimeRangeDecode(
+          'DATEADD(DATETIME("2021-01-27T00:00:00"), -7, day) : 2021-01-27T00:00:00',
+        ),
+      ).toEqual({
+        customRange: {
+          sinceDatetime: '2021-01-20T00:00:00',
```
Comment (ktmud) [inline superset-frontend/spec/javascripts/explore/components/DateFilterControl/utils_spec.ts:216]: I'm not sure I fully understand the purpose of the `customTimeRangeDecode` function. It is supposed to apply the `dateadd` and `datetime` functions? However, [according to the code](https://github.com/apache/superset/blob/5d816a6e75a77c426b8ce3e5a3bf3a00043439b8/superset-frontend/src/explore/components/controls/DateFilterControl/utils.ts#L118), this `sinceDatetime` seems to always return  `7_DAYS_AGO` when the input format is `relative : specific`.

Comment (zhaoyongjie) [reply superset-frontend/spec/javascripts/explore/components/DateFilterControl/utils_spec.ts:216]: image

Comment (ktmud) [reply superset-frontend/spec/javascripts/explore/components/DateFilterControl/utils_spec.ts:216]: Then shouldn't `sinceDatetime` be set to `2021-01-27T00:00:00` here, just to be more consistent with what is set in the input values?

Do you also do decode/encode when switching between non-advanced modes (i.e. modes that doesn't allow free text)? Not sure how feasible it is, but gut feeling tells me that it might be easier and cleaner to use he same config object internally for all frames and only do decode/encode when the time picker needs to communicate with the outside world.

Comment (zhaoyongjie) [reply superset-frontend/spec/javascripts/explore/components/DateFilterControl/utils_spec.ts:216]: - `customTimeRangeEncode` is used only in the CustomFrame.
- `customTimeRangeDecode` is used in 2 places: CustomFrame and guessFrame function in DateFilterControl.

customTimeRangeDecode can determine whether an expression can be used in CustomFrame.

Comment (zhaoyongjie) [reply superset-frontend/spec/javascripts/explore/components/DateFilterControl/utils_spec.ts:216]: `sinceDatetime` set to `2021-01-27T00:00:00` just to be more consistent in CustomFrame.

Comment (ktmud) [reply superset-frontend/spec/javascripts/explore/components/DateFilterControl/utils_spec.ts:216]: Thanks for the explanation.

**Comment by zhaoyongjie** [comment]
> BTW, I found this line:
> 
> https://github.com/apache/superset/blob/6731cd0be6852c890a5e856e79470d08eb760437/superset-frontend/src/explore/components/controls/DateFilterControl/types.ts#L60
> 
> could probably be updated to
> 
> ```
>   untilMode: DateTimeModeType;
> ```

thanks for pointing this out. I will fix it.

**Review by etr2460 — APPROVED** [review]
thanks for the updates, lgtm!
