### PR TITLE
fix: properly render booleans in FilterBox and explore page data preview

### LINKED ISSUE #12106: [explore] Data section in Explore empty for column with boolean values
The new Data section on chart explore is empty if the column type is boolean.

### Expected results

Display the values

### Actual results

Empty column

#### Screenshots
Screen Shot 2020-12-17 at 4 53 37 PM

#### How to reproduce the bug

1. Go to 'Explore'
2. Create chart which includes a boolean column
3. Scroll down to Data section

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by ktmud**
### SUMMARY

Fixes #12106 #12105 

Also hides the data preview pane for FilterBox.

#### After Fix

In FilterBox:

In data preview:

### TEST PLAN

Manual verification.

1. Try create a calculated column that returns boolean values in the `wb_health_population` dataset

### ADDITIONAL INFORMATION

- [ ] Has associated issue:
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by rusackas — APPROVED** [review]
LGTM, appreciate you taking the time to dig in!

**Review by villebro — APPROVED** [review]
LGTM. I'm surprised the lack of this logic wasn't causing trouble before (apparently booleans weren't proper booleans before?).

File: superset-frontend/src/explore/components/DataTableControl.tsx [hunk 1]
```diff
@@ -95,11 +96,30 @@ export const useFilteredTableData = (
     );
   }, [data, filterText]);
 
-export const useTableColumns = (data?: Record<string, any>[]) =>
+export const useTableColumns = (
+  data?: Record<string, any>[],
+  moreConfigs?: { [key: string]: Partial<Column> },
```
Comment (ktmud) [inline superset-frontend/src/explore/components/DataTableControl.tsx:101]: Extends the possibility of overriding column configs. Not used anywhere for now.

**Comment by ktmud** [comment]
> LGTM. I'm surprised the lack of this logic wasn't causing trouble before (apparently booleans weren't proper booleans before?).

Maybe they were returned as strings by the API? I'm not sure...

**Comment by kgabryje** [comment]
> LGTM. I'm surprised the lack of this logic wasn't causing trouble before (apparently booleans weren't proper booleans before?).

Apparently not displaying booleans is a known bug in react-table https://github.com/tannerlinsley/react-table/issues/799

File: superset-frontend/src/visualizations/FilterBox/FilterBox.jsx [hunk 2]
```diff
@@ -216,7 +216,13 @@ class FilterBox extends React.PureComponent {
       const color = 'lightgrey';
       const backgroundImage = `linear-gradient(to right, ${color}, ${color} ${perc}%, rgba(0,0,0,0) ${perc}%`;
       const style = { backgroundImage };
-      return { value: opt.id, label: opt.id, style };
+      let label = opt.id;
+      if (label === true) {
+        label = t('True');
+      } else if (label === false) {
+        label = t('False');
```
Comment (etr2460) [inline superset-frontend/src/visualizations/FilterBox/FilterBox.jsx:223]: I'm actually not sure we want translations here (I know, goes against my usual comments!).

The reason being, we want to display the data as it exists in the table, and I don't know of any SQL dialects that translate the keywords for boolean values. I think `"TRUE"` and `"FALSE"` are probably best here, although would also accept `"true"` and `"false"`

Comment (ktmud) [reply superset-frontend/src/visualizations/FilterBox/FilterBox.jsx:223]: I thought it made sense to translate as the FilterBox is a user-facing interface, but I agree maybe more data-savvy users would want them to display as what the database displays.

I'm going to extra them as constants so that customized Superset could easily override.
