### PR TITLE
Pass url parameters from dashboard to charts

### LINKED ISSUE #6708: Jinja macro url_params is not working from the dashboard
URL filters are not working as expected. I created a query with the URL parameter and created a chart out of it. The chart won't work by itself unless the user explicitly passes the URL filter to the chart. Generated a chart view with by proving the URL parameter to the chart and saved it to a new dashboard. Now I am passing the URL parameter to the dashboard and it is not working. It will refresh and display the cache irrespective of the filter value

### PR DESCRIPTION
**Pull request by villebro**
### CATEGORY

Choose one

- [x] Bug Fix
- [x] Enhancement (new features, refinement)
- [ ] Refactor
- [x] Add tests
- [ ] Build / Development Environment
- [x] Documentation

### SUMMARY
Currently URL parameters are correctly handled in explore mode. However, current functionality is limited/broken in the following ways:
- Any default values for `url_params` specified in charts are erased if the chart is opened via the Charts page.
- query parameters passed to dashboards are not forwarded to chart requests, making them unusable in dashboards.

This PR does the following:
- Default values for query parameters are left unchanged when opening a chart via the Charts page.
- URL parameters passed to a dashboard are updated to the chart defaults prior to rendering.
- Add note about setting default values for `url_params`.
- Add cypress test to ensure params are passed through from the dashboard to chart requests.
- Add python test to ensure that url params are appended to pre-defined params.

### SCREENSHOTS
Datasource query:
image

Chart metadata with default values for `url_params`:
image

Dashboard with url parameter (note `name2` falling back to default value):
image

### TEST PLAN
- Tested locally
- CI
- Ensured that new tests fail when run on master branch

### ADDITIONAL INFORMATION

- [x] Has associated issue: closes #6708 
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### REVIEWERS
@senturkayhan @rsdpyenugula @mistercrunch @graceguo-supercat @etr2460

### CODE REVIEW

**Comment by villebro** [comment]
This is ready for review

File: superset/assets/cypress/integration/dashboard/url_params.js [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+import { WORLD_HEALTH_DASHBOARD } from './dashboard.helper';
+
+export default () => describe('dashboard url params', () => {
+  let sliceIds = [];
+
+  beforeEach(() => {
+    cy.server();
+    cy.login();
+
+    cy.visit(WORLD_HEALTH_DASHBOARD + '?param1=123&param2=abc');
```
Comment (villebro) [inline superset/assets/cypress/integration/dashboard/url_params.js]: Here I would have used `qs` introduced in cypress `3.5.0` (https://docs.cypress.io/guides/references/changelog.html#3-5-0), but since we're still on `3.4.1`, I had to put it in the URL by hand. If there are no objections, I can bump to `3.6.1` which would make this test slightly cleaner (being able to assert against the same object that's being passed to visit).

**Comment by villebro** [comment]
Nudging testers/reviewers, would be great to get 👀 on this to kill this long standing bug.

File: superset/views/core.py [hunk 2]
```diff
@@ -2192,13 +2192,19 @@ def dashboard(**kwargs):
                 "slice_can_edit": slice_can_edit,
             }
         )
+        url_params = {
+            key: value
+            for key, value in request.args.items()
+            if key not in ("edit", "standalone")
```
Comment (mistercrunch) [inline superset/views/core.py]: The blacklisting here seems brittle. Wondering if it's necessary.

**Review by mistercrunch — COMMENTED** [review]
Minor note, otherwise LGTM

File: superset/assets/cypress/integration/dashboard/url_params.js (hunk 1 above)
Comment (graceguo-supercat) [reply superset/assets/cypress/integration/dashboard/url_params.js]: 👍

**Review by graceguo-supercat — APPROVED** [review]

**Comment by ForzaDesignStudio** [comment]
Hi, i am trying this and have followed the solution but it will not filter for me. i have done they query in sql lab, made the chart and changed the metadata that makes a table with name_1, name_2, but changing the URL does not seem to filter my dashboard. Any idea why this is not working? Did you test this on a server rather than locally just? thanks! 
Version 0.35.1

image

**Comment by villebro** [comment]
@ForzaDesignStudio unfortunately this had to be dropped from `0.35.2` as it didn't apply cleanly to the `0.35` branch. As it stands this fix will be available in the `0.36.0` release, probably due out this month.

**Comment by ForzaDesignStudio** [comment]
thank you for the quick reply. i will try it in the next release.
