### PR TITLE
fix(sql lab): MultiSelector component render twice

### LINKED ISSUE #20702: [SQL Lab] MultiSelector component render twice
When you select 3 or more tables in drop-down and Click remove all chosen tables then MultiSelector component render values twice

#### How to reproduce the bug

Click SQL Lab and select SQL Editor in drop-down menu.
Select DB connection in Databases drop-down
Select schema in Schema drop-down
Select 3 or more tables in drop-down
Click remove all chosen tables in 'Select table…' field

### Expected results

MultiSelector component render once.

### Actual results

MultiSelector component render twice.

#### Screenshots

https://user-images.githubusercontent.com/29536522/178799559-f07e7f1a-397b-4edc-8126-7d0baba47dcf.mov

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

@michael-s-molina @kgabryje @codyml @zhaoyongjie @diegomedina248 @jinghua-qa

### PR DESCRIPTION
**Pull request by diegomedina248**
### SUMMARY

As explained in #20702, when you select more than one table in SQL Lab and try to clear them all, then the component appears to be rerendering twice (or more).

The issue is that the tables are being removed one by one and, specially if the backend persistence is enabled, then, as the backend responds, the value of the select is updated only by that single table.

This PR ensures all tables are deleted at once, preventing the issue.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

Before:

https://user-images.githubusercontent.com/17252075/178904735-972fa6f7-2ab9-4981-a5e1-51f898f695d7.mov

After:

https://user-images.githubusercontent.com/17252075/178904685-8f927c05-150e-4c1d-8801-6dc35d5bcf67.mov

### ADDITIONAL INFORMATION
Fixes #20702
- [ ] Has associated issue:
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

File: superset-frontend/src/SqlLab/actions/sqlLab.js [hunk 1]
```diff
@@ -1213,16 +1213,20 @@ export function collapseTable(table) {
...
 
-export function removeTable(table) {
+export function removeTables(tables) {
   return function (dispatch) {
     const sync = isFeatureEnabled(FeatureFlag.SQLLAB_BACKEND_PERSISTENCE)
-      ? SupersetClient.delete({
-          endpoint: encodeURI(`/tableschemaview/${table.id}`),
-        })
+      ? Promise.all(
+          tables.map(table =>
```
Comment (Antonio-RiveroMartnez) [inline superset-frontend/src/SqlLab/actions/sqlLab.js:1220]: Could `tables` be `null` or `undefined` at some point?

**Review by Antonio-RiveroMartnez — APPROVED** [review]

**Comment by EugeneTorap** [comment]
@diegomedina248 Thank you for this hot fix!
@michael-s-molina Can we merge it?

**Review by michael-s-molina — APPROVED** [review]
