### PR TITLE
fix(plugin-chart-echarts): support truncated numeric x-axis

### LINKED ISSUE #26139: Bar chart with numeric x-axis always starts x-axis at zero regardless of data
Trying out 3.1.0rc1 I noticed that one of my bar charts looked wrong.

In version 3.0.0:

image

In version 3.1.0rc1:
image

I tried making a new chart with another dataset where I have year as a numeric and I experienced the same thing, though the x-axis terminated around 2500 instead of 7000 in the screenshot above.

### Environment
GENERIC_CHART_AXES is enabled

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by villebro**
### SUMMARY
A recent PR that added support for numerical x-axes caused unintuitive results when the x-axis contained a highly constrained interval, e.g. the years 1980-2017. In this case, the x-axis was bounded between [0, 7000], causing a highly spiked appearance. This is in contrast with other visualization tools, that default automatically truncating the x-axis.

This PR adds two new x-axis truncation controls, similar to the existing ones for the y-axis. With this change, the x-axis will be truncated by default. If the lower and/or upper bounds are left undefined, they will default to the min and max values from the dataset (calculated automatically by ECharts). This ensures that the data is bounded correctly.

### AFTER
Now the x-axis is automatically truncated (see the new "TRUNCATE X AXIS" control, which defaults to being checked):
image

By defining the lower and/or upper bound, the x-axis is updated accordingly:
image

### BEFORE
When disabling x-axis truncation, the current "dirac delta"-like behavior is reproduced on the Video Game example chart:
image

### ADDITIONAL INFORMATION

- [x] Has associated issue: closes #26139
- [ ] Required feature flags:
- [ ] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Comment by villebro** [comment]
@michael-s-molina @sfirke I've created a chart that demonstrates how this feature works: [Truncated numerical x-axis](http://35.93.27.117:8080/explore/?slice_id=97) I may add a new integration test to ensure the e2e flow works, but in the meantime I think the PR should be ready for review.

File: superset-frontend/plugins/plugin-chart-echarts/src/Bubble/constants.ts [hunk 1]
```diff
@@ -26,6 +26,7 @@ export const DEFAULT_FORM_DATA: Partial<EchartsBubbleFormData> = {
   logYAxis: false,
   xAxisTitleMargin: 30,
   yAxisTitleMargin: 30,
+  truncateXAxis: false,
```
Comment (villebro) [inline superset-frontend/plugins/plugin-chart-echarts/src/Bubble/constants.ts:29]: Note that for bubble chart, I'm assuming truncation is disabled, as it's more likely people want to see it starting from origo in this case (having a truncated x axis but a non-truncated y axis doesn't make sense for a scatter plot IMO).

**Comment by michael-s-molina** [comment]
Thanks for the PR @villebro. While testing, I found a weird behavior when applying the bounds to temporal and categorial axes. I pushed a change to ignore the bounds for non-numerical axis and also improved the tooltip description to make it more clear that this control is only for numerical types.

**Review by michael-s-molina — APPROVED** [review]
LGTM. Thanks for the fix @villebro.

**Comment by sfirke** [comment]
This is a nice enhancement, thank you @villebro 🙌 !

**Comment by john-bodley** [comment]
Out of interest @villebro where was the original [1900, 2017) range defined?

**Comment by john-bodley** [comment]
@villebro sorry by bad I was looking at the wrong screenshot. I meant the [0, 2,500) interval which resulted in the original "dirac delta"-like behavior.

File: superset-frontend/plugins/plugin-chart-echarts/src/Bubble/constants.ts (hunk 1 above)
Comment (michael-s-molina) [reply superset-frontend/plugins/plugin-chart-echarts/src/Bubble/constants.ts:29]: No objection. We can cherry-pick the change for the next patch.

**Comment by villebro** [comment]
> @villebro sorry by bad I was looking at the wrong screenshot. I meant the [0, 2,500) interval which resulted in the original "dirac delta"-like behavior.

@john-bodley oh, that range wasn't explicitly defined anywhere, that's just what ECharts defaults to unless the bounds are either overridden or set to `dataMin` and `dataMax`.

**Comment by sadpandajoe** [comment]
@villebro I think this pr might have a weird affect on current echart bubble charts. I've documented the issue here: https://github.com/apache/superset/issues/26242.
