### PR TITLE
fix(explore): pie chart label bugs

### LINKED ISSUE #12989: [chart]Label type selection not working on Pie chart
### Expected results

Label type changed

### Actual results

Label type doesn't changed

#### Screenshots

ZOoO4Gkebk

#### How to reproduce the bug

1. Go to 'Charts'
2. Click on 'any Pie chart.'
3. Change Label Type

### Environment

(please complete the following information):

- superset version: `master`
- python version: `based on master`
- node.js version: `based on master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### PR DESCRIPTION
**Pull request by villebro**
### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF
Bump `superset-ui` packages to version 0.17.8 and fix a the following Pie Chart bugs:
- Label sometimes disappears on hover. This was fixed by bumping ECharts to the 5.0.2 version.
- Custom label type changing doesn't work. This was caused by the custom label prop to be called `label_type` in the plugin but `pie_label_type` in the control panel. To fix this, the generic name was chosen (will make it easier to reuse the control value later when switching between chart types) and all references to `pie_label_type` in exising chart metadata was renamed to `label_type`.

Also updates some unrelated code that depends on changes to `superset-ui/core` that relate to native filter metadata.

### TEST PLAN
Verify that both up and down migration works, and that pie chart works properly.

### ADDITIONAL INFORMATION

- [x] Has associated issue: closes #12989
- [ ] Changes UI
- [ ] Requires DB Migration.
- [ ] Confirm DB Migration upgrade and downgrade tested.
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by dpgaspar — APPROVED** [review]

**Review by simcha90 — APPROVED** [review]

File: superset-frontend/src/explore/components/controls/VizTypeControl.jsx [hunk 1]
```diff
@@ -166,15 +166,21 @@ const VizTypeControl = props => {
...
+    })
     .map(type => ({
       key: type,
       value: registry.get(type),
     }))
     .concat(
       registry
         .entries()
-        .filter(entry => !entry.value.isNativeFilter)
+        .filter(entry => {
```
Comment (simcha90) [inline superset-frontend/src/explore/components/controls/VizTypeControl.jsx:180]: may be move it to some utils like
```
getVisibleCharts = ({ behaviours } = {}) => {
      return behaviors?.includes(Behavior.CROSS_FILTER) || !behaviors?.length;
    }
}
and use it like:

```
.filter(type =>getVisibleCharts(registry.get(type)))
and
.filter(entry =>getVisibleCharts(entry.value))
```

**Review by ktmud — APPROVED** [review]
